sul-dlss/dor-services-app

Gemfile
Gemfile.lock

Notice how much could be removed.
Closes #12

dor-services bump and dependency rework

---

Gemfile
Gemfile.lock

i did `bundle update dor-services`, and it did rails and nokogiri too, for whatever reason.  that seems unobjectionable, so i left it.  happy to investigate and try to limit, if people would prefer.

upgrade dor-services, rails, nokogiri

---

Gemfile
Gemfile.lock

@jmartin-sul this PR upgrades dor-services

upgrade to dor-services 5.10.0

---

Gemfile
Gemfile.lock

See https://github.com/sul-dlss/purl-fetcher/issues/90

upgrade to dor-services 5.10.1

---

Gemfile
Gemfile.lock
README.md
lib/update_marc_record_service.rb
spec/dor_services_app_spec.rb
spec/spec_helper.rb
spec/update_marc_spec.rb

switch to new .thumb method from dor-services

---

app/models/symphony_reader.rb
app/xslt/MARC21slim2MODS3-6.xsl
spec/models/symphony_reader_spec.rb

XSL typo fix is also offered upstream as https://github.com/LibraryOfCongress/MarcMods3.6xsl/pull/2

Catalog service improvements

---

app/models/dor/service_item.rb
app/models/dor/update_marc_record_service.rb
spec/controllers/objects_controller_spec.rb
spec/rails_helper.rb
spec/service_item_spec.rb
spec/support/datastreams.rb
spec/update_marc_spec.rb

add z subfield for stanford only objects

---

app/models/dor/update_marc_record_service.rb
spec/update_marc_spec.rb

fix writing out of marc records that contain quotes in them

---

app/models/dor/goobi.rb
app/models/dor/service_item.rb
spec/goobi_spec.rb
spec/service_item_spec.rb

fixes #99 
also, see https://github.com/sul-dlss/sul-goobi/issues/65 for the goobi side of the issue (already done)

Look for DPG ocr tag when setting attribute in goobi notify call

---

app/models/symphony_reader.rb
spec/models/symphony_reader_spec.rb

Exclude any provided 001 and explicitly set the catkey as the 001 and SIRSI as 003
Fixes #91

Include only the catkey in the 001 field

---

app/xslt/MARC21slim2MODS3-6_SDR.xsl

LC stylesheet updated with previous local changes (see https://consul.stanford.edu/display/chimera/MODS+schema+and+MARC+transformation).
More intensive bugfixes/revisions in progress.

LC MARC2MODS 3.6 v.1.118 with local changes to 3.4 merged in

---

app/models/marcxml_resource.rb

Per request by @arcadiafalcone , update the MARC_TO_MODS mapping to our version of 3.6.

Update to our modified 3.6 version

---

app/models/dor/goobi_tag.rb
spec/dor/goobi_spec.rb
spec/dor/goobi_tag_spec.rb

encode tag name and values when generating goobi request xml

---

.travis.yml

Add Ruby 2.5.3 to the test matrix

---

config/deploy/dev.rb

we only have -stage and -prod.

cap deploy: dor-services-dev no longer exists

---

.travis.yml

ruby updated by puppet on VMs; app deployed afterwards.

travis: only test deployed ruby version

---

config/initializers/dor_config.rb
config/settings.yml

Set the credentials for the catalog service client

---

config/initializers/ssl.rb

Hopefull this prevents SSL errors such as #203

Set the TLS version manually

---

spec/controllers/objects_controller_spec.rb
spec/controllers/sdr_controller_spec.rb
spec/controllers/versions_controller_spec.rb
spec/controllers/workflows_controller_spec.rb
spec/services/workspace_service_spec.rb
spec/support/assembleable_versionable_item.rb
spec/support/versionable_item.rb

This doesn't provide anything that we use.

Remove dependency on Assembleable

---

app/controllers/objects_controller.rb
spec/controllers/objects_controller_spec.rb

Added 422 error for ArgumentErrors.

---

bin/repub

Needed to move this because PublishMetadataService moved into dor-services-app.

Move bin/repub from common-accessioning

---

lib/tasks/seeds/druid:rv601yh2288.xml
lib/tasks/seeds/druids

SdrIngestService in Common-accessioning requires this.

Add preservation workflow to the seeds

---

.rubocop_todo.yml
spec/requests/metadata_refresh_spec.rb
spec/services/refresh_metadata_action_spec.rb

all specs must end in *_spec.rb

Rename a spec

---

app/services/registration_service.rb

Fixes a race condition where goobiWF was starting, but couldn't get source_id

Don't start workflow until after save

---

Gemfile.lock
app/controllers/objects_controller.rb
app/controllers/versions_controller.rb
app/services/registration_service.rb
app/services/version_service.rb
spec/controllers/objects_controller_spec.rb
spec/controllers/versions_controller_spec.rb
spec/services/registration_service_spec.rb
spec/services/version_service_spec.rb

Avoid deprecated Dor::CreateWorkflowService
Fixes #259

Use the workflow service client for starting workflows

---

app/controllers/workflows_controller.rb
spec/controllers/workflows_controller_spec.rb

The workflow service handles this now

Deprecate the workflows controller

---

app/services/catalog_handler.rb
config/initializers/dor_config.rb
config/settings.yml
spec/services/metadata_service_spec.rb

Just use the internal mechanisims.
Fixes #253

Don't call out to this service over the network

---

config/initializers/dor_config.rb
config/settings.yml
docker-compose.yml

Solrizer doesn't make much sense
Merge these first:
https://github.com/sul-dlss/shared_configs/pull/935
https://github.com/sul-dlss/shared_configs/pull/934

Change the config from solrizer to solr

---

app/controllers/versions_controller.rb
app/services/version_service.rb
config/routes.rb
spec/controllers/versions_controller_spec.rb
spec/services/version_service_spec.rb

Adds new route for checking if a version can be opened for an object.

---

app/models/dor/update_marc_record_service.rb
spec/dor/update_marc_record_service_spec.rb

Use the correct purl_base_url variable

---

app/controllers/workspaces_controller.rb
app/services/cleanup_reset_service.rb
app/services/cleanup_service.rb
config/initializers/dor_config.rb
spec/controllers/workspaces_controller_spec.rb
spec/services/cleanup_reset_service_spec.rb
spec/services/cleanup_service_spec.rb

Ref https://github.com/sul-dlss/dor-services/pull/637

Move cleanup from dor-services

---

Gemfile
Gemfile.lock
app/controllers/versions_controller.rb
config/routes.rb
spec/controllers/versions_controller_spec.rb

Add a new openable route that will replace openeable

---

app/controllers/versions_controller.rb

Bundler.require does this for us

Remove unnecessary require of deprecation

---

.rubocop.yml
.rubocop_todo.yml
app/controllers/application_controller.rb
app/controllers/objects_controller.rb
app/services/constituent_service.rb
app/services/item_query_service.rb
app/services/reset_content_metadata_service.rb
config/routes.rb
spec/rails_helper.rb
spec/requests/virtual_merge_spec.rb
spec/services/constituent_service_spec.rb

Ref https://github.com/sul-dlss/argo/issues/1458

Add a way to do virtual merge through an API

---

app/services/constituent_service.rb
app/services/item_query_service.rb
app/services/reset_content_metadata_service.rb
spec/services/constituent_service_spec.rb
spec/services/item_query_service_spec.rb

Fixes #334 - ensures ConstituentService does not combine dark or citation_only objects.

Combinable items

---

app/controllers/embargoes_controller.rb
spec/requests/update_embargo_spec.rb

Embargo service expects a Date object

---

lib/tasks/seeds/druid:sh219xb1690.xml
lib/tasks/seeds/druids

add registrationWF to seeds

---

Gemfile
Gemfile.lock
app/controllers/application_controller.rb
app/controllers/objects_controller.rb
app/controllers/sdr_controller.rb
app/models/dor/goobi.rb
app/services/publish_metadata_service.rb
app/services/sdr_client.rb
app/services/version_service.rb
spec/dor/goobi_spec.rb
spec/services/sdr_client_spec.rb
spec/services/version_service_spec.rb

For consistency with other dlss projects

Transition from RestClient to Faraday

---

spec/controllers/objects_controller_spec.rb
spec/requests/add_release_tags_spec.rb

controller specs are deprecated

Extract add release tag spec to a request spec

---

spec/controllers/objects_controller_spec.rb
spec/requests/update_marc_record_spec.rb

controller specs are deprecated

Extract update marc spec to a request spec

---

spec/controllers/objects_controller_spec.rb
spec/requests/register_object_spec.rb

Controller specs are deprecated.

Extract registration specs to request specs

---

openapi.json

The API docs were missing for this endpoint.
That was the whole point 😉

Add API docs for virtual merge endpoint

---

app/services/sdr_client.rb
spec/services/sdr_client_spec.rb

Log message provided in https://app.honeybadger.io/projects/50568/faults/54724105 was insufficient for easy debugging
No api changes

Provide more context to the error received when connecting to SDR

---

app/models/symphony_reader.rb
spec/models/symphony_reader_spec.rb

Skip validating symphony response length when chunked.

---

Capfile
Gemfile
Gemfile.lock
README.md
config/application.rb
config/deploy.rb
config/environments/development.rb
config/environments/production.rb
config/initializers/okcomputer.rb
config/routes.rb
config/sidekiq.yml
docker-compose.yml

Connects to sul-dlss/dor-services-app#336
~Blocked by sul-dlss/puppet#4463~

Add Sidekiq to process background jobs

---

.gitignore
Gemfile
Gemfile.lock

Some of us greatly prefer pry over byebug.
N/A.

add pry-byebug as some of us prefer it

---

spec/requests/add_release_tags_spec.rb
spec/requests/authorization_spec.rb
spec/requests/batch_create_virtual_objects_spec.rb
spec/requests/collections_for_object_spec.rb
spec/requests/metadata_refresh_spec.rb
spec/requests/metadata_spec.rb
spec/requests/notify_goobi_spec.rb
spec/requests/publish_object_spec.rb
spec/requests/register_object_spec.rb
spec/requests/show_object_spec.rb
spec/requests/update_embargo_spec.rb
spec/requests/update_marc_record_spec.rb
spec/requests/virtual_merge_spec.rb
spec/support/auth_helper.rb

Move JWT set up to the AuthHelper

---

.circleci/config.yml
Dockerfile
docker-compose.yml
docker/invoke.sh

Prior to this, the application in containerland was not connecting to its database, and the docker-compose image lacked psql
n/a

Align docker configuration with workflow-service

---

app/controllers/workspaces_controller.rb
app/services/reset_workspace_service.rb
app/services/sdr_client.rb
app/services/version_service.rb
config/routes.rb
config/settings.yml
openapi.json
spec/controllers/workspaces_controller_spec.rb
spec/services/reset_workspace_service_spec.rb
spec/services/version_service_spec.rb

This puts this function behind an API so that the process can be more effectively managed
Yes

Move reset workspace from common-accessioning

---

config/environments/development.rb
config/environments/production.rb

What was there was copypasta that I missed. This will allow jobs to process.

Use default queue for sidekiq

---

app/services/delete_service.rb

The previous methods no longer worked with dor-services 8
n/a

Update method of deleting objects from fedora and solr

---

openapi.json

This allows it to match up with the rails routes. No functional change.
Yes.

Update the OAS to use object_id where appropriate

---

app/jobs/create_virtual_objects_job.rb

part of sul-dlss/argo#1728
- virtual object job traps more broadly for errors in the hopes of avoiding random restarts and getting error messages back to consumers
- virtual object job will complete with errors in many more circumstances where it formerly just dangled.
@andrewjbtw just want you to be aware of this change, hopefully to be deployed on Monday
n/a

virt obj processing rescues StandardError and ensures it will end

---

app/services/workspace_service.rb

I think there may be dead code here.  Adding an alert will help us to understand if it's truly dead or not.
n/a

Add an experiment about whether source is always required

---

openapi.json

Make openapi.json valid JSON

---

app/jobs/start_preservation_workflow_job.rb
app/services/sdr_ingest_service.rb
config/settings.yml
spec/jobs/start_preservation_workflow_job_spec.rb

Reverts sul-dlss/dor-services-app#506

Revert "Callback when preservation ingest has started"

---

README.md

Fix README links.

---

app/jobs/start_preservation_workflow_job.rb
app/services/sdr_ingest_service.rb
config/settings.yml
spec/jobs/start_preservation_workflow_job_spec.rb

Reverts sul-dlss/dor-services-app#526

Revert "Revert "Callback when preservation ingest has started""

---

app/services/refresh_metadata_action.rb

make it easier to understand.
n/a

Add documentation.

---

app/controllers/metadata_refresh_controller.rb
app/services/refresh_metadata_action.rb
openapi.json
spec/requests/metadata_refresh_spec.rb
spec/services/refresh_metadata_action_spec.rb

This helps understand what can go wrong with this step
yes

Differentiate between missing ids and bad data

---

Gemfile.lock

Update rack to 2.0.8

---

.circleci/config.yml
Gemfile
Gemfile.lock

Test on the ruby 2.7 build

---

app/services/metadata_service.rb
spec/services/metadata_service_spec.rb

Fixes #567 
Not entirely sure if this is the right way to resolve this issue, but walking through the code and backtrace it seems to be the point of failure.

Check for a valid catkey in the metadata service

---

app/controllers/metadata_controller.rb
app/services/legacy_metadata_service.rb
spec/requests/legacy_metadata_update_spec.rb

Fixes #590 (missing kwarg)
n/a

Pass required event_factory to LegacyMetadataService

---

app/services/shelving_service.rb
spec/services/shelving_service_spec.rb

Pass the event_factory parameter to the ShelvingService constructor

---

app/jobs/create_virtual_objects_job.rb
app/services/constituent_service.rb
spec/jobs/create_virtual_objects_job_spec.rb
spec/services/constituent_service_spec.rb

Create virtual jobs was failing.
n/a

Pass the event_factory into the ConstituentService

---

app/controllers/objects_controller.rb

These lines are not needed.
n/a

Remove unnecessary logging

---

spec/rails_helper.rb
spec/requests/create_workspaces_spec.rb

This code isn't used, so there's no need to keep it.
n/a

Remove unused method stubs

---

app/services/registration_service.rb

I'm pretty sure this is always sent.  if that is the case, we could make this required and eliminate some conditionals which make the code confusing.
n/a

Add experiment about rights not being provided

---

Gemfile
Gemfile.lock
app/services/embargo_release_service.rb
config/deploy.rb
config/schedule.rb
lib/tasks/dor_services_app.rake
spec/services/embargo_release_service_spec.rb

Move embargo release to dor-services-app, since it is not really a robot.
No.

Add embargo release service

---

Capfile
config/deploy.rb

I messed up configuring whenever.
No.

Fixes cap/whenever config.

---

app/services/registration_service.rb

The processed parameters are a bit confusing.
n/a

Log the raw parameters rather than the processed parameters

---

openapi.yml
spec/requests/register_object_spec.rb

There was no documented spec before
yes

Add the spec for object registration

---

app/services/registration_service.rb
spec/services/registration_service_spec.rb

Call RefreshMetadataAction with the correct parameters

---

openapi.yml

Make the seed_datastream param an array

---

Gemfile
Gemfile.lock
app/services/cocina/mapper.rb
spec/requests/collections_for_object_spec.rb
spec/requests/show_object_spec.rb
spec/services/cocina/mapper_spec.rb

Update the mapper to return the title

---

app/services/cocina/mapper.rb
spec/services/cocina/mapper_spec.rb

Provides more detail about the specific type of content.
Fixes #537
n/a

Map the content type tag to cocina type

---

Gemfile
Gemfile.lock
app/services/cocina/object_creator.rb

Using the appropriate models.
n/a

Refactor object create to use request models

---

Gemfile
Gemfile.lock
app/controllers/objects_controller.rb
app/services/cocina/object_creator.rb

To support latest cocina-models release
n/a

Refactor to work with cocina-models 0.20.0

---

Gemfile
Gemfile.lock

To keep abreast of the latest releases.
n/a

Update to faraday 1.0

---

Gemfile
app/services/cleanup_reset_service.rb
app/services/cleanup_service.rb
app/services/constituent_service.rb
app/services/item_query_service.rb
app/services/prune_service.rb
app/services/public_xml_service.rb
app/services/publish_metadata_service.rb
app/services/reset_workspace_service.rb

Use the correct yard tag (@raise)

---

Gemfile
Gemfile.lock
app/services/cocina/mapper.rb
openapi.yml
spec/requests/collections_for_object_spec.rb
spec/requests/show_object_spec.rb
spec/services/cocina/mapper_spec.rb

So we can get the access property.
n/a

Show the access for the cocina model

---

app/services/cocina/access_builder.rb
app/services/cocina/dro_structural_builder.rb
app/services/cocina/mapper.rb
app/services/cocina/object_creator.rb
openapi.yml
spec/requests/create_object_spec.rb

So that the process tag will be set correctly.
no

Creating an object sets the viewingDirection

---

openapi.yml

This structure was not documented in the openapi.yml
yes

Add documentation about sourceId and catalogLinks

---

app/services/cocina/dro_structural_builder.rb
openapi.yml
spec/services/cocina/mapper_spec.rb

Map checksums to cocina model

---

Gemfile
Gemfile.lock
app/jobs/log_failure_job.rb
app/jobs/log_success_job.rb
app/jobs/start_preservation_workflow_job.rb
app/services/cleanup_reset_service.rb
app/services/datastream_extractor.rb
app/services/delete_service.rb
app/services/embargo_release_service.rb
app/services/item_query_service.rb
app/services/version_service.rb
app/services/workflow_client_factory.rb
config/initializers/dor_config.rb
config/settings.yml
spec/jobs/log_failure_job_spec.rb
spec/jobs/log_success_job_spec.rb
spec/jobs/start_preservation_workflow_job_spec.rb
spec/services/datastream_extractor_spec.rb
spec/services/delete_service_spec.rb
spec/services/embargo_release_service_spec.rb
spec/services/item_query_service_spec.rb
spec/services/version_service_spec.rb

To test the rather substantial changes in dor-services 9
n/a

Upgrade to dor-services 9

---

app/services/cocina/dro_structural_builder.rb
openapi.yml
spec/services/cocina/mapper_spec.rb

Cocina mapper adds file size

---

Gemfile
Gemfile.lock

Use the latest changes in cocina-models.
n/a

Upgrade cocina-models to 0.24.0

---

Gemfile
Gemfile.lock
spec/rails_helper.rb

This avoids adding an unnecessary dependency.
n/a
no

Run tests within a transaction

---

Gemfile
Gemfile.lock
app/services/cocina/dro_structural_builder.rb
app/services/cocina/mapper.rb

This involved casting strings to int or bool to conform to the new cocina models.
n/a
no

Upgrade cocina-models

---

app/services/cocina/dro_structural_builder.rb
spec/services/cocina/mapper_spec.rb

Map filename to cocina representation

---

Gemfile
Gemfile.lock
app/controllers/objects_controller.rb
app/services/cocina/dro_structural_builder.rb
app/services/cocina/mapper.rb
app/services/cocina/object_creator.rb
openapi.yml
spec/requests/collections_for_object_spec.rb
spec/requests/create_object_spec.rb
spec/requests/show_object_spec.rb
spec/services/content_metadata_generator_spec.rb

To switch to generated cocina models and use new descriptive model.
Yes
Yes

Switched to generated cocina models

---

app/jobs/preserve_job.rb
spec/jobs/preserve_job_spec.rb

Ref https://github.com/sul-dlss/google-books/issues/474
no
no

PreserveJob should retry when there are errors

---

spec/services/administrative_tags_spec.rb

Make array of tags in test easier to parse

---

config/deploy.rb
config/deploy/prod.rb
config/deploy/stage.rb
config/initializers/sidekiq.rb
config/settings.yml

Adds new workers for dor-services-app

---

.dockerignore

Smaller images make for less waiting around.
No.
No.

Keep the image svelte

---

lib/capistrano/tasks/sidekiq.rake

This is required on centos7
no
stage

Add the --all flag to systemctl

---

openapi.yml

Update to latest cocina-models.
Yes.
To be tested.

Updated to cocina-models-0.32.0.

---

.circleci/config.yml

preparing to upgrade ruby
na
no

newer ruby for circle build

---

config/deploy/prod.rb

To add a second worker server.
No
No

Adds new worker server.

---

app/services/administrative_tags.rb
spec/requests/administrative_tags_spec.rb
spec/services/administrative_tags_spec.rb

do not error out on duplicate tag creation

---

openapi.yml

Better organization of the documentation
yes
no

Tag tags as tags

---

config/settings.yml

sdr_url setting is no longer used

---

app/controllers/administrative_tags_controller.rb
config/routes.rb

Simplify the administrative tags routing

---

app/controllers/administrative_tags_controller.rb
config/routes.rb
openapi.yml
spec/requests/search_for_tags_spec.rb

This will enable https://github.com/sul-dlss/argo/issues/165
yes
yes, but will be tested when the corresponding argo pr is created.

Add search for tags

---

app/services/administrative_tags.rb

Avoid a race condition when creating tags

---

app/jobs/publish_job.rb
app/jobs/shelve_job.rb
spec/jobs/publish_job_spec.rb
spec/jobs/shelve_job_spec.rb

Ref https://github.com/sul-dlss/common-accessioning/pull/656
Ref sul-dlss/argo#1789
Ref https://github.com/sul-dlss/workflow-server-rails/pull/377
no
Yes, was tested on stage.

Remove the completed steps

---

app/services/administrative_tags.rb

Adjust rollback logic so as not to use the same transaction

---

app/services/content_metadata_generator.rb
spec/services/content_metadata_generator_spec.rb

We were not giving geo objects the correct resource types
Test suite
n/a

Add the correct resource types for geo objects

---

app/services/content_metadata_generator.rb
spec/dor/update_marc_record_service_spec.rb

This makes it easier to reason about, and has more realistic behavior
Test suite
n/a

[Refactor] Update test to stub fewer methods

---

app/models/dor/goobi.rb

Capturing information learned from talking with Peter.
n/a
n/a

Add documentation about Goobi interaction

---

app/models/dor/goobi.rb
app/models/dor/service_item.rb
spec/dor/goobi_spec.rb
spec/dor/service_item_spec.rb

Makes the code easer to understand.
Test suite
n/a

[Refactor] Move goobi methods into the concrete class pertaining to Goobi

---

Gemfile
Gemfile.lock
app/models/dor/service_item.rb
app/models/dor/update_marc_record_service.rb
spec/dor/service_item_spec.rb
spec/dor/update_marc_record_service_spec.rb

[Refactor] Use upstream accessor methods

---

app/models/dor/goobi.rb
app/models/dor/service_item.rb
app/models/dor/update_marc_record_service.rb
spec/dor/goobi_spec.rb
spec/dor/service_item_spec.rb
spec/dor/update_marc_record_service_spec.rb

There's no code like no code.
test suite
n/a

[Refactor] Remove unnecessary code from ServiceItem

---

app/services/cocina/from_fedora/administrative.rb
app/services/cocina/from_fedora/apo.rb
app/services/cocina/from_fedora/collection.rb
app/services/cocina/from_fedora/descriptive.rb
app/services/cocina/from_fedora/dro.rb
app/services/cocina/from_fedora/identification.rb
app/services/cocina/mapper.rb

This takes care of the class growing too long and should allow for more targeted tests
Test suite
n/a

Refactor mapper into individual class mappers

---

Gemfile
Gemfile.lock
openapi.yml
spec/services/content_metadata_generator_spec.rb

adjust openapi.yml and tests for the new models
test suite
openapi.yml

Update the cocina model

---

app/controllers/objects_controller.rb
app/models/marcxml_resource.rb
app/models/symphony_reader.rb
app/services/cocina/object_creator.rb
app/services/metadata_service.rb
app/services/refresh_metadata_action.rb
spec/requests/create_object_spec.rb

This makes it easier to understand the dataflow.
Test suite
n/a

Associate catch block with the method that uses it 

---

app/services/cocina/object_creator.rb
app/services/cocina/object_updater.rb
app/services/cocina/to_fedora/access.rb
app/services/cocina/to_fedora/content_type.rb
app/services/cocina/to_fedora/process_tag.rb
spec/requests/update_metadata_spec.rb

Update was missing the latest updates to the mapping to access.
Test suite
n/a

Extract a shared module for mapping access to fedora

---

app/services/cocina/object_creator.rb
app/services/cocina/object_updater.rb
app/services/validate_dark_service.rb
spec/services/validate_dark_service_spec.rb

No functional changes.
Previously one precondition was in the validator and one was outside.
Test suite
n/a

[Refactor] Move all preconditions into the validator

---

app/controllers/workspaces_controller.rb

This will allow us to figure out why items may not be being cleaned up.
Test suite
n/a

Instrument cleanup

---

app/controllers/objects_controller.rb
app/services/cocina/from_fedora/dro.rb
app/services/cocina/from_fedora/dro_structural.rb
app/services/cocina/mapper.rb
app/services/solr_connection_error.rb
openapi.yml
spec/requests/show_object_spec.rb
spec/services/cocina/from_fedora/dro_structural_spec.rb

This prevents common-accessioning from logging a 500 with no hint as to why something went wrong
Fixes #933
Test suite
openapi.yml

Give a nice error when solr is down.

---

spec/rails_helper.rb
spec/support/foxml_helper.rb

Keep related functions encapsulated.
Test suite
n/a

Move instantiate_fixture to the foxml_helper

---

app/services/embargo_release_service.rb
spec/services/embargo_release_service_spec.rb

This was caused by an earlier refactoring and went untested. I am fixing this and adding coverage now. Related to a production issue.
Unit tests.
None

Fix bug with 20% visibility embargo releases

---

app/services/cocina/object_creator.rb
app/services/cocina/object_updater.rb
app/services/cocina/to_fedora/identity.rb
spec/requests/create_object_spec.rb
spec/requests/update_metadata_spec.rb

This will support ETDs using the Cocina API to set the agreement.
Test suite
n/a

Add the ability to set and modify the agreement via the cocina API

---

app/jobs/shelve_job.rb

To avoid a timed out connection.  Fixes #943 
Test suite
n/a

Clear database connection after shelving

---

app/services/cocina/to_fedora/access.rb

Add pointer to consul docs on rightsMetadata

---

app/services/cocina/to_fedora/content_metadata_generator.rb

To English a little better.
CI
None

Correct a typo in a constant

---

Gemfile
Gemfile.lock
openapi.yml

Update cocina-models to support controlled digital lending

---

config/initializers/okcomputer.rb

The application has a database now.
Deployed to stage, verified a passing check at /status/database
Updates to DevOpsDocs are pending.

Allow database check

---

app/services/cocina/object_updater.rb
spec/services/cocina/to_fedora/access_spec.rb

Setting rights on a collection is not taking effect
N/A
N/A

Add collection access update

---

Gemfile
Gemfile.lock
app/services/cocina/from_fedora/descriptive.rb
app/services/cocina/from_fedora/descriptive/titles.rb
openapi.yml
spec/services/cocina/from_fedora/descriptive/titles_spec.rb
spec/services/cocina/from_fedora/descriptive_spec.rb

Must be released with 
https://github.com/sul-dlss/sdr-client/pull/132
https://github.com/sul-dlss/dor-services-client/pull/188
To update to the latest cocina-models
Test suite.

Upgrade to cocina-models 0.40.1

---

app/services/cocina/object_creator.rb
spec/requests/create_object_spec.rb

to newly registered items
Fixes https://github.com/sul-dlss/argo/issues/2256
Test suite.

Copy the default use and copyright statements from the APO

---

app/services/cocina/to_fedora/content_metadata_generator.rb
app/services/cocina/to_fedora/resource_type.rb
spec/services/cocina/to_fedora/content_metadata_generator_spec.rb

Fixes https://github.com/sul-dlss/argo/issues/2261

Create correct subresource types for media objects

---

Gemfile.lock

Fixes https://app.honeybadger.io/projects/50568/faults/68130941

Update dor-services to 9.6.2

---

app/services/cocina/from_fedora/descriptive/titles.rb
spec/services/cocina/from_fedora/descriptive/titles_spec.rb

Ref https://github.com/sul-dlss-labs/cocina-descriptive-metadata/pull/18

Update uniform title mapping

---

.rubocop.yml
app/services/cocina/file_set.rb
app/services/cocina/to_fedora/content_metadata_generator.rb
app/services/cocina/to_fedora/resource_type.rb
spec/services/cocina/to_fedora/content_metadata_generator_spec.rb

Ref https://github.com/sul-dlss/argo/issues/2261
Test suite.

Set the thumbnail attribute for media resources that have thumbnails

---

app/services/cocina/to_fedora/descriptive.rb
bin/validate-cocina-roundtrip

Script to test our descriptive cocina mapping on real data

---

app/services/cocina/from_fedora/dro_structural.rb
spec/requests/create_object_spec.rb
spec/requests/update_metadata_spec.rb
spec/services/cocina/from_fedora/dro_structural_spec.rb

Fixes https://github.com/sul-dlss/argo/issues/2262
Tested on stage.

Copy the role attribute from Fedora to use in Cocina

---

app/services/cocina/object_updater.rb
app/services/cocina/to_fedora/process_tag.rb
spec/services/cocina/to_fedora/process_tag_spec.rb

Fixes https://github.com/sul-dlss/argo/issues/2270
Tested in staging and Andrew signed off.

Add a Process : Content Type tag for webarchive-seeds

---

app/services/cocina/to_fedora/descriptive.rb
app/services/cocina/to_fedora/descriptive/note.rb
spec/services/cocina/to_fedora/descriptive/note_spec.rb
spec/services/cocina/to_fedora/descriptive/title_spec.rb
spec/services/cocina/to_fedora/descriptive_spec.rb

Map cocina note to abstract

---

app/services/cocina/to_fedora/descriptive/note.rb
spec/services/cocina/to_fedora/descriptive/note_spec.rb

Add support for multilingual abstract in cocina

---

app/services/cocina/to_fedora/descriptive/note.rb
spec/services/cocina/to_fedora/descriptive/note_spec.rb

Add displayLabel to abstract from cocina

---

app/services/cocina/to_fedora/descriptive.rb
app/services/cocina/to_fedora/descriptive/subject.rb
app/services/cocina/to_fedora/descriptive/title.rb
spec/services/cocina/to_fedora/descriptive/subject_spec.rb
spec/services/cocina/to_fedora/descriptive_spec.rb

Map basic subjects from cocina to MODS

---

app/services/cocina/to_fedora/descriptive.rb
app/services/cocina/to_fedora/descriptive/subject.rb
spec/services/cocina/to_fedora/descriptive/subject_spec.rb
spec/services/cocina/to_fedora/descriptive_spec.rb

Map Cocina subject to MODS XML

---

app/services/cocina/to_fedora/descriptive.rb
app/services/cocina/to_fedora/descriptive/event.rb
app/services/cocina/to_fedora/descriptive/translated_event.rb
spec/services/cocina/to_fedora/descriptive/event_spec.rb
spec/services/cocina/to_fedora/descriptive_spec.rb

Map cocina event to single originInfo dateCreated

---

app/services/cocina/from_fedora/descriptive/event.rb
spec/services/cocina/from_fedora/descriptive/event_spec.rb

To make progress in the mapping of cocina descriptive schema

Map place to cocina event

---

app/services/cocina/from_fedora/descriptive/event.rb
spec/services/cocina/from_fedora/descriptive/event_spec.rb

Map issuance and frequency to cocina model

---

app/services/cocina/to_fedora/descriptive/event.rb
spec/services/cocina/to_fedora/descriptive/event_spec.rb

See https://github.com/sul-dlss-labs/cocina-descriptive-metadata/issues/44

Set the correct MARC eventType

---

spec/services/cocina/to_fedora/descriptive/subject_spec.rb

Provide reason for TODO

---

app/services/cocina/from_fedora/descriptive.rb
app/services/cocina/from_fedora/descriptive/subject.rb
spec/services/cocina/from_fedora/descriptive/subject_spec.rb
spec/services/cocina/from_fedora/descriptive_spec.rb

Map single-term subject topic to cocina model

---

app/services/cocina/from_fedora/descriptive/form.rb
app/services/cocina/to_fedora/descriptive.rb
app/services/cocina/to_fedora/descriptive/form.rb
spec/services/cocina/from_fedora/descriptive/form_spec.rb
spec/services/cocina/from_fedora/descriptive_spec.rb
spec/services/cocina/to_fedora/descriptive/form_spec.rb

To support the cocina mapping.

Map typeOfResource to cocina form

---

app/services/cocina/from_fedora/descriptive.rb
app/services/cocina/from_fedora/descriptive/identifier.rb
spec/services/cocina/from_fedora/descriptive/identifier_spec.rb

Map identifier from MODS to cocina

---

app/services/cocina/to_fedora/descriptive.rb
app/services/cocina/to_fedora/descriptive/contributor.rb
spec/services/cocina/to_fedora/descriptive/contributor_spec.rb

Map cocina contributor to MODS name

---

app/services/cocina/to_fedora/descriptive.rb
app/services/cocina/to_fedora/descriptive/language.rb
spec/services/cocina/to_fedora/descriptive/language_spec.rb

Map basic language from cocina to MODS XML

---

app/services/cocina/to_fedora/descriptive.rb
app/services/cocina/to_fedora/descriptive/identifier.rb
spec/services/cocina/to_fedora/descriptive/identifier_spec.rb

Map MODS identifier to cocina

---

app/services/cocina/from_fedora/descriptive/subject.rb
spec/services/cocina/from_fedora/descriptive/subject_spec.rb

Map geographicCode subject to cocina

---

app/services/cocina/from_fedora/descriptive/contributor.rb
spec/services/cocina/from_fedora/descriptive/contributor_spec.rb
spec/services/cocina/from_fedora/descriptive_spec.rb

We were using incorrect types for names in cocina.

Correct types for contributor names in cocina

---

app/services/cocina/from_fedora/descriptive.rb
app/services/cocina/from_fedora/descriptive/admin_metadata.rb
spec/services/cocina/from_fedora/descriptive/admin_metadata_spec.rb

Map recordInfo to cocina descriptive admin metadata

---

app/services/cocina/to_fedora/descriptive/subject.rb
spec/services/cocina/to_fedora/descriptive/subject_spec.rb

See https://github.com/sul-dlss-labs/cocina-descriptive-metadata/pull/36#pullrequestreview-507853433

Use lcsh as the subject authority

---

.rubocop.yml

Enable new rubocop cops

---

app/services/cocina/from_fedora/descriptive/subject.rb
app/services/cocina/to_fedora/descriptive/subject.rb
spec/services/cocina/from_fedora/descriptive/subject_spec.rb
spec/services/cocina/to_fedora/descriptive/subject_spec.rb

Multi term subject with authority but no valueURI

---

app/services/cocina/from_fedora/descriptive/admin_metadata.rb
spec/services/cocina/from_fedora/descriptive/admin_metadata_spec.rb

Build the descriptionStandard converted from MARC

---

app/services/cocina/from_fedora/descriptive.rb
app/services/cocina/from_fedora/descriptive/related_resource.rb
app/services/cocina/to_fedora/descriptive/related_resource.rb
spec/services/cocina/from_fedora/descriptive/related_resource_spec.rb
spec/services/cocina/from_fedora/descriptive_spec.rb
spec/services/cocina/to_fedora/descriptive/related_resource_spec.rb

Map MODS relatedItem to cocina descriptive

---

app/services/cocina/from_fedora/descriptive.rb
app/services/cocina/from_fedora/descriptive/subject.rb
spec/services/cocina/from_fedora/descriptive/subject_spec.rb

Support subjects with names 

---

app/services/cocina/to_fedora/descriptive/contributor.rb
spec/services/cocina/to_fedora/descriptive/contributor_spec.rb

Add missing contributor roles

---

app/services/cocina/from_fedora/descriptive/form.rb
app/services/cocina/from_fedora/descriptive/subject.rb
spec/services/cocina/from_fedora/descriptive/form_spec.rb
spec/services/cocina/from_fedora/descriptive/subject_spec.rb

Map subject cartographics to cocina

---

app/services/cocina/from_fedora/descriptive/form.rb
app/services/cocina/from_fedora/descriptive/subject.rb
spec/services/cocina/from_fedora/descriptive/form_spec.rb
spec/services/cocina/from_fedora/descriptive/subject_spec.rb

Map MODS subject/genere nodes to cocina form and subject

---

app/services/cocina/to_fedora/descriptive/related_resource.rb

Add a relatedResource type conversion for original

---

app/services/cocina/to_fedora/descriptive/related_resource.rb
spec/services/cocina/from_fedora/descriptive_spec.rb

Fix typo in relatedResource types

---

app/services/cocina/from_fedora/descriptive/contributor.rb
app/services/cocina/from_fedora/descriptive/titles.rb
spec/services/cocina/from_fedora/descriptive/contributor_spec.rb
spec/services/cocina/from_fedora/descriptive_spec.rb

Map MODS contributors with additional subelements to cocina

---

app/services/cocina/from_fedora/descriptive/event.rb
spec/services/cocina/from_fedora/descriptive/event_spec.rb

Map originInfo publisher to cocina event

---

app/services/cocina/to_fedora/descriptive/form.rb
spec/services/cocina/to_fedora/descriptive/form_spec.rb

Map form of type genre from cocina to MODS

---

app/services/cocina/to_fedora/descriptive.rb
app/services/cocina/to_fedora/descriptive/admin_metadata.rb
spec/services/cocina/to_fedora/descriptive/admin_metadata_spec.rb
spec/services/cocina/to_fedora/descriptive/identifier_spec.rb

Map cocina admin_metadata to MODS recordInfo

---

app/services/cocina/to_fedora/descriptive/related_resource.rb

Add constituent resource type

---

app/services/cocina/to_fedora/descriptive/related_resource.rb

Fixes #1181 
Fixes #1168 
Fixes #1166

Add some missing relationship translations

---

app/services/cocina/from_fedora/descriptive/form.rb
app/services/cocina/to_fedora/descriptive/form.rb
spec/services/cocina/from_fedora/descriptive_spec.rb
spec/services/cocina/to_fedora/descriptive/form_spec.rb

Map cocina form to MODS physicalDescription

---

app/services/cocina/from_fedora/descriptive/contributor.rb
app/services/cocina/from_fedora/descriptive/subject.rb
spec/services/cocina/from_fedora/descriptive/subject_spec.rb

Map name subject with multiple nameParts to cocina

---

app/services/cocina/from_fedora/descriptive/event.rb
spec/services/cocina/from_fedora/descriptive/event_spec.rb

Map edition from MODS to cocina event

---

app/services/cocina/to_fedora/descriptive/title.rb
spec/services/cocina/to_fedora/descriptive/title_spec.rb

Map uniform titles from cocina to MODS

---

bin/validate-cocina-roundtrip

Disregard MODS version
Fixes #1179

Normalize the XML comparison

---

app/services/cocina/to_fedora/descriptive/note.rb
app/services/cocina/to_fedora/descriptive/related_resource.rb
spec/services/cocina/to_fedora/descriptive/related_resource_spec.rb

Map relatedItem without type to MODS

---

app/services/cocina/to_fedora/descriptive/subject.rb
spec/services/cocina/to_fedora/descriptive/subject_spec.rb

Map subject-name with multiple name parts to MODS

---

app/services/cocina/from_fedora/descriptive/form.rb
app/services/cocina/to_fedora/descriptive/form.rb
spec/services/cocina/from_fedora/descriptive/form_spec.rb
spec/services/cocina/from_fedora/descriptive_spec.rb
spec/services/cocina/to_fedora/descriptive/form_spec.rb

Map authority properties on form elements to cocina

---

app/services/cocina/from_fedora/descriptive/subject.rb
spec/services/cocina/from_fedora/descriptive/subject_spec.rb

Add a cocina mapping for subject occupation

---

Gemfile
Gemfile.lock
app/services/cocina/from_fedora/access.rb
app/services/cocina/from_fedora/collection.rb
app/services/cocina/object_updater.rb
app/services/cocina/to_fedora/access.rb
openapi.yml
spec/requests/collections_for_object_spec.rb
spec/requests/create_collection_spec.rb
spec/requests/show_object_spec.rb
spec/services/cocina/to_fedora/access_spec.rb
spec/services/cocina/to_fedora/descriptive/title_spec.rb

Update cocina models.
NA
openapi

[HOLD] Updates cocina models.

---

app/services/cocina/to_fedora/descriptive/contributor.rb
spec/services/cocina/to_fedora/descriptive/contributor_spec.rb

Map name with additional subelements to MODS

---

app/services/cocina/to_fedora/descriptive/subject.rb
spec/services/cocina/to_fedora/descriptive/subject_spec.rb

Map model with single subject-topic with authority but no valueURI to MODS

---

Gemfile
Gemfile.lock

To support classification and geographic in cocina models

Update cocina models to 0.42.0

---

app/services/cocina/from_fedora/descriptive.rb
app/services/cocina/from_fedora/descriptive/classification.rb
app/services/cocina/to_fedora/descriptive.rb
app/services/cocina/to_fedora/descriptive/classification.rb
spec/services/cocina/from_fedora/descriptive/classification_spec.rb
spec/services/cocina/to_fedora/descriptive/classification_spec.rb

Fixes #1094 
Blocked by adding to cocina data model.
Unit.
N/A

Map classification to descriptive metadata for cocina

---

app/services/cocina/from_fedora/descriptive/form.rb
spec/services/cocina/from_fedora/descriptive/form_spec.rb

closes #1225
Fix mapping error.
Unit
NA

Handles form source without authorityURI.

---

app/services/cocina/to_fedora/descriptive/related_resource.rb

closes #1237
Add a missing value for related item type.
NA
NA

Adds otherVersion related item type.

---

app/services/cocina/to_fedora/descriptive/related_resource.rb

Add missing related resource type

---

spec/services/cocina/to_fedora/descriptive/subject_spec.rb

Complete subject mapping spec

---

app/services/cocina/from_fedora/descriptive/titles.rb

Closes #1281 by adding additional context to the comment regarding bad data.
N/A
Comment.

Add comment about bad displayLabel

---

config/initializers/okcomputer.rb

ops wants to check for data loss, similarly to argo, prescat, and sul-pub
deployed to qa briefly to verify a passing check
DevOps docs change is upcoming.

Check for data loss via okcomputer endpoint

---

.gitignore
Gemfile
Gemfile.lock
README.md
bin/generate-cache
bin/generate-druid-list
bin/validate-cocina-roundtrip
bin/validate-to-cocina
lib/fedora_cache.rb

Provide tooling for testing Cocina mappings.
Locally.
README

Adds scripts for creating cache and validating mapping to Cocina.

---

bin/validate-to-cocina

Use progressbar for validate-to-cocina

---

README.md

Add some info to the readme on how to run cocina model validations on a server.

add info on how to test mappings on sdr-deploy

---

app/services/cocina/from_fedora/descriptive/subject.rb
spec/services/cocina/from_fedora/descriptive/subject_spec.rb

Ref #1274
On deploy server:
```
795 of 350000 (0.22714285714285715%)%)
```

Handle subject with #N/A authority or subject-name with #N/A types

---

app/services/cocina/from_fedora/descriptive/contributor.rb
spec/services/cocina/from_fedora/descriptive/contributor_spec.rb

Fix #1310 
New unit test; on the console

do not add nil for nameIdentifiers source

---

app/services/cocina/from_fedora/descriptive/contributor.rb
spec/services/cocina/from_fedora/descriptive/contributor_spec.rb

(mostly) fixes #1314 
New unit test added
None

remove invalid namePart type

---

app/services/cocina/from_fedora/descriptive/related_resource.rb
spec/services/cocina/from_fedora/descriptive/related_resource_spec.rb

alert on any non-standard resource types; small refactoring

---

app/services/cocina/from_fedora/descriptive/subject.rb
spec/services/cocina/from_fedora/descriptive/subject_spec.rb

Makes changes for #1277 (but should not close that ticket)
(approach approved by Arcadia)
new unit tests

remove invalid subject subelements

---

README.md
bin/generate-cache
bin/validate-cocina-roundtrip

Allow cache to be regenerated randomly to allow refreshing the cache.
Locally.
README.

Generate random cache

---

bin/validate-to-cocina

Fix stats for validate-to-cocina.

---

README.md
bin/generate-cache
bin/validate-cocina-roundtrip
bin/validate-to-cocina

Improve commandline argument handling.
Locally.
README.

Command args

---

README.md
bin/generate-cache

Provide a mechanism for progressively regenerating the cache.
Locally
README.

Auto regen

---

.rubocop_todo.yml
app/services/cocina/from_fedora/descriptive/contributor.rb

No functional changes.
So we don't have a global limit that is quite so high.

Lower the threshold for Metrics/PerceivedComplexity

---

README.md
bin/validate-cocina-roundtrip

Additional enhancements to the validate-cocina-roundtrip script.
Locally.
NA

Validate-cocina-roundtrip enhancements

---

bin/validate-cocina-roundtrip

The need for speed.
Locally
NA

Parallelizes validate-cocina-roundtrip.

---

bin/validate-to-cocina

Previous approach was resulting the Deadworker errors.
sdr-deploy
NA

Monkeypatch Honeybadger for validate-to-cocina.

---

README.md

Fixed validate-to-cocina command in README.

---

README.md
bin/validate-to-fedora

Make it easier to identify errors raised when mapping to fedora.
Locally
README

Adds bin/validate-to-fedora

---

README.md
bin/generate-cache

Make it easier to generate cache for a list of druids or a single druid.
Locally
README

Add support for providing a list of druids to generate-cache.

---

app/services/cocina/to_fedora/descriptive.rb
app/services/cocina/to_fedora/descriptive/geographic.rb
spec/services/cocina/from_fedora/descriptive/geographic_spec.rb
spec/services/cocina/to_fedora/descriptive/geographic_spec.rb

closes #1378
To fix fedora mapping for geo so does not raise errors.
Unit, locally
NA

Fix to fedora mapping for geo.

---

bin/validate-cocina-roundtrip

Also output the druid and Cocina model, which are helpful for fixing mappings.
Locally
NA

Tweaks to results files.

---

.rubocop.yml
app/services/cocina/from_fedora/descriptive/admin_metadata.rb
app/services/cocina/to_fedora/descriptive/admin_metadata.rb
spec/services/cocina/from_fedora/descriptive/admin_metadata_spec.rb
spec/services/cocina/to_fedora/descriptive/admin_metadata_spec.rb

closes #1385
Map record change date in both directions.
NA

Maps record change date.

---

app/services/cocina/to_fedora/descriptive.rb
spec/services/cocina/to_fedora/descriptive_spec.rb

Matchy, matchy.
Unit, sdr-deply
NA

Determine MODS version from note.

---

Gemfile
Gemfile.lock
spec/rails_helper.rb

To make it easier to compare expected and actual data differences in the test suite.
CI
None

Improve data diffing in test output

---

.rubocop.yml
app/services/cocina/from_fedora/descriptive/titles.rb
app/services/cocina/to_fedora/descriptive/title.rb
spec/services/cocina/from_fedora/descriptive/titles_spec.rb
spec/services/cocina/to_fedora/descriptive/title_spec.rb

To map multiple uniform titles.
NA

Map multi uniform title

---

.rubocop.yml
app/services/cocina/from_fedora/descriptive/titles.rb
app/services/cocina/to_fedora/descriptive/title.rb
spec/services/cocina/from_fedora/descriptive/titles_spec.rb
spec/services/cocina/to_fedora/descriptive/title_spec.rb

closes #1437 
Map titleInfo script attribute
NA

Map titleInfo script attribute

---

app/services/cocina/from_fedora/descriptive/event.rb
app/services/cocina/to_fedora/descriptive/event.rb
spec/services/cocina/from_fedora/descriptive/event_spec.rb

closes #1440
To map type and code placeTerms.
NA

Maps type and code placeTerms.

---

app/services/cocina/from_fedora/descriptive/descriptive_builder.rb
app/services/cocina/from_fedora/descriptive/location.rb
spec/services/cocina/from_fedora/descriptive/location_spec.rb
spec/services/cocina/from_fedora/descriptive_spec.rb

refs #1412
Add support for mapping location from fedora.
NA

Adds support for mapping location from fedora.

---

app/services/cocina/from_fedora/descriptive/location.rb
app/services/cocina/to_fedora/descriptive/descriptive_writer.rb
app/services/cocina/to_fedora/descriptive/location.rb
spec/services/cocina/from_fedora/descriptive/location_spec.rb
spec/services/cocina/to_fedora/descriptive/location_spec.rb
spec/services/cocina/to_fedora/descriptive/related_resource_spec.rb

closes #1412
To complete the mapping for location.
NA

Adds mapping to fedora for location.

---

app/services/cocina/from_fedora/descriptive/language.rb

Remove constants that were only called once, having to reference the top of the file made it harder to read the code.  Also removed unnecessary queries.

[Refactor] Refactor language mapping

---

Gemfile
Gemfile.lock
app/services/cocina/from_fedora/descriptive/descriptive_builder.rb
app/services/cocina/from_fedora/descriptive/related_resource.rb
app/services/cocina/to_fedora/descriptive/descriptive_writer.rb
openapi.yml

* Update cocina model
* Remove omit builder functionality that is no longer necessary.
NA

Update cocina model and remove omitted builders.

---

app/services/cocina/from_fedora/descriptive/notes.rb
app/services/cocina/to_fedora/descriptive/note.rb
spec/services/cocina/from_fedora/descriptive/notes_spec.rb
spec/services/cocina/to_fedora/descriptive/note_spec.rb

closes #1420
Mapping table of contents.
NA

Adds support for mapping table of contents.

---

app/services/cocina/from_fedora/descriptive/subject_authority_codes.rb
spec/services/cocina/from_fedora/descriptive/subject_spec.rb

New ISO codes array to SUBJECT_AUTHORITY_CODES

---

Gemfile
Gemfile.lock
bin/validate-cocina-roundtrip

closes #1471
To make it easier to understand the differences when roundtripping.
Locally
NA

Improves validate-cocina-roundtrip diffing.

---

Gemfile
Gemfile.lock
app/services/mods_equivalent_service.rb
bin/validate-cocina-roundtrip
spec/services/mods_equivalent_service_spec.rb

To allow this functionality to be re-used and to add tests.
Unit, locally
NA

MODS equivalent service

---

app/services/cocina/mods_normalizer.rb
bin/validate-cocina-roundtrip
spec/services/cocina/mods_normalizer_spec.rb

To allow this service to be re-used and tested.
Unit, locally
NA

Add MODS normalizer service

---

Gemfile
Gemfile.lock
app/services/mods_equivalent_service.rb

Replace Levenshtein distance with a less expensive algorithm for determining similarity between nodes.
Locally.
NA

Remove Levenshtein distance.

---

app/services/cocina/from_fedora/descriptive/language.rb
spec/services/cocina/from_fedora/descriptive/language_spec.rb

Handles languageTerm missing code attribute.

---

.rubocop.yml
app/services/mods_equivalent_service.rb
spec/services/mods_equivalent_service_spec.rb

To improve diffing.
Unit, locally.
NA

Improve diffing for altRepGroup and nameTitleGroup.

---

app/services/cocina/from_fedora/descriptive/form.rb
spec/services/cocina/from_fedora/descriptive/form_spec.rb

closes #1545
Account for bad data.
NA

Handle blank genre authority.

---

app/services/cocina/from_fedora/descriptive/subject.rb
spec/services/cocina/from_fedora/descriptive/subject_spec.rb

closes #1552
Maps subject displayLabel.
NA

Maps subject displayLabel.

---

app/services/cocina/to_fedora/descriptive/title.rb
spec/services/cocina/to_fedora/descriptive/title_spec.rb

closes #1546
Map titleInfo displayLabel
NA

Map titleInfo displayLabel.

---

app/services/cocina/to_fedora/descriptive/subject.rb
spec/services/cocina/to_fedora/descriptive/subject_spec.rb

closes #1554
Map cartographic valueURI and authority.
NA

Map cartographic valueURI and authority.

---

app/services/cocina/from_fedora/descriptive/geographic.rb
app/services/cocina/mods_normalizer.rb
bin/validate-cocina-roundtrip
spec/services/cocina/from_fedora/descriptive/geographic_spec.rb
spec/services/cocina/mods_normalizer_spec.rb

closes #1543
closes #1550
Ways to create bad data are infinite.
NA

Normalizes geo PURLs. Notifies on bad geo PURLs.

---

app/services/cocina/from_fedora/descriptive/notes.rb
app/services/cocina/to_fedora/descriptive/note.rb
spec/services/cocina/from_fedora/descriptive/notes_spec.rb

closes #1480
Map multilingual note.
NA

Maps multilingual note.

---

app/services/cocina/from_fedora/descriptive/subject.rb
spec/services/cocina/from_fedora/descriptive/subject_spec.rb

closes #1555
You know, temporal encoding.
NA

Adds encoding for temporal subject.

---

app/services/cocina/from_fedora/descriptive/location.rb
app/services/cocina/mods_normalizer.rb
app/services/cocina/to_fedora/descriptive/location.rb
spec/services/cocina/from_fedora/descriptive/location_access_condition_spec.rb
spec/services/cocina/mods_normalizer_spec.rb
spec/services/cocina/to_fedora/descriptive/location_access_condition_spec.rb

closes #1556
Map access condition.
NA

Map access condition.

---

app/services/cocina/from_fedora/descriptive/notes.rb
app/services/cocina/to_fedora/descriptive/note.rb
spec/services/cocina/from_fedora/descriptive/notes_spec.rb
spec/services/cocina/to_fedora/descriptive/note_spec.rb

closes #1592
Map script attribute for notes.
NA

Adds script to notes.

---

.rubocop.yml
app/services/cocina/from_fedora/descriptive/contributor.rb
app/services/cocina/from_fedora/descriptive/name_builder.rb
app/services/cocina/from_fedora/descriptive/subject.rb
app/services/cocina/from_fedora/descriptive/titles.rb
app/services/cocina/to_fedora/descriptive/contributor.rb
app/services/cocina/to_fedora/descriptive/contributor_writer.rb
app/services/cocina/to_fedora/descriptive/descriptive_writer.rb
app/services/cocina/to_fedora/descriptive/event.rb
app/services/cocina/to_fedora/descriptive/id_generator.rb
app/services/cocina/to_fedora/descriptive/name_title_group.rb
app/services/cocina/to_fedora/descriptive/note.rb
app/services/cocina/to_fedora/descriptive/related_resource.rb
app/services/cocina/to_fedora/descriptive/title.rb
app/services/cocina/to_fedora/descriptive/translated_event.rb
spec/services/cocina/from_fedora/descriptive/contributor_spec.rb
spec/services/cocina/from_fedora/descriptive/subject_name_spec.rb
spec/services/cocina/from_fedora/descriptive/titles_spec.rb
spec/services/cocina/to_fedora/descriptive/contributor_h2_spec.rb
spec/services/cocina/to_fedora/descriptive/contributor_spec.rb
spec/services/cocina/to_fedora/descriptive/event_spec.rb
spec/services/cocina/to_fedora/descriptive/note_spec.rb
spec/services/cocina/to_fedora/descriptive/related_resource_spec.rb
spec/services/cocina/to_fedora/descriptive/title_spec.rb

Fixes nameTitleGroup handling.

---

app/services/cocina/from_fedora/descriptive.rb
spec/services/cocina/from_fedora/descriptive_spec.rb

closes #1622
Report altRepGroup errors.
NA

Notifies for altRepGroup errors.

---

app/services/cocina/from_fedora/descriptive/form.rb
app/services/cocina/to_fedora/descriptive/form.rb
spec/services/cocina/from_fedora/descriptive/form_spec.rb
spec/services/cocina/to_fedora/descriptive/form_spec.rb

closes #1599
Map manuscript.
NA

Maps manuscript.

---

app/services/cocina/from_fedora/descriptive/geographic.rb
app/services/cocina/to_fedora/descriptive/geographic.rb
bin/validate-cocina-roundtrip
spec/services/cocina/from_fedora/descriptive/geographic_spec.rb

closes #1626
Fix geo mapping errors that were raising to_fedora errors.
NA

Geographic mapping fixes. Additional validate-cocina-roundtrip logging.

---

app/services/cocina/from_fedora/descriptive/notes.rb
app/services/cocina/to_fedora/descriptive/note.rb
spec/services/cocina/from_fedora/descriptive/notes_target_audience_spec.rb
spec/services/cocina/to_fedora/descriptive/note_target_audience_spec.rb

closes #1608
Map target audience notes
NA

Maps target audience notes.

---

app/services/cocina/from_fedora/descriptive/notes.rb
spec/services/cocina/from_fedora/descriptive/notes_spec.rb
spec/services/cocina/to_fedora/descriptive/note_spec.rb

closes #1590
Maps multilingual TOCs
NA

Maps multilingual TOCs.

---

app/services/cocina/mods_normalizer.rb
spec/services/cocina/mods_normalizer_spec.rb

Normalizes empty relatedItem parts.

---

app/services/cocina/from_fedora/descriptive/notes.rb
spec/services/cocina/from_fedora/descriptive/notes_spec.rb

closes #1651
Multilingual goodness.
NA

Maps multilingual abstact.

---

app/services/cocina/from_fedora/descriptive/event.rb

I had to puzzle out the method and I couldn't do it with the abbreviated one line notation.  :-(

cocina from_fedora event: refactor for readability

---

app/services/cocina/from_fedora/descriptive/location.rb
app/services/cocina/mods_normalizer.rb
app/services/cocina/to_fedora/descriptive/location.rb
spec/services/cocina/from_fedora/descriptive/location_spec.rb
spec/services/cocina/mods_normalizer_spec.rb
spec/services/cocina/to_fedora/descriptive/location_spec.rb

closes #1654
Map purl attributes and additional purl normalization.
NA

Map purl attributes and additional purl normalization.

---

app/services/cocina/from_fedora/descriptive/alt_rep_group.rb
app/services/cocina/from_fedora/descriptive/contributor.rb
app/services/cocina/from_fedora/descriptive/event.rb
app/services/cocina/from_fedora/descriptive/name_builder.rb
app/services/cocina/from_fedora/descriptive/notes.rb
app/services/cocina/from_fedora/descriptive/subject.rb
app/services/cocina/from_fedora/descriptive/titles.rb
app/services/cocina/to_fedora/descriptive/contributor_writer.rb
spec/services/cocina/from_fedora/descriptive/contributor_spec.rb
spec/services/cocina/to_fedora/descriptive/contributor_spec.rb
spec/services/cocina/to_fedora/descriptive/title_spec.rb

closes #1647
Map transliterated names.
NA

Maps transliterated names. Refactors strategy for handling altRepGroups.

---

app/services/cocina/mods_normalizer.rb
spec/services/cocina/mods_normalizer_spec.rb

closes #1648
Sometimes it is missing.
NA

Normalize geo PURL by adding when missing.

---

app/services/cocina/from_fedora/descriptive/subject.rb
app/services/cocina/to_fedora/descriptive/descriptive_writer.rb
app/services/cocina/to_fedora/descriptive/subject.rb
spec/services/cocina/from_fedora/descriptive/subject_spec.rb
spec/services/cocina/to_fedora/descriptive/subject_classification_spec.rb
spec/services/cocina/to_fedora/descriptive/subject_geographic_spec.rb
spec/services/cocina/to_fedora/descriptive/subject_name_spec.rb
spec/services/cocina/to_fedora/descriptive/subject_spec.rb

closes #1655
Map multilingual subjects.
NA

Maps multilingual subjects.

---

app/services/cocina/from_fedora/descriptive/form.rb
app/services/cocina/to_fedora/descriptive/form.rb
spec/services/cocina/from_fedora/descriptive/form_spec.rb
spec/services/cocina/to_fedora/descriptive/form_spec.rb

Map collection and typeOfResource displayLabel.

---

app/services/cocina/from_fedora/descriptive/location.rb
spec/services/cocina/from_fedora/descriptive/location_spec.rb

Fixes #1677
To fix #1677.
CI
None

Add digital repository to location mapping

---

app/services/cocina/to_fedora/descriptive/subject.rb
spec/services/cocina/from_fedora/descriptive/subject_spec.rb
spec/services/cocina/to_fedora/descriptive/subject_spec.rb

closes #1709
Maps displayLabel, lang, and script for structured subjects
NA

Maps displayLabel, lang, and script for structured subjects.

---

app/services/cocina/from_fedora/descriptive/name_builder.rb
spec/services/cocina/from_fedora/descriptive/contributor_spec.rb

Fixes #1721
```
Success:   91717 (91.717%)
Different: 7621 (7.621%)
```
```
Success:   91854 (91.854%)
Different: 7484 (7.484%)
```

Ignore names with missing nameParts in FromFedora mapping

---

app/services/cocina/mods_normalizer.rb
spec/services/cocina/mods_normalizer_spec.rb

closes #1713
Nothing is normal.
NA

Fixes a flavor of subject authority normalization.

---

app/services/cocina/to_fedora/descriptive/contributor_writer.rb
spec/services/cocina/to_fedora/descriptive/contributor_spec.rb

Before
```
Success:   95536 (95.536%)
Different: 3802 (3.802%)
```
After
```
Success:   95684 (95.684%)
Different: 3654 (3.654%)
```

Map parallel contributor language to fedora

---

app/services/cocina/from_fedora/descriptive/form.rb
app/services/cocina/from_fedora/descriptive/subject.rb
app/services/cocina/mods_normalizer.rb
app/services/cocina/to_fedora/descriptive/subject.rb
spec/services/cocina/from_fedora/descriptive/form_spec.rb
spec/services/cocina/from_fedora/descriptive/subject_spec.rb
spec/services/cocina/mods_normalizer_spec.rb
spec/services/cocina/to_fedora/descriptive/subject_spec.rb

closes #1652
Because cartographics had to be complex too ...
NA

Map/normalize multiple cartographic subjects.

---

app/services/cocina/to_fedora/descriptive/related_resource.rb

[Refactor] Refactor the RelatedResource mapping

---

app/services/cocina/from_fedora/descriptive/subject.rb
spec/services/cocina/from_fedora/descriptive/subject_spec.rb
spec/services/cocina/to_fedora/descriptive/subject_spec.rb

closes #1792
Updated specs from Arcadia.
NA

Removes hardcoded cartograhic encoding.

---

app/services/cocina/mods_normalizer.rb
spec/services/cocina/mods_normalizer_spec.rb

closes #1751
Normalize PURL within relatedItem.
NA

Normalize PURL within relatedItem.

---

app/services/cocina/from_fedora/descriptive/subject_authority_codes.rb
app/services/cocina/to_fedora/descriptive/subject.rb
app/services/cocina/to_fedora/descriptive/title.rb
spec/services/cocina/to_fedora/descriptive/title_spec.rb

closes #1756
Map authority, authorityURI, and valueURI for title. Also, added some authorities for Parker.
NA

Map authority, authorityURI, and valueURI for title.

---

app/services/cocina/from_fedora/descriptive/event.rb
app/services/cocina/to_fedora/descriptive/event.rb
spec/services/cocina/from_fedora/descriptive/event_spec.rb
spec/services/cocina/to_fedora/descriptive/event_spec.rb

closes #1780
Maps presentation.
NA

Maps presentation.

---

app/services/cocina/from_fedora/descriptive/event.rb
app/services/cocina/to_fedora/descriptive/event.rb
spec/services/cocina/from_fedora/descriptive/event_spec.rb
spec/services/cocina/to_fedora/descriptive/event_spec.rb

closes #1783
Map supplied place name.
NA

Map supplied place name.

---

app/services/cocina/from_fedora/descriptive/subject.rb
spec/services/cocina/from_fedora/descriptive/subject_spec.rb

Detect and notify on bad subjects.

---

app/services/cocina/to_fedora/descriptive.rb

I just bumped into it on the way to something else.

rename variable for accuracy

---

spec/services/cocina/from_fedora/descriptive/contributor_spec.rb
spec/services/cocina/to_fedora/descriptive/contributor_spec.rb

Align examples with https://github.com/sul-dlss-labs/cocina-descriptive-metadata/pull/316/files
Unit
NA

Fixes name mapping example 7h.

---

README.md
bin/report
bin/validate-to-cocina
bin/validate-to-fedora

closes #1804
Because Arcadia required it.
sdr-deploy
README

Adds report for finding items with parts.

---

app/services/cocina/from_fedora/descriptive/event.rb
app/services/cocina/mods_normalizer.rb
app/services/cocina/to_fedora/descriptive/event.rb
spec/services/cocina/from_fedora/descriptive/event_spec.rb
spec/services/cocina/mods_normalizer_spec.rb
spec/services/cocina/to_fedora/descriptive/event_spec.rb

Maps originInfo dateValid.

---

spec/services/cocina/from_fedora/descriptive/contributor_spec.rb
spec/services/cocina/to_fedora/descriptive/contributor_spec.rb

closes #1853
Add mapping per Arcadia.
Unit
NA

Add name mapping example 13b.

---

app/services/cocina/from_fedora/descriptive/related_resource.rb
app/services/cocina/from_fedora/descriptive/title_builder.rb
app/services/cocina/mods_normalizer.rb
app/services/cocina/to_fedora/descriptive/related_resource.rb
spec/services/cocina/from_fedora/descriptive/related_resource_part_spec.rb
spec/services/cocina/from_fedora/descriptive/related_resource_spec.rb
spec/services/cocina/mods_normalizer_spec.rb
spec/services/cocina/to_fedora/descriptive/related_resource_part_spec.rb

closes #1805
Map relatedItem part.
NA

Maps relatedItem part.

---

app/services/cocina/from_fedora/descriptive/contributor.rb
spec/services/cocina/from_fedora/descriptive/contributor_spec.rb
spec/services/cocina/from_fedora/descriptive_spec.rb
spec/services/cocina/to_fedora/descriptive/contributor_spec.rb

closes #1846
Per new mapping from Arcadia.
Unit
NA

Adds name mapping example 1b.

---

app/services/cocina/from_fedora/descriptive/name_builder.rb
app/services/cocina/to_fedora/descriptive/contributor_writer.rb
spec/services/cocina/from_fedora/descriptive/contributor_spec.rb
spec/services/cocina/to_fedora/descriptive/contributor_spec.rb
spec/services/cocina/to_fedora/descriptive/title_spec.rb

closes #1822
closes #1827
Per Arcadia.
NA

Adjust status=primary contributor mapping.

---

Gemfile
Gemfile.lock
app/services/cocina/from_fedora/descriptive/admin_metadata.rb
app/services/cocina/to_fedora/descriptive/admin_metadata.rb
openapi.yml
spec/services/cocina/from_fedora/descriptive/admin_metadata_spec.rb
spec/services/cocina/to_fedora/descriptive/admin_metadata_spec.rb

Keep up with the Jones.
Unit
NA

Updated to cocina-models 0.45.0

---

spec/services/cocina/from_fedora/descriptive/form_spec.rb
spec/services/cocina/from_fedora/descriptive/subject_spec.rb
spec/services/cocina/to_fedora/descriptive/subject_spec.rb

Map cartographic subject with multiple coordinate representations.

---

app/services/cocina/from_fedora/descriptive/access.rb
app/services/cocina/mods_normalizer.rb
spec/services/cocina/from_fedora/descriptive/access_spec.rb
spec/services/cocina/mods_normalizer_spec.rb
spec/services/cocina/to_fedora/descriptive/access_spec.rb

closes #1888
Add additional mapping.
NA

Map multiple locations and URLs with usage=primary display

---

spec/services/cocina/from_fedora/descriptive/form_spec.rb
spec/services/cocina/mapping/descriptive/mods/physical_description_spec.rb
spec/services/cocina/to_fedora/descriptive/form_spec.rb

Align physicalDescription with new approach for mapping specs.
Unit
NA

Physical description

---

spec/services/cocina/from_fedora/descriptive/identifier_spec.rb
spec/services/cocina/mapping/descriptive/mods/identifier_spec.rb
spec/services/cocina/to_fedora/descriptive/identifier_spec.rb

reduce ongoing costs of mods/cocina mappings
changes to specs only

mods identifier <--> cocina mapping specs reworked

---

spec/services/cocina/from_fedora/descriptive/related_resource_spec.rb
spec/services/cocina/mapping/descriptive/mods/related_item_spec.rb
spec/services/cocina/to_fedora/descriptive/related_resource_spec.rb

Align related item with new approach for mapping specs.
Unit
NA

Move Related item tests

---

Gemfile
Gemfile.lock
spec/rails_helper.rb
spec/services/cocina/mapping/descriptive/mods/origin_info_publisher_spec.rb
spec/services/cocina/mapping/descriptive/mods/subject_cartographic_spec.rb
spec/support/mods_mapping_spec_helper.rb

Make sure that can perform a complete roundtrip.
Unit
NA

Adds testing of roundtripped MODS to cocina.

---

.rubocop.yml
spec/services/cocina/mapping/descriptive/h2/subject_spec.rb
spec/support/mods_mapping_spec_helper.rb

…to MODS to COCINA (for H2)
* Add tests for H2 subjects.
* Add testing for cocina-first mapping.
Unit
NA

Mapping tests for subject for H2

---

spec/services/cocina/mapping/descriptive/h2/note_spec.rb

Add tests for notes for H2.

---

app/services/cocina/from_fedora/descriptive/event.rb
app/services/cocina/to_fedora/descriptive/event.rb
spec/services/cocina/mapping/descriptive/mods/origin_info_spec.rb

closes #1929
Broken test = bad
NA

Fix Single dateOther test.

---

app/services/cocina/from_fedora/descriptive/event.rb
spec/services/cocina/mapping/descriptive/mods/origin_info_publisher_spec.rb

Fix Publisher - transliterate test.

---

spec/services/cocina/mapping/descriptive/mods/title_info_spec.rb

closes #1923
Working tests are better than broken tests.
Unit
NA

Fix Uniform title with authority test.

---

spec/services/cocina/mapping/descriptive/h2/related_item_spec.rb

Add mapping tests for related resource for H2.

---

app/services/cocina/mods_normalizer.rb
spec/services/cocina/mapping/descriptive/mods/origin_info_spec.rb

closes #1932
Broken test bad.
NA

Fix originInfo eventType differs from date type test.

---

app/services/cocina/mods_normalizer.rb
spec/services/cocina/mapping/descriptive/mods/origin_info_publisher_spec.rb

closes #1943
Broken tests are bad.
NA

Fix Publisher with dateOther type test.

---

app/services/cocina/to_fedora/descriptive/title.rb

Remove dead code

---

app/services/cocina/from_fedora/descriptive/event.rb
app/services/cocina/mods_normalizer.rb
spec/services/cocina/mapping/descriptive/mods/origin_info_place_spec.rb

closes #1946
The test's ancestors once worked.
NA

Fix Place - text (authorized) test.

---

spec/services/cocina/mapping/descriptive/mods/subject_name_spec.rb

Remove cruft.

---

app/services/cocina/from_fedora/descriptive/subject.rb
spec/services/cocina/mapping/descriptive/mods/subject_cartographic_spec.rb

closes #1950
xit indicates test decay.
NA

Fix Cartographic subject with multiple coordinate representations test.

---

spec/services/cocina/mapping/descriptive/mods/part_spec.rb
spec/services/cocina/mapping/descriptive/mods/physical_description_spec.rb
spec/services/cocina/mapping/descriptive/mods/record_info_spec.rb
spec/services/cocina/mapping/descriptive/mods/related_item_spec.rb
spec/services/cocina/mapping/descriptive/mods/table_of_contents_spec.rb
spec/services/cocina/mapping/descriptive/mods/type_of_resource_spec.rb

doing a pass through mapping specs to ensure we're not missing more tests.
last commit fixes two broken specs.

mods mapping spec formatting 

---

app/services/cocina/from_fedora/descriptive/event.rb
app/services/cocina/from_fedora/descriptive/name_builder.rb
app/services/cocina/from_fedora/descriptive/subject.rb
app/services/cocina/from_fedora/descriptive/titles.rb
app/services/cocina/to_fedora/descriptive/name_title_group.rb
spec/services/cocina/from_fedora/descriptive/contributor_spec.rb
spec/services/cocina/from_fedora/descriptive/subject_name_spec.rb
spec/services/cocina/from_fedora/descriptive_spec.rb
spec/services/cocina/mapping/descriptive/mods/name_spec.rb
spec/services/cocina/mapping/descriptive/mods/title_info_spec.rb

closes #1924
Broken tests are bad.
NA

Fix Multilingual uniform title test.

---

spec/services/cocina/mapping/descriptive/mods/name_spec.rb

* Clarify reason for xit.
* Un-xit a working test.
Unit
NA

Name mapping test tweaks.

---

spec/services/cocina/mapping/descriptive/mods/abstract_spec.rb

To partially address #1936 
n/a
n/a

Spec update abstract

---

app/services/cocina/from_fedora/descriptive/access.rb
spec/services/cocina/mapping/descriptive/h2/related_item_spec.rb
spec/services/cocina/mapping/descriptive/mods/related_item_spec.rb

closes #1973
closes #1968
Fix broken tests.
NA

Fixes Related Link test and Related item without title test.

---

spec/services/cocina/mapping/descriptive/mods/name_spec.rb

closes #1987
Test broken.
Unit
NA

Fix name with language test.

---

spec/services/cocina/mapping/descriptive/mods/name_spec.rb

closes #1989
Fix broken test.
Unit
NA

Fix transliterated name with role test.

---

spec/services/cocina/mapping/descriptive/mods/title_info_spec.rb

closes #1978
Fix broken test.
Unit
NA

Fix Complex multilingual title test.

---

spec/services/cocina/mapping/descriptive/mods/name_spec.rb

Update name mapping specs
n/a
n/a

Spec update name

---

spec/services/cocina/mapping/descriptive/h2/access_h2_spec.rb

Add MODS mappings for H2 access

---

spec/services/cocina/mapping/descriptive/h2/note_spec.rb

Closes #1974 Closes #1975 
n/a
n/a

Add MODS mapping to H2 note

---

Gemfile
Gemfile.lock
openapi.yml

Keep cocina-models in sync.
Unit
openapi.yml

Updated cocina-models

---

app/services/cocina/from_fedora/descriptive/notes.rb
app/services/cocina/to_fedora/descriptive.rb
app/services/cocina/to_fedora/descriptive/note.rb
spec/services/cocina/mapping/descriptive/mods/abstract_spec.rb
spec/support/mods_mapping_spec_helper.rb

Implement mapping for abstract with xlink.

---

spec/services/cocina/mapping/descriptive/mods/name_spec.rb

closes #2005
Turns out the test works ...
Unit
NA

Un-xit full name with additional subelements test.

---

spec/services/cocina/mapping/descriptive/mods/subject_name_spec.rb

Add roundtrip mapping and partially address #1936 
n/a
n/a
Implementation tickets #2017 and #2018

Update subject/name mapping spec

---

spec/services/cocina/mapping/descriptive/mods/subject_name_spec.rb

Add a missing mapping
n/a
n/a
Implementation ticketed at #2018

Add MODS mapping for subject name with role

---

spec/services/cocina/mapping/descriptive/mods/subject_name_spec.rb

closes #2019
It just works -- magic!
Unit
NA

Un-xited Name subject with role test.

---

app/services/cocina/from_fedora/descriptive/subject_authority_codes.rb

closes #2028
It was wrong.
NA
NA

Fix iso3166 country code.

---

app/services/cocina/from_fedora/descriptive/subject.rb
app/services/cocina/mods_normalizer.rb
app/services/cocina/to_fedora/descriptive/subject.rb
spec/services/cocina/from_fedora/descriptive/subject_name_spec.rb
spec/services/cocina/mapping/descriptive/mods/subject_spec.rb
spec/services/cocina/mapping/descriptive/mods/subject_topic_spec.rb
spec/services/cocina/mods_normalizer_spec.rb

closes #1962
Tests want to be green.
NA

Fixed multi-term topic subject with authority for terms test.

---

app/services/cocina/from_fedora/descriptive/notes.rb
app/services/cocina/mods_normalizer.rb
spec/services/cocina/mapping/descriptive/mods/note_spec.rb
spec/services/cocina/mapping/descriptive/mods/table_of_contents_spec.rb

Implement mapping for xlink in note.

---

app/services/cocina/from_fedora/descriptive/form.rb
app/services/cocina/to_fedora/descriptive/form.rb
spec/services/cocina/from_fedora/descriptive/form_spec.rb
spec/services/cocina/from_fedora/descriptive_spec.rb
spec/services/cocina/mapping/descriptive/mods/physical_description_spec.rb

closes #1996
Make mapping of physicalDescriptions more consistent.
NA

Implements mapping for multiple physical descriptions.

---

spec/services/cocina/mapping/descriptive/h2/subject_spec.rb

Closes #1967 
n/a
n/a
Implementation ticket: #2058

H2 non fast subject

---

spec/services/cocina/mapping/descriptive/mods/subject_geographic_spec.rb

Closes #2023 
n/a
n/a
Implementation ticket: #2061

Add mapping for hierarchicalGeographic with authority

---

app/services/cocina/from_fedora/descriptive/contributor.rb
app/services/cocina/from_fedora/descriptive/name_builder.rb
app/services/cocina/from_fedora/descriptive/subject.rb
app/services/cocina/mods_normalizer.rb
app/services/cocina/to_fedora/descriptive/contributor_writer.rb
app/services/cocina/to_fedora/descriptive/subject.rb
spec/services/cocina/mapping/descriptive/mods/name_spec.rb
spec/services/cocina/mapping/descriptive/mods/subject_name_spec.rb

closes #2007
More mapping goodness.
NA

Implement mapping for name with xlink.

---

spec/services/cocina/mapping/descriptive/mods/name_spec.rb

Closes #2039 
n/a
n/a
Implementation ticket: #2065

Add mapping for name with multiple affiliations

---

spec/services/cocina/mapping/descriptive/mods/record_info_spec.rb

Closes #2037 
n/a
n/a
Implementation ticket: #2063

Add mapping for multiple recordContentSource

---

app/services/cocina/from_fedora/descriptive/name_builder.rb
spec/services/cocina/mapping/descriptive/mods/name_spec.rb

closes #2065
Yeah mappings!
Unit
NA

Implement mapping for name with multiple affiliations.

---

spec/services/cocina/mapping/descriptive/mods/subject_geographic_spec.rb

closes #2061
The test works.
Unit
NA

Un-xit hierarchicalGeographic subject with authority spec.

---

spec/services/cocina/mapping/descriptive/mods/genre_spec.rb
spec/services/cocina/mapping/descriptive/mods/language_spec.rb
spec/services/cocina/mapping/descriptive/mods/name_spec.rb
spec/services/cocina/mapping/descriptive/mods/subject_classification_spec.rb
spec/services/cocina/mapping/descriptive/mods/subject_genre_spec.rb
spec/services/cocina/mapping/descriptive/mods/subject_spec.rb
spec/services/cocina/mapping/descriptive/mods/title_info_spec.rb
spec/services/cocina/mapping/descriptive/mods/type_of_resource_spec.rb

Closes #1952 
n/a
n/a
Implementation ticket: #1952

Mapping multi primary

---

app/services/cocina/from_fedora/descriptive/admin_metadata.rb
app/services/cocina/to_fedora/descriptive/admin_metadata.rb
spec/services/cocina/from_fedora/descriptive/admin_metadata_spec.rb
spec/services/cocina/mapping/descriptive/mods/record_info_spec.rb

Implement mapping for multiple recordContentSource.

---

.rubocop.yml
app/services/cocina/mods_normalizer.rb
app/services/cocina/mods_normalizers/geo_extension_normalizer.rb
app/services/cocina/mods_normalizers/name_normalizer.rb
app/services/cocina/mods_normalizers/origin_info_normalizer.rb
app/services/cocina/mods_normalizers/subject_normalizer.rb
app/services/cocina/mods_normalizers/title_normalizer.rb
spec/services/cocina/mods_normalizer_spec.rb
spec/services/cocina/mods_normalizers/geo_extension_normalizer_spec.rb
spec/services/cocina/mods_normalizers/name_normalizer_spec.rb
spec/services/cocina/mods_normalizers/origin_info_normalizer_spec.rb
spec/services/cocina/mods_normalizers/subject_normalizer_spec.rb
spec/services/cocina/mods_normalizers/title_normalizer_spec.rb
spec/support/mods_mapping_spec_helper.rb

closes #2050
Code maintainability.
NA

Splits up mods normalizer.

---

spec/services/cocina/mapping/descriptive/h2/note_spec.rb

closes #2011
closes #2012
Green is my favorite color.
Unit
NA

Un-xited H2 note specs.

---

spec/services/cocina/mapping/descriptive/mods/name_spec.rb

Closes #2076 
n/a
n/a
Implementation ticket: #2077

Map corporate and family name with authority

---

spec/services/cocina/mapping/descriptive/mods/subject_title_spec.rb

Closes #2056 
n/a
n/a
Implementation ticket: https://github.com/sul-dlss/dor-services-app/issues/2074

Add mappings for title subject

---

spec/services/cocina/mapping/descriptive/mods/record_info_spec.rb

Closes #2055 
n/a
n/a
Implementation ticket: #2088

Add mapping for descriptive standard with authority

---

spec/services/cocina/mapping/descriptive/mods/subject_genre_spec.rb

Closes #2048 Closes #2049 
n/a
n/a
Implementation ticket: #2090

Add genre subject mappings

---

bin/report

refs #2035
Help with detecting bad data.
Locally
NA

Adds reports for find bad MODS elements and attrs.

---

spec/services/cocina/mapping/descriptive/mods/title_info_spec.rb

Partially addresses #1936 
n/a
n/a
Implementation ticket: #2100

Add title mapping for xlink

---

spec/services/cocina/mapping/descriptive/mods/name_spec.rb

Partially addresses #1936 
n/a
n/a
Implementation ticket: #2102

Add xlink mappings for name and alternativeName

---

.rubocop.yml
app/services/cocina/from_fedora/descriptive/contributor.rb
app/services/cocina/mods_normalizers/name_normalizer.rb
spec/services/cocina/mapping/descriptive/mods/name_spec.rb
spec/services/cocina/mods_normalizers/name_normalizer_spec.rb

closes #2043
Infinite bad data.
NA

Warn for repeated name data error and normalize.

---

spec/services/cocina/mapping/descriptive/mods/name_spec.rb

Model change for more precise mappings
n/a
cocina-descriptive-metadata
Implements model changes made in https://github.com/sul-dlss-labs/cocina-descriptive-metadata/pull/338

Change non-ordered name mappings from structuredValue to groupedValue

---

app/services/cocina/from_fedora/descriptive/admin_metadata.rb
app/services/cocina/from_fedora/descriptive/authority.rb
app/services/cocina/to_fedora/descriptive/admin_metadata.rb
spec/services/cocina/from_fedora/descriptive/admin_metadata_spec.rb
spec/services/cocina/mapping/descriptive/mods/record_info_spec.rb
spec/services/cocina/to_fedora/descriptive/admin_metadata_spec.rb

closes #2088
To bring joy to the world.
NA

Implement descriptive standard with authority.

---

spec/services/cocina/mapping/descriptive/mods/location_spec.rb

Closes #2051 
n/a
n/a
Implementation ticket: #2114

Update location spec

---

app/services/cocina/from_fedora/descriptive/name_builder.rb
app/services/cocina/to_fedora/descriptive/contributor_writer.rb
spec/services/cocina/mapping/descriptive/mods/name_spec.rb

Implement name with display label.

---

app/services/cocina/from_fedora/descriptive/subject.rb

closes #2112
Fix bug.
Locally.
NA

Avoids nil error.

---

app/services/cocina/from_fedora/descriptive/contributor.rb
app/services/cocina/from_fedora/descriptive/form.rb
app/services/cocina/from_fedora/descriptive/language.rb
app/services/cocina/from_fedora/descriptive/primary.rb
app/services/cocina/from_fedora/descriptive/subject.rb
app/services/cocina/from_fedora/descriptive/titles.rb
app/services/cocina/mods_normalizer.rb
app/services/cocina/to_fedora/descriptive/form.rb
app/services/cocina/to_fedora/descriptive/subject.rb
spec/services/cocina/mapping/descriptive/mods/genre_spec.rb
spec/services/cocina/mapping/descriptive/mods/language_spec.rb
spec/services/cocina/mapping/descriptive/mods/name_spec.rb
spec/services/cocina/mapping/descriptive/mods/subject_classification_spec.rb
spec/services/cocina/mapping/descriptive/mods/subject_genre_spec.rb
spec/services/cocina/mapping/descriptive/mods/subject_spec.rb
spec/services/cocina/mapping/descriptive/mods/title_info_spec.rb
spec/services/cocina/mapping/descriptive/mods/type_of_resource_spec.rb
spec/services/cocina/mods_normalizer_spec.rb
spec/support/mods_mapping_spec_helper.rb

closes #2053
Remediate bad data.
NA

Implement mapping for multiple instances of usage=primary.

---

Gemfile
Gemfile.lock
openapi.yml

Latest cocina is the >-est cocina.
Unit
openapi

Updates cocina model.

---

app/services/cocina/from_fedora/descriptive/access.rb
app/services/cocina/from_fedora/descriptive/descriptive_builder.rb
app/services/cocina/from_fedora/descriptive/purl.rb
app/services/cocina/mods_normalizer.rb
spec/services/cocina/mapping/descriptive/mods/location_spec.rb
spec/services/cocina/mods_normalizer_spec.rb

closes #2114
Mapping adjustment
NA

Implement update to location mapping.

---

app/services/cocina/from_fedora/descriptive/title_builder.rb
app/services/cocina/mods_normalizers/title_normalizer.rb
app/services/cocina/to_fedora/descriptive/title.rb
spec/services/cocina/mapping/descriptive/mods/title_info_spec.rb

closes #2100
Mapping goodness.
NA

Implement xlink mapping for title.

---

app/services/cocina/from_fedora/descriptive/name_builder.rb
app/services/cocina/to_fedora/descriptive/contributor_writer.rb
spec/services/cocina/mapping/descriptive/mods/name_spec.rb

closes #2102
Mapping goodness.
NA

Implement xlink mappings for name and alternativeName.

---

spec/services/cocina/mapping/descriptive/mods/genre_spec.rb

Un-xit genre with usage spec.

---

app/services/cocina/from_fedora/descriptive/contributor.rb
app/services/cocina/from_fedora/descriptive/name_builder.rb
app/services/cocina/mods_normalizers/name_normalizer.rb
app/services/cocina/to_fedora/descriptive/contributor_writer.rb
spec/services/cocina/mapping/descriptive/mods/name_spec.rb

Implement etal for contributors.

---

app/services/cocina/from_fedora/descriptive/form.rb
app/services/cocina/to_fedora/descriptive/descriptive_writer.rb
app/services/cocina/to_fedora/descriptive/form.rb
spec/services/cocina/mapping/descriptive/mods/genre_spec.rb
spec/services/cocina/to_fedora/descriptive/form_spec.rb

Implements multilingual form.

---

app/services/cocina/to_fedora/descriptive/title.rb
spec/services/cocina/mapping/descriptive/mods/title_info_spec.rb

closes #2147
So I can get back to watching the impeachment.
Unit, local
NA

Implement mapping for supplied title.

---

bin/report

closes #2141
Root out bad data.
sdr-deploy
NA

Adds report on frequency.

---

spec/services/cocina/mapping/descriptive/mods/origin_info_logic_spec.rb
spec/services/cocina/mapping/descriptive/mods/origin_info_spec.rb

Partly addresses #2128 and #2135
n/a
n/a

Update originInfo spec

---

bin/report

closes #2151
Per Arcadia
sdr-deploy
NA

Adds reports for bad eventTypes and bad valueURIs.

---

app/services/cocina/from_fedora/descriptive/event.rb
app/services/cocina/mods_normalizer.rb
app/services/cocina/mods_normalizers/origin_info_normalizer.rb
app/services/cocina/to_fedora/descriptive/event.rb

Some comments and organization as I figure stuff out along the way.

originInfo mapping - some comments and formatting

---

spec/services/cocina/mapping/descriptive/mods/name_spec.rb
spec/services/cocina/mapping/descriptive/mods/title_info_spec.rb

Closes #2135 (with #2130)
n/a
n/a
Implementation ticket: #2153

Update altRepGroup warnings

---

spec/services/cocina/mapping/descriptive/mods/location_spec.rb

Closes #2134 Closes #2140
n/a
n/a
Implementation ticket: #2155

Update purl mappings

---

spec/services/cocina/mapping/descriptive/mods/related_item_spec.rb

Closes #2146 
n/a
n/a
Implementation ticket: #2157

Add spec for untyped name in related item

---

app/services/cocina/from_fedora/descriptive.rb
spec/services/cocina/from_fedora/descriptive_spec.rb
spec/services/cocina/mapping/descriptive/mods/name_spec.rb
spec/services/cocina/mapping/descriptive/mods/title_info_spec.rb

closes #2153
Per Arcadia, improve warnings.
Unit
NA

Adjust altRepGroup warning.

---

app/services/cocina/from_fedora/descriptive/contributor.rb
spec/services/cocina/mapping/descriptive/mods/related_item_spec.rb

closes #2157
Less warnings are better.
Unit
NA

Implement updated relatedItem mapping.

---

spec/services/cocina/mapping/descriptive/mods/related_item_spec.rb

Just needed a little tweak.
Unit
NA

Unxit Related item with related item spec.

---

bin/refresh-metadata

Make the report more monitorable.
sdr-deply
NA

Tweaks to refresh-metadata script.

---

app/services/cocina/mods_normalizer.rb
spec/services/cocina/mods_normalizer_spec.rb

Normalizes xsi namespace.

---

app/services/cocina/mods_normalizers/subject_normalizer.rb
spec/services/cocina/mods_normalizers/subject_normalizer_spec.rb

Subject norm

---

spec/services/cocina/mapping/descriptive/mods/note_spec.rb

Unxit Note with unmatched altRepGroup spec.

---

app/services/cocina/from_fedora/descriptive/contributor.rb
app/services/cocina/from_fedora/descriptive/name_builder.rb
app/services/cocina/mods_normalizers/name_normalizer.rb
spec/services/cocina/mapping/descriptive/mods/name_spec.rb

Implement Name with valueURI only (authority URI).

---

app/services/cocina/to_fedora/descriptive/contributor_writer.rb
spec/services/cocina/mapping/descriptive/mods/name_spec.rb

closes #2191
Yet Another Variation
NA

Maps namePart type.

---

app/services/cocina/from_fedora/descriptive/subject.rb
spec/services/cocina/mapping/descriptive/mods/subject_geographic_spec.rb

closes #2186
Mapping excellence.
NA

Map hierarchical geographic with authority.

---

spec/services/cocina/mapping/descriptive/mods/related_item_spec.rb

Merge mish-mash broke main.
Unit
NA

Fix broken relatedItem test.

---

app/services/cocina/to_fedora/descriptive/subject.rb
spec/services/cocina/mapping/descriptive/mods/subject_geographic_spec.rb

closes #2193
It's complicated.
NA

Fix mapping for geographic subject authority.

---

app/services/cocina/from_fedora/descriptive/subject.rb
app/services/cocina/mods_normalizers/subject_normalizer.rb
spec/services/cocina/mapping/descriptive/mods/physical_description_spec.rb
spec/services/cocina/mapping/descriptive/mods/subject_spec.rb

Map subject with language attributes

---

app/services/cocina/from_fedora/descriptive/form.rb
app/services/cocina/to_fedora/descriptive/form.rb
spec/services/cocina/from_fedora/descriptive_spec.rb
spec/services/cocina/mapping/descriptive/mods/physical_description_spec.rb

Implement physical description mappings

---

bin/remediate-languageTerm
bin/remediate-naf
bin/repub

closes #2200.
closes #2201.
Bad data -> Good data
sdr-deploy
NA

Adds remediation scrips. Updates repub script.

---

app/services/cocina/from_fedora/descriptive/event.rb
app/services/cocina/to_fedora/descriptive/event.rb
spec/services/cocina/mapping/descriptive/mods/origin_info_date_spec.rb

Fixes sul-dlss/happy-heron#541

Express date ranges as EDTF range in Cocina

---

spec/services/cocina/mapping/descriptive/mods/name_spec.rb
spec/services/cocina/mapping/descriptive/mods/origin_info_date_spec.rb
spec/services/cocina/mapping/descriptive/mods/origin_info_place_spec.rb
spec/services/cocina/mapping/descriptive/mods/origin_info_spec.rb
spec/services/cocina/mapping/descriptive/mods/record_info_spec.rb
spec/services/cocina/mapping/descriptive/mods/subject_cartographic_spec.rb
spec/services/cocina/mapping/descriptive/mods/title_info_spec.rb
spec/services/cocina/mapping/descriptive/mods/type_of_resource_spec.rb

mostly to please the OCD-ed-ness of Naomi and Arcadia.
it's just specs.

reformatting xit specs for consistency, and one is already implemented

---

README.md
bin/cache-o-matic.sh
bin/generate-cache
bin/generate-druid-list

refs #2189
Keep the cache up-to-date-ish.
sdr-deploy
README

Adds script for updating cache.

---

app/services/cocina/mods_normalizer.rb
spec/services/cocina/mods_normalizer_spec.rb

closes #2216
Must reach 100.
NA

Fix altRepGroup normalization.

---

spec/services/cocina/mapping/descriptive/mods/physical_description_spec.rb

Add physicalDescription spec for extent with unit attribute

---

app/services/cocina/from_fedora/descriptive/form.rb
spec/services/cocina/mapping/descriptive/mods/physical_description_spec.rb

closes #2222
Remove MODS cruft.
NA

Remove empty physicalDescription notes.

---

app/services/cocina/from_fedora/descriptive/access.rb
spec/services/cocina/mapping/descriptive/mods/location_spec.rb

closes #2230
Remove MODS cruft.
NA

Do not map empty contact notes.

---

app/services/cocina/from_fedora/descriptive/name_builder.rb
app/services/cocina/to_fedora/descriptive/contributor_writer.rb
spec/services/cocina/mapping/descriptive/mods/name_spec.rb

closes #2231
It slices and dices.
NA

Map lang and script for name.

---

app/services/cocina/from_fedora/descriptive/titles.rb
spec/services/cocina/mapping/descriptive/mods/related_item_spec.rb
spec/support/mods_mapping_spec_helper.rb

Only look for nameTitleGroup within same relatedItem.

---

app/services/cocina/from_fedora/descriptive/subject.rb
spec/services/cocina/mapping/descriptive/mods/subject_classification_spec.rb

closes #2228
Mapping clarity.
NA

Stop ordinalizing edition.

---

app/services/cocina/from_fedora/descriptive/notes.rb
spec/services/cocina/mapping/descriptive/mods/target_audience_spec.rb

closes #2225
Yet Another Attribute.
NA

Map targetAudience displayLabel.

---

app/services/cocina/mods_normalizers/subject_normalizer.rb

closes #2215
Bug fix.
Locally
NA

Handle normalizing subjects with no children.

---

app/services/cocina/to_fedora/descriptive/subject.rb
spec/services/cocina/mapping/descriptive/mods/subject_name_spec.rb

closes #2223
Infinite flavors of metadata.
NA

Map simple name subject with display form and role.

---

spec/services/cocina/mapping/descriptive/mods/note_spec.rb

Closes #2165 
n/a
Implementation ticket #2244 
n/a

Add mapping for note with ID attribute

---

app/services/cocina/mods_normalizer.rb
spec/services/cocina/mods_normalizer_spec.rb

closes #2229
Per @arcadiafalcone 
Unit, local
NA

Remove script and lang attributes from relatedItem.

---

app/services/cocina/to_fedora/descriptive/subject.rb
spec/services/cocina/mapping/descriptive/mods/subject_name_spec.rb

closes #2227
Names needed some hand holding.
NA

Fix name subject mapping error.

---

spec/services/cocina/mapping/descriptive/mods/subject_geographic_spec.rb

Closes #2232
n/a
n/a
Implementation ticket #2253

Add mapping for geographic subject with authority

---

spec/services/cocina/mapping/descriptive/mods/access_condition_spec.rb
spec/services/cocina/mapping/descriptive/mods/location_spec.rb
spec/services/cocina/mapping/descriptive/mods/record_info_spec.rb
spec/services/cocina/mapping/descriptive/mods/related_item_spec.rb
spec/services/cocina/mapping/descriptive/mods/subject_spec.rb

Partially addresses #1936 and completes xlink:href mappings
n/a
n/a
Implementation ticket #2256

Map remaining instances of xlink

---

app/services/cocina/from_fedora/descriptive/notes.rb
app/services/cocina/to_fedora/descriptive/note.rb
spec/services/cocina/mapping/descriptive/mods/note_spec.rb

closes #2244
You know ... ids for notes.
NA

Implement mapping for note with ID attribute.

---

spec/services/cocina/mapping/descriptive/mods/origin_info_spec.rb
spec/services/cocina/mods_normalizers/origin_info_normalizer_spec.rb

to make our roundtripping work
it's all specs

add more specs for originInfo roundtripping and normalization

---

app/services/cocina/from_fedora/descriptive/form.rb
app/services/cocina/to_fedora/descriptive/form.rb
spec/services/cocina/mapping/descriptive/mods/genre_spec.rb

closes #2235
Mapping change.
NA

Implement mapping for genre with form attribute.

---

app/services/cocina/from_fedora/descriptive/subject.rb
app/services/cocina/mods_normalizers/subject_normalizer.rb
app/services/cocina/to_fedora/descriptive/subject.rb
spec/services/cocina/mapping/descriptive/mods/subject_geographic_spec.rb
spec/services/cocina/mapping/descriptive/mods/subject_topic_spec.rb
spec/services/cocina/mods_normalizers/subject_normalizer_spec.rb

closes #2253
Apparently marcgac isn't special.
NA

Implement mapping for geographic subject with authority.

---

app/services/cocina/from_fedora/descriptive/form.rb
app/services/cocina/to_fedora/descriptive/form.rb
spec/services/cocina/mapping/descriptive/mods/physical_description_spec.rb

closes #2265
I made a mistake.
NA

Fix extent unit.

---

spec/services/cocina/mapping/descriptive/mods/title_info_spec.rb

Closes #2266
n/a
n/a
Implementation ticket #2290

Add MODS mapping for unstructured translated title

---

spec/services/cocina/mapping/descriptive/mods/origin_info_date_spec.rb

Add keyDate to date mapping for EDTF encoding

---

spec/services/cocina/mapping/descriptive/mods/subject_spec.rb

Closes #2282 
n/a
n/a
Implementation ticket #2301

Add mapping and warning for subject with xlink and value

---

app/services/cocina/from_fedora/descriptive/subject.rb
app/services/cocina/to_fedora/descriptive/subject.rb
spec/services/cocina/mapping/descriptive/mods/subject_topic_spec.rb

closes #2278
Eventually I'll get it right.
NA

Fix subject topic mismapping.

---

app/services/cocina/to_fedora/descriptive/admin_metadata.rb
spec/services/cocina/mapping/descriptive/mods/record_info_spec.rb

languageTerm mapping when text only (no code).

---

app/services/cocina/to_fedora/descriptive/subject.rb
spec/services/cocina/mapping/descriptive/mods/subject_title_spec.rb

closes #2284
Happy mapping.
NA

Do not write script or lang for subject titles.

---

.rubocop.yml
app/services/cocina/from_fedora/descriptive/related_resource.rb
app/services/cocina/to_fedora/descriptive/related_resource.rb
spec/services/cocina/mapping/descriptive/mods/part_spec.rb

Closes #2269 Closes #2272 Closes #2277
n/a
n/a
Implementation ticket #2298

Rework mappings for MODS part

---

bin/report

closes #2241
Hunt bad data.
sdr-deploy
NA

Report on MODS 3.4 records converted from MARC.

---

app/services/cocina/mods_normalizers/origin_info_normalizer.rb

To reduce cognitive load.  "origin_info" and "normalize" were overused.
```
Status (n=1000; not using Missing for success/different/error stats):
Success:   983 (99.494%)
Different: 5 (0.506%)
Missing (no descMetadata):     12 (1.2%)
```
```
Status (n=1000; not using Missing for success/different/error stats):
Success:   983 (99.494%)
Different: 5 (0.506%)
Missing (no descMetadata):     12 (1.2%)
```

origin_info_normalizer: rename methods for clarity

---

app/services/cocina/from_fedora/descriptive/titles.rb
app/services/cocina/to_fedora/descriptive/title.rb
spec/services/cocina/mapping/descriptive/mods/title_info_spec.rb

closes #2306
Fix parallel titles.
NA

Fix implementation of parallel title roundtrip mapping.

---

app/services/cocina/mods_normalizers/subject_normalizer.rb
spec/services/cocina/mods_normalizers/subject_normalizer_spec.rb

closes #2283
Mapping goodness.
NA

Fix subject normalization error.

---

app/services/cocina/from_fedora/descriptive/admin_metadata.rb
app/services/cocina/to_fedora/descriptive/admin_metadata.rb
app/services/cocina/to_fedora/descriptive/contributor_writer.rb
app/services/cocina/to_fedora/descriptive/role_writer.rb
spec/services/cocina/mapping/descriptive/h2/admin_metadata_h2_spec.rb
spec/services/cocina/mapping/descriptive/h2/contributor_h2_spec.rb
spec/services/cocina/mapping/descriptive/h2/related_item_h2_spec.rb

Implement updated H2 mappings.

---

app/services/cocina/to_fedora/descriptive/subject.rb
spec/services/cocina/mapping/descriptive/mods/subject_geographic_spec.rb

Fix geographic subject mapping error.

---

bin/cache-o-matic.sh
bin/generate-cache
bin/generate-druid-list

Adds quiet option to cache-o-matic and related tools.

---

app/services/cocina/to_fedora/descriptive/title.rb
spec/services/cocina/mapping/descriptive/mods/title_info_spec.rb

closes #2271
Mapping. Enough said.
NA

Fix transliteration mismapping.

---

spec/services/cocina/mapping/descriptive/mods/location_spec.rb

Closes #2325 
n/a
n/a
Implementation ticket #2280

Add mapping for repository with attributes

---

Gemfile
Gemfile.lock
openapi.yml

Update cocina-models to 0.48.0

---

app/services/cocina/from_fedora/descriptive/access.rb
app/services/cocina/to_fedora/descriptive/access.rb
spec/services/cocina/mapping/descriptive/mods/location_spec.rb

closes #2280
codes and values. Or is it values and codes?
NA

Map physical repository with additional attributes.

---

bin/report

refs #1976
Hoping to remediate rather than map.
sdr-deploy
NA

Adds report for bad places.

---

spec/services/cocina/mapping/descriptive/mods/origin_info_spec.rb
spec/services/cocina/mods_normalizers/origin_info_normalizer_spec.rb

Adds some specs indicated in #2240
it's specs

add originInfo mapping and norm specs per #2240

---

spec/services/cocina/mapping/descriptive/mods/physical_description_spec.rb

Closes #2347 
n/a
n/a
Implementation ticket #2355

Add mapping for multilingual physical description

---

spec/services/cocina/mapping/descriptive/mods/part_spec.rb

Closes #2345 
n/a
n/a
Implementation ticket #2353

Map MODS part/extent/list

---

app/services/cocina/from_fedora/descriptive/related_resource.rb
app/services/cocina/to_fedora/descriptive/related_resource.rb
spec/services/cocina/mapping/descriptive/mods/part_spec.rb

Implement part list.

---

spec/services/cocina/mapping/descriptive/mods/origin_info_spec.rb
spec/services/cocina/mods_normalizers/origin_info_normalizer_spec.rb

part of #2145
added specs only

add origin_info_norm spec and origin_info mapping spec for multievent displayLabel

---

spec/services/cocina/mapping/descriptive/mods/origin_info_date_spec.rb
spec/services/cocina/mapping/descriptive/mods/origin_info_event_type_spec.rb

tests for new new simpler mapping of originInfo for clean roundtrips
it is just specs

Origin info logic test

---

spec/services/cocina/mapping/descriptive/mods/origin_info_date_spec.rb

More originInfo spec reworking
n/a
n/a

Update originInfo date specs for new approach

---

Gemfile
Gemfile.lock
app/controllers/objects_controller.rb
app/services/notifications/object_created.rb
config/settings.yml
spec/services/notifications/object_created_spec.rb

https://github.com/sul-dlss/happy-heron/issues/797

Add a rabbitmq message when creating an object

---

spec/services/cocina/mapping/descriptive/mods/origin_info_event_type_spec.rb

Add mapping for copyright notice event

---

app/services/cocina/from_fedora/descriptive.rb
app/services/cocina/mods_normalizer.rb
spec/services/cocina/from_fedora/descriptive_spec.rb
spec/services/cocina/mods_normalizer_spec.rb

closes #2366
Data un-integrity.
NA

Handle MODS version mismatches.

---

app/services/cocina/to_fedora/descriptive/subject.rb
spec/services/cocina/mapping/descriptive/mods/subject_topic_spec.rb

closes #2374
Please let this this be the last.
NA

Map Multi-term topic subject with authority for set and a topic.

---

Gemfile
Gemfile.lock
openapi.yml

Change need by @arcadiafalcone to map Events.
Unit
openapi.yml

Updates cocina model to 0.49.0

---

spec/services/cocina/mapping/descriptive/mods/origin_info_publisher_spec.rb

Update publisher specs

---

spec/services/cocina/mapping/descriptive/mods/origin_info_spec.rb

Updating originInfo mappings for roundtripping
n/a
n/a
Implementation ticket #2390

Update main originInfo mappings

---

app/services/cocina/from_fedora/dro.rb
spec/services/cocina/mapper_spec.rb

See https://github.com/sul-dlss/cocina-models/issues/211

Map geographic metadata to cocina

---

spec/services/cocina/mapping/descriptive/mods/origin_info_place_spec.rb

Mappings
n/a
n/a
Implementation ticket #2398

Spec update place

---

app/controllers/objects_controller.rb
openapi.yml
spec/requests/show_object_spec.rb

This is useful for indexing in ProcessableIndexer where it adds modified_latest_dttsi to solr

Add a way to communicate when the item was last modified

---

spec/services/cocina/mapping/descriptive/h2/event_h2_spec.rb

Improve cocina>mods>cocina roundtripping
n/a
n/a
Implementation ticket #2401

Update event mapping to match new originInfo handling

---

spec/services/cocina/mapping/descriptive/mods/title_info_spec.rb

Closes #2368 
CircleCI
n/a
Implementation ticket #2420

Add mapping for uniform title with duplicate name

---

spec/services/cocina/mapping/descriptive/mods/identifier_spec.rb

Closes #2362 
CircleCI
n/a
Implementation ticket #2422

Add mapping for parallel identifier

---

spec/services/cocina/mapping/descriptive/mods/subject_title_spec.rb

Closes #2372 
CircleCI
n/a
Implementation ticket #2426

Add mapping for uniform title subject

---

spec/services/cocina/mapping/descriptive/mods/subject_cartographic_spec.rb

Closes #2371 
CircleCI
n/a
Implementation ticket #2424

Add mapping for cartographic subject with multiple scale subelements

---

spec/services/cocina/mapping/descriptive/mods/physical_description_spec.rb

Enable progress on #2355 
n/a
n/a

Mapping for multilingual physicalDescription

---

app/services/cocina/from_fedora/descriptive/contributor.rb
app/services/cocina/from_fedora/descriptive/name_builder.rb
app/services/cocina/mods_normalizers/name_normalizer.rb
app/services/cocina/to_fedora/descriptive/contributor_writer.rb
app/services/cocina/to_fedora/descriptive/subject.rb
app/services/cocina/to_fedora/descriptive/title.rb
spec/services/cocina/mapping/descriptive/mods/title_info_spec.rb
spec/services/cocina/mods_normalizers/name_normalizer_spec.rb

Implement duplicate name mapping spec.

---

app/services/mods_equivalent_service.rb
bin/validate-cocina-roundtrip
spec/services/cocina/mods_normalizer_spec.rb
spec/services/cocina/mods_normalizers/name_normalizer_spec.rb

accuracy and clean code reduces cognitive load 
test suite

specs and validate-roundtrip-cocina descriptive typos corrected

---

spec/services/cocina/mapping/descriptive/h2/contributor_h2_spec.rb

Fix minor errors in H2 contributor mapping

---

app/services/cocina/from_fedora/descriptive/subject.rb
app/services/cocina/from_fedora/descriptive/title_builder.rb
app/services/cocina/to_fedora/descriptive/title.rb
spec/services/cocina/mapping/descriptive/mods/subject_title_spec.rb

closes #2426
Mapping is fund.
NA

Implement mapping for uniform title subject.

---

spec/services/cocina/mapping/descriptive/mods/part_spec.rb

Closes #2455 Closes #2485
CircleCI
n/a
Implementation ticket #2499

Add mappings for part

---

spec/services/cocina/mapping/descriptive/mods/name_spec.rb

Closes #2489 
CircleCI
n/a
Implementation ticket #2501

Add mapping for name repeated with different roles

---

app/services/cocina/from_fedora/apo.rb
app/services/cocina/to_fedora/apo_rights.rb
spec/requests/create_object_spec.rb
spec/requests/update_metadata_spec.rb

Ref https://github.com/sul-dlss/argo/issues/2420

Map collectionsForRegistration on AdminPolicies to cocina

---

spec/services/cocina/mapping/descriptive/mods/subject_title_spec.rb

Closes #2526 
CircleCI
n/a
Implementation ticket #2528

Add specs for multiscript titles converted from MARC

---

spec/services/cocina/mapping/descriptive/mods/origin_info_place_spec.rb

Closes #2492 
CircleCI
n/a
Implementation ticket #2535

Add spec for paired placeTerms with different authorities

---

bin/validate-cocina-roundtrip

Admin policies were not being correctly monkeypatched.
Local
NA

Tweak to validate-cocina-roundtrip monkeypatching.

---

spec/services/cocina/mapping/descriptive/mods/genre_spec.rb
spec/services/cocina/mapping/descriptive/mods/subject_cartographic_spec.rb
spec/services/cocina/mapping/descriptive/mods/subject_classification_spec.rb
spec/services/cocina/mapping/descriptive/mods/subject_genre_spec.rb
spec/services/cocina/mapping/descriptive/mods/subject_geographic_spec.rb

Closes #2417 
CircleCI
n/a
Implementation ticket for new mappings: #2530

Update subject mappings and fix typo in genre specs

---

spec/services/cocina/mapping/descriptive/mods/subject_name_spec.rb

Closes #2512 Closes #2488
CircleCI
n/a
Implementation ticket #2524

Update name subject mappings

---

spec/services/cocina/mapping/descriptive/mods/name_spec.rb

Closes #2367
CircleCI
n/a
**NOTE**
https://github.com/sul-dlss/cocina-models/pull/224 needs to be implemented and a new cocina-models gem cut before this PR can be merged.
Implementation ticket #2475

Add mapping for multiscript name and role

---

Gemfile
Gemfile.lock
openapi.yml

Latest is greatest.
Unit
openapi

Updates to cocina-models 0.56.0.

---

app/services/cocina/to_fedora/descriptive/descriptive_writer.rb

I'm seeing some local test flappiness.
Unit
NA

Disambiguates IdGenerator.

---

app/controllers/datastreams_controller.rb
spec/requests/datastreams_spec.rb

Per Andrews request https://github.com/sul-dlss/argo/pull/2522#issuecomment-802269717

Supply the datastream version

---

app/services/cocina/from_fedora/identification.rb
app/services/cocina/object_creator.rb
app/services/cocina/object_updater.rb
spec/requests/create_object_spec.rb
spec/requests/update_metadata_spec.rb
spec/services/cocina/mapper_spec.rb
spec/services/cocina/object_updater_spec.rb

closes #2543
Mapping completeness and required to decouple indexer.
Unit
NA

Maps and updates barcode.

---

Dockerfile

This only affects our test/development environments.
Avoids this concurrency error https://github.com/rails/rails/issues/32451
This happens when Argo registers an object and dor-services-app calls dor-indexing-app
which calls back to dor-services-app for the list of AdministrativeTags.
dor-services-app cannot respond to this second request, so the indexing call times out.
This probably wouldn't be a problem in Rails 6, but ActiveFedora is preventing that upgrade.

Run the docker image in RAILS_ENV=production

---

Gemfile.lock
app/controllers/objects_controller.rb
app/services/cocina/from_fedora/access.rb
app/services/cocina/from_fedora/apo.rb
app/services/cocina/from_fedora/collection.rb
app/services/cocina/from_fedora/dro.rb
app/services/cocina/from_fedora/dro_access.rb
app/services/cocina/from_fedora/embargo.rb
app/services/cocina/object_creator.rb
app/services/cocina/to_fedora/access.rb
app/services/cocina/to_fedora/default_rights.rb
app/services/cocina/to_fedora/dro_access.rb
app/services/cocina/to_fedora/rights.rb
openapi.yml
spec/requests/create_object_spec.rb
spec/requests/update_metadata_spec.rb
spec/services/cocina/from_fedora/access_spec.rb
spec/services/cocina/from_fedora/dro_access_spec.rb

This makes it possible to set all the default rights and related (use statement, copyright, etc) via the Cocina model.

Map the defaultAccess property of the AdminPolicy 

---

.rubocop.yml
.rubocop_todo.yml
app/services/cocina/from_fedora/descriptive/notes.rb
app/services/cocina/from_fedora/descriptive/part_builder.rb
app/services/cocina/from_fedora/descriptive/related_resource.rb
app/services/cocina/to_fedora/descriptive/note.rb
app/services/cocina/to_fedora/descriptive/part_writer.rb
app/services/cocina/to_fedora/descriptive/related_resource.rb
spec/services/cocina/mapping/descriptive/mods/part_spec.rb

Implement top level part mapping.

---

app/services/cocina/from_fedora/descriptive/part_builder.rb
app/services/cocina/to_fedora/descriptive/part_writer.rb
spec/services/cocina/mapping/descriptive/mods/part_spec.rb

Implement mapping for part with hierarchy.

---

bin/reports/report-rights-access_condition
bin/reports/report-rights-missing_use

Help with remediation.
Local
NA

Rights reports

---

app/services/cocina/object_updater.rb
spec/requests/update_metadata_spec.rb

Prior to this change they were only set on create

Default rights should be updated

---

spec/services/cocina/mapping/descriptive/h2/related_item_h2_spec.rb

Closes #2586
CircleCI
n/a
Implementation ticket #2594

Remove relatedResource type to support full roundtrip mapping

---

app/services/cocina/to_fedora/default_rights.rb
spec/services/cocina/to_fedora/default_rights_spec.rb

And fixed a typo in the public domain license
Fixes #2598

Update the ToFedora::DefaultRights to accept missing license

---

spec/services/cocina/mapping/descriptive/mods/note_spec.rb

Closes #2569 
CircleCI
n/a
Implementation ticket #2579

Add mapping for note with type summary turning into abstract

---

spec/services/cocina/mapping/descriptive/mods/subject_name_spec.rb

Add mapping for subject name with affiliation

---

spec/services/cocina/mapping/descriptive/h2/form_h2_spec.rb

Fix H2 Essay value.

---

spec/services/cocina/mapping/descriptive/h2/form_h2_spec.rb

Align with specs for genre and type of resource.
Unit
NA

Fix Data - GIS H2 form spec.

---

spec/services/cocina/mapping/descriptive/h2/event_h2_spec.rb

Closes #2603
CircleCI
n/a
Implementation ticket #2607 and https://github.com/sul-dlss/happy-heron/issues/1306

Update H2 approximate date mappings

---

spec/services/cocina/mapping/descriptive/h2/form_h2_spec.rb

Fix 3d form H2 example.

---

app/services/cocina/mods_normalizer.rb
spec/services/cocina/mapping/descriptive/mods/note_spec.rb
spec/services/cocina/mods_normalizer_spec.rb

Implement roundtrip mapping of note with type summary.

---

spec/services/cocina/mapping/descriptive/h2/form_h2_spec.rb

So that it is in sync with H2.
Unit
NA

Fix software-code H2 example.

---

spec/services/cocina/mapping/descriptive/h2/event_h2_spec.rb

closes #2607
It was easy.
Unit
NA

Implement H2 mappings for approximate dates.

---

Gemfile
Gemfile.lock
openapi.yml

This supports the work of sul-dlss/argo#2404.
CI
OpenAPI spec

Update OpenAPI spec to keep pace with cocina-models 0.57.0

---

app/controllers/objects_controller.rb
app/jobs/unpublish_job.rb
app/services/unpublish_service.rb
config/routes.rb
openapi.yml
spec/jobs/unpublish_job_spec.rb
spec/requests/unpublish_object_spec.rb
spec/services/unpublish_service_spec.rb

Fixes #2538 
New tests for `UnpublishJob`, `UnpublishService`, and a new request spec.
n/a

New Unpublish Endpont

---

app/services/cocina/to_fedora/access.rb
app/services/cocina/to_fedora/default_rights.rb
app/services/cocina/to_fedora/license.rb
config/initializers/rights_metadata_monkeypatch.rb
spec/services/cocina/to_fedora/license_spec.rb

So that we can add cc0 to argo.  Ref https://github.com/sul-dlss/argo/issues/2617

Add support for the cc0 license

---

app/services/cocina/from_fedora/descriptive/subject.rb
spec/services/cocina/mapping/descriptive/h2/subject_h2_spec.rb

Update event subject mapping to fully roundtrip

---

app/services/cocina/from_fedora/descriptive/contributor.rb
app/services/cocina/to_fedora/descriptive/contributor_writer.rb
spec/services/cocina/mapping/descriptive/h2/contributor_h2_spec.rb

Closes #2584 
CircleCI
n/a
Implementation ticket #2591

Streamline H2 contributor mapping to support full roundtripping

---

app/services/cocina/object_updater.rb
spec/services/cocina/object_updater_spec.rb

Remove invalid kwarg

---

app/services/cocina/from_fedora/descriptive/subject.rb
app/services/cocina/mods_normalizers/subject_normalizer.rb
app/services/cocina/to_fedora/descriptive/subject.rb
spec/services/cocina/mapping/descriptive/mods/subject_name_spec.rb
spec/services/cocina/mods_normalizers/subject_normalizer_spec.rb
spec/services/cocina/to_fedora/descriptive/subject_name_spec.rb

closes #2581
Best mapping ever.
NA

Implements additional subject name examples.

---

bin/reports/report-desc-multi_langterms

closes #2486
Report requested by Arcadia.
sdr-deploy
NA

Adds report for records with multiple languageTerms.

---

app/services/cocina/from_fedora/descriptive/form.rb
app/services/cocina/to_fedora/descriptive/form.rb
spec/services/cocina/mapping/descriptive/mods/physical_description_spec.rb

Mapping for multilingual physicalDescription.

---

app/models/marcxml_resource.rb
app/xslt/MARC21slim2MODS3-7_SDR_v2-4.xsl

Closes #2673 
Local transforms
n/a

Update MARC2MODS XSLT to fix parallel 245c mapping

---

spec/services/cocina/mapping/descriptive/mods/subject_spec.rb

Closes #2627 
CircleCI
n/a
Implementation ticket #2687

Add mapping for subject with authorityURI only

---

spec/services/cocina/mapping/descriptive/mods/record_info_spec.rb

Closes #2669 
CircleCI
n/a
Implementation ticket #2689

Add mapping for recordInfoNote

---

spec/services/cocina/mapping/descriptive/mods/name_spec.rb

Add mapping for duplicate name with uniform title

---

app/controllers/objects_controller.rb

Fix typo when sending an updated message

---

spec/services/cocina/mapping/descriptive/mods/subject_name_spec.rb

Closes #2723 Closes #2724 
CircleCI
n/a

Subject name with nested structuredValue/parallelValue; subject name without name type

---

spec/services/cocina/mapping/descriptive/mods/name_spec.rb

Closes #2736 
CircleCI
n/a
Implementation ticket #2738

Add mapping for multiple contributor roles

---

spec/services/cocina/mapping/descriptive/mods/name_spec.rb

Closes #2734
CircleCI
n/a
Implementation ticket #2475

Add mapping for name with altRepGroup and affiliation

---

spec/services/cocina/mapping/descriptive/mods/record_info_spec.rb

Closes #2725 
CircleCI
n/a
Implementation ticket #2740

Add mapping for multiple record modification dates

---

spec/services/cocina/mapping/descriptive/mods/abstract_spec.rb

Closes #2718 
CircleCI
n/a
Implementation ticket #2728

Update abstract specs

---

Dockerfile

Update dockerfile to 2.7.3

---

app/models/marcxml_resource.rb
app/xslt/MARC21slim2MODS3-7_SDR_v2-5.xsl

Closes #2711 Closes #2746
local transforms
n/a

Update MARC2MODS XSLT

---

README.md
bin/validate-rights-cocina-roundtrip

refs #2700
Real data is the best data.
Local
README

Adds tool for validating rights roundtripping.

---

app/services/cocina/to_fedora/administrative_metadata.rb
spec/services/cocina/to_fedora/administrative_metadata_spec.rb

Don't leave unused nodes in administrativeMetadata
