app/controllers/objects_controller.rb, app/services/cocina/object_updater.rb
I found these var names a bit confusing when i was doing some initial debugging on https://github.com/sul-dlss/dor-services-app/issues/2598.  In particular, the use of `obj` as the second param to `ObjectUpdater.run` (and corresponding ivar name in the class) for a cocina model instance, but in the caller (`ObjectsController#update`) as a Fedora object passed as the first param to `ObjectUpdater.run` made it cumbersome to trace through what was happening by copying and running parts of the code individually in Rails console.
unit tests
n/a, though hopefully this hews closer to the convention suggested by https://github.com/sul-dlss/cocina-models/#usage-conventions
=> "obj" var name disambiguation

app/services/cocina/from_fedora/dro.rb, app/services/cocina/object_creator.rb, app/services/cocina/object_updater.rb, app/services/cocina/to_fedora/identity.rb, spec/services/cocina/object_creator_spec.rb
Agreements were being returned with type: "http://cocina.sul.stanford.edu/models/object.jsonld"
=> Return the correct cocina type for agreements

app/services/cocina/object_updater.rb, spec/services/cocina/object_updater_spec.rb
Related to sul-dlss/argo#2562.  Ideally, this should be merged and deployed first, but not super critical (it will just leave some extraneous XML in contentMetadata in certain circumstances if the argo PR is deployed first).
The problem occurs if you change the content type from a book type to a non-book type, as this will currently leave behind the unneeded `<bookData>` node. As noted in a comment in the code, everything in DSA works fine when you switch from a non-book type to a book type, because in this case the changes in sul-dlss/argo#2562 will generate  a completely updated structural part of the cocina-model, which will then rebuild and replace the contentMetadata, thus adding the new `<bookData>` node.  
This PR:
- removes these extra nodes when you are switching content types in …
=> update object updater spec

app/services/legacy_metadata_service.rb
Fixes #2478 - filter hydrus objects out when sending alerts to HB of date mismatches
Existing unit tests
=> Filter hydrus objects out of HB alerts

Gemfile, Gemfile.lock
We don't need to pin simplecov anymore now that we switched to code-climate
=> unpin simplecov

app/services/cocina/object_creator.rb, app/services/ur_admin_policy_factory.rb, config/settings.yml, spec/requests/create_object_spec.rb, spec/services/ur_admin_policy_factory_spec.rb
There is no way to create new objects in the system until the Ur-AdminPolicy exists.  Presently Argo has a factory that writes directly into Fedora to accomplish this, but we want to decouple Argo from Fedora.  Now, we can turn on a feature flag when this is run in a test container which will automatically bootstrap the Ur-AdminPolicy.
=> Bootstrap the Ur-AdminPolicy

app/services/cocina/object_creator.rb
Previously it could get a validation failure when it validated the AdminPolicy and found that it didn't exist yet.  The creation came too late.
=> Create the AdminPolicy before running the validation for its existance

app/services/cocina/from_fedora/file_sets.rb, spec/services/cocina/from_fedora/dro_structural_spec.rb
Fixes #2625 - allow resource labels in cocina to be blank if they are not in contentMetadata.
Cocina model requires label, but should be ok with it blank: https://github.com/sul-dlss/cocina-models/blob/main/lib/cocina/models/file_set.rb#L29
Updated existing test to reflect change.
=> allow resource labels to be blank if they do not exist

Gemfile, Gemfile.lock
Allow values that are optional to be cleared out (set to null).
Ran integration tests on stage & qa.
=> Bump dependency to cocina-models 0.58.1

app/services/cocina/from_fedora/access.rb, app/services/cocina/from_fedora/dro_access.rb, app/services/cocina/to_fedora/access.rb, app/services/cocina/to_fedora/dro_access.rb, spec/services/cocina/from_fedora/access_spec.rb, spec/services/cocina/from_fedora/dro_access_spec.rb, spec/services/cocina/to_fedora/access_spec.rb, spec/services/cocina/to_fedora/dro_access_spec.rb
Connects to sul-dlss/argo#2404
Fixes sul-dlss/argo#2612
Data loss is bad.
CI. Should prolly be tested in QA by @andrewjbtw before we go forward.
None
=> Consistently map licenses, copyright statements, and use statements for items and collections

Gemfile, Gemfile.lock, openapi.yml, spec/requests/update_metadata_spec.rb
This allows some properties of the AdminPolicyDefaultAccess to be set to null
=> Update to cocina 0.58.2

app/services/cocina/from_fedora/dro_structural.rb, app/services/cocina/from_fedora/file_sets.rb, spec/services/cocina/from_fedora/file_sets_spec.rb
There's no need for the FromFedora::FileSet class to know about tags, all it needs to know is whether to notify Honeybadger or not
=> Refactor to make the parameters reveal the intention

app/services/cocina/to_fedora/access.rb, spec/services/cocina/to_fedora/access_spec.rb
Connects to sul-dlss/argo#2404
Without this change, if I have (e.g.) an ODC license set and then set a CC license, the item or collection will now have multiple licenses.
CI
None
=> When setting the license, make sure to blank existing licenses

app/services/cocina/to_fedora/access.rb, app/services/cocina/to_fedora/dro_access.rb, config/initializers/rights_metadata_monkeypatch.rb, spec/services/cocina/to_fedora/dro_access_spec.rb
Connects to sul-dlss/argo#2404
I honestly am not sure if we would ever see this in production but I have data that looks like this in Argo locally and I figured it was worth writing a new test and patching it in. Not sure what the harm is, despite the small cost of added code.
CI, local testing
None
=> Ensure use and license fields are initialized before setting them

config/routes.rb
So we stop getting daily emails from cron that look like this:
```
WARNING: Sidekiq::Web.session_secret= is no longer relevant and will be removed in Sidekiq 7.0. /opt/app/dor_services/dor_services/shared/bundle/ruby/2.7.0/gems/sidekiq-6.2.0/lib/sidekiq/web.rb:75:in `set'
```
See https://github.com/mperham/sidekiq/issues/4846
=> fix deprecation warning from sidekiq

app/services/cocina/object_updater.rb, spec/requests/update_metadata_spec.rb
=> Stop sending an extra parameter to ToFedora::Identity

config/application.rb, config/routes.rb, docker-compose.yml
Fixes #2638
This PR follows the instructions from the Sidekiq docs: https://github.com/mperham/sidekiq/wiki/Monitoring#rails-api-application-session-configuration
It also adds a SECRET_KEY_BASE to the web docker-compose service, which is required now that we switched to RAILS_ENV=production. This value is not used anywhere else, so it seems safe to have here. No .env hijinks needed, I do not think.
CI, locally
None
=> Fix sidekiq web UI

lib/fedora_loader.rb
fedora_loader (part of validate-cocina-roundtrip) needs to monkeypatch AdministrativeTags.for() so that the dsa-client is used to get tags. (Use of AdministrativeTags.for() was recently added to mapping.)
Local
NA
=> Monkeypatch AdministrativeTags.for for fedora_loader.

spec/services/cocina/mapping/descriptive/mods/name_spec.rb, spec/services/cocina/mapping/descriptive/mods/origin_info_place_spec.rb, spec/services/cocina/mapping/descriptive/mods/physical_description_spec.rb, spec/services/cocina/mapping/descriptive/mods/subject_name_spec.rb, spec/services/cocina/mapping/descriptive/mods/subject_title_spec.rb
let(:druid) statements were generating unnecessary data
n/a
n/a
=> Remove remaining let(:druid) statements from specs

app/services/cocina/from_fedora/access.rb, app/services/cocina/from_fedora/dro_access.rb, app/services/cocina/from_fedora/license.rb, app/services/cocina/to_fedora/license.rb, app/services/publish/metadata_transfer_service.rb, app/services/publish/rights_metadata.rb, config/initializers/rights_metadata_monkeypatch.rb, spec/requests/create_object_spec.rb, spec/requests/update_metadata_spec.rb, spec/services/cocina/from_fedora/access_spec.rb, spec/services/cocina/from_fedora/license_spec.rb, spec/services/cocina/to_fedora/access_spec.rb, spec/services/cocina/to_fedora/default_rights_spec.rb, spec/services/cocina/to_fedora/dro_access_spec.rb, spec/services/cocina/to_fedora/license_spec.rb, spec/services/publish/rights_metadata_spec.rb
This allows us to accept more licenses including the CC 4.0 licenses.  This still preserves how we publish the data to PURL, so although we can now accept all the licenses that H2 accepts, PURL will not yet know how to display them all.
Fixes #2628
Fixes #2592
Once this is merged and deployed we should be able to remediate: https://argo.stanford.edu/view/druid:qk286xn8411
=> Create a license node for storing the license URI

app/services/cocina/from_fedora/descriptive/titles.rb, spec/services/cocina/mapping/descriptive/mods/subject_title_spec.rb
Fixes #2528 - extraneous type="parallel" node in some mappings
=> do not type type="parallel" in multiscript titles

lib/fedora_loader.rb
They don't roundtrip, so should be excluded from validation.
sdr-deploy
NA
=> Do not roundtrip parts.

app/validators/cocina/description_roundtrip_validator.rb, spec/validators/cocina/description_roundtrip_validator_spec.rb
closes #2621
Cocina allows empty arrays, which can confuse roundtripping.
Unit
NA
=> Remove blanks when validating descriptive roundtripping.

app/services/publish/rights_metadata.rb
https://github.com/sul-dlss/argo/blob/fcec47fbe7d6acb28597f618025613335d713567/app/forms/apo_form.rb#L87
=> Use the correct URL that matches what is used by Argo

app/controllers/objects_controller.rb, app/services/version_service.rb, spec/requests/start_accession_spec.rb, spec/services/version_service_spec.rb
~~HOLD:~~ Currently causing an integration tests to fail in QA (UPDATE: These tests all fail even with main branch of DSA deployed to QA, so likely unrelated to the work in this PR)
```
SDR_ENV=qa rspec ./spec/features/create_apo_spec.rb:19 # Use Argo to create an APO and verify new objects inherit it's rights is expected to have text "The following defaults will apply to all newly registered objects."
```
~~The pre-assembly spec is causing this exception with the legacy_metadata service: https://app.honeybadger.io/projects/50568/faults/78762991   .... assume because it is closing a version now via the new codepath?  But not sure why this is a problem.~~
-------
Came out of discussions on some work being done by John here: https://github.com/sul-dlss/sdr-api/pull/285 
The method we call …
=> allow objects that are currently opened to be accessioned properly

app/services/embargo_service.rb
Because we're going to need to know this as we decouple DSA from Fedora 3.
=> Document why we write the embargo date to two places

app/services/cocina/from_fedora/descriptive/contributor.rb, spec/services/cocina/mapping/descriptive/mods/name_spec.rb
fixes #2456
unit tests, roundtrip validation on sdr-deploy (as expected, numbers remain unchanged, since this only adds notification for bad data):
```
[deploy@sdr-deploy dor-services-app]$ bin/validate-desc-cocina-roundtrip -s 100000 
Testing |Time: 00:10:27 | ================================================================================== | Time: 00:10:27
Success:   99346 (99.776%)
Different: 223 (0.224%)
Missing (no descMetadata):     431 (0.431%)
[deploy@sdr-deploy dor-services-app]$ 
[deploy@sdr-deploy dor-services-app]$ git checkout 2456-notify-on-names-same-altRepGroup-diff-type
Branch …
```
=> notify if names have same altRepGroup but differ in type

app/services/cocina/from_fedora/descriptive/titles.rb, app/services/cocina/to_fedora/descriptive/title.rb, spec/services/cocina/mapping/descriptive/mods/title_info_spec.rb
* stricter check when mapping cocina `title` `parallelValue` `type` info back to fedora/MODS `titleInfo` `type` attribute
* relax restriction on when MODS `titleInfo` `type` attribute value is included in cocina `title` `parallelValue` element
fixes #2658
unit tests, roundtrip validation script on sdr-deploy
```
[deploy@sdr-deploy dor-services-app]$ bin/validate-desc-cocina-roundtrip -s 500000
Testing |Time: 00:46:08 | ================================================================================== | Time: 00:46:08
Status (n=500000; not using Missing for success/different/error stats):
Success:   496618 (99.791%)
Different: 1042 (0.209%)
Missing (no descMetadata):     2340 (0.468%) …
```
=> tweak mapping of parallel title value types

spec/requests/create_collection_spec.rb, spec/requests/create_object_spec.rb, spec/requests/update_metadata_spec.rb, spec/support/cocina_matchers.rb
The `equal_cocina_model` matcher compares a JSON string as actual value against a Cocina model coerced to JSON as expected value. We want to compare these as JSON rather than as hashes, else we'll have to start deep-converting some values within the hashes, thinking of date/time values in particular. This matching behavior continues what dor-services-app was already doing before this custom matcher was written.
Note, though, that when actual and expected values do *not* match, we coerce both values to hashes to allow the `super_diff` gem to highlight the areas that differ. This is easier to scan than two giant JSON strings.
CI
None
=> Match Cocina structures as JSON but give hashes to SuperDiff

bin/validate-desc-cocina-roundtrip
for easier skimming when coming back to test output, and easier visual comparison of results copied from different runs (i.e., assuage my own OCD tendencies)
small run on sdr-deploy:
```
[deploy@sdr-deploy dor-services-app]$ bin/validate-desc-cocina-roundtrip -s 1
warning: parser/current is loading parser/ruby27, which recognizes
warning: 2.7.2-compliant syntax, but you are running 2.7.1.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
/opt/app/deploy/sdr-deploy/shared/bundle/ruby/2.7.0/gems/actionpack-5.2.5/lib/action_dispatch/middleware/stack.rb:37: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/opt/app/deploy/sdr-deploy/shared/bundle/ruby/2.7.0/gems/actionpack-5.2.5/lib/action_dispatch/mid …
```
=> print current branch info with roundtrip test results

Dockerfile
This reverts commit 5d886e05d7f282a13566b4385aeee4c9d01b6d43.
This is no longer necessary now that mimemagic is no longer in the Gemfile.lock
=> Revert "Add shared-mime-info to the dockerfile"

app/services/publish/metadata_transfer_service.rb, app/services/publish/public_xml_service.rb, app/services/publish/rights_metadata.rb, spec/services/publish/public_xml_service_spec.rb, spec/services/publish/rights_metadata_spec.rb
Previously we were adjusting the rightsMetadata.xml, but purl doesn't use that. It uses the rightsMetadata inside the public xml
=> Adjust the public XML sent to purl to have the new license tag sent

app/services/cocina/object_creator.rb
less confusing var names is ... less confusing.
=> refactor object_creator to use clearer names for objects

app/services/cocina/from_fedora/apo.rb, app/services/cocina/to_fedora/roles.rb
less confusion is a good thing.
unit tests still work.  yay.
=> disambiguate names of some vars in cocina mappings

app/services/embargo_service.rb, app/services/publish/metadata_transfer_service.rb, app/services/publish/public_xml_service.rb, app/services/publish/rights_metadata.rb, spec/services/publish/rights_metadata_spec.rb
There's no reason for us to have this tracked in two places.  This makes it clear which place is the canonical location.
=> Add the embargoReleaseDate to rightsMetadata just as it is sent to purl

config/routes.rb, spec/requests/administrative_tags_spec.rb
Fixes sul-dlss/argo#2611 - admin tags cannot be edited/deleted currently if they have dots in the them due to default rails routing behavior, this fixes it
Added new tests, verified they fail without the routing fix, adding routing fix, see them passing.
=> allow dots in admin tags when routing

app/services/cocina/object_creator.rb, app/services/cocina/object_updater.rb, app/services/cocina/to_fedora/administrative_metadata.rb, spec/services/cocina/object_updater_spec.rb
"apo_rights" was misleading as the class is specific to the administrativeMetadata datastream - no "rights" involved.  If there is a desire to keep "apo" in the name, I would consider "apo_administrative_metadata" as an alternative.
unit tests.
=> rename administrative_metadata (was apo_rights)

app/services/publish/public_xml_service.rb, spec/services/publish/public_xml_service_spec.rb
Previously this was getting returned as an array of DateTime objects which does not serialize automatically into the required format.  This explicitly picks the first element an casts it as expected similar to how OM does: https://github.com/samvera-deprecated/om/blob/cf34329b45f608f6addfe3786c0fcb2ac93ef0e2/lib/om/xml/term.rb#L104
Republished https://argo-stage.stanford.edu/view/druid:dt084sz4619 and now it shows in purl as embargoed
=> Serialize the release date correctly

app/services/publish/metadata_transfer_service.rb, spec/services/publish/metadata_transfer_service_spec.rb
It's unnecessary complexity.  Purl has no used for these files.
=> Don't publish files that purl doesn't use

app/services/publish/rights_metadata.rb, spec/services/publish/rights_metadata_spec.rb
Previously if the rightsMetadata already had a node, it would make a new node rather than replacing the existing node.
=> Prevent duplicate embargoReleaseDate nodes from being sent to PURL

app/services/workflow_client_factory.rb
Fixes #2692 which was a problem because the docker container has no disk persistence
=> Allow the rails log to be used for workflow

app/services/cocina/from_fedora/descriptive/subject.rb, spec/services/cocina/mapping/descriptive/mods/subject_classification_spec.rb
Fixes #2695
Self-evident.
CI + sdr-deploy:
```
$ bin/validate-cocina-roundtrip -s 10000
Success:   9743 (99.959%)
Different: 4 (0.041%)
Update error:     0 (0.0%)
Missing:     0 (0.0%)
Unmapped:     253 (2.53%)
$ bin/validate-desc-cocina-roundtrip -fs 10000
Success:   9952 (99.97%)
Different: 3 (0.03%)
Missing (no descMetadata):     45 (0.45%)
```
```
$ bin/validate-cocina-roundtrip -s 10000
Success:   9743 (99.959%)
Different: 4 …
```
=> Filter out blank subject classification editions

app/controllers/objects_controller.rb, app/services/notifications/object_created.rb, app/services/notifications/object_updated.rb, app/services/notifications/rabbit_channel.rb, spec/services/notifications/object_updated_spec.rb, spec/services/notifications/rabbit_channel_spec.rb
This will allow us to trigger indexing and lower the load on DSA, because we send the model to the channel. Then DSA can read the data off the channel rather than having to make a GET request back to DSA.
Ref #2559
=> Add RabbitMQ notifications when an object is updated

.rubocop.yml, app/services/cocina/to_fedora/administrative_metadata.rb, spec/services/cocina/mapping/administrative/apo_administrative_spec.rb
part of #2704
- Adds roundtripping apo adminstrativeMetadata spec before working on ticket #2659
- doesn't create empty dissemination elements in APO administrativeMetaadata (part of #2644)
- it's a spec, and a fix added because the spec illustrated it.
=> apo adminMetadata mapping: roundtrip spec AND only create disseminationWF if there is one

.rubocop_todo.yml, app/services/cocina/from_fedora/access.rb, app/services/cocina/to_fedora/access.rb, app/services/cocina/to_fedora/rights_metadata_generator.rb, spec/requests/create_object_spec.rb, spec/requests/update_metadata_spec.rb, spec/services/cocina/from_fedora/access_spec.rb, spec/services/cocina/from_fedora/dro_access_spec.rb, spec/services/cocina/to_fedora/rights_metadata_generator_spec.rb
Connects to sul-dlss/argo#2382
Rights metadata containing e.g. file-specific nodes reveal a bug in the prior `FromFedora/Access` implementation, namely the assumption that the presence of a single access=read node is meaningful. Instead of hand-crafted, buggy XPaths, re-use the logic that is already in place in the dor-rights-auth gem.
This PR adds full object-level rights mappings on both the to- and from-fedora sides (32 cases a piece).
CI, locally, and tested in QA by Andrew, who comments below that this is good to go.
None
=> Fix bug with rights determinations when metadata has multiple access nodes

lib/fedora_cache.rb
refs #2700
To test embargo mapping, need to change embargo datastream.
NA
NA
=> Add embargo metadata to cached datastreams.

app/services/version_service.rb, config/settings.yml, spec/services/version_service_spec.rb
This will allow for richer tests in the Argo testing environment, where we don't have a preservation-catalog container.
=> Add a feature flag for synching versions with preservation

.rubocop.yml, app/services/cocina/from_fedora/dro_access.rb, spec/services/cocina/mapping/access/dro_access_spec.rb, spec/support/matchers/deep_ignore_order_matcher.rb
Part of #2701, this PR presents a new spec file that can eventually become the replacement for many of the tests in:
- services/cocina/from_fedora/dro_access_spec.rb
- services/cocina/from_fedora/license_spec.rb
- services/cocina/to_fedora/dro_access_spec.rb
- services/cocina/to_fedora/license_spec.rb
- services/cocina/to_fedora/rights_metadata_generator_spec.rb
Mike and I have solemnly sworn to remove test duplication before #2701 and file level access implementation is done.
This approach, as well as this specific PR, may also ease some testing for @justinlittman as he works on updating embargo and access models in cocina and all the other changes that fall out of it.
it adds a spec.
=> DROAccess symmetrical mapping unit tests - a pattern and some examples

spec/services/cocina/from_fedora/dro_access_spec.rb, spec/services/cocina/mapping/access/dro_access_spec.rb, spec/services/cocina/to_fedora/dro_access_spec.rb
- Adds a couple specs to mapping/access/dro_access_spec
- removes duplicate specs as promised in PR #2753.
I left the from_fedora and to_fedora license specs alone because they appear to be appropriate unit tests for that code ("what if the license is in the XML _this_ way?  _that_ way?  will it find all these cases?)
This adds the example from sul-dlss/cocina-models/issues/236, and thus:
Closes sul-dlss/cocina-models/issues/236
I'm not closing #2701 as I think work in progress in #2744 and #2748 may impact that ticket.
it's a spec.
=> mapping/access/dro_access_spec: add to it and remove duplication elsewhere

.rubocop_todo.yml, app/services/cocina/from_fedora/access.rb, app/services/cocina/from_fedora/access/access_rights.rb, app/services/cocina/from_fedora/dro_structural.rb, app/services/cocina/from_fedora/file_sets.rb, app/services/cocina/object_creator.rb, app/services/cocina/object_updater.rb, app/services/cocina/to_fedora/access.rb, app/services/cocina/to_fedora/dro_access.rb, app/services/cocina/to_fedora/rights/file_level.rb, app/services/cocina/to_fedora/rights/object_level.rb, app/services/cocina/to_fedora/rights_metadata_generator.rb, spec/requests/create_object_spec.rb, spec/requests/update_metadata_spec.rb, spec/services/cocina/from_fedora/dro_access_spec.rb, spec/services/cocina/from_fedora/dro_structural_spec.rb, spec/services/cocina/from_fedora/file_sets_spec.rb, spec/services/cocina/object_updater_spec.rb, spec/services/cocina/to_fedora/rights_metadata_generator_spec.rb
**HOLD** until this can be thoroughly tested in QA/stage
Fixes sul-dlss/argo#2382
These commits complete mapping file-level rights from Fedora to Cocina and back. This is the first SDR implementation of rights mapping at the file level.
CI, and will be tested in QA/stage
None
=> Map file-level rights metadata between Fedora and Cocina

bin/validate-to-desc-cocina
that's the (ruby) way to have a block provide a result and short circuit the rest of its code
fixes #2745
using this branch, i ran `bin/validate-to-desc-cocina` and `bin/validate-to-desc-cocina -s 1000`, and both completed without error (before this change, the latter was consistently crashing as described in the issue).
n/a
=> block for map should use 'next' instead of 'return'

.rubocop.yml
to silence rubocop messages besides cop results.
=> rubocop.yml: add new cop

app/services/cocina/from_fedora/descriptive/hydrus_default_title_builder.rb, spec/services/cocina/from_fedora/descriptive/hydrus_default_title_builder_spec.rb
A small refinement to existing behavior (which used a placeholder for empty-title Hydrus items and fell through to `Titles.build` for a `relatedItem`).  Prevents an unnecessary "Missing title" warning.
connects to #2759
(paired w/ @justinlittman, who suggested this approach to suppressing the warning)
- _This seems like an improvement that didn't fix the issue entirely_: it prevented the `[DATA ERROR] Missing title` alert when `deposit_via_hydrus_spec.rb` deposits an item, but there's still a `Missing title` alert when the collection is created/opened.  This fix also seems prevent the `Missing title` alert that would occur when visiting this Hydrus item's Argo view page: https://argo-stage.stanford.edu/view/druid:bt639bc2787
n/a
=> HydrusDefaultTitleBuilder: skip Titles.build for empty title related item

.rubocop.yml, app/services/cocina/from_fedora/administrative.rb, app/services/cocina/from_fedora/collection.rb, app/services/cocina/from_fedora/dro.rb, app/services/cocina/from_fedora/dro_structural.rb, app/services/cocina/from_fedora/identification.rb, app/services/cocina/to_fedora/identity.rb, spec/services/cocina/mapping/identification/agreement_spec.rb, spec/services/cocina/mapping/identification/apo_spec.rb, spec/services/cocina/mapping/identification/collection_spec.rb, spec/services/cocina/mapping/identification/dro_spec.rb, spec/spec_helper.rb
Part of #2703, this PR presents four new spec files that are focused on the mapping code (from_fedora, to_fedora) that affects identityMetadata.xml for Fedora objects, and Cocina::Identification models.
There is a teeny bit of refactoring included -- trying to get more of the code to follow the naming conventions we agreed on in an infradev meeting ("fedora_collection" "cocina_dro" etc.)
it adds specs.
=> Roundtrip identification mapping specs

app/services/cocina/from_fedora/descriptive/subject.rb, app/services/cocina/normalizers/mods/subject_normalizer.rb, spec/services/cocina/mapping/descriptive/mods/subject_geographic_spec.rb
Currently the MARC standard is to pad out this code to seven digits with dash, however, the lookup table that LOC publishes does not have any padding.
Fixes #2805 
```
Success:   99371 (99.996%)
Different: 4 (0.004%)
Missing (no descMetadata):     625 (0.625%)
```
=> Normalize marcgac codes

app/services/cocina/from_fedora/identification.rb, app/services/cocina/normalizers/identity_normalizer.rb, bin/validate-cocina-roundtrip, spec/services/cocina/mapping/identification/dro_spec.rb, spec/services/cocina/normalizers/identity_normalizer_spec.rb
closes #2804
Handle bad data when mapping,
Unit, local
NA
=> Handle leading and trailing spaces in source id.

app/services/cocina/normalizers/content_metadata_normalizer.rb, spec/services/cocina/normalizers/content_metadata_normalizer_spec.rb
refs #2808
Allow roundtrip testing until we determine how to handle special project phoenix content metadata.
Unit, local
NA
=> Normalize content metadata specific to project phoenix.

app/services/cocina/normalizers/content_metadata_normalizer.rb, spec/services/cocina/normalizers/content_metadata_normalizer_spec.rb
Better map the mapping code.
Unit, local
NA
=> Only normalize reading order when resources are present.

app/services/cocina/normalizers/rights_normalizer.rb, app/services/cocina/to_fedora/license.rb, spec/services/cocina/normalizers/rights_normalizer_spec.rb, spec/services/cocina/to_fedora/license_spec.rb
closes #2803
Empty use statements are an error.
Unit, local
NA
=> Avoid empty use elements.

app/services/cocina/normalizers/rights_normalizer.rb, bin/validate-cocina-roundtrip, bin/validate-rights-cocina-roundtrip, spec/services/cocina/normalizers/rights_normalizer_spec.rb
Fixes #2797 - adjust rights normalization to deal with license code style differences
1. remove the "roundtrip" normalizer (which used to normalize the XML that came back from the roundtrip), which is no longer necessary, and eliminate some methods called by it
2. change the normalizer to take in a datastream as a parameter instead of xml, since the method I am calling to convert to license URIs takes a datastream
Updated tests and tested on sdr-deploy for 100 objects
=> adjust rights normalization for licenses

spec/fixtures/apo_druid_fg890hx1234.xml, spec/fixtures/item_druid_bc123df4567.xml, spec/services/item_query_service_spec.rb, spec/services/publish/dublin_core_service_spec.rb, spec/services/publish/metadata_transfer_service_spec.rb, spec/services/publish/public_desc_metadata_service_spec.rb, spec/services/publish/public_xml_service_spec.rb, spec/services/published_relationships_filter_spec.rb, spec/services/thumbnail_service_spec.rb
This only affects test code
This will get in our way as we move toward using cocina models, which doesn't tolerate invalid druids.
=> Rename test fixture to be a valid druid

spec/services/publish/metadata_transfer_service_spec.rb
This is only a testing change
The mods was provided as the return value from PublicDescMetadataService, not for use as the source mods
=> Remove unnecessary stub

spec/services/cocina/mapping/identification/dro_spec.rb
Fixes #2816 - avoid double escaping in identity metadata on roundtrip
Unxited an existing test
=> update identity metadata specs to reflect what is happening with escaping

app/services/cocina/from_fedora/descriptive/access.rb
There no longer is any "count check"
=> Remove comment that is out of date

app/services/cocina/normalizers/rights_normalizer.rb, spec/services/cocina/mapping/access/collection_access_spec.rb, spec/services/cocina/mapping/access/dro_access_spec.rb, spec/services/cocina/normalizers/rights_normalizer_spec.rb
- to keep future changes to rights_normalizer from inadvertently breaking other expected rightsMetadata.xml mappings
- to ensure our mapping tests are aligned with current rights_normalizer code
part of #2701
it's all unit tests;  wiring in the unit tests found an error in the rights_normalizer code, which is fixed and included here.
=> rightsMetadata.xml mapping "unit" specs: wire in rights_normalizer

app/services/cocina/from_fedora/dro_structural.rb, app/services/cocina/normalizers/identity_normalizer.rb, app/services/cocina/to_fedora/identity.rb, spec/requests/create_object_spec.rb, spec/requests/update_metadata_spec.rb, spec/services/cocina/mapping/identification/agreement_identity_spec.rb, spec/services/cocina/mapping/identification/apo_identity_spec.rb, spec/services/cocina/mapping/identification/collection_identity_spec.rb, spec/services/cocina/mapping/identification/dro_identity_spec.rb, spec/services/cocina/normalizers/identity_normalizer_spec.rb
- to keep future changes to identity_normalizer from inadvertently breaking other expected identityMetadata.xml mappings
- to ensure our mapping tests are aligned with current identity_normalizer code
Closes #2814
Part of #2703
it's all specs; wiring in the unit tests found some errors in the identity_normalizer and mapping code, which are fixed and included here.
=> identityMetadata.xml mapping "unit" specs: wire in identity_normalizer

app/services/publish/access_conditions.rb, app/services/publish/public_desc_metadata_service.rb
This is a pure refactor which helps separate the responsibility for adding accessConditions from the other operations that have to be done to make public descriptive metadata.
=> Extract AccessConditions class from PublicDescMetadataService

lib/tasks/seeds/druid:bx911tp9024.xml, lib/tasks/seeds/druid:hv992ry2431.xml, spec/fixtures/apo_druid_fg890hx1234.xml, spec/fixtures/item_druid_qv648vd4392.xml, spec/fixtures/item_druid_xh235dd9059.xml, spec/fixtures/sdr_repo/dd116zh0343/v0001/data/metadata/identityMetadata.xml, spec/fixtures/sdr_repo/dd116zh0343/v0001/manifests/signatureCatalog.xml, spec/fixtures/sdr_repo/jq937jp0017/v0001/data/metadata/identityMetadata.xml, spec/fixtures/workspace/dd/116/zh/0343/dd116zh0343/metadata/identityMetadata.xml, spec/services/cocina/mapping/identification/dro_identity_spec.rb, spec/services/cocina/normalizers/identity_normalizer_spec.rb, spec/services/sdr_ingest_service_spec.rb
This property has been deprecated and keeping it around in fixtures is confusing
=> Remove agreementId from identityMetadata fixtures

.rubocop.yml, app/services/cocina/normalizers/identity_normalizer.rb, app/services/cocina/object_creator.rb, app/services/cocina/object_updater.rb, app/services/cocina/to_fedora/identity.rb, spec/requests/update_metadata_spec.rb, spec/services/cocina/mapping/identification/agreement_identity_spec.rb, spec/services/cocina/mapping/identification/apo_identity_spec.rb, spec/services/cocina/mapping/identification/collection_identity_spec.rb, spec/services/cocina/mapping/identification/dro_identity_spec.rb, spec/services/cocina/object_updater_spec.rb
closes #2834
Complete roundtrip mapping.
Unit
NA
=> Maps release tags from cocina to fedora.

app/services/cocina/add_purl_to_description.rb, app/services/cocina/from_fedora/descriptive.rb, app/services/cocina/from_fedora/descriptive/access.rb, app/services/cocina/from_fedora/descriptive/descriptive_builder.rb, app/services/cocina/from_fedora/descriptive/purl.rb, app/services/cocina/from_fedora/descriptive/related_resource.rb, app/services/cocina/normalizers/mods_normalizer.rb, app/services/purl.rb
This allows us to accept items in test where the purl link is https://purl-test.stanford.edu and not get a roundtripping error.
Ref https://app.honeybadger.io/projects/50568/faults/79355918
=> Allow the purl base to be configured

app/services/cocina/from_fedora/descriptive/access.rb, app/services/cocina/from_fedora/descriptive/purl.rb, app/services/cocina/from_fedora/descriptive/related_resource.rb, app/services/cocina/normalizers/mods_normalizer.rb, app/services/purl.rb
previously it was using a hardcoded regex, which works for production, but not for staging. It was causing the h2 object that were reaccessioned to fail round trip testing
=> Test for purlness of urls by using the configured base url

app/services/unpublish_service.rb, spec/services/unpublish_service_spec.rb
This prevents a NoMethodError when called from UnpublishJob
Fixes #2853
=> Move the unpublish method to the class

app/controllers/events_controller.rb, spec/factories/events.rb, spec/requests/events_spec.rb
I got confused when i went looking for a replication event on a test object that I'd versioned this morning, and the newest event seemed to be 26 days old.  Turns out the latest events were at the bottom, so i figured there was a SQL query that might need an `order by`.
I guess the consumer of the list could sort it (Argo for example just displays the list in the order it comes back, AFAICT).  But this seems like a fine deterministic default for most consumers, and it was slightly easier to make and test this change here, so I went ahead and sorted in DSA.
Compare this random QA object to this random prod object:
I suspect we mostly get a consistent sort by chance, because SQL results often return in creation order if no other order is specified (but of course, that's not guaranteed).
=> EventsController: return event list sorted by creation date (newest first)

app/jobs/unpublish_job.rb
To address this question to JCoyne in slack:
```
is this vestigial from some testing?  druid qs084jr2183 doesn’t exist. https://dor-services-prod.stanford.edu/queues/retries.
```
A manual integration test that ensure no errors are thrown all the way through the process is indicated.
=> Add missing kwarg when unpublishing

app/services/publish/access_conditions.rb, spec/services/publish/public_desc_metadata_service_spec.rb
=> Add missing xlink namespace on publish

app/services/cocina/normalizers/embargo_normalizer.rb, app/services/cocina/object_creator.rb, bin/validate-cocina-roundtrip, spec/services/cocina/normalizers/embargo_normalizer_spec.rb
closes #2837
Object create will help find unmapped, existing data that object update does not.
Unit, local
NA
=> Add support for roundtrip validation using object create.

app/services/embargo_release_service.rb, app/services/notifications/embargo_lifted.rb, spec/services/embargo_release_service_spec.rb, spec/services/notifications/embargo_lifted_spec.rb
So that h2 can log that the embargo was lifted.
Ref https://github.com/sul-dlss/happy-heron/issues/1347
=> Publish a RabbitMQ message when an embargo is lifted on an object

app/services/cocina/from_fedora/descriptive/value_uri.rb, spec/services/cocina/from_fedora/descriptive/value_uri_spec.rb
closes #2451
Handle bad data.
NA
=> Handle blank valueURIs.

Gemfile.lock, openapi.yml
Fixes #2851 - validate lane medical barcodes
~~[HOLD] for sul-dlss/cocina-models#262 and updated version of the gem~~
=> allow lane medical barcodes to validate

app/services/publish/license.rb
So that this change will work: https://github.com/sul-dlss/happy-heron/pull/1590
=> Update licenses to their https version.

app/services/publish/license.rb, config/licenses.yml, spec/services/publish/public_desc_metadata_service_spec.rb
This was requested by the access team in 2021-06-09 to support new licenses, so they don't need to maintain a lookup table.
=> Add a descriptive message in accessMetadata for new licenses

app/controllers/marcxml_controller.rb, app/controllers/metadata_refresh_controller.rb, app/controllers/objects_controller.rb, app/models/symphony_reader.rb, spec/models/symphony_reader_spec.rb, spec/requests/create_object_spec.rb, spec/requests/get_catkey_spec.rb, spec/requests/get_marcxml_spec.rb, spec/requests/metadata_refresh_spec.rb
When you send a catkey that symphony doesn't know about, it should be a you problem, not a me problem.
=> Return a 400 bad request when catkey isn't found

app/validators/cocina/description_roundtrip_validator.rb
Troubleshooting with JSON is easier than a Ruby hash.
NA
NA
=> Log JSON for easier troubleshooting.

app/services/cocina/to_fedora/identity.rb, spec/services/cocina/to_fedora/identity_spec.rb
Currently a cocina update appends release tags, which causes an exponential proliferation of release tags.  The correct approach is to overwrite these tags.
=> Cocina update should overwrite release tags

openapi.yml
to silence some warnings from running `openapi-enforcer validate openapi.yml`
Same as in sul-dlss/cocina-models/pull/268
openapi validator, unit tests
=> Openapi.yml: tweaks to silence validator warnings

Gemfile, Gemfile.lock, openapi.yml
Hold because this must be released in conjunction with the dor-services-client release.
=> Update cocina-models to 0.61.0

app/controllers/objects_controller.rb, config/routes.rb, openapi.yml, spec/requests/update_doi_metadata_spec.rb
We will need to be able to update DOI metadata at DataCite;  the mechanism chosen is for DSA to perform these requests.  
This PR is for a dummy endpoint so other tickets can be unblocked as we wait for definitive DataCite mappings from Arcadia.
part of #2912
request spec added.
openapi.yml
=> update_doi_metadata endpoint added

app/services/doi.rb, config/settings.yml, spec/requests/create_object_spec.rb, spec/services/cocina/object_creator_spec.rb
This prefix belongs to a set of credentials that include a username and password
=> Rename doi_prefix to datacite.prefix

spec/support/mods_mapping_spec_helper.rb
confusion is bad.
it's a comment change.
=> spec/support/mods_mapping_spec_helper: improve on confusing comment

app/services/cocina/to_datacite/attributes.rb, app/services/cocina/to_datacite/title.rb, spec/services/cocina/mapping/descriptive/h2_datacite/title_h2_datacite_spec.rb, spec/services/cocina/to_datacite/attributes_spec.rb
Arcadia's specs and my additions to them
=> datacite mappings: cocina title -> datacite titles

app/services/cocina/to_datacite/attributes.rb, app/services/cocina/to_datacite/identifier.rb, spec/services/cocina/mapping/descriptive/h2_datacite/identifiers_h2_datacite_spec.rb, spec/services/cocina/to_datacite/attributes_spec.rb
Arcadia's specs and my additions to them.
=> datacite mappings: cocina identifier and purl -> datacite identifiers

app/services/synchronous_indexer.rb, spec/services/synchronous_indexer_spec.rb
Earlier today I had failures in the argo test suite when DSA was unable to write to the index.  There were no errors, making this difficult to track down.
=> Log errors when the indexing service is unreachable

spec/services/cocina/mapping/descriptive/h2_datacite/related_resource_h2_datacite_spec.rb
Deactivate mapping that won't be used until next version of API
CircleCI
n/a
=> Comment out DataCite relatedItem mapping unsupported by the REST API v2

app/services/cocina/to_datacite/attributes.rb, app/services/cocina/to_datacite/related_resource.rb, spec/services/cocina/mapping/descriptive/h2_datacite/related_resource_h2_datacite_spec.rb, spec/services/cocina/to_datacite/attributes_spec.rb
Deactivate relatedItem DataCite mapping that won't be used until version 3 of DataCite ReST API (current version is 2)
unit tests
=> cocina to datacite mappings: DataCite relatedItem not yet supported

app/services/cocina/to_datacite/attributes.rb, app/services/cocina/to_datacite/subject.rb, spec/services/cocina/mapping/descriptive/h2_datacite/subject_h2_datacite_spec.rb, spec/services/cocina/to_datacite/attributes_spec.rb
Arcadia's specs and my additions to them
=> datacite mappings: cocina subjects -> DataCite subjects

.rubocop.yml
=> rubocop.yml: take out unnec excludes

app/services/cocina/to_datacite/event.rb, spec/services/cocina/to_datacite/event_pub_year_spec.rb
This PR implements extracting correct publication year for DataCite mapping from cocina events
unit tests adapted from Arcadia's tests
=> datacite mappings: cocina event -> DataCite publicationYear with unit tests

app/services/cocina/to_datacite/event.rb, spec/services/cocina/to_datacite/event_pub_year_spec.rb
To align with the latest from Arcadia, and because clear, useful comments lower maint costs
unit tests
=> comment tweaks re: datacite publicationYear mapping

.rubocop.yml, app/services/cocina/to_datacite/event.rb, spec/services/cocina/to_datacite/event_dates_spec.rb
~~[Hold until Arcadia clarifies Submitted date algorithm and Created date algorithm and until PR #2949 is merged so this can be rebased.]~~
This PR implements extracting correct date info for DataCite from cocina events
unit tests adapted from Arcadia's tests
=> datacite mappings: cocina event -> DataCite dates with unit tests

spec/services/cocina/mapping/descriptive/h2/contributor_h2_spec.rb
MODS roundtrip required
CircleCI
n/a
=> Remove unroundtrippable data from H2-Cocina-MODS contributor mapping

spec/services/cocina/mapping/descriptive/h2/subject_h2_spec.rb
Add missing mapping (supersedes #2957)
CircleCI
n/a
Implementation ticket #2961
=> Add H2-MODS mapping for multiple subject terms

spec/services/cocina/mapping/descriptive/h2/contributor_h2_spec.rb
To correct mapping
CircleCI
n/a
=> Remove misplaced note

app/services/cocina/to_datacite/subject.rb
We don't need to check for presence because compact is already doing that.
=> prevent duplicate calls to the subject method

app/services/cocina/from_fedora/descriptive/identifier_builder.rb, app/services/cocina/from_fedora/descriptive/name_builder.rb, app/services/cocina/to_fedora/descriptive/contributor_writer.rb, spec/services/cocina/mapping/descriptive/h2/contributor_h2_spec.rb, spec/services/cocina/mapping/descriptive/mods/name_spec.rb, spec/services/cocina/mapping/descriptive/mods/origin_info_publisher_spec.rb
part of #2960
This implements roundtrippable contributor mappings in DSA to support h2 functionality.
unit tests
=> H2 contrib roundtrip mappings

app/services/cocina/to_datacite/form.rb, spec/services/cocina/mapping/descriptive/h2_datacite/form_h2_datacite_spec.rb
NOTE:  **It may be advantageous NOT to merge this and wait for correct, roundtrippable mappings from @arcadiafalcone.**
To be able to debug `update_doi_metadata` endpoint and `UpdateDoiMetadataJob`   
If this is merged, issue #2979 is about removing the hardcodings.
created some H2 objects in stage.
=> datacite form mappings hardcoded as a stopgap

.rubocop.yml, app/services/cocina/object_updater.rb, spec/services/cocina/object_updater_spec.rb
Currently if an item has multiple project tags, it is causing a retry loop because the code is assuming that there will be only one project tag. This raises an error when more than one project tag is encountered.
Unit, production
=> Avoid retry loop when multiple project tags

app/services/cocina/from_fedora/descriptive/event.rb
=> Remove an unnecessary compact call

spec/services/cocina/mapping/descriptive/mods/datacite_extension_spec.rb
To help with testing Cocina>MODS>Cocina roundtrip for DataCite extension.
CircleCI
n/a
=> Add MODS>Cocina mapping for roundtripping DataCite resourceTypeGeneral

app/services/publish/public_desc_metadata_service.rb, spec/services/publish/public_desc_metadata_service_spec.rb
This allows the DOI to display in PURL
=> Export doi to the public desc metadata

app/services/cocina/to_datacite/attributes.rb, spec/services/cocina/to_datacite/attributes_spec.rb
It is required in order to produce a findable DOI
=> Set the datacite publisher

spec/services/cocina/mapping/descriptive/h2_datacite/contributor_h2_datacite_spec.rb
Datacite Role no longer added to descriptive cocina.
=> Remove Datacite Role from contributor mapping specs.

spec/services/cocina/mapping/descriptive/h2_datacite/creators_h2_datacite_spec.rb, spec/services/cocina/to_datacite/event_dates_spec.rb, spec/services/cocina/to_datacite/event_pub_year_spec.rb
closes #3020
H2 is no longer sending DataCite roles.
Unit
=> Remove DataCite roles from specs.

app/services/publish/public_desc_metadata_service.rb, spec/services/publish/public_desc_metadata_service_spec.rb
closes #3021
Prefer valid XML.
Unit
NA
=> Correctly sets namespace for mods identifier.

app/controllers/objects_controller.rb, openapi.yml, spec/requests/start_accession_spec.rb
Previously we were using 406, which should only be used for content negotiation.  This was an improper use and the client was not handling it, so sdr-client would re-queue the request and get into a loop.
=> Use a conflict error when accessioning can't be started

app/services/publish/metadata_transfer_service.rb, app/services/publish/public_cocina_service.rb, spec/services/publish/metadata_transfer_service_spec.rb, spec/services/publish/public_cocina_service_spec.rb
So that we can begin sharing the new Cocina models with the Access team.   This change sanitizes the structural by removing any non-published fileset/files just as is done in the public xml.
Fixes #734
To be tested on stage.
=> Publish Cocina models to purl

app/services/publish/public_xml_service.rb, spec/services/publish/public_xml_service_spec.rb
Fixes https://github.com/sul-dlss/purl/issues/528 and fixes https://github.com/sul-dlss/content_search/issues/350 by converting the internal resource identifiers to xml:id-valid identifiers.
=> Remove cocina urls from published resource ids

app/services/datastream_extractor.rb, spec/services/datastream_extractor_spec.rb
Fixes downstream error in Preservation Catalog that causes the following error when running integration tests:
Unit and integration tests
n/a
=> Sets provenanceMetadata to false with test change

app/services/sdr_ingest_service.rb, spec/services/sdr_ingest_service_spec.rb
In ruby typically we don't use methods beginning with `get_`
=> [refactor] Update method names to use idiomatic ruby

app/services/cocina/object_updater.rb, app/services/cocina/to_fedora/process_tag.rb, spec/services/cocina/to_fedora/process_tag_spec.rb
This was causing a problem in ObjectUpdater when it tries to add a tag with a nil value
=> Handle a nil process content type tag

.rubocop.yml
Remove warnings when running rubocop
=> Enable new rubocops

README.md, bin/validate-cocina-roundtrip
Create is better than update because it requires less normalization.
Local
README
=> Switch validate-cocina-roundtrip to default to create.

app/services/cocina/normalizers/content_metadata_normalizer.rb, spec/services/cocina/normalizers/content_metadata_normalizer_spec.rb
closes #3114
Roundtripping happiness.
Sequence is not always present for every resource node in content metadata, but is present when mapped from cocina.
Before:
```
Success:   9038 (90.489%)
Different: 918 (9.191%)
Create error:     32 (0.32%)
Missing:     4 (0.04%)
Expected unmapped:     8 (0.08%)
```
After:
```
Success:   9465 (94.764%)
Different: 481 (4.816%)
Mapping error:     10 (0.1%)
Create error:     32 (0.32%)
Missing:     4 (0.04%)
Expected unmapped:     8 (0.08%)
Bad cache: …
```
=> Normalize resource sequence for content metadata.

README.md
Updating to use bin/rails as Rails docs currently do, rather than rake.
README
=> Updating README's generate_token command

app/services/cocina/from_fedora/file_sets.rb, app/services/cocina/normalizers/content_metadata_normalizer.rb, spec/services/cocina/mapping/structural/dro_structural_spec.rb
closes #3151
Mapping
Before:
```
Success:   94514 (94.589%)
Different: 4980 (4.984%)
Create error:     427 (0.427%)
Expected unmapped:     79 (0.079%)
```
After:
```
Success:   94514 (94.589%)
Different: 4980 (4.984%)
Create error:     427 (0.427%)
Expected unmapped:     79 (0.079%)
```
=> Map/normalize attr labels (content metadata).

app/services/cocina/normalizers/content_metadata_normalizer.rb, spec/services/cocina/normalizers/content_metadata_normalizer_spec.rb
closes #3085
Mapping
Before:
```
Success:   94046 (94.123%)
Different: 5477 (5.481%)
Create error:     395 (0.395%)
```
After:
```
Success:   94046 (94.123%)
Different: 5477 (5.481%)
Create error:     395 (0.395%)
```
=> Normalize location (content metadata).

app/services/cocina/normalizers/content_metadata_normalizer.rb, spec/services/cocina/normalizers/content_metadata_normalizer_spec.rb
closes #3119
Mapping
Before:
```
Success:   94046 (94.123%)
Different: 5477 (5.481%)
Create error:     395 (0.395%)
```
After:
```
Success:   94291 (94.368%)
Different: 5232 (5.236%)
Create error:     395 (0.395%)
```
=> Removes format attribute from file node (content metadata).

.rubocop_todo.yml, app/services/preserve/file_inventory_builder.rb, app/services/sdr_ingest_service.rb, spec/services/preserve/file_inventory_builder_spec.rb, spec/services/sdr_ingest_service_spec.rb
Each class should have a single responsibility, this refactoring creates a new class with the exclusive responsibility of building a Moab::FileInventory. 
Unit tests.
=> [refactor] Extract FileInventoryBuilder from SdrIngestService

app/services/preserve/bag_verifier.rb, app/services/sdr_ingest_service.rb, spec/services/preserve/bag_verifier_spec.rb, spec/services/sdr_ingest_service_spec.rb
Each class should only have one responsibility.  This new class verifies the bag is as expected.
=> [refactor] Extract Preserve::BagVerifier from SdrIngestService

app/services/cocina/from_fedora/file_sets.rb, spec/services/cocina/mapping/structural/dro_structural_spec.rb
closes #3155
Mapping.
Before:
```
Success:   9409 (94.184%)
Different: 545 (5.455%)
Create error:     36 (0.36%)
Expected unmapped:     10 (0.1%)
```
After:
```
Success:   9409 (94.184%)
Different: 545 (5.455%)
Create error:     36 (0.36%)
Expected unmapped:     10 (0.1%)
```
=> Omit empty mimetypes from cocina.

app/services/cocina/normalizers/content_metadata_normalizer.rb, spec/services/cocina/normalizers/content_metadata_normalizer_spec.rb
closes #3172
Be more specific when normalizing. This will allow us to verify that correctly handling all cases of <attr>.
Before:
```
Success:   94790 (94.868%)
Different: 5128 (5.132%)
```
After:
```
Success:   94533 (94.611%)
Different: 5385 (5.389%)
Bad cache:     0 …
```
=> Adjust normalization of attr node (content metadata).

bin/reports/report-content-objectid
Fixes #3118 
Spot-checked druids in Argo for objectID attribute in resource node
=> Report on contentMetadata resources with objectIds

Dockerfile
This is the version we have in CI, so I naïvely reckon it's the same we should have in the image?
=> Standardize on Ruby 2.7.5

bin/reports/report-rels-apo_agreement_ids
To find APOs without agreement ids
On sdr-deploy:
bin/reports/report-rels-apo_agreement_ids
using: 
/opt/app/deploy/dor-services-app/druids.txt
I've attached the report here:
[rels_apo_without_agreement_ids.csv](https://github.com/sul-dlss/dor-services-app/files/7901797/rels_apo_without_agreement_ids.csv)
Here is one of the items it found:
https://argo.stanford.edu/view/druid:cw247ty3859
Being new to the various data models I'm not confident this is finding what was needed, so please check [the logic](https://github.com/sul-dlss/dor-services-app/blob/apo-without-agreementids/bin/reports/report-rels-apo_agreement_ids#L12).
=> Report to find APOs without agreementids

bin/reports/report-content-thumb
Info for #3187 next steps. Report on resources with thumb attribute. 10 druids were found. 
Run on sdr-deploy with full `druids.testbed.txt`
=> Report on resources with thumb attribute

bin/validate-cocina-roundtrip
Fixes #3125 
Current (main):
```
Success:   93858 (94.447%)
Different: 5518 (5.553%)
Missing from cache:     32 (0.032%)
Expected unmapped:     592 (0.592%)
```
After:
```
Success:   93858 (94.447%)
Different: 5518 (5.553%)
Missing from cache:     32 (0.032%)
Expected unmapped:     592 (0.592%)
```
Round Trip results against large dataset
=> Remove rightsMetadata on round trip

app/services/cocina/normalizers/content_metadata_normalizer.rb, spec/services/cocina/normalizers/content_metadata_normalizer_spec.rb
Remove <attr name="representation"> from the mapping. Fixes #3180
`<attr name="representation">` was an artifact of some old prototyping work and is no longer needed.
Unit tests
=> remove attr representation

app/services/cocina/from_fedora/apo.rb, spec/services/cocina/mapping/administrative/apo_administrative_spec.rb
and un-skip relevant test; also fix unskipped test with updated license URL, and shared example with expected roundtrip XML difference.
closes #3126 
n/a
=> include sunet IDs when mapping role info from fedora to cocina

app/services/cocina/normalizers/embargo_normalizer.rb, spec/services/cocina/normalizers/embargo_normalizer_spec.rb
closes #3123
Roundtripping.
Unit
Before:
```
Success:   9536 (95.436%)
Different: 456 (4.564%)
Expected unmapped:     8 (0.08%)
```
After:
```
Success:   9538 (95.456%)
Different: 454 (4.544%)
Expected unmapped:     8 (0.08%)
```
=> Removes released embargoes.

app/services/cocina/normalizers/embargo_normalizer.rb, spec/services/cocina/normalizers/embargo_normalizer_spec.rb
closes #3122
Don't discard data that want to keep.
Unit
=> Stop normalizing embargo nodes with text.

spec/services/cocina/normalizers/embargo_normalizer_spec.rb
i merged #3207, then #3205, but the former made it so that the assumptions of the latter's test no longer held.
unit
n/a
=> embargo_normalizer_spec: #normalize_empty test with values accounts for fact that released embargoes get normalized out

bin/reports/report-content-file_deliver
Report to find deliver attributes on file elements in contentMetadata. File attached to #3070.
Run on full druids.testbed.txt file and spot-checked.
=> Report on file deliver attribute

openapi.yml
openapi.yml must be kept in sync with cocina-models or all h*ll breaks loose.
=> Fix openapi.yml so that matches cocina-models.

app/services/cocina/normalizers/identity_normalizer.rb, bin/reports/report-identity-multi_catkeys, spec/services/cocina/normalizers/identity_normalizer_spec.rb
Remove duplicate catkeys from identity metadata
Ran reports on sdr-deploy to identify items that have multiple catkeys. Ran unit tests.
Closes #2833
=> Multiple catkeys

app/services/cocina/from_fedora/file_sets.rb, app/services/cocina/normalizers/content_metadata_normalizer.rb, spec/services/cocina/mapping/structural/dro_structural_spec.rb, spec/services/cocina/normalizers/content_metadata_normalizer_spec.rb
Resolves #3070. Maps deliver attribute to publish attribute on contentMetadata files and removes deprecated deliver attribute. 
Added tests and unit tests pass. 
Before:
```Status (n=100000; not using Missing for success/different/error stats):
Success:   94916 (94.994%)
Different: 5002 (5.006%)
```
After:
```Status (n=100000; not using Missing for success/different/error stats):
Success:   94916 (94.994%)
Different: 5002 (5.006%)
Expected …
```
=> Map and normalize contentMetadata file deliver attribute

app/services/cocina/normalizers/content_metadata_normalizer.rb, spec/services/cocina/normalizers/content_metadata_normalizer_spec.rb
closes #3084
Normalization
Unit
=> Removes data attribute from resource node (content metadata).

app/services/cocina/normalizers/content_metadata_normalizer.rb, spec/services/cocina/normalizers/content_metadata_normalizer_spec.rb
Resolves #3127. Normalization to put content Id at root level.
Before
```
Success:   94844 (94.922%)
Different: 5074 (5.078%)
```
After
```
Success:   95156 (95.234%)
Different: 4762 (4.766%)
```
=> Normalizing missing objectId in contentMetadata

app/services/cocina/from_fedora/descriptive/form.rb, spec/services/cocina/mapping/descriptive/mods/physical_description_spec.rb
Resolves #2731. 
Unit tests pass.
Result of running `bin/validate-desc-cocina-roundtrip` on a single druid with the extent and note (druid:gx952gd8699) is:
```Status (n=1; not using Missing for success/different/error stats):
Success:   1 (100.0%)
```
Results of running `bin/validate-desc-cocina-roundtrip -s 100000 -i druids.testbed.txt`
Before:
```
Success:   99983 (99.983%)
Different: 17 (0.017%)
```
After
```
Status (n=100000; …
```
=> descriptiveMetadata mapping for extent unit

app/services/cocina/normalizers/identity_normalizer.rb, spec/services/cocina/normalizers/identity_normalizer_spec.rb
Resolves #3213. Normalizes to always add objectCreator to identityMetadata (some records do not have it originally). 
Added test and unit tests passing. 
Results of ` bin/validate-cocina-roundtrip -s 100000 -i druids.testbed.txt`:
Before:
```Status (n=100000; not using Missing for success/different/error stats):
Success:   94916 (94.994%)
Different: 5002 (5.006%)
```
After:
```Status (n=100000; not using Missing for success/different/error stats):
Success:   94919 (94.997%)
Different: 4999 (5.003%) …
```
=> Normalizes missing objectCreator in identityMetadata.

app/services/cocina/from_fedora/descriptive/admin_metadata.rb, app/services/cocina/to_fedora/descriptive/admin_metadata.rb, spec/services/cocina/mapping/descriptive/mods/record_info_spec.rb
Resolves #2689 to map recordInfoNote from MODS. 
Unit tests. Validating on sdr-deploy with `bin/validate-desc-cocina-roundtrip`:
Before
```Status (n=100000; not using Missing for success/different/error stats):
Success:   99984 (99.984%)
Different: 16 (0.016%)
```
After
```Status (n=100000; not using Missing for success/different/error stats):
Success:   99984 (99.984%)
Different: 16 (0.016%)
```
=> MODS recordInfoNote mapping

app/controllers/metadata_controller.rb, app/services/publish/dublin_core_service.rb, app/services/publish/public_xml_service.rb, spec/services/publish/dublin_core_service_spec.rb
instead of a Fedora object
closes #3099 
unit tests
n/a
=> refactor DublinCoreService to take MODS XML created by PublicDescMetadataService

app/services/cocina/normalizers/admin_normalizer.rb, bin/validate-cocina-roundtrip, spec/services/cocina/mapping/administrative/apo_administrative_spec.rb, spec/services/cocina/normalizers/admin_normalizer_spec.rb
Fixes #2707 - admin administrativeMetadata normalizer, add a spec for the new normalizer, run normalizer in validation script and in adminMetadata spec
Test suite
=> add normalizer for adminMetadata

README.md, bin/validate-to-desc-cocina
closes #3216
Handle the case where an item is deleted from Fedora, but not deleted from cache.
sdr-deploy
=> Fix validate-to-desc-cocina to handle a missing Fedora item.

app/services/cocina/from_fedora/descriptive/admin_metadata.rb, spec/services/cocina/mapping/descriptive/mods/record_info_spec.rb
Resolves #2740.
Unit tests and running `bin/validate-desc-cocina-roundtrip`.
As always, I'd appreciate attention to the ruby methods I'm using, especially in this case `modification_events&.each`.
Before:
```Status (n=100000; not using Missing for success/different/error stats):
Success:   99992 (99.993%)
Different: 7 (0.007%)
Missing (no descMetadata):     1 (0.001%)
```
After:
```Status (n=100000; not using Missing for success/different/error stats):
Success:   99992 (99.993%)
Different: 7 (0.007%)
Missing (no descMetadata):     1 (0.001%)
```
=> Map multiple record modification notes

app/services/cocina/from_fedora/access/license.rb, app/services/deep_equal.rb, bin/validate-cocina-roundtrip, spec/services/cocina/mapping/access/dro_access_spec.rb, spec/services/cocina/mapping/administrative/apo_administrative_spec.rb, spec/services/cocina/mapping/identification/dro_identity_spec.rb, spec/services/deep_equal_spec.rb, spec/support/matchers/deep_ignore_order_matcher.rb
Fixes #3129
Includes:
* Add normalization of APO default rights to cocina roundtrip validator
* Make checking of `#use_license` safer in the APO context as DefaultObjectRightsDS does not define this method allowing us to use our existing rights normalizer on APO rights
* Allow DeepEqual service to smartly compare XML blobs in Cocina (currently used only in the APO context)
* Improve how APO admin feature specs read in RSpec using more idiomatic, less repetitive `it`/`describe`/etc. labels
```
$ bin/validate-cocina-roundtrip -f -r -s 10000
Success:   9643 (96.546%)
Different: 344 (3.444%)
Mapping error:     1 (0.01%)
Unmapped: …
```
=> Normalize APO rights

README.md, bin/clean-druid-list, bin/validate-cocina-roundtrip
More effective testing. In particular, provide the ability to clean up our druid lists and items are purged and to omit descriptive md differences when evaluating roundtrip differences.
sdr-deploy, local
=> Tooling tweaks

app/services/cocina/normalizers/content_metadata_normalizer.rb, spec/services/cocina/mapping/administrative/apo_administrative_spec.rb, spec/services/cocina/normalizers/content_metadata_normalizer_spec.rb
Fixes #2802 - remove geoData from contentMetadata when normalizing.
Also, add one extra parens I forgot to add in #3231 to make things consistent.
Added a new test, ran 10k test bed druids through roundtrip and recorded stats (see comment below)
=> remove geodata from contentMetadata when normalizing

app/services/cocina/normalizers/content_metadata_normalizer.rb, spec/services/cocina/normalizers/content_metadata_normalizer_spec.rb
Fixes #3251 - normalize empty XML content metadata
See stats from running validate-cocina-roundtrip on sample druids below.
Added a test, ran round-trip test on sdr-deploy
=> normalize empty xml contentMetadata

app/services/cocina/to_fedora/administrative_metadata.rb, spec/services/cocina/to_fedora/administrative_metadata_spec.rb
Resolves #3248.
Test added and unit test pass. Running `bin/validate-desc-cocina-roundtrip -s 100000 -i druids.testbed.txt` shows no change.
Before
```Status (n=100000; not using Missing for success/different/error stats):
Success:   99984 (99.984%)
Different: 16 (0.016%)
```
After
```Status (n=100000; not using Missing for success/different/error stats):
Success:   99984 (99.984%)
Different: 16 (0.016%)
```
=> Administrative metadata mapping for registration node

app/services/cocina/normalizers/content_metadata_normalizer.rb, spec/services/cocina/normalizers/content_metadata_normalizer_spec.rb
Resolves #3247.
Added test and unit tests pass. When running `bin/validate-cocina-roundtrip -s 100000 -i druids.testbed.txt` success goes up.
Before 
```Status (n=100000; not using Missing for success/different/error stats):
Success:   96007 (96.086%)
Different: 3911 (3.914%)
```
After
```Success:   96076 (96.155%)
Different: 3842 (3.845%)
```
=> Removes id attr from contentMetadata in normalization

app/services/cocina/normalizers/content_metadata_normalizer.rb, spec/services/cocina/normalizers/content_metadata_normalizer_spec.rb
Fixes #3243 - normalize blank <imageData> nodes and remove blank width and height attributes from contentMetadata
Added a new test
See `validate-cocina-roundtrip` results below
=> normalize imageData in contentMetadata

app/services/cocina/from_fedora/dro.rb, app/services/cocina/from_fedora/dro_structural.rb, app/services/cocina/from_fedora/file_sets.rb, bin/validate-rights-cocina-roundtrip, spec/services/cocina/from_fedora/dro_structural_spec.rb, spec/services/cocina/from_fedora/file_sets_spec.rb, spec/services/cocina/mapping/access/dro_access_spec.rb, spec/services/cocina/mapping/structural/dro_structural_spec.rb
closes #3232
after grepping around to double-check that i was using the right alert format, i realized i'd missed some applicable centralized code for this sort of alert, but also that the existing code wanted a druid, which wasn't immediately available from where the alert was being sent.  i threw on a second commit passing in the druid from the caller, and switching `FileSets` to use the centralized notifier code, but if it turns out that's bad for some reason, i can knock that commit off (or otherwise tweak as needed, of course).
unit tests
n/a
=> FileSets: if HB alerting on an invalid type, tag alert as data error

app/services/cocina/from_fedora/dro.rb, app/services/cocina/from_fedora/identification.rb, app/services/cocina/object_creator.rb, app/services/cocina/object_updater.rb, app/services/cocina/to_fedora/identity.rb, spec/services/cocina/mapping/identification/dro_identity_spec.rb, spec/services/cocina/object_updater_spec.rb
To allow multiple catkeys to be expressed as Cocina identification.catalogLinks. Fixes #3221 
Unit tests and roundtrip testing on sdr-deploy:
Before: 
```
Testing |Time: 00:20:10 | ============================================================================================== | Time: 00:20:10
Success:   96078 (96.157%)
Different: 3840 (3.843%)
```
After:
```
Testing |Time: 00:20:12 | ============================================================================================== | Time: 00:20:12
Status (n=100000; not …
```
=> Allow for multiple catkeys

app/services/cocina/from_fedora/dro_structural.rb, app/services/cocina/normalizers/content_metadata_normalizer.rb, spec/services/cocina/mapping/access/dro_access_spec.rb, spec/services/cocina/mapping/structural/dro_structural_spec.rb, spec/services/cocina/normalizers/content_metadata_normalizer_spec.rb
Resolves #3128 to map hasMemberOrders > viewingDirection for all books and normalize readingOrder and bookData to all Fedora book objects. 
Added tests and unit tests pass. `bin/validate-cocina-roundtrip -s 100000 druids.testbed.txt`:
Before:
```
Success:   95561 (95.64%)
Different: 4355 (4.359%)
Mapping error:     1 (0.001%)
Expected unmapped:     83 (0.083%)
```
After
```Status (n=100000; not using Missing for success/different/error stats):
Success:   95976 (96.056%)
Different: 3940 (3.943%)
Mapping error:     1 (0.001%)
Normalization error:     0 …
```
=> Normalize and complete mapping of readingOrder

openapi.yml
New header was added here: https://github.com/sul-dlss/dor-services-app/pull/3198/files and is now used here: https://github.com/sul-dlss/dor_indexing_app/pull/722 .... add to openapi
existing tests
=> add new created_at header to openapi

app/services/cocina/from_fedora/descriptive/contributor.rb, app/services/cocina/from_fedora/descriptive/subject.rb, spec/services/cocina/from_fedora/descriptive/subject_name_spec.rb, spec/services/cocina/mapping/descriptive/mods/name_spec.rb
Resolves #2794 to remove missing name type error.
Unit tests. I don't think this affects roundtripping, but if that's useful as a check, let me know and I'll run it.
=> Removing missing name type warning.

app/controllers/metadata_controller.rb, app/controllers/objects_controller.rb, app/models/dor/update_marc_record_service.rb, app/services/publish/public_xml_service.rb, app/services/thumbnail_service.rb, spec/dor/update_marc_record_service_spec.rb, spec/requests/legacy_metadata_update_spec.rb, spec/requests/metadata_spec.rb, spec/requests/update_marc_record_spec.rb, spec/services/publish/public_xml_service_spec.rb, spec/services/thumbnail_service_spec.rb, spec/support/datastreams.rb
Closes #3253 
- Rewrites ThumbnailService to take a Cocina object
- Updates PublicXmlService to use a Cocina object for thumbnails
- Updates UpdateMarcRecordService to use a Cocina object for thumbnails
UpdateMarcRecordService (in progress) and PublicXmlService will be completely rewritten for cocina in follow up issues/PRs.
Updated unit tests
=> Cocina-ize ThumbnailService

app/services/cocina/to_fedora/descriptive/subject.rb, spec/services/cocina/mapping/descriptive/mods/subject_name_spec.rb
Partially addresses #2733. Remaining mapping to be handled in separate PR. 
Unit tests pass. No change with `bin/validate-desc-cocina-roundtrip -s 100000 -i druids.testbed.txt`
Before
```
Success:   99984 (99.984%)
Different: 16 (0.016%)
```
After
```
Success:   99984 (99.984%)
Different: 16 (0.016%)
```
=> Implementing subject name specs.

app/services/cocina/normalizers/identity_normalizer.rb, bin/reports/report-identity-otherids_labels, spec/services/cocina/normalizers/identity_normalizer_spec.rb
A decision was made not to map otherId[@name="label"]. This PR tests that they are removed during normalization, and also does the removal.
Unit tests. Here is before/after roundtrip report from sdr-deploy:
Before:
```
Success:   96092 (96.174%)
Different: 3822 (3.825%)
Mapping error:     1 (0.001%)
Expected unmapped:     85 (0.085%)
```
After:
```
Success:   96099 (96.181%)
Different: 3815 (3.818%)
Mapping error:     1 (0.001%)
Missing from cache: …
```
=> Normalize otherid labels

app/services/cocina/normalizers/content_metadata_normalizer.rb, spec/services/cocina/normalizers/content_metadata_normalizer_spec.rb
Resolves #3121 to remove "stacks" attribute from contentMetadata root. 
Added test and ran unit tests. Results of `bin/validate-cocina-roundtrip -s 100000 -i druids.testbed.txt ` are unchanged. 
Before:
```
Success:   96320 (96.399%)
Different: 3598 (3.601%)
```
After
```
Success:   96320 (96.399%)
Different: 3598 (3.601%) …
```
=> Normalizing stacks out of contentMetadata root.

app/services/cocina_object_store.rb, spec/services/cocina_object_store_spec.rb
For roundtrip validation, I'm going to need to inject the CocinaObjectStore, which makes more sense as an instantiable class.
Unit
=> Make CocinaObjectStore an instantiable class.

app/models/dor/update_marc_record_service.rb
I found the comments confusing as I wasn't sure what "It" referred to.
=> update_marc_record_service: remove "It" from method comments

app/controllers/admin_policy_defaults_controller.rb, app/services/workflow_client_factory.rb, config/application.rb, openapi.yml, spec/requests/apply_admin_policy_defaults_spec.rb, spec/support/cocina_matchers.rb
And apply APO defaults only to items that are in the registered or opened workflow states.
Fixes #3168
Fixes sul-dlss/argo#3019
This commit changes the AdminPolicyDefaultsController so that it saves and loads Cocina objects instead of Fedora ones. It tests both cases of default defaultAccess and custom defaultAccess. It also copies over an RSpec matcher from Argo allowing comparison of Cocina substructures, in this case the access substructure.
CI. Will also test in stage.
None
=> Cocina-ize the AdminPolicyDefaultsController

lib/fedora_loader.rb
So that agreements can roundtrip.
Local
=> Fix loading of Dor::Agreemnt in cache.

app/controllers/admin_policy_defaults_controller.rb, app/services/apply_admin_policy_defaults.rb, spec/requests/apply_admin_policy_defaults_spec.rb, spec/services/apply_admin_policy_defaults_spec.rb, spec/support/cocina_matchers.rb
The controller was doing too much. The service still doing a lot... but the data model is what it is. 
We could consider further rounds of refactoring in the future. The fact that the new service object is an iceberg (tiny public API, lots of private code) makes me wonder if there aren't more abstractions than can be teased out, but I'm also getting the sense that another round of abstraction might be premature at this point. (I.e., the next abstraction isn't clear to me and I don't want to force it.) Open to ideas if folks would like more further refactoring in this commit.
CI
None
=> Refactor application of APO defaults

app/services/cocina/normalizers/content_metadata_normalizer.rb, spec/services/cocina/normalizers/content_metadata_normalizer_spec.rb
Fixes #3283 - remove dataType attribute from file nodes in contentMetadata during normalization
new test
=> remove dataType attribute from file nodes in contentMetadata

app/services/cocina/normalizers/mods/subject_normalizer.rb, app/services/cocina/to_fedora/descriptive/subject.rb, spec/services/cocina/mapping/descriptive/mods/subject_cartographic_spec.rb
closes #2470
Before:
```
Status (n=250000; not using Missing for success/different/error stats):
Success:   249976 (99.991%)
Different: 23 (0.009%)
Missing (no descMetadata):     1 (0.0%)
```
After:
```
Status (n=250000; not using Missing for success/different/error stats):
Success:   249977 (99.991%)
Different: 22 (0.009%)
Missing (no descMetadata):     1 (0.0%)
```
=> Fix mapping of parallel carto subjects.

app/jobs/shelve_job.rb, app/services/shelving_service.rb, spec/jobs/shelve_job_spec.rb, spec/services/shelving_service_spec.rb
Also, stop getting web archiving stacks location from stacks attribute.
closes #3082.
So that the stacks attribute in content metadata can be deprecated.
Unit
=> Cocina-izes shelving service. 

app/controllers/mods_controller.rb, config/routes.rb, openapi.yml, spec/requests/mods_update_spec.rb
We want to have a stable API for updating MODS even after we switch to a Cocina based datastore.
Fixes #3282
=> Add a method for updating the MODS

spec/services/cocina/normalizers/embargo_normalizer_spec.rb
refs #3284 - test embargo normalization
Added a new test
=> add another test for embargo normalization

app/controllers/metadata_controller.rb
Cannot currently update legacy metadata that maps to invalid cocina.
=> Limit load_cocina_object in MetadataController.

app/services/cocina/to_fedora/descriptive/subject.rb, spec/services/cocina/mapping/descriptive/mods/subject_name_spec.rb, spec/services/cocina/to_fedora/descriptive/subject_name_spec.rb
Resolves #2733. (Second half was already addressed by #3276.) Maps back to MODS when Cocina has a name subject with structuredValue > parallelValue > structuredValue.
Added spec and ran unit tests. I had to disable Metrics/CyclometricComplexity on one existing method. (It's disabled on other methods in this mapping already.) Wondering if I should be trying to refactor that, or create a ticket for it?
Ran `bin/validate-desc-cocina-roundtrip -s 100000 -i druids.testbed.txt` and no change. 
Before:
```Status (n=100000; not using Missing for success/different/error stats):
Success:   99985 (99.985%)
Different: 15 (0.015%)
```
After:
```Status (n=100000; not …
```
=> Name subjects with subelements, role, displayForm, and subject subdivision

bin/reports/report-rels-apo_agreement_ids
The existing test was not finding all APOs.
Local
=> Fix report-rels-apo_agreement_ids test.

app/services/cocina/normalizers/embargo_normalizer.rb, spec/services/cocina/normalizers/embargo_normalizer_spec.rb
The embargo metadata should not include `twentyPctVisibilityStatus` and `twentyPctVisibilityReleaseDate` when `twentyPctVisibilityStatus` is `released`.
Closes #3285 
Note: I left a question in #3285 which may be relevant for the review.
Unit tests, and roundtrip testing on sdr-deploy.
```
Success:   96282 (96.365%)
Different: 3632 (3.635%)
Expected unmapped:     86 (0.086%)
```
```
Success:   96284 (96.367%)
Different: 3630 (3.633%)
Create error:     0 …
```
=> Remove embargo twentyPct elements when released

app/services/cocina/to_fedora/license.rb, spec/services/cocina/to_fedora/license_spec.rb
Fixes sul-dlss/argo#3018
Without this change, the APO edit page in Argo (e.g., https://argo-stage.stanford.edu/view/druid:sc012gz0974) fails to do what the user expects when they set the default use license for an APO to none.
CI + @andrewjbtw tested successfully IN QA
None
=> Remove the license if the user has said so

spec/services/publish/metadata_transfer_service_spec.rb
This should fix the main build.
Unit test updated.
=> Fix missing mock in metadata_transfer_service_spec

app/controllers/objects_controller.rb, app/services/cocina_object_store.rb, app/services/notifications/object_created.rb, app/services/notifications/object_updated.rb, spec/services/cocina_object_store_spec.rb, spec/services/notifications/object_created_spec.rb, spec/services/notifications/object_updated_spec.rb
Closes #3297 by fetching created and modified dates from the existing fedora object (or setting to Time.zone.now on create) and publishing to rabbitmq.
Unit
=> Add date attributes to rabbit messages on created and updated

spec/factories/collections.rb, spec/factories/dros.rb, spec/models/collection_spec.rb, spec/models/dro_spec.rb, spec/requests/collections_for_object_spec.rb
reduces number of fixtures and defaults to using unique druids for each object, which is slightly more realistic
unit
n/a
=> FactoryBot dro and collection fixtures have unique druids by default

bin/validate-cocina-roundtrip
Better roundtrip testing for Hydrus objects when using the `-n` (no descriptive) flag.
Local
=> Adds special handling for Hydrus.

app/services/cocina/normalizers/content_metadata_normalizer.rb, spec/services/cocina/normalizers/content_metadata_normalizer_spec.rb
Closes #3317 by downcasing the type attribute of a files checksum during normalization:
N=10000
Before:
```
Success:   9610 (96.486%)
Different: 350 (3.514%)
Expected unmapped:     40 (0.4%)
```
After:
```
Success:   9671 (97.098%)
Different: 289 (2.902%)
Expected unmapped:     40 (0.4%)
```
Updated unit tests
=> Downcase checksum type when normalizing contentMetadata

app/services/cocina/normalizers/base.rb, app/services/cocina/normalizers/embargo_normalizer.rb, app/services/cocina/normalizers/mods_normalizer.rb, bin/validate-cocina-roundtrip, spec/services/cocina/normalizers/embargo_normalizer_spec.rb
Fixes #3284 - do not blindly remove all `<releaseAccess>` nodes, as some of them may contain important empty nodes.  Test for this was added in #3301 and now passes.
HOLD: re-running validate cocina tests
Existing tests.
=> [HOLD] fix normalization of embargoMetadata

app/services/cocina/normalizers/content_metadata_normalizer.rb, spec/services/cocina/normalizers/content_metadata_normalizer_spec.rb
Closes #3324 by adding `type="file"` to contentMetadata root nodes that are missing it.
Unit test added
Roundtrip validation is currently running (n=100000)
=> Add type attribute to contentMetadata when missing on normalization

app/models/dor/update_marc_record_service.rb, spec/dor/update_marc_record_service_spec.rb
Part of #3346 
https://app.honeybadger.io/projects/50568/faults/83916162
Updated Unit test.
=> Return nil for ckeys when identification node is empty or not included

app/services/cocina/normalizers/role_normalizer.rb, spec/services/cocina/normalizers/role_normalizer_spec.rb
Closes #3341 by removing the `objectId` attribute from the `roleMetadata` datastream on roundtrip validation.
Before:
```
Success:   96892 (97.318%)
Different: 2670 (2.682%)
Missing from cache:     1 (0.001%)
Expected unmapped:     437 (0.437%)
```
After:
```
Success:   96892 (97.318%)
Different: 2670 (2.682%)
Missing from cache:     1 (0.001%)
Expected unmapped:     437 (0.437%) …
```
=> Remove objectId from roleMetadata during normalization

app/controllers/metadata_controller.rb, app/models/dor/update_marc_record_service.rb, app/services/publish/metadata_transfer_service.rb, app/services/release_tags.rb, spec/dor/update_marc_record_service_spec.rb, spec/requests/metadata_spec.rb, spec/services/release_tags_spec.rb
closes #3348
UpdateMarcRecordService uses ReleaseTags, but has already been cocina-ized.
Unit
=> Allow ReleaseTags to accept cocina objects.

app/services/events_migration_service.rb, spec/services/events_migration_service_spec.rb
refs #2394
Events are currently split between the events datastream and the DB. This migrates open and close events from the events datastream to the DB.
Follow-up for this ticket is to create migration script (#3351)
Unit
=> Creates a migration service for events.

app/services/cocina/to_fedora/descriptive/subject.rb, spec/services/cocina/mapping/descriptive/mods/subject_name_spec.rb
Fixes #3039
```
$ bin/validate-desc-cocina-roundtrip -r -s 350000 -f
On branch name: main (commit: 797681e7)...
Status (n=350000; not using Missing for success/different/error stats):
Success:   349974 (99.993%)
Different: 23 (0.007%)
Missing (no descMetadata):     3 (0.001%)
```
```
$ bin/validate-desc-cocina-roundtrip -r -s 350000 -f
On branch name: subject-name-affiliation#3039 (commit: 30d0026a)...
Status (n=350000; not using Missing for success/different/error stats):
Success:   349982 (99.995%)
Different: 17 (0.005%)
Missing (no descMetadata):     1 (0.0%)
```
=> Map name subjects with affiliations and genres

app/services/cocina/normalizers/content_metadata_normalizer.rb, spec/services/cocina/normalizers/content_metadata_normalizer_spec.rb
Fixes #3321 - normalize/remove empty labels (and do not create new empty ones in existing normalization)
- New unit test
- Running roundtrip validation on sdr-deploy (results below) : 0.015% improvement! 🥇
=> remove empty labels; do not create new ones

app/services/cocina/normalizers/role_normalizer.rb, bin/reports/report-role-groups, spec/services/cocina/normalizers/role_normalizer_spec.rb
Fixes #3319 by removing group nodes that are outside of role nodes. This typically only happens for APOs.
Unit test updated.
Pending roundtrip validation.
Round trip using `druids.apos.txt`:
Before:
```Status (n=1270; not using Missing for success/different/error stats):
Success:   748 (58.898%)
Different: 515 (40.551%)
Mapping error:     7 (0.551%)
```
After:
```
Status (n=1270; not using Missing for success/different/error stats):
Success:   1015 (79.921%)
Different: 248 (19.528%)
Mapping error:     7 (0.551%)
Unmapped: …
```
=> Normalize group when outside of a role node

app/validators/cocina/collection_existence_validator.rb, spec/requests/create_object_spec.rb, spec/validators/cocina/collection_existence_validator_spec.rb
Fixes #3307 by looking for the collection in the CocinaObjectStore. This also adds a missing test for CollectionExistsenceValidator
Additional unit test.
=> Rewrite collection existence validator for cocina

app/services/cocina/normalizers/admin_normalizer.rb, spec/services/cocina/normalizers/admin_normalizer_spec.rb
Resolves #3325 to normalize out empty workflows within dissemination nodes. 
Added test and unit tests. Running `bin/validate-cocina-roundtrip -s 100000 -i druids.testbed.txt ` has no change. 
Before
``` 
Success:   97152 (97.232%)
Different: 2766 (2.768%)
```
After
```
Success:   97152 (97.232%)
Different: 2766 (2.768%)
Bad cache:     0 …
```
=> Normalize out dissemination nodes with empty workflow ids.

app/services/cocina/normalizers/admin_normalizer.rb, spec/services/cocina/normalizers/admin_normalizer_spec.rb
Fixes #3345 - remove more empty dissemination nodes
- Updated existing similar test with new pattern
- cocina roundtrip validation tests (results shown below)
=> remove empty dissemination workflow nodes

app/services/cocina_migration_service.rb, app/services/cocina_object_store.rb, bin/migrate, spec/services/cocina_migration_service_spec.rb, spec/services/cocina_object_store_spec.rb
closes #3351
To allow migration from Fedora to Cocina.
Unit, QA
=> Adds migration script for cocina, versions, and events.

app/services/cocina/normalizers/identity_normalizer.rb, bin/validate-cocina-roundtrip, spec/services/cocina/mapping/identification/agreement_identity_spec.rb, spec/services/cocina/mapping/identification/apo_identity_spec.rb, spec/services/cocina/mapping/identification/collection_identity_spec.rb, spec/services/cocina/mapping/identification/dro_identity_spec.rb, spec/services/cocina/normalizers/identity_normalizer_spec.rb
Fixes #3320 - if missing when normalizing, add objectLabel to identityMetadata using value pulled from fedora object
- Added new unit tests
- roundtrip validation on server
=> add objectLabel node with value from fedora object if not in datastream

app/services/cocina/normalizers/content_metadata_normalizer.rb, spec/services/cocina/normalizers/content_metadata_normalizer_spec.rb
Resolves #3318. Removes provider_checksum from contentMetadata/resource/file. 
Added spec and unit tests. Running `bin/validate-cocina-roundtrip -s 100000 -i druids.testbed.txt ` on sdr-deploy has the different rate go up, so trying to figure that out by comparing with run on main. DRAFT until then. 
Before
```Status (n=100000; not using Missing for success/different/error stats):
Success:   97152 (97.232%)
Different: 2766 (2.768%)
```
After
```
Success:   96610 (96.689%)
Different: 3308 (3.311%)
Mapping error:     0 …
```
=> Normalizing out provider_checksum in contentMetadata.

app/models/dor/update_marc_record_service.rb, spec/dor/update_marc_record_service_spec.rb
Fixes #3369 
Updated unit test
=> Extract catkey instead of model definition for set in 856

app/services/cocina/from_fedora/apo.rb, spec/requests/show_object_spec.rb, spec/requests/update_metadata_spec.rb, spec/services/cocina/mapping/administrative/apo_administrative_spec.rb, spec/services/cocina/mapping/identification/apo_identity_spec.rb
part of #3336 (the same changes for Collection records will be in a separate PR)
APOs should use the existing `objectLabel` in `identityMetadata` for the value of cocina `label` if the `objectLabel` exists.
unit tests and this data:
Note:  most of the failing APOs still have other roundtrip problems.
```sh
$ bin/validate-cocina-roundtrip -i tmp/druid-lists/druids.apos.txt -f -n
Status (n=1270; not using Missing for success/different/error stats):
Success:   1055 (83.071%)
Different: 205 (16.142%)
Mapping error:     10 (0.787%)
````
```sh
Status (n=1270; not using Missing for success/different/error stats):
Success: …
```
=> apo identityMetadatata.xml objectLabel used for cocina label (when objectLabel exists)

Gemfile
dlss specific gems were in the general ruby list;  I like the idea of separating them out;  this takes care of that and will make it easier to stay consistent moving forward.
=> Gemfile: a slight reorg

.rubocop.yml
I got sick of waiting for rubocop to run and found out others had the same problem.
=> speed up rubocop by ignoring more

app/services/cocina/from_fedora/collection.rb, spec/services/cocina/mapper_spec.rb, spec/services/cocina/mapping/identification/collection_identity_spec.rb
closes #3336  (PR #3381 was for APOs)
Collections should use the existing `objectLabel` in `identityMetadata` for the value of cocina `label` if the `objectLabel` exists.
unit tests and this data:
```
$ bin/validate-cocina-roundtrip -i tmp/druid-lists/druids.collections.txt -f -n
```
```
Status (n=2687; not using Missing for success/different/error stats):
Success:   2676 (99.591%)
Different: 11 (0.409%)
```
```
Status (n=2687; not using Missing for success/different/error stats):
Success:   2582 (96.092%)
Different: 105 (3.908%) …
```
=> collection identityMetaadata.xml objectLabel used for cocina label (when objectLabel exists)

app/services/cocina/object_creator.rb, app/validators/cocina/apo_existence_validator.rb, spec/requests/create_collection_spec.rb, spec/requests/create_object_spec.rb, spec/requests/update_metadata_spec.rb, spec/services/cocina/object_creator_spec.rb, spec/validators/cocina/apo_existence_validator_spec.rb
Fixes #3306 by using CocinaObjectStore to verify the existence of an APO
Update unit tests
Adds a unit test for ApoExistenceValidator that was missing.
=> Rewrite ApoExistenceValidator for cocina objects

app/services/cocina/from_fedora/collection.rb, spec/services/cocina/mapper_spec.rb, spec/services/cocina/mapping/identification/collection_identity_spec.rb, spec/services/cocina/mapping/identification/dro_identity_spec.rb
Inspired by PRs #3381 and #3383, this adds the analogous spec for DRO objects.
Tagging @peetucket not because he has to review, but because THIS is what I couldn't articulate nor figure out how to write for a while.
it's a test, and it passes.
=> dro_identity_spec: add spec for missing objectLabel from identityMetadata.xml

app/controllers/objects_controller.rb, app/controllers/versions_controller.rb, app/models/object_version.rb, app/models/version_tag.rb, app/services/cocina/object_creator.rb, app/services/cocina/object_updater.rb, app/services/constituent_service.rb, app/services/embargo_release_service.rb, app/services/item_query_service.rb, app/services/version_migration_service.rb, app/services/version_service.rb, db/migrate/20220203155057_create_object_version.rb, db/structure.sql, spec/models/object_version_spec.rb, spec/models/version_tag_spec.rb, spec/requests/authorization_spec.rb, spec/requests/start_accession_spec.rb, spec/requests/versions_inventory_spec.rb, spec/requests/versions_spec.rb, spec/services/cocina/object_updater_spec.rb, spec/services/constituent_service_spec.rb, spec/services/embargo_release_service_spec.rb, spec/services/item_query_service_spec.rb, spec/services/version_migration_service_spec.rb, spec/services/version_service_spec.rb
closes #3170
Version metadata is being moved from the version datastream to the DB.
Unit
=> Cocina-izes VersionService. Stores version data in db.

app/services/cocina/object_updater.rb
Because it makes rubocop bark.
CI
nah
=> Fix typo in Rubocop exclusion

app/controllers/application_controller.rb, spec/requests/show_object_spec.rb
Every controller that uses cocina needs to have this error rescued, not just the objects_controller.
Unit
=> Move mapper error rescue to application_controller.

app/services/publish/fedora_public_content_metadata_generator.rb, app/services/publish/public_xml_service.rb
This will make it easier to swap with an implementation that uses cocina
=> [refactor] extract public contentMetadata generator class

app/services/publish/metadata_transfer_service.rb, app/services/publish/public_cocina_service.rb, spec/services/publish/metadata_transfer_service_spec.rb, spec/services/publish/public_cocina_service_spec.rb
This gets us closer to being able to remove the activefedora dependency from PublicXmlService
Ref #3329
=> Remove the ActiveFedora dependency from public_cocina_service

app/services/publish/metadata_transfer_service.rb
The item should not be re-retrieved just to get Cocina.
=> For metadata_transfer_service, use the item you have.

app/controllers/metadata_controller.rb, app/models/dor/update_marc_record_service.rb, app/services/publish/metadata_transfer_service.rb, app/services/release_tags.rb, app/services/release_tags/identity_metadata.rb, spec/dor/update_marc_record_service_spec.rb, spec/requests/metadata_spec.rb, spec/requests/show_object_spec.rb, spec/services/publish/metadata_transfer_service_spec.rb, spec/services/release_tags/identity_metadata_spec.rb, spec/services/release_tags_spec.rb
Fixes #3335 
- rewrite `ReleaseTags` to use cocina instead of fedora
- adjust all tests that used to mock fedora to instead mock cocina
- get rid of unused `#create` method (that was only used in tests)
- some refactoring of the tests to avoid duplication of pids
- revert `legacy_for` methods added here since they should no longer be needed: https://github.com/sul-dlss/dor-services-app/pull/3350
Note: I believe release tags are created in argo here: https://github.com/sul-dlss/argo/blob/main/app/jobs/release_object_job.rb#L55-L83   
So we should not need to the `#create` method I removed.
Todo:
~~- fix up `./spec/requests/show_object_spec.rb` to remove the dependency on the `ReleaseTags#create` method and instead mock the data in some way~~
~~- fix up …
=> Generate release tags from cocina instead of fedora

app/services/cocina/object_creator.rb, spec/requests/create_collection_spec.rb, spec/requests/create_object_spec.rb
Previously creating a collection with an APO that had default access would cause the server to raise an error because collections have no embargo property. This arose in https://github.com/sul-dlss/dor-services-app/commit/6c93258bced43d07647fd60bfd01305b09be2dd9
Fixes https://github.com/sul-dlss/argo/issues/3097
unit tests
=> Prevent invalid access from being copied from an APO to a collection

app/controllers/objects_controller.rb, app/services/version_service.rb, spec/requests/start_accession_spec.rb, spec/services/version_service_spec.rb
Versioning was not being performed correctly because a version open check was failing. See https://app.honeybadger.io/projects/50568/faults/83981315
Unit, By Andrew on stage.
=> Fix versioning for accession endpoint.

app/services/cocina/normalizers/mods_normalizer.rb, bin/validate-cocina-roundtrip
closes #3429
To get more accurate roundtrip testing results.
See results in #3429
=> Normalize identifier types before roundtripping.

app/services/cocina/object_updater.rb, app/services/cocina/to_fedora/identity.rb, spec/requests/update_metadata_spec.rb
refs #3408
So that objectLabels can be updated.
Unit
=> Overwrite identity objectLabel on update.

app/services/cocina/from_fedora/apo.rb, app/services/deep_equal.rb, spec/requests/create_object_spec.rb, spec/requests/update_metadata_spec.rb, spec/services/cocina/mapping/administrative/apo_administrative_spec.rb, spec/services/cocina/mapping/identification/apo_identity_spec.rb, spec/services/deep_equal_spec.rb
closes #3241
closes #3397
DefaultObjectRights is deprecated.
Unit
=> Removes mapping for defaultObjectRights.

app/controllers/application_controller.rb, app/controllers/metadata_controller.rb, app/controllers/mods_controller.rb, spec/requests/legacy_metadata_update_spec.rb, spec/requests/mods_update_spec.rb
closes #3426
To prevent users from producing bad data when editing datastreams.
Unit, qa
=> Require legacy updates to produce valid cocina before save.

bin/reports/report-content-video-data
As part of #3445, determine if there is more than one record with /contentMetadata/resource/file/videoData
ran it locally on a record known to have this condition.
=> add report for /contentMetadata/resource/file/videoData

bin/reports/report-content-checksum-attribs
as part of #3444 determine if there is more than one record with /contentMetadata/resource/file with @md5 or @sha1
ran the report locally on ETDs and it found the one ETD with this condition.
=> add report for /contentMetadata/resource/file checksum attributes

app/services/cocina/object_creator.rb, app/services/cocina/object_updater.rb, app/services/cocina/to_fedora/identity.rb, spec/requests/create_object_spec.rb, spec/services/cocina/mapping/identification/agreement_identity_spec.rb, spec/services/cocina/mapping/identification/collection_identity_spec.rb, spec/services/cocina/mapping/identification/dro_identity_spec.rb, spec/services/cocina/object_updater_spec.rb
We don't need a conditional around when to overwrite the label.
before:
```
[deploy@sdr-deploy dor-services-app]$ bin/validate-cocina-roundtrip -s 100000 -i druids.testbed.txt -f
Success:   99771 (99.853%)
Different: 133 (0.133%)
Mapping error:     14 (0.014%)
```
after
```
Success:   99777 (99.859%)
Different: 127 (0.127%)
Mapping error:     14 (0.014%) …
```
=> Simplify label setting logic

app/services/cocina/normalizers/admin_normalizer.rb, spec/services/cocina/mapping/administrative/apo_administrative_spec.rb, spec/services/cocina/normalizers/admin_normalizer_spec.rb
Closes #3322
Related to #3359, which is already closed.
Four separate pieces are removed from adminMetadata.xml;  all four of these only apply to APO objects
- `<relationships>`
- `<assembly>`
- `<accessioning>`
- `<descriptiveMetadata>` with a `<source>` child.
unit tests, roundtrip unit test,  and run actual roundtrips against APOs, and mixed object types.
`$ bin/validate-cocina-roundtrip -i druids.apos.txt -f -n`
[expect SMALL "Different" numbers in this section]
**APOs only:**
```
Status (n=1264; not using Missing for success/different/error stats):
Success:   1192 (94.304%)
Different: 72 (5.696%)
Bad cache: …
```
=> admin_metadata: normalize out cruft

bin/reports/report-content-file_deliver, bin/reports/report-content-missing_mimeType, bin/reports/report-content-not_in_sequence, bin/reports/report-content-objectid, bin/reports/report-content-problematic-virtual, bin/reports/report-content-thumb, bin/reports/report-content-virtual
`//` in xpath is interpreted as "search the whole tree ... which is no big deal for small trees of xml, but some of our contentMetadata is pathologically large.  This probably won't make a difference as it's not narrowing down the nodes to be searched in a single contentMetadataDS ... but it makes me feel better?
=> reports - improve paths for contentMetadata reports 

bin/reports/report-content-missing-file-size
add a report to help us decide how to deal with #3443
run on ETDs and it came back with the single known ETD with this problem.
=> report for contentMetadata/resource/file[@size='']

app/models/object_version.rb, app/services/datastream_extractor.rb, spec/models/object_version_spec.rb, spec/services/datastream_extractor_spec.rb
=> [Refactor] Move version metadata generation to ObjectVersion.

app/controllers/metadata_controller.rb, app/services/publish/metadata_transfer_service.rb, app/services/publish/public_cocina_service.rb, app/services/publish/public_xml_service.rb, spec/services/publish/metadata_transfer_service_spec.rb, spec/services/publish/public_xml_service_spec.rb
Fixes #3328
The only property from identityMetadata that is used by purl is the catkey:
https://github.com/search?q=identityMetadata+repo%3Asul-dlss%2Fpurl+path%3Aapp&type=Code
=> Export the identity metadata to the public metadata xml

app/services/publish/public_xml_service.rb, spec/requests/metadata_spec.rb, spec/services/publish/public_xml_service_spec.rb
purl-fetcher uses this to index they type: https://github.com/sul-dlss/purl-fetcher/blob/cc003ceaf67a90bbf549b1b4bd55706ddc0cc0c5/app/services/purl_parser.rb#L55-L57
Unit test added
=> Export the identityMetadata/objecType to public XML

app/services/cocina/from_fedora/identification.rb, spec/services/cocina/mapper_spec.rb
Fixes #3474 - ignore empty catkeys when mapping
Added new test and verified it fails before the change and passes after it (q: is it in the right place?  I couldn't find another better location...)
=> ignore empty catkeys when mapping from fedora

app/services/cocina/normalizers/content_metadata_normalizer.rb, spec/services/cocina/normalizers/content_metadata_normalizer_spec.rb
Fixes #3473 - normalize blank file directives (publish/preserve/shelve) to no
HOLD pending roundtrip validation testing
1. Added a new test
2. Running roundtrip validations, results in comment below
=> [HOLD] normalize blank file directives to no

app/services/cocina/from_fedora/collection.rb, app/services/cocina/from_fedora/identification.rb, spec/services/cocina/mapper_spec.rb
Fixes #3470 - previous catkeys for collections should be mapped (also strip extra spaces when mapping catkeys)
(Assuming this is what we want, and not what was coded before).
Added a new test (and verified it fails without change and passes with).
=> map previous catkeys for collections

bin/reports/report-content-resource-preview-not-geodata, bin/reports/report-content-resource-preview-yes-geodata
These reports were requested by Andrew, presumably to gain an understanding of what contentMetadata resources are of type "preview" and how it is used (captured in the ticket)
Part of #3467 
=> Reports for contentMetadata resource of type preview

app/services/cocina/from_fedora/apo.rb, app/services/cocina/from_fedora/collection.rb, app/services/cocina/from_fedora/dro.rb, app/services/cocina/from_fedora/label.rb, app/services/cocina/normalizers/identity_normalizer.rb, spec/services/cocina/from_fedora/label_spec.rb, spec/services/cocina/mapper_spec.rb, spec/services/cocina/normalizers/identity_normalizer_spec.rb
Some objects have line feeds in `<objectLabel>`. Line feeds are removed when mapping to Cocina, but line feeds also need to be removed from `<objectLabel>` when normalizing identity metadata.
Unit tests.
`bin/validate-cocina-roundtrip -s 100000 -n -f`
**Before:**
Success:   99907 (99.984%)
Different: 4 (0.004%)
Mapping error:     12 (0.012%)
Expected unmapped:     77 (0.077%)
**After:**
Success:   99906 (99.983%)
Different: 3 (0.003%)
Mapping error:     14 (0.014%)
Normalization …
=> Remove linefeeds from objectLabel in normalization

lib/report.rb
To help us use the -f flag more often for faster report runs.
=> report: better documentation of -f option

app/services/cocina/normalizers/admin_normalizer.rb, spec/services/cocina/normalizers/admin_normalizer_spec.rb
Fixes #3471 - remove contacts when normalizing adminMetadata
- Added new test
- validate-cocina-roundtrip results (shown in comments below, no change)
=> remove contact nodes from adminMetadata

app/services/cocina/normalizers/identity_normalizer.rb, spec/services/cocina/normalizers/identity_normalizer_spec.rb
Fixes #3401 
Equal round trip runs
```
Success:   99896 (99.978%)
Different: 6 (0.006%)
Mapping error:     16 (0.016%)
```
After:
```
Success:   99896 (99.978%)
Different: 6 (0.006%)
Mapping error:     16 (0.016%)
```
⚡ ⚠ If this change has cross service impact, ***run integration tests*** and/or test …
=> Remove duplicate source ids from original xml

bin/reports/report-invalid-agreement
Report for invalid agreement objects (re: action for #3469)
Ran report on just agreement objects.  Results below:
```
./bin/reports/report-invalid-agreement -f -i druids.agreements.txt
```
```
druid,apo,catkey,message
druid:dg278wx3858,,,
druid:dt823rz5296,,,
druid:ft372rz1240,,,
druid:gm695yd8142,,,
druid:hq927rk2991,,,
druid:mk868xs8150,,,
druid:mw295sx0691,,,
druid:pq564qy0793,,,
druid:py754rs4479,,,
druid:rd901vy3935,,,
druid:rp956gh8463,,,
druid:sb526wm1291,,,
druid:sh907mq5434,,,
druid:sj243xv3654,,,
druid:sp446mf1465,,,
druid:sq935ky5956,,,
druid:td469vd5422,,,
druid:tk248ff9846,,,
druid:tm368gc3870,,,
druid:vs363xg0079,,,
druid:vz378kx9883,,,
druid:xg091rg0886,,,
druid:xm864kq4041,,,
druid:yy885bd8557,,,
druid:zf455ms5258,,,
druid:zh724bv4125,,,
druid:zp985cv0241,,,
```
=> write report for invalid agreement objects

bin/validate-cocina-roundtrip
Keep `validate-cocina-roundtrip` from crashing and log the problem druids.
sdr-deploy
=> Catch errors in validate-cocina-roundtrip.

app/controllers/metadata_controller.rb, app/controllers/queries_controller.rb, app/services/cocina/from_fedora/descriptive/titles.rb, app/services/cocina_object_store.rb, app/services/publish/metadata_transfer_service.rb, app/services/publish/public_desc_metadata_service.rb, app/services/publish/public_xml_service.rb, app/services/title_builder.rb, spec/services/publish/dublin_core_service_spec.rb, spec/services/publish/metadata_transfer_service_spec.rb, spec/services/publish/public_desc_metadata_service_spec.rb, spec/services/title_builder_spec.rb
=> Decouple moving collections into public descriptive from ActiveFedora

app/services/preserve/bag_verifier.rb, spec/services/preserve/bag_verifier_spec.rb
The BagVerifier should ensure that `cocina.json` is present.
Unit tests.
closes #3496
=> Require cocina.json in BagVerifier

app/controllers/objects_controller.rb, app/services/cocina/object_creator.rb, app/services/cocina/object_updater.rb, app/services/cocina_object_store.rb, app/validators/cocina/object_validator.rb, spec/requests/update_metadata_spec.rb, spec/services/cocina/object_creator_spec.rb, spec/services/cocina_object_store_spec.rb, spec/validators/cocina/object_validator_spec.rb
closes #3497
Allow validation will need to be performed regardless of whether persisting to Fedora or PG.
Unit
=> Extracts validation from ObjectCreator and ObjectUpdater.

app/services/publish/public_xml_service.rb, spec/requests/metadata_spec.rb, spec/services/publish/public_xml_service_spec.rb
This value is used by the searchworks indexer for collection titles.
See https://github.com/sul-dlss/searchworks_traject_indexer/blob/master/lib/sdr_stuff.rb#L54
=> Include the objectLabel in the public xml

app/services/cocina/normalizers/content_metadata_normalizer.rb, spec/services/cocina/normalizers/content_metadata_normalizer_spec.rb
Resolves #3409 to normalize contentMetadata relationship node in virtual objects.
Added spec and specs pass. `bin/validate-cocina-roundtrip -s 100000` on sdr-deploy has no change:
Before:
```
Success:   99791 (99.873%)
Different: 127 (0.127%)
```
After
```
Success:   99791 (99.873%)
Different: 127 (0.127%)
Missing from cache:     0 …
```
=> Normalizing virtual object relationship type.

app/jobs/publish_job.rb, app/jobs/shelve_job.rb, app/validators/cocina/apo_existence_validator.rb, app/validators/cocina/collection_existence_validator.rb, app/validators/cocina/unique_source_id_validator.rb, app/validators/cocina/validate_dark_service.rb, spec/requests/create_object_spec.rb, spec/validators/cocina/validate_dark_service_spec.rb
confusing variable names leads to confusion. 
Closes #3506    @justinlittman  is this what the ticket meant?
unit tests
nope.
=> refactor: use cocina_object instead of item in validators

app/controllers/metadata_controller.rb, app/controllers/mods_controller.rb, app/services/cocina_object_store.rb, app/services/embargo_release_service.rb, app/services/notifications/embargo_lifted.rb, app/services/notifications/object_created.rb, app/services/notifications/object_deleted.rb, app/services/notifications/object_updated.rb, spec/requests/legacy_metadata_update_spec.rb, spec/requests/mods_update_spec.rb, spec/services/cocina_object_store_spec.rb, spec/services/embargo_release_service_spec.rb, spec/services/notifications/embargo_lifted_spec.rb, spec/services/notifications/object_created_spec.rb, spec/services/notifications/object_deleted_spec.rb, spec/services/notifications/object_updated_spec.rb
Fixes #3507 - make the notifications responsible for checking if rabbitMQ is enabled instead of the caller
Added new tests
NOTE: The diffs in the specs are less substantial than they appear.  The existing tests were moved into a new context of "RabbitMQ enabled", with mocking of that setting to true.  Then a new context block was added mocking RabbitMQ to disabled to verify the messages are not sent.
=> [refactor] each notification aborts itself if rabbitMQ is not enabled

app/services/cocina/normalizers/mods_normalizer.rb
Fixes #3461
First, they are not necessary, apparently! Second, they are causing the normalizer to break when navigating empty documents (like druid:xv582wk4533 with empty descMetadata).
CI + sdr-deploy
```shell
$ bin/validate-cocina-roundtrip -f -d druid:xv582wk4533
Status (n=1; not using Missing for success/different/error stats):
Success:   0 (0.0%)
Mapping error:     1 (100.0%)
```
☝🏻 used to raise `NoMethodError`
=> Remove unnecessary calls to `#root`

app/services/preservation_metadata_extractor.rb, spec/services/preservation_metadata_extractor_spec.rb
Fixes #3466 by calling `Cocina::ToFedora::ContentMetadataGenerator` in order to write content metadata for preservation instead of writing the fedora based datastream.
Updated unit test.
=> Use ContentMetadataGenerator to output contentMetadata XML for pres

app/services/cocina/object_creator.rb, app/services/cocina_object_store.rb, spec/services/cocina/object_creator_spec.rb, spec/services/cocina_object_store_spec.rb
Resolves #3511 to move druid minting from ObjectCreator to CocinaObjectStore.
Specs pass (made two changes, however).
=> Extracting druid minting from ObjectCreator

bin/reports/report-content-file-directives-blank
To find data to match certain criteria, presumably to be examined and decisions to be made.
Closes #3533
Ran code in rails console with hoked up contentMetadata.
=> add report-content-file-directives-blank

app/services/cocina/normalizers/content_metadata_normalizer.rb, app/services/cocina/object_creator.rb, spec/services/cocina/normalizers/content_metadata_normalizer_spec.rb
Fixes #3541 - normalize non-integer imagedata to be integers and strip units
Note: changed some existing method names to be more clear 
HOLD Pending validate cocina tests
- New unit test
- validate cocina roundtrip
=> [HOLD] normalize non-integer imagedata

app/services/cocina/normalizers/content_metadata_normalizer.rb, spec/services/cocina/normalizers/content_metadata_normalizer_spec.rb
closes #3567
Roundtrippin'
Before:
```
Success:   99795 (99.877%)
Different: 123 (0.123%)
```
After:
```
Success:   99795 (99.877%)
Different: 123 (0.123%) …
```
=> Normalizes empty resources.

app/controllers/mods_controller.rb, app/services/cocina/object_updater.rb, spec/requests/metadata_spec.rb, spec/requests/mods_update_spec.rb, spec/requests/update_metadata_spec.rb
Fixes #3529 by refactoring mods_controller#update for the CocinaObjectStore.
Fixes #3528 by refactoring mods_controller#show to use a cocina object
Updated tests
=> Decouple mods_controller from ActiveFedora

app/services/cocina/from_fedora/descriptive.rb, app/services/cocina/normalizers/mods_normalizer.rb, spec/services/cocina/normalizers/mods/title_normalizer_spec.rb, spec/support/mods_mapping_spec_helper.rb
closes #3553
Avoid normalizer error.
Before:
```
Success:   99795 (99.877%)
Different: 123 (0.123%)
```
After:
```
Success:   99795 (99.877%)
Different: 123 (0.123%) …
```
=> Handle Hydrus APOs with no descriptive metadata.

app/services/cocina/normalizers/identity_normalizer.rb, spec/services/cocina/normalizers/identity_normalizer_spec.rb
closes #3558
Roundtrippin'
Unit, local with druids mentioned in ticket, sdr-deploy
Before:
```
Status (n=50000; not using Missing for success/different/error stats):
Success:   49895 (99.86%)
Different: 70 (0.14%)
Expected unmapped:     35 (0.07%)
```
After:
```
Status (n=50000; not using Missing for success/different/error stats):
Success:   49895 (99.86%)
Different: 70 (0.14%)
Mapping error:     0 …
```
=> Remove trailing whitespace from catkeys and previous_catkeys.

app/services/cocina/object_creator.rb, app/services/cocina/object_updater.rb, app/services/cocina_object_store.rb, spec/requests/update_metadata_spec.rb, spec/services/cocina/object_creator_spec.rb, spec/services/cocina/object_updater_spec.rb, spec/services/cocina_object_store_spec.rb
closes #3512
Move non-Fedora specific code out of ObjectCreator and ObjectUpdater.
I implemented 3 tickets in a single PR so that I only had to run integration tests once.
Ran integration tests in QA.
=> Extract from ObjectCreator/ObjectUpdater to CocinaObjectStore.

app/services/access_merge_service.rb, app/services/cocina_object_store.rb, spec/requests/create_collection_spec.rb, spec/services/access_merge_service_spec.rb, spec/services/cocina_object_store_spec.rb
closes https://github.com/sul-dlss/google-books/issues/753
The previous logic was causing APO default object rights to trump collection/DRO provided rights.
Unit
=> [HOLD] Fixes logic for applying default object rights.

bin/reports/report-content-imagedata-not-num
To look beyond the tea leaves into the actual data, I presume.
Closes #3540 
I ran the code in this report against some contentMetadata in the rails console.
=> add report-content-imagedata-not-num

app/services/cocina/from_fedora/dro_structural.rb, app/services/cocina/from_fedora/viewing_direction_helper.rb, app/services/cocina/normalizers/content_metadata_normalizer.rb, spec/services/cocina/from_fedora/dro_structural_spec.rb
This prevents diffs from showing up in the round trip testing.
Fixes #3563
Before:
```
Status (n=25000; not using Missing for success/different/error stats):
Success:   24785 (99.863%)
Different: 34 (0.137%)
Missing from cache:     6 (0.024%)
Expected unmapped:     175 (0.7%)
```
After:
```
Status (n=25000; not using Missing for success/different/error stats):
Success:   24785 (99.863%)
Different: 34 (0.137%)
Missing from cache:     6 (0.024%)
Expected unmapped:     175 (0.7%)
Validate error: …
```
=> Create the missing bookData node as the first child when normalizing

app/services/cocina/from_fedora/file_sets.rb, app/services/cocina/normalizers/content_metadata_normalizer.rb, bin/validate-cocina-roundtrip, spec/services/cocina/from_fedora/dro_structural_spec.rb, spec/services/cocina/normalizers/content_metadata_normalizer_spec.rb
closes #3542 
per that ticket, when `<file mimetype="image/svg+xml">`:
* `<imageData>` should not be mapped to presentation
* `<imageData>` should be removed in normalization.
i also threw on a commit for printing branch info and time of run in `validate-cocina-roundtrip`, which i find helpful when doing roundtrip testing, happy to lop that off if people find it unnecessary.
=> omit imageData for SVG

app/controllers/objects_controller.rb, app/services/cocina_object_store.rb, spec/services/cocina_object_store_spec.rb
We're trying to get rid of the ActiveFedora dependency.
=> Decouple ObjectsController#show from ActiveFedora

app/models/dor/update_marc_record_service.rb, app/services/cocina/object_updater.rb, app/services/constituent_service.rb, app/services/item_query_service.rb, app/services/reset_content_metadata_service.rb, spec/dor/update_marc_record_service_spec.rb, spec/services/cocina/to_fedora/content_metadata_generator_spec.rb, spec/services/constituent_service_spec.rb, spec/services/item_query_service_spec.rb, spec/services/reset_content_metadata_service_spec.rb, spec/support/cocina_matchers.rb
Fixes #3331
Fixes #3177
This commit Cocinizes the major components involved in virtual object creation. It includes the following:
* Convert from Fedora to Cocina:
* `ConstituentService`
* `ItemQueryService`
* `ResetContentMetadataService`
* `ConstituentService` now triggers synchronous indexing of virtual objects to record the relationship in Solr, which is used subsequently when (re-)publishing constituents so their public XML includes this relationship
* `ConstituentService` also updates the MARC records for any constituent objects which have catkeys
* Add new validations to the `ItemQueryService` preventing virtual objects from having themselves as constituents, making sure all virtual objects and constituents are DROs/items, and disallowing constituents from being virtual objects …
=> Cocinize virtual object creation

app/services/cocina_object_store.rb, config/settings.yml, spec/services/cocina_object_store_spec.rb
`find` is a terrible flag.
```
2.7.0 :010 > Settings.enabled_features.postgres.find
=> #<Enumerator: #<Config::Options update=true, create=true, destroy=true, find=false>:find>
2.7.0 :011 > Settings.enabled_features.postgres
=> #<Config::Options update=true, create=true, destroy=true, find=false>
2.7.0 :014 > Settings.enabled_features.postgres.create
=> true
```
Unit
=> Change feature flag for postgres find.

app/services/cocina/from_fedora/descriptive/title_builder.rb, app/services/cocina/to_fedora/descriptive/title.rb, app/services/title_builder.rb, spec/services/cocina/mapping/descriptive/mods/title_info_spec.rb, spec/services/title_builder_spec.rb
Mapping logic for non-sorting characters assumed that there could be only one trailing space. However, a case appeared in integration testing in which there was multiple trailing spaces.
Unit
```
Before:
Success:   99798 (99.88%)
Different: 120 (0.12%)
Validate error:     0 …
```
=> Fix non-sorting with extra spaces.

bin/archive-fedora, lib/fedora_archiver.rb, spec/spec_helper.rb
This command line utility can be used to download the FOXML archive files from a Fedora instance based on a list of druids.
I tested against https://sul-dor-migrate.stanford.edu/fedora with 250,000 items. I wrote a [little program](https://gist.github.com/edsu/d0051fd6c89099af34621986f90b90ce) to analyze the log file that archive-fedora generates and it looks like for 4.3M items it will take 14 days, and generate 94 GB of data. The size seemed low to me, if the FOXML truly contains all versions of datastreams for the object?
Closes #3102
=> Archive versions

app/models/dor/update_marc_record_service.rb, spec/dor/update_marc_record_service_spec.rb
Fixes #3641 by restoring the selection of part sort from description.note (as well as title parts)
Fixed a bad test that suggested it was testing part sort from note, but was really title.
=> Restore fetching 856 sort from note as well as title

app/controllers/members_controller.rb, spec/requests/members_for_collection_spec.rb
This helps us decouple from ActiveFedora
=> Stop using ActiveFedora::Base.internal_uri

app/models/dor/update_marc_record_service.rb, app/services/thumbnail_service.rb, spec/dor/update_marc_record_service_spec.rb, spec/requests/mods_update_spec.rb, spec/requests/update_marc_record_spec.rb, spec/services/publish/public_xml_service_spec.rb, spec/services/thumbnail_service_spec.rb
closes #3638
Reduce use of dor-services gem.
=> Stop using Dor::PidUtils.

app/services/apply_admin_policy_defaults.rb, spec/services/apply_admin_policy_defaults_spec.rb
closes #3648
Access rights were getting merged instead of applied, leading to erroneous rights.
Unit
=> Apply APO defaults, not merge.

app/services/delete_service.rb, app/services/reset_workspace_service.rb, app/services/shelving_service.rb, spec/services/cleanup_service_spec.rb, spec/services/delete_service_spec.rb, spec/services/reset_workspace_service_spec.rb, spec/services/shelving_service_spec.rb
Fixes #3637 -- also verified there are no more instances of `Dor::Config` left in the code
Existing tests
=> use settings instead of dor:config

app/validators/cocina/description_roundtrip_validator.rb, spec/validators/cocina/description_roundtrip_validator_spec.rb
Roundtrip validation was causing refresh metadata to mistakingly fail.
Unit
=> Ignore identifiers when roundtrip validating.

app/controllers/metadata_refresh_controller.rb, app/services/cocina/object_creator.rb, app/services/legacy_refresh_metadata_action.rb, app/services/refresh_metadata_action.rb, bin/refresh-metadata, spec/requests/metadata_refresh_spec.rb, spec/services/cocina/object_creator_spec.rb, spec/services/legacy_refresh_metadata_action_spec.rb, spec/services/refresh_metadata_action_spec.rb
Fixes #3169 - rewrites RefreshMetadataAction to use cocina objects, Moves existing RefreshMetadataAction into LegacyRefreshMetadataAction for object creation where Draft cocina objects do not have the required externalIdentifier yet.
Updated unit tests.
=> Rewrite RefreshMetadataAction for Cocina objects

app/services/cocina/object_creator.rb, app/services/cocina_object_store.rb, spec/services/cocina/object_creator_spec.rb, spec/services/cocina_object_store_spec.rb
closes #3625
This action is required regardless of datastore.
Unit
=> Move creating description from label to CocinaObjectStore

app/services/publish/public_xml_service.rb, app/services/publish/rights_metadata.rb, bin/reports/report-rights-discover-world, spec/requests/metadata_spec.rb, spec/services/publish/public_xml_service_spec.rb, spec/services/publish/rights_metadata_spec.rb
Hold for testing by Andrew
Fixes #3330
This adds a lot of rights combinations based on https://argo-stage.stanford.edu/catalog?f%5Bnonhydrus_collection_title_ssim%5D%5B%5D=rights+examples for testing and builds the `rightsMetadata` XML for PublicXml.
Prior to this the only change to the rights metadata datastream in public xml was to add an embargo release date, so this change is relatively significant in that now it has to build the XML.
Updated unit tests.
As this touches integration tests should probably be run.
=> Rewrite rights metadata in public xml to use Cocina

app/services/cocina/to_fedora/collection_access.rb, app/services/cocina/to_fedora/dro_access.rb, spec/services/cocina/to_fedora/collection_access_spec.rb, spec/services/cocina/to_fedora/dro_access_spec.rb
Fixes https://github.com/sul-dlss/argo/issues/3200
While the issue this closes is only about DROs, I figure we are going to run into the same problem with collections eventually, so bring parity to the access approaches of DROs and collections.
CI, and in QA (approved by @andrewjbtw)
=> Allow collection and item use statements to be blanked

app/services/cocina_object_store.rb, app/validators/cocina/object_validator.rb, db/migrate/20220307201030_add_unique_source_id_to_dros.rb, db/migrate/20220307201420_add_unique_source_id_to_collections.rb, db/structure.sql, spec/models/collection_spec.rb, spec/models/dro_spec.rb, spec/services/cocina_object_store_spec.rb
closes #3665
This approach is more reliable then querying Solr (since updating Solr involves a latency).
Unit
=> Adds uniqueness constraint for sourceId for DROs and collections.

app/services/cocina/normalizers/content_metadata_normalizer.rb, spec/services/cocina/normalizers/content_metadata_normalizer_spec.rb
Deal with messy virtual objects.
Unit
Before:
```
Success:   9979 (99.87%)
Different: 13 (0.13%)
Expected unmapped:     8 (0.08%)
Virtual objects:
Status (n=4674; not using Missing for success/different/error stats):
Success:   4611 (98.652%)
Different: 63 (1.348%)
Mapping error:     0 …
```
=> Virtual object normalization

app/services/cocina/normalizers/content_metadata_normalizer.rb, spec/services/cocina/normalizers/content_metadata_normalizer_spec.rb
Reading order was getting dropped in normalization for virtual objects.
Unit
Before:
```
Success:   9980 (99.88%)
Different: 12 (0.12%)
Expected unmapped:     8 (0.08%)
```
After:
```
Success:   9980 (99.88%) …
```
=> Tweaks ordering of content metadata normalizers.

app/services/cocina/from_fedora/dro_structural.rb, spec/services/cocina/mapping/structural/virtual_object_spec.rb
closes #3687
Virtual object mapping wasn't correctly handling constituents with multiple files.
Unit
=> Dedupe virtual object members.

bin/archive-fedora, lib/fedora_archiver.rb
It would be useful to see a projection of how long the archive process might take in addition to the progress bar.
I tested against https://sul-dor-migrate.stanford.edu/fedora with a few thousand druids.
=> Improve archive-fedora progressbar

config/deploy/qa.rb
To deploy the latest code behind the load balancer
I verified capistrano could deploy to the nodes.
=> Deploy qa to load balancer

Capfile, Gemfile, Gemfile.lock, config/deploy.rb
To enable the app to deploy to Ubuntu machines
By deploying it beforehand.
=> Let the app deploy to Ubuntu

app/services/apply_admin_policy_defaults.rb
Previously it would look up the APO once for each file in the object.
Fixes #3699
=> Add cache to prevent repeated lookup of APO

app/services/notifications/object_updated.rb, spec/services/notifications/object_updated_spec.rb
This was part of the update to cocina-models 0.68.0
CI and running integration tests in QA
=> Use the project admin tag for routing update messages

app/services/cocina/object_updater.rb, spec/services/cocina/object_updater_spec.rb
Fixes #3693 - provide better error message indicating which way the version mismatches (is that what you were thinking Jcoyne?)
Added a new test
=> indicate which way version is mismatched

app/validators/cocina/unique_source_id_validator.rb, spec/requests/create_object_spec.rb
Previously it was inspecting a single element array, but now it just shows the single conflicting druid
Fixes https://github.com/sul-dlss/sdr-api/issues/415
=> Fix the message returned on a source ID conflict

app/services/cocina/from_fedora/descriptive/identifier_builder.rb, spec/services/cocina/mapping/descriptive/mods/identifier_spec.rb, spec/services/cocina/mapping/descriptive/mods/part_spec.rb
closes #3728
Per specs.
Before:
```
Success:   99981 (99.981%)
Different: 19 (0.019%)
```
After:
```
Success:   99981 (99.981%)
Different: 19 (0.019%)
Missing (no descMetadata): …
```
=> Implements streamlined identifier specs.

app/services/item_query_service.rb, spec/services/item_query_service_spec.rb
Fixes #3675 to allow a virtual object to be recreated via CSV upload.
Ran the create virtual objects integration test on QA. Loaded a CSV with a current virtual object druid and only one of its constituents. Then the job completed, only the specified constituent was a member. The other was no longer attached. Also, specs passed and added to them.  
=> Allow existing virtual objects to be changed.

bin/migrate-audit
closes #3712
Per @andrewjbtw allow verifying that all objects were migration from Fedora to PG.
On DSA migrate:
```
[dor_services@dor-services-migrate current]$ RAILS_ENV=production bin/migrate-audit -i ~/druids.20220219.txt -s 250000
Provided druids: 250000
Found: 246283
Missing: 3717
```
=> Adds migration audit script.

app/services/cocina_object_store.rb, spec/services/cocina_object_store_spec.rb
Some attributes are not required in request cocina, but are required in cocina. This inserts them when missing.
=> Handle attributes that are not required in request cocina.

app/models/collection.rb, app/models/dro.rb, spec/models/collection_spec.rb, spec/models/dro_spec.rb
Patches a bug we are seeing in QA since QA has collections w/o identification metadata (and DROs w/o structural metadata) and cocina-models 0.70.0 now requires both of these.
CI + tested in QA
=> Default required DRO & collection metadata to an empty hash instead of nil

app/controllers/metadata_refresh_controller.rb, spec/requests/metadata_refresh_spec.rb
Fixes a production bug: https://app.honeybadger.io/projects/50568/faults/84622595
This exception is raised when acting on a collection: collection identification metadata does not include barcodes, so this raises a `NoMethodError`.
CI
=> Do not assume all identification metadata has barcodes

app/services/cocina/from_fedora/descriptive/titles.rb, spec/services/cocina/from_fedora/descriptive/titles_spec.rb
closes #3752
Handle anomalous data without raising.
Unit
=> Handle empty titles when mapping uniform titles.

app/controllers/objects_controller.rb, app/controllers/queries_controller.rb, app/models/admin_policy.rb, app/models/collection.rb, app/models/dro.rb, app/services/cocina_object_store.rb, db/migrate/20220311015318_add_lock_version.rb, db/structure.sql, openapi.yml, spec/models/admin_policy_spec.rb, spec/models/dro_spec.rb, spec/requests/collections_for_object_spec.rb, spec/requests/create_object_spec.rb, spec/requests/show_object_spec.rb, spec/requests/update_metadata_spec.rb, spec/services/cocina_object_store_spec.rb
Prevent confusion over immutable cocina objects.
Unit, integration tests in QA
=> Very optimistic locking

app/services/synchronous_indexer.rb, spec/services/synchronous_indexer_spec.rb
So that SynchronousIndexer passes a cocina object without metadata. DIA does not expect the metadata.
Unit
=> Handle DROWithMetadata in SynchronousIndexer.

app/services/cocina_object_store.rb, spec/requests/update_metadata_spec.rb, spec/services/cocina_object_store_spec.rb
The RFC (https://datatracker.ietf.org/doc/html/rfc7232#section-2.3) specifies opqaue ETags, so opaqify them.
=> Make the ETag value opaque.

app/services/cocina/object_updater.rb, openapi.yml, spec/requests/batch_create_virtual_objects_spec.rb, spec/services/cocina/object_updater_spec.rb
refs https://github.com/sul-dlss/argo/issues/2821
To allow clearing constitutuents from a virtual object.
QA
=> Allow empty constituents in openapi to allow clearing virtual objects.

bin/reports/report-desc-identifier-type
Fixes #3783. 
Run on sdr-deploy: `bin/reports/report-desc-identifier-type -i druids.txt`
There were 48 values in the result, including `""`, which may appear as a blank line in the attached file, depending on how you're viewing it.  
[results-identifiers.txt](https://github.com/sul-dlss/dor-services-app/files/8398607/results-identifiers.txt)
=> Report on desc metadata identifier type

Gemfile, Gemfile.lock, app/services/prune_service.rb, spec/services/prune_service_spec.rb
Do not delete the parent when pruning Access druids, since these druids lack the extra leaf (ID) directory that non-Access druids have. This is causing unintentional pruning of the Stacks.
CI
=> Fix bug with pruning Access druids

app/services/cocina_object_store.rb, spec/services/cocina_object_store_spec.rb
=> Compare the opaque lock value for active-record based models

bin/reports/report-desc-low_parallel_values, lib/report.rb
Fixes #3795
To accomplish this, modify the Report class so it can map Fedora content to Cocina and report on that.
CI and tested the new report and an existing report on sdr-deploy
=> Add report for single-entry parallelValues

bin/reports/report-desc-edtf
As part of migration we needed a report for what look like invalid EDTF values in MODS records.
Closes #3797
Ran the report on sdr-deply against the full set of druids.txt.
=> Report on invalid EDTF in MODS dates

app/services/publish/public_desc_metadata_service.rb
Otherwise it raises a deprecation warning about the argument provided
=> TitleBuilder should be called with an array of titles

bin/validate-cocina-roundtrip
Fixes #3771
This commit makes two quality-of-life changes to the Cocina roundtrip validator:
1. Use some code from Argo (and then Rails5-ify it 😒) to allow for optionally quieter Cocina  output in roundtrip validator (removing empty arrays from descriptive metadata in the original and roundtrip Cocina)
2. Use `super_diff` to make terser, more colorful, more sensible Cocina diffs.
You can see the difference `super_diff` brings here:
CI + sdr-deploy
=> Add roundtrip flag for quieter output

bin/reports/report-desc-w3cdtf
Resolves #3796. 
Ran report on sdr-deploy against druids.txt. Report with 156,048 druids attached to issue #3796.
=> Report on w3cdtf-encoded date validity

bin/reports/report-desc-form_types
We needed a report of what form types are in use in MODS descriptive metadata.
Closes #3781
=> Report on form type in MODS

bin/reports/report-desc-part_types
Fixes #3786. Report on part type attribute values. 
Ran this on sdr-deploy with druids.txt and 0 records found. @arcadiafalcone says this is possible, but I appreciate eyes on this in case I did something incorrectly. 
=> Report on part type values

.rubocop.yml, app/services/cocina/from_fedora/descriptive/contributor.rb, app/services/cocina/normalizers/mods/name_normalizer.rb, spec/services/cocina/mapping/descriptive/mods/name_spec.rb, spec/services/cocina/normalizers/mods/name_normalizer_spec.rb
This PR implements new mappings from Arcadia for further contributor deduping on MODS -> cocina mappings, which she added as specs in PR #3819.
Fixes #3820
```
Success:   99782 (99.864%)
Different: 122 (0.122%)
Mapping error:     14 (0.014%)
```
```
Status (n=100000; not using …
```
=> more name deduping for MODS -> cocina mappings

bin/reports/report-desc-part-text_type
Fixes #3788 - report on part/text type unique values
Running report on sdr-deploy
=> add report for part/text types

.gitignore, bin/reports/report-top-level-desc-note_types
Fixes #3826 - new report for note types at top level only...also gitignore .txt and .csv files at root of app directory (if you run report locally, you may get these files and don't want to commit them)
Running example report on sdr-deploy
=> add new report; ignore any txt or csv files at root of app

spec/services/cocina/mapping/descriptive/mods/name_spec.rb
Because we have specs that pass right underneath, implying these xit lines are no longer needed.  I also asked Arcadia.
=> remove two spurious xit statements from mapping name_spec

lib/administrative_tags.rb, lib/fedora_cache.rb, lib/fedora_loader.rb, spec/spec_helper.rb
Fix monkeypatching of AdministrativeTags for caching.
```
/opt/app/deploy/sdr-deploy/shared/bundle/ruby/2.7.0/gems/pg-1.3.5/lib/pg/connection.rb:637:in `async_connect_or_reset': FATAL:  password authentication failed for user "postgres" (PG::ConnectionBad)
from /opt/app/deploy/sdr-deploy/shared/bundle/ruby/2.7.0/gems/pg-1.3.5/lib/pg/connection.rb:707:in `new'
from /opt/app/deploy/sdr-deploy/shared/bundle/ruby/2.7.0/gems/pg-1.3.5/lib/pg.rb:69:in `connect'
from /opt/app/deploy/sdr-deploy/shared/bundle/ruby/2.7.0/gems/activerecord-5.2.7/lib/active_record/connection_adapters/postgresql_adapter.rb:692:in `connect'
from /opt/app/deploy/sdr-deploy/shared/bundle/ruby/2.7.0/gems/activerecord-5.2.7/lib/active_record/connection_adapters/postgresql_adapter.rb:223:in `initialize'
```
⚡ ⚠ If this …
=> Fix monkeypatching of AdministrativeTags.

spec/services/cocina/mapping/descriptive/mods/access_condition_spec.rb
Implementation ticket #3865 
Add mapping for variant access note type
=> Add access condition note mapping to support type validation

app/services/cocina/from_fedora/descriptive/access.rb, app/services/cocina/normalizers/mods_normalizer.rb, spec/services/cocina/mapping/descriptive/mods/access_condition_spec.rb
Apparently we want to allow MODS to have "restrictionsOnAccess" as a type in the accessCondition
Fixes #3865
```
Status (n=250000; not using Missing for success/different/error stats):
Success:   249484 (99.874%)
Different: 279 (0.112%)
Mapping error:     36 (0.014%)
Expected unmapped:     201 (0.08%)
```
**NEWLY FIXED by this branch:**  NONE
**NEWLY BROKEN by this branch:**  NONE …
=> mapping: allow restrictionsOnAccess in incoming MODS

app/models/dor/update_marc_record_service.rb, spec/dor/update_marc_record_service_spec.rb
Per Andrew, when we export an 856 to Symphony, we no longer need |x for SET;  set objects are passé, and the information in |x for "set" is exactly the same as the information in |x for "collection"
Fixes #3871
=> update_marc_records_service: 856 |x for _set_ is no longer needed

spec/dor/update_marc_record_service_spec.rb, spec/factories/collections.rb, spec/factories/dros.rb, spec/models/collection_spec.rb, spec/models/dro_spec.rb, spec/services/cocina/mapping/structural/virtual_object_spec.rb, spec/services/cocina/object_creator_spec.rb, spec/services/cocina/to_datacite/event_dates_spec.rb, spec/services/cocina/to_datacite/event_pub_year_spec.rb, spec/services/cocina_object_store_spec.rb, spec/services/item_query_service_spec.rb, spec/services/publish/metadata_transfer_service_spec.rb, spec/services/publish/public_desc_metadata_service_spec.rb
Next cocina models release is going to require that purls and external identifiers match.
=> Align purls and external identifiers.

bin/validate-cocina
So that we don't accidentally use up HB quota.
=> Avoid excessive HB alerting when running validate-cocina.

.rubocop_todo.yml, app/services/cocina_object_store.rb, app/services/mods_service.rb, app/services/mods_utils.rb, app/services/refresh_metadata_action.rb, spec/requests/create_collection_spec.rb, spec/requests/create_object_spec.rb, spec/requests/metadata_refresh_spec.rb, spec/services/mods_service_spec.rb, spec/services/refresh_metadata_action_spec.rb
Everything is metadata; this service deals with MODS so it such be names as such.
=> Rename MetadataService to ModsService.

app/models/object_version.rb, app/services/version_service.rb, spec/models/object_version_spec.rb, spec/services/version_service_spec.rb
So we don't need a data remediation oriented bulk action in argo to supply missing version descriptions and tags (ticketed as #3493).  
Since we already will have empty descriptions and/or tags in the object version in the database from the migration, we have a whole series of tickets to address blank versions in our postgres SDR and to have a database constraint and openapi layer enforcement and plugging any holes in SDR code that allow versions to be created without required fields and nice error messages for HB etc.
Fixes #3910
specs
=> closing an object version now allows blank description and/or significance

app/services/cocina_object_store.rb, spec/requests/update_metadata_spec.rb, spec/services/cocina_object_store_spec.rb
Opaque locks are difficult to troubleshoot. Since this is an internal API opaque locks are unnecessary.
=> Unopaque locks.

app/controllers/application_controller.rb, app/controllers/objects_controller.rb, app/controllers/versions_controller.rb, openapi.yml, spec/requests/versions_spec.rb
In some uses of the endpoint, the client intends to further update the cocina object. To do this, it needs a cocina object with the updated version AND the etag lock for the current version.
Unit
=> Changes version open endpoint to return cocina object.

app/services/version_migration_service.rb, spec/services/version_migration_service_spec.rb
We want to avoid ObjectVersions without description or tag;  this will allow us to provide defaults for missing data upon migration.
Fixes #3904
spec
=> VersionMigrationService provides defaults for tag and description 

app/controllers/versions_controller.rb, openapi.yml, spec/requests/versions_spec.rb
This is part of a series of tickets to ensure that object versions, moving forward, will always have a description and a tag.
Fixes #3906
specs, ran all integration tests on qa
=> require description and significance parameters for VersionsController.create

app/controllers/objects_controller.rb, app/services/cocina/object_updater.rb
This ensures we continue to have the validation even after we remove the Fedora object store
Fixes #3901
Test suite
=> Move validation for path and body identifier on update to the controller

app/controllers/objects_controller.rb
=> Remove lyberservices-scripts from docs about the accession endpoint

app/services/notifications/embargo_lifted.rb, spec/services/notifications/embargo_lifted_spec.rb
Fixes sul-dlss/happy-heron#2230
We need to strip the metadata from the cocina model before publishing to the queue, since the consumer (currently H2) does not expect it to be there.
Updated specs to verify metadata is stripped when publishing the message.
=> strip metadata before publishing embargo release message to queue

spec/factories/admin_policies.rb, spec/factories/collections.rb, spec/factories/dros.rb, spec/models/admin_policy_spec.rb, spec/models/collection_spec.rb, spec/models/dro_spec.rb, spec/requests/collections_for_object_spec.rb, spec/services/cocina_object_store_spec.rb, spec/services/synchronous_indexer_spec.rb
To avoid naming conflicts when start using cocina model factories.
=> Rename active record factories.

config/application.rb
The new cocina-models code needs the base url for purl.
test suite
=> Initialize cocina-models with purl base url

app/services/cocina_object_store.rb, app/services/fedora_persistence.rb
This will make them easier to remove when the time comes. (fewer merge conflicts)
test suite
=> Extract the Fedora coupled persistence methods to their own module

README.md
rubocop seems to behave differently under rake than when invoking it
directly:
```
$ rake rubocop
app/services/cocina/from_fedora/dro.rb:46:7: W: Lint/ShadowedException: Do not shadow rescued Exceptions.
rescue Rubydora::FedoraInvalidRequest, StandardError => e ...
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
app/services/cocina_object_store.rb:155:3: W: Lint/ShadowedException: Do not shadow rescued Exceptions.
rescue Rubydora::FedoraInvalidRequest, StandardError => e ...
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
app/services/events_migration_service.rb:19:3: W: Lint/ShadowedException: Do not shadow rescued Exceptions.
rescue Rubydora::FedoraInvalidRequest, StandardError => e ...
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ …
```
=> Use rspec for tests

bin/reports/report-desc-date_ranges
Fixes #3965 - date range report for ruderman collection
on sdr-deploy, results in comment below
Run with just list of ruderman druids:
`bin/reports/report-desc-date_ranges -i /opt/app/deploy/dor-services-app/ruderman.txt -f`
=> create date range report

README.md, app/controllers/metadata_refresh_controller.rb, app/services/cocina_object_store.rb, app/services/refresh_metadata_action.rb, spec/services/cocina_object_store_spec.rb
Fixes #3847 - check to be sure catkey/barcodes are refresh-able before pulling
Also, update some related code comments to better reflect reality.
Finally, add a note about dor-services-app ruby version needed for testing to the readme
Added a new test
=> only refresh catkeys/barcodes that are marked to refresh

app/controllers/metadata_refresh_controller.rb, app/services/cocina_object_store.rb, app/services/refresh_metadata_action.rb, spec/services/cocina_object_store_spec.rb, spec/services/refresh_metadata_action_spec.rb
After working on #3993 (modifying how barcode/catkeys are refreshed), I thought it would be wise to remove the duplication of the logic I modified and place in a central location as well.  
Added some tests too.
Question: is there a reason the refresh action in the controller goes digging for a barcode while the cocina object store class does not?  Should they work the same way (i.e. by moving that bit of logic out of the controller and into the single "identifiers" method)?
New tests
=> Refactor catkeys/barcode fetching method

app/controllers/objects_controller.rb, app/controllers/versions_controller.rb, app/services/embargo_release_service.rb, app/services/version_service.rb, spec/requests/start_accession_spec.rb, spec/requests/versions_spec.rb, spec/services/embargo_release_service_spec.rb
This improves the readability of the code by not requiring a lot of boilerplate, while maintaining dependency injection.
fixes #3935
Test suite
=> [refactor] Provide a default event_factory for the VersionService

app/validators/cocina/apo_existence_validator.rb, spec/validators/cocina/apo_existence_validator_spec.rb
To allow seeding in Argo (which requires UR APO).
Unit
=> Exempt UR APO from ApoExistenceValidator.

app/services/cocina_object_store.rb, app/services/ur_admin_policy_factory.rb, app/validators/cocina/apo_existence_validator.rb, config/settings.yml, spec/requests/create_object_spec.rb, spec/services/ur_admin_policy_factory_spec.rb, spec/validators/cocina/apo_existence_validator_spec.rb
It was trying to create Fedora objects.
Tested with argo.
=> Convert ur apo factory to use activerecord.

app/services/publish/public_xml_service.rb, spec/requests/metadata_spec.rb, spec/services/publish/public_xml_service_spec.rb
We are decoupling from dor-services
There doesn't appear to be any code that references this property, but many fixtures have it populated: https://github.com/search?p=2&q=org%3Asul-dlss+publishVersion&type=Code
=> Stop making reference to Dor::VERSION

app/controllers/objects_controller.rb, app/services/delete_service.rb, spec/services/delete_service_spec.rb
closes #4002
Allow tracking of purged objects.
=> Adds a delete event when purging.

app/controllers/application_controller.rb, app/controllers/objects_controller.rb, app/services/cocina_object_store.rb
We don't have Mapping errors anymore.
CI
=> Remove unnecessary rescue blocks

spec/services/cocina_object_store_spec.rb, spec/services/refresh_metadata_action_spec.rb
Purl.for() is more concise and we're decoupling from dor-services
CI
=> Stop using Dor::PidUtils

app/models/object_version.rb
```
DEPRECATION WARNING: NOT conditions will no longer behave as NOR in Rails 6.1. To continue using NOR conditions, NOT each condition individually (`.where.not(:tag => ...).where.not(:version => ...)`). (called from update_current_version at /Users/jlittman/data/sdr/dor-services-app/app/models/object_version.rb:66)
```
=> Fix Rails 6.1 deprecation warning.

Dockerfile
```
argo-dor-services-app-1  | Running server
argo-dor-services-app-1  | Puma starting in single mode...
argo-dor-services-app-1  | * Puma version: 5.6.4 (ruby 2.7.5-p203) ("Birdie's Version")
argo-dor-services-app-1  | *  Min threads: 5
argo-dor-services-app-1  | *  Max threads: 5
argo-dor-services-app-1  | *  Environment: production
argo-dor-services-app-1  | *          PID: 1
argo-dor-services-app-1  | I, [2022-05-10T18:40:50.310479 #1]  INFO -- honeybadger: ** [Honeybadger] Initializing Honeybadger Error Tracker for Ruby. Ship it! version=4.12.1 framework=rails level=1 pid=1
argo-dor-services-app-1  | * Listening on http://0.0.0.0:3000
argo-dor-services-app-1  | /usr/local/bundle/gems/puma-5.6.4/lib/puma/launcher.rb:248:in `write': No such file or directory @ rb_sysopen - …
```
=> Fix Dockerfile.

app/services/cocina/from_fedora/data_error_notifier.rb, spec/services/cocina/from_fedora/data_error_notifier_spec.rb
And remove feature flags because we're happy with this behavior now.
=> Remove unused DataErrorNotifier#warn

app/services/publish/public_desc_metadata_service.rb, app/services/publish/public_xml_service.rb
This PR makes this differentiation, because Ruby 3 is not as tolerant of this ambiguity
CI
=> Rails passes a hash of options to #to_xml, not kwargs

app/controllers/metadata_refresh_controller.rb, app/services/marc_service.rb, spec/requests/metadata_refresh_spec.rb
Based on testing of https://github.com/sul-dlss/argo/pull/3681 and discussion in https://stanfordlib.slack.com/archives/C09M7P91R/p1652304265980159
1. The error message you get in Argo when a catkey is not found and there is no barcode in the record is confusing and looks like this: 
```
An error occurred while attempting to refresh metadata: Catkey not found in Symphony (Catalog record not found with 6671606567 and )
```
It makes more sense to clearly label the catkey and barcode values sent (or make it clear they are blank via the label)
2. The error message you get in Argo when there is a catkey but it is not set to refresh also gives a technically correct but not very useful error message:
```
An error occurred while attempting to refresh metadata: No resolvable identifiers …
```
=> better error messages for metadata refresh from symphony

spec/requests/create_object_spec.rb
There no longer are Hydrus objects.
=> Remove Hydrus test

app/services/shelvable_files_stager.rb, app/services/shelving_service.rb, spec/services/shelvable_files_stager_spec.rb, spec/services/shelving_service_spec.rb
Previously both ShelvableFilesStager and ShelvingService needed to be aware of ContentMetadata. Now that concern is wholly within ShelvingService
=> Refactor ShelvingService

app/controllers/objects_controller.rb, app/services/delete_service.rb, openapi.yml, spec/requests/destroy_spec.rb, spec/services/delete_service_spec.rb
Closes #4013 this passes a user_name to the delete service in order to record in the event.
If there is more to this ticket, please comment and I'm happy to address.
Updated unit tests.
=> Pass user_name to the delete service

app/services/preservation_metadata_extractor.rb, spec/services/preservation_metadata_extractor_spec.rb
=> Exclude the workflows.xml file from preservation.

openapi.yml
The dor-services-client doesn't support it yet.
=> Don't require user_name on delete

Capfile, Gemfile, Gemfile.lock, config/deploy.rb
We are handling this via puppet instead, by ensuring a default system bashrc is executed, which will take care of RVM bootstrapping.
CI + QA
=> Remove capistrano-rvm and other bits added to help deploy to ubuntu boxes

app/services/update_marc_record_service.rb, spec/services/update_marc_record_service_spec.rb
Fixes #4085 - updates to setting of rights when creating MARC records sent to searchworks
- For any object with `controlledDigitalLending` set to true, we will set CDL rights in the marc.  This is a fix of missing behavior.
- We will *not* set CDL rights anymore for objects with view=world and download=stanford (this seems wrong to Andrew and me).  Instead rights will now be blank in the marc.  This is a change in existing behavior.
- We will continue to leave rights blank for records with view=stanford and download=none.  This is the current behavior but had a test now to verify.  This behavior may change in the future if needed.
New/updated tests
=> set CDL rights when boolean is set to true

app/reports/bad_edtf_dates.rb, app/reports/bad_iso8601_dates.rb, app/reports/bad_w3cdtf_dates.rb
This commit adds some trickier cases to the date validation reports. This likely doesn't change the overall report very much given most of our data is simpler than this accounts for, but does give us a fuller picture of how much date validation work lies ahead of being able to switch on date validation at cocina creation time.
It also fixes the output of the W3CDTF report to include bad values, as specified, instead of literal `true`s
Ran on stage and prod.
=> Catch highly nested values in date validation reports

app/services/publish/public_xml_service.rb, spec/requests/metadata_spec.rb, spec/services/publish/public_xml_service_spec.rb
Fixes #4095 - publish sourceId (always) and barcode (for items only when available) to identityMetadata public XML
Updated test
=> add sourceid and barcode (for items if avaialble) to public XML identity metadata

app/models/admin_policy.rb, app/models/collection.rb, app/models/dro.rb, app/models/repository_record.rb, app/services/cocina_object_store.rb, spec/factories/dros.rb
The model can encapsulate the lock generation.
Test suite.
=> [refactor] Extract lock generation from the CocinaObjectStore

app/controllers/administrative_tags_controller.rb, app/models/repository_record.rb, app/services/cocina_object_store.rb, app/services/notifications/object_created.rb, app/services/notifications/object_updated.rb, spec/services/cocina_object_store_spec.rb, spec/services/notifications/object_created_spec.rb, spec/services/notifications/object_updated_spec.rb
Rather than an array which has the same data, but relies on the consumer knowing the order.
We don't have to remember what is in the array and in which order.
CI
=> [refactor] CocinaObjectStore#cocina_to_ar_save now returns an object with metadata

app/models/admin_policy.rb, app/models/collection.rb, app/models/dro.rb, app/models/repository_record.rb, spec/models/admin_policy_spec.rb, spec/models/collection_spec.rb, spec/models/dro_spec.rb
This tells you all at once the fields you omitted rather than having to wait for the NOT NULL constraint to be triggered one field at a time.
Test suite
=> Add activeRecord validation for repository objects

Dockerfile
=> Remove obsolete ENV vars from dockerfile

README.md, config/schedule.rb, lib/tasks/missing_druids.rake
This documents the missing_druid rake task in the README and adds a cron task to run at 8:35pm. I chose this time to avoid the every 15 minute run of google books download and deposit. 
=> Cron missing druid rake task and add to README

Gemfile, Gemfile.lock, README.md, Rakefile, app/jobs/create_event_job.rb, config/deploy.rb, config/initializers/sneakers.rb, config/settings.yml, lib/tasks/rabbitmq.rake, spec/jobs/create_event_job_spec.rb
refs https://github.com/sul-dlss/preservation_catalog/issues/1860
Resilience for Pres Cat's event reporting.
=> Adds async event creation consumer.

lib/tasks/missing_druids.rake
I noticed this output in the cron email for stage/qa:
```
Retrieved 32187 druids from SOLR
Retrieved 3 druids from DB
Missing 172 druids in SOLR
```
`Retrieved 3 druids from DB` is obviously not accurate, the actual number is the combination of Dro/Collection/AdminPolicy counts (the 3).
=> Fix the output of the missing druid rake task

app/models/collection.rb, app/models/dro.rb, app/services/cocina_object_store.rb
Scope returns all when nothing found, which in this case is undesired behavior.
QA
=> Switch to class method instead of scope for find_by_source_id.

app/models/repository_record.rb, config/locales/en.yml, spec/models/admin_policy_spec.rb, spec/models/collection_spec.rb, spec/models/dro_spec.rb
We no longer require a meaningful label to be set. Label is a legacy of Fedora
Fixes #4134
=> Allow label to be a blank string

app/reports/invalid_language_uris.rb, app/reports/invalid_location_uris.rb, app/reports/invalid_name_uris.rb
This excludes others like 'previous symphony'
=> Only return symphony catatalogRecordIds

bin/clean-druid-list, bin/generate-druid-list, config/application.rb, config/honeybadger.yml, config/initializers/activefedora_solr_updates.rb
We don't have ActiveFedora in the stack anymore.
=> Remove the vestiges of ActiveFedora

Gemfile, Gemfile.lock
https://github.com/honeybadger-io/honeybadger-ruby/issues/435 has been fixed in the `master` branch by https://github.com/honeybadger-io/honeybadger-ruby/pull/441 but a new gem version with the fix has yet to be cut (and we need to be able to deploy this project, which we can't since the commit `Gemfile.lock` points to is now missing from Github).
=> point honeybadger to master branch

.rubocop.yml, app/models/symphony_reader.rb
https://github.com/rubocop-hq/rubocop/issues/8508 was fixed in August 2020.
=> rubocop Style/CaseLikeIf enabled as bug was fixed

app/reports/unusual_language_source_uris.rb
Follow on to #4182 ... slashes were supposed to be optional at end of URL.  See https://github.com/sul-dlss/dor-services-app/issues/4179#issuecomment-1216900775
Ran report on production and verified it worked as expected
=> adjustment to report - slashes are optional at end of URL

app/reports/invalid_location_uris.rb
Report is dialing into unexpected name uris
Closes #4188
Report is at: https://gist.github.com/ndushay/442ddf6df15c89fde40e4cf2b4cefb8f
vz332dg7306 is a prod record Arcadia set up for testing, and it does appear on the report as expected.
=> report: invalid location uris tweaked per #4188

config/application.rb
This prevents some irrelevant deprecation warnings
Test suite
=> Use the rails 7.0 defaults

app/reports/invalid_name_uris.rb
Report is dialing into unexpected name uris, per #4185
Closes #4185
Report is at: https://gist.github.com/ndushay/442ddf6df15c89fde40e4cf2b4cefb8f
vz332dg7306 is a prod record Arcadia set up for testing, and it does appear on the report as expected.
=> report: invalid name uris tweaked per #4185

Gemfile, Gemfile.lock, openapi.yml
To use cocina-models that accommodate the DOI exceptions. And to be in sync.
=> update openapi.yml and gems for cocina-models 0.84.0 (DOI exceptions)

README.md
sul-dlss/cocina-models/pull/520 put information about running reports in the cocina-models README, but since the report code lives in this repo, it makes sense to say something about it in this README also.
screenshot:
=> README: add info about running reports

app/services/member_service.rb, app/services/publish/metadata_transfer_service.rb, spec/services/member_service_spec.rb, spec/services/publish/metadata_transfer_service_spec.rb
Fixes #4195
This commit changes the `Publish::MetadataTransferService` such that when a collection is (re-)published, its members are (re-)published. Not all members, though: only those members that are 1) already published, and 2) not in the `Opened` state. It does this work using the existing `MemberService` which is extended here to add a param excluding items in the `Opened` state.
CI. This needs testing in a deployed environment. Will work with Andrew on that.
=> [HOLD] Republish collection members when collection is (re-)published

app/services/create_object_service.rb, spec/services/create_object_service_spec.rb
Goes with H2 PR https://github.com/sul-dlss/happy-heron/pull/2718 which adds a DOI placeholder to the exported citation. 
Unit, deploying to QA, running integration test for h2 object creation. 
=> Replacing :doi: placeholder in h2 citations

app/reports/descendant_source_code_no_uri.rb
Related to #4238 
I also paired with Arcadia so she can, at a minimum, change the path expression for the different properties she's interested in, but possibly write some of her own reports in the future.   The tricky ones stump Mike and me, so she will likely reach out for help at times.
Ran report, checked the results, until it made sense.
=> exemplar report for source codes without uris for descendants of certain properties

Gemfile, Gemfile.lock, openapi.yml
Removing usused parallelContributor from cocina-models and thus this API;  using updated cocina-models gem with this change.
Part of https://github.com/sul-dlss/cocina-models/issues/532
=> update to cocina-models 0.85.0; update openapi.yml to remove parallelContributor

app/reports/property_existence_collections.rb, app/reports/property_existence_dros.rb
- for #4244, sul-dlss/cocina-models/issues/532 ...
- To create a general tool that can be used by devs or @arcadiafalcone for this purpose.
I ran reports for sul-dlss/cocina-models/issues/532 and for #4244 with this, and found some data with #4244 ...
=> add reports to detect existence of cocina property in dros and collections

app/reports/property_nesting_level_collections.rb, app/reports/property_nesting_level_dros.rb
Arcadia and I were interested in figuring out how deeply nested our descriptive data is.  Answer:  ugly.
Part of #4243
=> add reports for property nesting levels (dros and collections)

Gemfile, Gemfile.lock
preservation-client version 5.0 removes primary_moab_location, which is never used here, thus perfectly safe here.
=> preservation-client is now version 5.0.0

app/validators/cocina/file_hierarchy_validator.rb, app/validators/cocina/object_validator.rb, spec/validators/cocina/file_hierarchy_validator_spec.rb, spec/validators/cocina/object_validator_spec.rb
refs https://github.com/sul-dlss/dor-services-app/issues/4256
To only allow the use of file hierarchies for content types that are supported in access.
Unit
=> Validates that only file content type has file hierarchies.

README.md, config/schedule.rb, config/settings.yml
Fixes #4293
This commit uses honeybadger check-ins to ensure regularly scheduled cron jobs are running, like the approach already being used in prescat and H2.
CI
=> Add honeybadger check-ins to cron jobs

app/services/update_marc_record_service.rb, spec/services/update_marc_record_service_spec.rb
Fixes #4297 - do not add collection info to 856 if collection not released to searchworks
I don't believe we checked for this in the past (but perhaps it is an uncommon occurrence).  The code used to be in `app/models/dor/update_marc_record_service.rb` before it was moved sometime mid-2022, but digging back to spring 2022, the code looks basically the same as it does now.
~~[HOLD] until we know this answer to this question: do we skip if the collection has *no* release tags (also implies not released), or only skip if the collection explicitly has a "false" release tag (which is what the example druid in the ticket has, item: https://argo.stanford.edu/view/druid:mv522rq4275, associated collection: https://argo.stanford.edu/view/druid:gk894yk3598)~~  validated
Updated tests
=> don't add collection info to 856 when collection not released to searchworks

Gemfile.lock
To allow long-running preservation operations to complete without timing out.
Connects to sul-dlss/moab-versioning#266
CI and tested in stage.
=> Bump preservation-client to 5.1.1 to pick up higher timeout value

app/reports/file_counts.rb
I wanted to test sul-embed with an SDR object with lots of files so I wrote this report to find objects with lots of files. If my understanding of Cocina is correct it the JSONPath should select and count all the filenames out of the structural metadata.
If it's working, the SDR object with the most files is https://argo.stanford.edu/view/druid:rm242zg2446 
Ran it on `sdr-infra.stanford.edu` against Stage and Production databases. 
=> Added a file counts report

bin/validate-cocina
The option is called `sample`, not `sample_size`. Without this change, every run operates against the entire environment.
CI + ran `bin/validate-cocina`
=> Fix bug in validate-cocina with sample option

app/reports/catkeys_with_colons.rb
Connects to sul-dlss/cocina-models#561
DSA and cocina-models have a catkey regex that currently allows one or more digits separated by colons, but Arcadia reports that catkeys do not use colons. I ran this report in all three envs and confirmed that there are zero catkeys that contain any characters other than `0-9` digits.
CI + ran on sdr-infra against all envs
=> Add report for catkeys containing colons

Gemfile, Gemfile.lock
none of the pres client changes are to methods used by dor-services-app, based on a grep for pres client invocations
(this is just meant to allow automated dependency updates to keep pres client updated)
unit tests
=> bump preservation-client to 6.x

app/validators/cocina/object_validator.rb, config/settings.yml, spec/validators/cocina/object_validator_spec.rb
Part of #4363 
After identifying the objects that fail file hierarchy validation, we will need to temporarily disable it so those objects can be updated.  This adds a feature flag (which defaults to ON) with which we can disable when needed.
Updated test
=> add a feature flag to disable file hierarchy validation if needed

app/reports/invalid_cocina.rb
Connected to #4360  - create a report to look for non file type objects that have invalid file hierarchy cocina
On stage
=> add report to look for invalid file hierarchy cocina

app/services/reset_content_metadata_service.rb, spec/services/reset_content_metadata_service_spec.rb
Fixes sul-dlss/argo#3945
This commit changes the behavior of a service used in virtual object creation. It simplifies the code by assuming, and enforcing during virtual object creation, that a Cocina item may have no more than one member order. This change was cleared by @andrewjbtw.
CI & successfully integration-tested in QA
=> Change virtual object creation to assume a single member order

app/services/catalog/folio_reader.rb, app/services/catalog/marc_service.rb, app/services/catalog/symphony_reader.rb, app/services/create_object_service.rb, app/services/mods_service.rb, app/services/preserve/bag_verifier.rb, app/services/refresh_metadata_action.rb, app/services/reset_workspace_service.rb, app/validators/cocina/object_validator.rb, spec/services/refresh_metadata_action_spec.rb
Fixes #4399 
My reading of the code is that we are not actually raising `SymphonyReader` exceptions anywhere other than the `MarcService` where they are re-raised as `MarcService` exception.  There were a number of code comments where this was incorrect, so I changed those, and fixed a mocked test to reflect reality.  Not sure there are actual code changes needed.
CI
=> update comments to reflect actual errors raised

app/services/catalog/add_folio_catalog_links_service.rb, app/services/create_object_service.rb, app/services/update_object_service.rb, config/settings.yml, spec/services/catalog/add_folio_catalog_links_service_spec.rb, spec/services/create_object_service_spec.rb, spec/services/update_object_service_spec.rb
closes #4376
Allow Symphony and Folio catalog links to peacefully co-exist during the transition.
Unit
=> Adds feature for syncing catalog links.

app/services/migrators/folio.rb, spec/services/migrators/folio_spec.rb
closes #4376
Add folio catalog links to existing cocina data to support Folio.
Unit
=> Adds folio migrator.

bin/migrate-cocina
closes #4416
Avoid unexpected migration failures.
QA
=> Run ObjectValidator as part of dry run.

app/services/publish/public_xml_service.rb, spec/services/publish/public_xml_service_spec.rb
closes #4420
So that HRID is available to access systems.
Unit
=> Include folio instance HRID in public XML.

app/reports/file_sizes.rb
I thought it could be interesting to have a report that generated the file sizes for objects by querying the Cocina. In production it took 07:57 to generate the top ten:
```
$ bin/rails r -e production "FileSizes.report(10)"
```
```csv
druid,size_bytes
druid:tc646zc6154,5924462712275
druid:hn683db0520,3996542922303
druid:jw191jc5840,3958397136776
druid:yy759hp4897,3893031401640
druid:gx410cs0527,3695106416640
druid:pn552ht1089,3200147796304
druid:jf301dx7536,2934381031128
druid:kw792th2190,2931077798578
druid:dc086ym2763,2791747154683
druid:kf921gd3855,2571824274964
```
Running on sdr-infra.
⚡ ⚠ If this change has cross service impact, including data writes to shared file systems, ***run [integration tests](https://github.com/sul-dlss/infrastructure-integration-test)*** and/or test in …
=> File sizes report

app/services/catalog/marc_856_generator.rb, app/services/catalog/symphony_writer.rb, spec/services/catalog/marc856_generator_spec.rb, spec/services/catalog/symphony_writer_spec.rb
Reverts sul-dlss/dor-services-app#4423
Turning the Marc 856 into a hash created problems -- 
- the output contained "\" where previously there were none
- it's unclear if this change will have deleterious effects on records with previous symphony ckeys  (this is presumably to zero out 856s from incorrect ckeys)
- it may be that the Symphony code that reads the 856s has nuances beyond just adding 856s to a record.  Sometimes they are removed.  Sometimes they are updated.
We are backing this out for now;  we need to understand the goals better before we do this
=> Revert "Refactor 856 marc serialization into hash"

app/jobs/publish_job.rb, config/sidekiq.yml
refs #3972
Allow greater control over concurrency of publish job.
=> Separates publish into own queue.

app/services/catalog/marc_856_generator.rb, app/services/catalog/symphony_writer.rb, spec/services/catalog/marc856_generator_spec.rb, spec/services/catalog/symphony_writer_spec.rb
This refactors `marc856generator` to return an array of hashed data used to create stub 856 records and moves all symphony specific serialization into `SymphonyWriter` 
Example output with 2 previous catkey values:
```
[
{
catalog_record_id: '123',
druid: bare_druid
},
{
catalog_record_id: '456',
druid: bare_druid
},
{
catalog_record_id: '8832162',
druid: bare_druid,
indicators: '41',
subfields: [
{ code: 'u', value: "https://purl.stanford.edu/#{bare_druid}" },
{ code: 'x', value: 'SDR-PURL' },
{ code: 'x', value: 'item' },
{ code: 'x', value: "file:#{bare_druid}%2Fwt183gy6220_00_0001.jp2" },
{ code: 'x', value: "collection:#{collection_bare_druid}:8832162:Collection label & A Special character" },
{ code: 'x', value: 'rights:world' }
]
}
]
```
=> Refactor of marc856generator to serialize 856 string

config/initializers/folio_client.rb, spec/services/catalog/marc_comparison_service_spec.rb
see PR title (also similar change to client init in https://github.com/sul-dlss/hydra_etd/pull/1428/files)
unit
=> two small touchups: remove commented cruft, better HB notification on failure to configure Folio client

app/services/catalog/marc_856_generator.rb, app/services/catalog/symphony_writer.rb, app/services/catalog/update_marc_856_record_service.rb, spec/services/catalog/marc856_generator_spec.rb, spec/services/catalog/symphony_writer_spec.rb, spec/services/catalog/update_marc856_record_service_spec.rb
Allow Marc856Generator to be used by FolioWriter as well.
Unit
=> Move symphony specific logic from Marc856Generator to SymphonyWriter.

Gemfile.lock, app/services/publish/metadata_transfer_service.rb, spec/services/publish/metadata_transfer_service_spec.rb
This will help reduce load on the purl-fetcher server as we don't need to load xml from the filesystem
=> Send public cocina to PURL-fetcher

app/services/preserve/file_inventory_builder.rb, spec/fixtures/workspace/ab/123/cd/4567/ab123cd4567/metadata/.nfs123456, spec/services/preserve/file_inventory_builder_spec.rb
Fixes #4450 - ignore .nfs files from metadata directory when building bag for preservation ingest
This changed `FileInventoryBuilder` is used by the `PreservationIngestService` to prepare the bag for sending to preservation, so I believe this change will exclude the .nfs files.  See https://github.com/sul-dlss/dor-services-app/blob/main/app/services/preservation_ingest_service.rb#L20-L22
Added an example `.nfs` file to the existing fixtures used by the spec I changed, and then verified that the new tests which ensure it's not there fail before the code fix and pass after it.
=> ignore nfs files when building file list for preservation

app/services/release_tags.rb, spec/services/release_tags_spec.rb
Ruby idioms help you understand the intention
ci
=> Rename method to indicate it's boolean return value

app/services/release_tags.rb
This is easier to read. You don't need to decode the return values.
CI
=> Prefer casecmp? to casecmp().zero?

app/services/thumbnail_service.rb, spec/services/thumbnail_service_spec.rb
Fixes #4456
This bug, as far as I can tell, has been around since we cocinized the thumbnail service which prior to this commit returned the druid of the first member of a virtual object as its thumbnail link. Instead, pass this druid back to the thumbnail service to get the expected thumbnail link (the bare druid followed by the filename of the first jp2 of the first member).
=> Fix bug with generating thumbnail links for virtual objects

app/services/goobi_service.rb
This issue sul-dlss/common-accessioning#1043 discusses intermittent problems with the goobi service sending data during registration.  I can't think of a reason for this (particularly as the tags used to determine the workflow name we send to goobi are in local database and so there should be nothing like a race condition for when they are available).
I did notice that we memoize certain values in the goobi service, including the value that apparently sometimes gets set as the default incorrectly, for no apparent reason (they are used only once per instance).  I don't have a reason that this would explain the intermittency, but just putting this up for discussion/reaction.
Existing tests
=> no need to memoize results only used once

app/controllers/metadata_controller.rb, app/services/catalog/folio_writer.rb, app/services/catalog/marc_856_generator.rb, app/services/catalog/symphony_writer.rb, app/services/publish/metadata_transfer_service.rb, app/services/publish/public_cocina_service.rb, app/services/publish/public_xml_service.rb, app/services/release_tags.rb, spec/requests/metadata_spec.rb, spec/services/catalog/folio_writer_spec.rb, spec/services/catalog/marc856_generator_spec.rb, spec/services/catalog/symphony_writer_spec.rb, spec/services/publish/metadata_transfer_service_spec.rb, spec/services/publish/public_xml_service_spec.rb, spec/services/release_tags_spec.rb
The public cocina release tags will only contain the latest release tag for each project (same as the public XML)
=> Export release tags to the public cocina

app/reports/file_set_types.rb
Need to identify cocina-models with particular filetypes  (old ETD vocab -- 4 diff file types)
=> add file_set_type report

app/reports/virtual_object_constituents_with_catkeys.rb
closes #4446
Ran the report from `sdr-infra` VM, per [DSA instructions](https://github.com/sul-dlss/dor-services-app#running-reports) and [cocina-models instructions](https://github.com/sul-dlss/cocina-models#running-reports-in-dsa).
I ran the full report a couple times while testing, using rails console.  I also did a couple small test runs using rails runner.  And I just did one last full run using rails runner, and redirecting the output to a CSV file, per usage instructions in the new report class' top-level comment.  I'll attach that CSV output to #4446.
I didn't add unit tests, since we seem to let manual testing suffice for reports, but happy to revisit that if people want.
⚡ ⚠ If this change has cross service impact, including data writes to shared file systems, ***run …
=> add report for catkeys associated with virtual object constituent druids

app/jobs/publish_job.rb, app/services/publish/metadata_transfer_service.rb, spec/jobs/publish_job_spec.rb, spec/services/publish/metadata_transfer_service_spec.rb
fixes sul-dlss/argo#3972
I believe this should spawn a series of independent publish jobs for each member of a collection, setting them to the low priority queue, instead of trying to iterate and re-publish each collection member as part of the collection publishing.  This should allow the collection publish itself to complete quickly, while the collection members publish over time as the jobs complete.
~~HOLD - tested on stage and need to pass in the workflow param...fixing PR now~~
Updated the test
Tested on stage with a large collection and watched jobs spawn and re-publish happen
=> spawn jobs for released members

app/jobs/publish_job.rb, config/settings.yml, config/settings/development.yml, spec/requests/administrative_tags_spec.rb
* remove obsolete `fedora_url` from config
* remove obsolete references to fedora from test error messages in specs
* remove obsolete fedora reference from `PublishJob#perform` param description
unit tests
=> remove some fedora cruft

app/reports/descriptive_shape.rb
Generate a report of the shape of JSON in descriptive metadata. The shape is represented as a set of JSON paths which have either a string or number value, and the number of times they appear in the data:
```csv
path,count
.purl,4452
.title[].value,4321
.form[].type,2163
.form[].value,1810
.form[].source.value,1358
.note[].value,1319
.event[].date[].type,825
.event[].date[].encoding.code,629
.event[].date[].qualifier,2
.event[].date[].structuredValue[].type,18
.event[].date[].structuredValue[].value,18
```
The hope is that it might help in evaluating how we might want to further normalize and constrain descriptive metadata so that it is easier to edit.
Using sdr-infra.stanford.edu against QA (running now on Prod).
⚡ ⚠ If this change has cross service impact, including data writes to …
=> Add a report for descriptive metadata

config/deploy.rb
These are no longer in shared_configs.
=> Remove bogus linked_files entries from deploy config

app/jobs/publish_job.rb, app/services/publish/metadata_transfer_service.rb, spec/jobs/publish_job_spec.rb, spec/services/publish/metadata_transfer_service_spec.rb
Fixes #4511: when re-publishing all items as part of a collection publish (which can happen during collection release), we do *not* need to update a workflow step when done.  The fact that a publish occurs is already noted in the Event history, and attempting to update a workflow step can cause errors such as this: https://app.honeybadger.io/projects/50568/faults/58644364  This occurs when the publish occurs for items that were never released, as part of a collection release (which triggers all member items to be published as well).  Currently we try to notify the workflow service that the `release-publish` step is completed, which is both unnecessary (as the publish step was not triggered by a workflow in that object) and will cause problems if that particular item has never been through …
=> do not update publish step in workflow service when pubishing items in collection

app/services/publish/public_cocina_service.rb, spec/services/publish/public_cocina_service_spec.rb, spec/services/publish/public_xml_service_spec.rb
[HOLD] to verify collection publishing works as expected (test in stage) and isn't missing additional info neded
Fixes #4515 - collection publishing should use same logic for building administrative public XML as we do for items
Question: previously we were just returning the entire collection cocina, which is different than we do for items.   Unclear if this approach is removing public XML data for collections that should otherwise be published (though all current tests pass still).
Added unit tests
=> [HOLD] only add last releaseTag to a collection object in public XML

app/reports/descriptive_shape.rb
This commit includes options for generating stats for Cocina objects
that have links to the catalog, or don't have links to the catalog. This
is to try to help see how the metadata changes based on whether it was
derived from MARC or not.
This was accidentally not committed before because it was hacked on live
over on the sdr-infra server (sorry!)
The report was run on sdr-infra, I think? It was a while ago...
=> Add catalog limits

app/reports/descriptive_shape.rb
Because for these reports (to be used for visualizations), we don't want to count empty strings, empty arrays, or empty hashes.
Sample:
| Path  | count from  cocina-shape csv | count with this change | notes |
| ------------- | ------------- | ------------- | ------------- |
| .form[].type | 19134787  |  19149410 | bigger - more data now |
| .form[].value | 19154130  |  19169166 | bigger - more data now |
| .form[].source.code | 8047351  |  8040441 | smaller - showing the change here matters  |
| .form[].source.value | 6833221  |  6828312 | smaller |
| .note[].type | 5335050  |  5332403 | smaller |
| .note[].value | 13045378  |  13039404 | smaller |
| .note[].displayLabel | 4717437  |  4715473 | smaller |
| .note[].structuredValue[].value | 1801233  |  1797313 | smaller |
from:
``` …
```
=> descriptive_shape report: don't count empty values

config/initializers/okcomputer.rb, config/settings.yml
Sidekiq latency can grow large if a lot of content is accessioned all at once (as the queue will grow faster than it's being worked on for a while).  This is OK and we don't need to be alerted, so increase the failure level much higher (to 15 minutes).  Also put in config so we can adjust easily and per environment if needed.
=> increase sidekiq latency threshold and put in config

app/controllers/workspaces_controller.rb, app/jobs/reset_workspace_job.rb, spec/jobs/reset_workspace_job_spec.rb, spec/requests/reset_workspace_spec.rb
closes #1039
So avoid timeouts when service is slow to complete.
Unit, infra integration
=> Changes reset workspace to a job.

spec/services/catalog/folio_writer_spec.rb
Code supports sending to FOLIO records, but no spec
N/A
=> Add spec for release to multiple FOLIO records

app/services/goobi_service.rb, spec/services/goobi_service_spec.rb
Part of #4549 
When we switch to Folio, we will want to send folio_instance_hrids to the Goobi system instead of catkeys.  Thus the XML we construct needs to use our ILS feature flag to decide what to send.
Note that the name of the XML element we send to Goobi will continue to be "catkey", as changing this will require a code change on the Goobi end (which is out of our control and which the contractor would have to complete).
Two notes:
- The call that Goobi makes at the end of the process is not affected by the ILS change, as it is simply a call to start accessioning to the `/v1/objects/druid:DRUID_HERE/accession` endpoint of DSA.  There is no reference to catkey at all at this point. See https://github.com/sul-dlss/DevOpsDocs/blob/master/projects/goobi/operations-concerns.md for more …
=> send either catkey or folio_instance_hrid to goobi depending on what is active

app/controllers/objects_controller.rb, app/controllers/versions_controller.rb, app/controllers/workspaces_controller.rb, app/services/cocina_object_store.rb, app/services/constituent_service.rb, app/services/embargo_release_service.rb, app/services/version_service.rb, bin/migrate-cocina, spec/requests/authorization_spec.rb, spec/requests/reset_workspace_spec.rb, spec/requests/start_accession_spec.rb, spec/requests/versions_spec.rb, spec/services/cocina_object_store_spec.rb, spec/services/constituent_service_spec.rb, spec/services/embargo_release_service_spec.rb, spec/services/version_service_spec.rb
Avoid instantiating a cocina object when it isn't needed to increase performance.
Unit, Integration
=> Stop using cocina object when only version and druid needed

app/controllers/objects_controller.rb, app/jobs/update_marc_job.rb, app/services/catalog/folio_writer.rb, config/settings.yml, config/settings/test.yml, spec/jobs/update_marc_job_spec.rb, spec/requests/update_marc_record_spec.rb, spec/services/catalog/folio_writer_spec.rb
Resolves #4454 to update FOLIO marc record 856 fields in the releaseWF, without concurrent updates. Will require deploying along with puppet and shared_configs PRs. 
Do not merge until coordinated with related shared_configs, common_accessioning, puppet PR reviews.
Tested in QA with 100 druids released to same FOLIO record.
=> Make update_marc_record a job

config/application.rb
Avoid future committee configuration problems.
Before:
```
bundle exec rspec spec/requests/authorization_spec.rb
[DEPRECATION] Committee: please set parameter_overwite_by_rails_rule = false because we'll change default value to "true" in next major version.
[DEPRECATION] Committee: please set parameter_overwite_by_rails_rule = false because we'll change default value to "true" in next major version.
```
After:
```
bundle exec rspec spec/requests/authorization_spec.rb
```
=> Add committee configuration to remove warnings.

config/initializers/okcomputer.rb, spec/requests/status_spec.rb
Fixes #4570 - replace symphony with folio check
For discussion with team, re: do we want external checks like this or are separate nagios alerts sufficient?  
See https://stanfordlib.slack.com/archives/C09M7P91R/p1692899929140329
=> replace symphony check with folio check, if feature flag enabled

app/validators/cocina/apo_existence_validator.rb, lib/tasks/seed.rake
Provide an approach to allow seeding APOs / Admin Policies for QA/stage reset.
QA
=> Add rake tasks to support seeding.

app/services/constituent_service.rb, spec/services/constituent_service_spec.rb
=> No longer update marc 856 from ConstituentService.

app/reports/catalog_links_previous_folio_only.rb
To help understand the scope of the problem found in #4586 -- which objects have a previous folio ID but not a current folio ID.  Finds all objects with previous folio ID and lists the current ones too so you can find any that are blank.
Ran on sdr-infra
=> Add new report for reporting on previous folio ID

Gemfile.lock
To allow dor_indexing_app to use stanford-mods, a small, backwards compatible change was made to cocina-models in PR sul-dlss/cocina-models/pull/625
CI
I will run integration tests after all the cocina-models downstream updates are done
=> update to cocina-models 0.91.2

app/services/preservation_ingest_service.rb, spec/services/preservation_ingest_service_spec.rb
refs #4594
More understandable code.
Unit, integration test
=> Refactor and annotate PreservationIngestService.

spec/jobs/publish_job_spec.rb, spec/jobs/shelve_job_spec.rb
closes #4366
Dark is validated by cocina models, so no need to do so in shelve or publish jobs. That makes these tests unnecessary.
=> Remove skipped tests that are no longer applicable.

app/services/digital_stacks_service.rb
closes https://github.com/sul-dlss/common-accessioning/issues/1107
Renaming while shelving was failing because the rename process was comparing a size that was an integer against a size that was a string. See logging below:
```
I, [2023-10-04T06:09:00.274160 #686972]  INFO -- : [ActiveJob] [ShelveJob] [eb580e54-d70e-4fc9-a828-789ec32eb828] RENAME - Renaming 2 files in /stacks/mp/491/pr/4725
I, [2023-10-04T06:09:00.274555 #686972]  INFO -- : [ActiveJob] [ShelveJob] [eb580e54-d70e-4fc9-a828-789ec32eb828] RENAME - Renaming /stacks/mp/491/pr/4725/image.jpg to /stacks/mp/491/pr/4725/85a32f398e228e8228ad84422941110597e0d87a
I, [2023-10-04T06:09:00.286342 #686972]  INFO -- : [ActiveJob] [ShelveJob] [eb580e54-d70e-4fc9-a828-789ec32eb828] RENAME - /stacks/mp/491/pr/4725/image.jpg exists? true
I, …
```
=> Correctly rename file when shelving.

bin/validate-cocina
To allow catching MODS transformation errors.
=> Add MODS transformation validation to bin/validate-cocina

app/reports/property_multiple_events.rb
Closes #4618 
Ran in qa and verified the results match the selection criteria:
```
purl,title,collection name,APO
https://sul-purl-stage.stanford.edu/fc661cd6790,SUL Logo for Fenugreek Leaf Curry Leaves,"Fenugreek Leaf Curry Leaves",druid:zx485kb6348
https://sul-purl-stage.stanford.edu/gw372yy8196,SUL Logo for Arrowroot Curry Leaves,"Arrowroot Curry Leaves",druid:zx485kb6348
https://sul-purl-stage.stanford.edu/tv885tb9774,SUL Logo for Mint Cashews,"Mint Cashews",druid:zx485kb6348
https://sul-purl-stage.stanford.edu/ft059yx6058,SUL Logo for Tandoori Mix Coconut Water,"Tandoori Mix Coconut Water",druid:zx485kb6348
https://sul-purl-stage.stanford.edu/wx441ty6154,SUL Logo for Cayenne Pepper Peppercorns,"Cayenne Pepper Peppercorns",druid:zx485kb6348
```
⚡ ⚠ If this change has cross service …
=> Add report for objects with multiple events but no folio hrid

Gemfile.lock
This helps when lograge has to deal with deprecations, which is currently causing HB exceptions due to a changed Rails API.
Fewer HB exceptions that aren't meaningful is a good thing.
CI
=> Bump lograge to 0.14.0

app/reports/property_events_with_display_label.rb
Closes #4619 
Ran against production using [the cocina-models instrucitons](https://github.com/sul-dlss/cocina-models#running-reports-in-dsa) and verified the data through a cursory spot check that that showed the cocina data matches the selection criteria of at least one event WITH a displayLabel and does not include a folio HRID.
There are 563554 records in production matching this case.
Example data:
```
https://purl.stanford.edu/kk202jh4049,Interview with Stefania Moroianu,In Transit: An Oral History Project about Crossing Borders,druid:yf767bj4831
https://purl.stanford.edu/fp590fv0002,Interview with Megha Parwani,In Transit: An Oral History Project about Crossing Borders,druid:yf767bj4831
https://purl.stanford.edu/kp438vz9202,Interview with Anita Too,In Transit: An Oral History …
```
=> Add report for events with displayLabel but no folio HRID

app/services/cleanup_service.rb, config/settings.yml, lib/tasks/cleanup.rake, spec/services/cleanup_service_spec.rb
Follow on from #4598 incorporating suggestions from John.
1. Moves the backup_path to settings to make it easily configurable and then stop passing it around as much
2. Add some additional output spacing
Updates specs
=> move backup_path to settings

config/initializers/okcomputer.rb
So that don't throw an error when Folio is down.
QA, stage
=> Handle error for Folio OKComputer check.

Gemfile, Gemfile.lock
Consistency with other apps and for rails, minor is too major for a dependency update.
=> Pin rails to minor.

app/controllers/workspaces_controller.rb, app/jobs/reset_workspace_job.rb, openapi.yml, spec/jobs/reset_workspace_job_spec.rb, spec/requests/reset_workspace_spec.rb
closes #4634
The reset_workspace step processing is done here in DSA by a job class, so that job class should updated the workflow status to "completed" ... since it is doing the work!
Unit, stage
=> Mark workflow step completed after actually performing reset workspace.

Gemfile, Gemfile.lock, openapi.yml, spec/requests/create_object_spec.rb, spec/requests/update_metadata_spec.rb
connects to sul-dlss/cocina-models#637 and sul-dlss/cocina-models#640
unit tests
will run integration tests on QA or stage once all the SDR apps have been updated (i.e. DSA updated to latest cocina-models in this PR, sdr-api updated to latest cocina-models in [related PR](https://github.com/sul-dlss/sdr-api/pull/628), and access-update-scripts `cocina_level2_prs.rb` has been run)
=> bump cocina-models version to get new field for file types, update openapi.yml and tests accordingly

config/application.rb
set `strict_reference_validation` to `true` on `RequestValidation` and `ResponseValidation` to silence deprecation warning
CI
=> explicitly enable upcoming committee default

app/services/cocina/to_xml/content_metadata_generator.rb, spec/services/cocina/to_xml/content_metadata_generator_spec.rb
Fixes #4641 
Note that `languageTag` is already available in the public JSON, see: https://sul-purl-stage.stanford.edu/wm783fb6812.json
=> Add language to the public xml content-metadata section

Gemfile, Gemfile.lock, openapi.yml
better validation for langauge tags, nilable language tags and use fields, stricter description validation
https://github.com/sul-dlss/cocina-models/releases/tag/v0.93.0
unit tests
will run integration tests on QA or stage once all the SDR apps have been updated (i.e. DSA updated to latest cocina-models in this PR, sdr-api updated to latest cocina-models in [related PR](https://github.com/sul-dlss/sdr-api/pull/630), and access-update-scripts `cocina_level2_prs.rb` has been run)
=> bump cocina-models version to get latest model validation changes, update openapi.yml accordingly

app/reports/empty_mediatypes.rb
Generate a CSV of items and their files that lack media types.
Fixes #4651
=> Emtpy media types report

app/reports/video_date_types.rb
Report to find videos and their collections where the video is world-downloadable at the object and file level, and has a date of type "publication". That date type is used to populate the "uploadDate" field in schema.org markup. 
Report run on stage and prod DSA.
Prod report with 153 videos: [VideoDateTypesAccessFileProd.csv](https://github.com/sul-dlss/dor-services-app/files/13640764/VideoDateTypesAccessFileProd.csv)
=> Report on videos valid for schema-org markup

app/reports/video_no_date_type.rb
Report to see whether there are videos that get their schema.org `uploadDate` from the first `event.date.value` or `event.date.structuredValue.value` with `event.type` null and `event.date.type` null.
(There aren't any. But if you look at all fileset resource types, not just video, there are 37 objects with this kind of metadata.)
Run on sdr-infra
=> Report on videos with dates with no type

config/initializers/folio_client.rb, config/settings.yml
Allows us to use different versions of FOLIO auth until we're upgraded to Poppy in late March. 
Deployed to QA and integration tests.
=> Add folio_client legacy_auth setting

config/settings.yml
more accurate comments save lives
=> settings: improved comment for rolling indexer pause_time_between_dodcs

openapi.yml
Part of https://github.com/sul-dlss/pre-assembly/issues/1397 and https://github.com/sul-dlss/pre-assembly/issues/1403 --- to start GIS Objects accessioning, we need to start `gisAssemblyWF` with the API call to DSA, and this is currently not possible as it violates this constraint.
Will deploy to stage
=> allow accessioning start call to start gisAssemblyWF

Gemfile.lock
To get new title indexing in dor_indexing gem 1.2.0, which uses new methods in cocina-models 0.94.2 - used in rolling (re)indexer.
CI is enough - we're just indexing a few new title fields.
=> use dor_indexing v1.2.0 and cocina-models 0.94.2

README.md
The rolling indexer runs on DSA now, so the info about it goes in this README.   (See sul-dlss/dor_indexing_app/pull/1098)
=> README: add rolling_index info

Gemfile, bin/rolling_index, config/settings.yml
To instrument a way to speed up (or slow down) the rolling_indexer at will.   This will help us shepherd indexing changes through quickly, or to slow down the rolling_indexer due to heavy DSA usage by some other project.
Fixes #4687
I ran it on qa with parallel value of 2 and of 1.
=> Parallelize rolling index

Gemfile, Gemfile.lock
Based on the comment, I suspect we could have stopped pinning this gem when we stopped using the dor-services gem.
I'm also hopeful this will resolve the HB errors with the rolling indexer
specs, integration tests in stage.
=> stop pinning stanford-mods

Gemfile.lock
Update dor_indexing_gem to v1.4.0 to start indexing to new replacement fields (see https://github.com/sul-dlss/dor_indexing/releases/tag/v1.4.0)
deployed to stage and ran integration tests.
=> bump dor_indexing gem to v1.4.0

solr_conf/conf/solrconfig.xml
Part of https://github.com/sul-dlss/dor_indexing_app/issues/1031
Makes solrconfig.xml aligned with sul-solr-configs (see sul-dlss/sul-solr-configs/pull/311) and argo sul-dlss/argo/pull/4328 
deployed changes in sul-dlss/argo/pull/4328 to qa and did searches for druids with and without prefixes.
=> solrconfig.xml: replace objectId_tesim with druid_prefixed_ssi and druid_bare_ssi

bin/validate-cocina
Get more info to help metadata remediators. 
Ran on prod with a cocina-models branch that would produce validation errors and fill a report. 
Sample rows from report:
```
druid,type,collection,message
druid:bc675gs0465,Dro,"","Multiple value, groupedValue, structuredValue, and parallelValue in description: note1, note2, note3"
druid:dq023sp1654,Dro,druid:qp986cj5218,"Multiple value, groupedValue, structuredValue, and parallelValue in description: event1.date1"
druid:dq375wm0695,Dro,"","Multiple value, groupedValue, structuredValue, and parallelValue in description: note1, note2, note3"
druid:fs229nd6736,Dro,druid:qp986cj5218,"Multiple value, groupedValue, structuredValue, and parallelValue in description: event1.date1"
```
=> Add collection to validate-cocina CSV

bin/validate-cocina
Collections don't have structural, so only grab the collection for DROs.
Ran `bin/validate-cocina` with invalid collections and the script doesn't blow up anymore. Also confirmed the collection is being captured for DROs.
=> bugfix bin/validate-cocina

app/models/administrative_tag.rb, app/models/tag_label.rb, spec/models/tag_label_spec.rb
Fixes sul-dlss/argo#4327
The regular expression used in the DSA codebase and at the API layer (as expressed in `openapi.yml`) allows the user to enter both leading and trailing whitespace for administrative tags, and we don't want this whitespace persisted. The solution in this commit adds normalization at the DB model layer, removing the bad whitespace.
I opted for this solution over a validation-based solution (tightening the various regular expressions) because that may make remediation of currently persisted bad data harder.
We could consider a follow-up step that tweaks the regexes, but also, that's arguably of limited value once this commit is merged and bad data is remediated. Why? More work than it's worth, because we'd likely want to couple that change with user messaging to give …
=> Normalize administrative tag labels to remove leading/trailing whitespace

solr_conf/conf/solrconfig.xml
~~hold for testing;  also hold for #4692~~  Andrew signed off.
part of sul-dlss/argo/issues/4329
This is desired for better Argo search results ... which now default to ordered by relevancy, not druid!
Naomi vetted it;  Naomi and Andrew vetted it together, too.
=> solrconfig.xml: boost primary author matches over other contributors in search results

app/services/catalog/folio_writer.rb, spec/services/catalog/folio_writer_spec.rb
Resolves #4706 to match MARC record 856 PURLs with `http://` or `https://` before deleting/updating.
Unit, deployed to stage (although we don't have integration tests to update a FOLIO record 856 as far as I can tell).
=> Ignore protocol when matching 856 PURL

app/controllers/metadata_refresh_controller.rb, spec/requests/metadata_refresh_spec.rb
refs https://github.com/sul-dlss/argo/issues/4326
So that a more informative message can be provided to Argo users.
Unit
=> Handle cocina validation errors when refreshing metadata from API.

app/services/delete_service.rb, spec/services/delete_service_spec.rb
closes #4740
Cleanup, similar to other active record models.
Unit
=> Delete ReleaseTag model objects when deleting an item.

app/reports/audit_release_tag_migration.rb
Usage: `bin/rails r -e production "AuditReleaseTagMigration.report"`
Fixes #4739
=> Create an audit script for checking the release tags migration

app/models/release_tag.rb, app/services/release_tags.rb, spec/services/release_tags_spec.rb
closes #4738
To phase in use of ReleaseTag model objects as release tags are migrated to the db.
Unit
=> Queries ReleaseTag model objects from ReleaseTags service.

app/jobs/shelve_job.rb
```
DEPRECATION WARNING: Calling `ActiveRecord::Base.clear_active_connections! is deprecated. Please call the method directly on the connection handler; for example: `ActiveRecord::Base.connection_handler.clear_active_connections!`. (called from perform at /Users/jcoyne85/workspace/sul-dlss/dor-services-app/app/jobs/shelve_job.rb:19)
```
=> Avoid deprecation warning with clear_active_connections

Gemfile, Gemfile.lock, bin/rolling_index
To avoid using DSC from within DSA. An alternative to https://github.com/sul-dlss/dor-services-app/pull/4752 that depends on https://github.com/sul-dlss/dor_indexing/pull/48
CI
=> Use lightweight, AR-backed repository callables for indexing

.gitignore, Gemfile, Gemfile.lock, openapi.yml, spec/services/publish/public_xml_service_spec.rb
related:
* update dor_indexing gem
* fix tests to provide value for previously optional release tag field
* require 'csv' in a file that uses `CSV.parse` (`registration_csv_converter_spec.rb` started failing without this change)
opportunistic touchup: add `.byebug_history` to `.gitignore`.
goes with https://github.com/sul-dlss/cocina-models/pull/697
=> require ReleaseTag "what" attribute as part of cocina-models upgrade

app/controllers/release_tags_controller.rb, app/services/catalog/folio_writer.rb, app/services/catalog/marc_856_generator.rb, app/services/publish/public_cocina_service.rb, app/services/release_tag_service.rb, bin/rolling_index, spec/services/catalog/folio_writer_spec.rb, spec/services/catalog/marc856_generator_spec.rb, spec/services/release_tag_service_spec.rb
closes #4763
Developer joy. Or at least less Developer confusion.
=> Renames ReleaseTags service to ReleaseTagService.

app/services/cocina_object_store.rb, app/services/create_object_service.rb, spec/services/cocina_object_store_spec.rb
closes #4772
So that direct use of active record is encapsulated.
Unit
=> Encapsulate checking that AdminPolicy exists behind CocinaObjectStore.

app/controllers/release_tags_controller.rb, openapi.yml, spec/requests/release_tags_spec.rb
closes #4767
API hygiene.
Unit
=> Return a 422 if release tags are being requested for an APO

.rubocop.yml
Fixing errors that showed up when I run rubocop locally
=> Fix wrong namespace errors when running rubocop

app/models/repository_object.rb
We don't want to have RepositoryObjects that have no versions.
=> Open a version in the transaction that creates the RepositoryObject

spec/services/cocina_object_store_spec.rb
This test was passing all the time as it wasn't actually testing anything.
=> Fix test to call #exist correctly with the database id

app/services/cocina_object_store.rb, spec/factories/repository_object_versions.rb, spec/services/cocina_object_store_spec.rb
=> Destroy the RepositoryObject when calling CocinaObjectStore#destroy

app/services/version_service.rb
So retrieve_version_from_preservation can be disabled so that that can_open? can be called from an Argo integration test.
=> Apply feature flag to retrieve_version_from_preservation

app/reports/export_cocina_from_druid_list.rb
fixes #4782 (in combo with the requested report output, see [comment with output location](https://github.com/sul-dlss/dor-services-app/issues/4782#issuecomment-2043841313))
manually running the report for ticket, as well as running it over a small test file that had a mix of good findable druids, blank lines, and invalid druids.  also some local testing using `FactoryBot` created `Dro`s when i was re-working the implementation.
examples from dev laptop testing:
```
% bin/rails r "ExportCocinaFromDruidList.report(druid_list_filename: 'test_druids.txt')" | gzip > test_druids.cocina.`date -Iseconds`.jsonl.gz
% zless test_druids.cocina.2024-04-05T00:45:41-07:00.jsonl.gz
{"cocinaVersion":"0.96.0","type":"https://cocina.sul.stanford.edu/models/book","externalIdentifier":"druid:zv000sf0000","lab …
```
=> [Report] cocina json for druid list

app/controllers/objects_controller.rb, openapi.yml, spec/requests/start_accession_spec.rb
closes #4830
This existing endpoint was doing crazy versioning. It should be just be opening a version if needed.
Unit, integration test.
=> Update accessioning endpoint for correctly versioning.

bin/migrate-cocina
Fixes #4778
This moves the logic that opens a version to happen prior to running the migration, allowing for:
1.) If this is a dry_run we check if the object is openable but don't actually open a version
2.) If the object is already open, we do not close it
We don't have unit testing for `bin/` perhaps there is a dry_run test that can be run manually?
=> Update migrator versioning logic to happen before migration

app/services/release_tag_service.rb, spec/requests/release_tags_spec.rb, spec/services/publish/metadata_transfer_service_spec.rb, spec/services/publish/public_xml_service_spec.rb, spec/services/release_tag_service_spec.rb
closes #4757
Release tags are now modeled in database.
Unit
=> Removes reading and writing of release tags to cocina.

app/services/version_service.rb, app/services/workflow_state_service.rb, spec/services/version_service_spec.rb, spec/services/workflow_state_service_spec.rb
closes #4842
Any assembly workflow should prevent closing since an assembly workflow might change the cocina / files.
Unit
=> Change assembling check in VersionService.

spec/services/publish/public_cocina_service_spec.rb, spec/services/publish/public_xml_service_spec.rb
PublicXmlService should just transform the public cocina to XML.  It does not handle stripping out unpublished files or duplicate release tags.
=> Disentangle tests for PublicXmlService from PublicCocinaService

spec/services/publish/public_cocina_service_spec.rb
we were missing tests for published files and for a collection.
=> Add tests for full coverage of PublicCocinaService

app/services/update_object_service.rb, spec/requests/update_metadata_spec.rb, spec/services/update_object_service_spec.rb
=> Notify honeybadger when an update is issued on a non-opened object

app/services/update_object_service.rb, app/services/version_service.rb, spec/services/update_object_service_spec.rb, spec/services/version_service_spec.rb
Follows #4854
- Update opened version not head version of repository object
- Fix build in `main`
CI
=> Update opened version not head version of repository object

app/services/repository_object_migrator.rb, spec/factories/object_versions.rb, spec/factories/repository_object_versions.rb, spec/services/repository_object_migrator_spec.rb
Fixes #4817
This commit adds a new `RepositoryObjectMigrator` service that takes a single druid/external ID---for a DRO or collection or admin policy---as input and creates a repository object instance and one or more repository object version instances. It does all of its work in a transaction and migrates all relevant information from the `ObjectVersion` table and the `Dro|Collection|AdminPolicy` table.
=> Add a migration service creating repository objects & versions

app/services/workflow_state_service.rb, spec/services/workflow_state_service_spec.rb
This commit is a set of small refactoring around the workflow state service, including:
* Place the `||` operator at the end of the line so we don't need to rely on commented-out newlines
* Streamline the logic & comments for determining if *only* the exceptional step is running in a WF
* Use predicate matchers in spec
CI
=> Refactor WorkflowStateService#active_workflow_except_step?

app/services/update_object_service.rb, app/services/version_service.rb, bin/migrate-cocina, spec/services/update_object_service_spec.rb, spec/services/version_service_spec.rb
* VersionService.open calls the UpdateObjectService as part of the opening operation. However, at that time the item is not yet opened.
* Migrator script uses UpdateObjectService in cases in which it is migrating without versioning.
=> Support skipping open check in UpdateObjectService.

app/models/repository_object_version.rb, spec/models/repository_object_version_spec.rb
closes #4767
So that RepositoryObjectVersions for APOs can be deserialized to cocina models.
Unit
=> Persist content type for admin policies.

app/services/create_object_service.rb, spec/services/create_object_service_spec.rb
So that RepositoryObjects are only created in environments where so configured.
Unit
=> Add feature flag when creating RepositoryObjects.

Gemfile, Gemfile.lock, config/application.rb
Graphqli needs sprockets or propshaft. There is no sass dependency
=> Remove unnecessary sass dependency

app/services/cleanup_service.rb, spec/services/cleanup_service_spec.rb
The current checks were inaccurate. In discussion with @andrewjbtw we determined that since he would be the only one running this service and it will be revamped in forthcoming discard draft work it was easiest to just remove the checks.
Unit
=> Removes checks from cleanup service.

app/services/indexer.rb, bin/rolling_index, spec/services/indexer_spec.rb
I goofed and mistakingly thought that DorIndexing.build submitted to solr, whereas it just builds the solr doc.
Unit, stage
=> Add solr docs to solr.

app/services/migrators/remove_release_tags.rb, spec/services/migrators/remove_release_tags_spec.rb
This makes the `verify` stage of migration give us more interesting results
CI
=> Make RemoveReleaseTags migrator a little smarter

app/services/create_object_service.rb, app/services/ur_admin_policy_factory.rb, spec/requests/create_collection_spec.rb, spec/requests/create_object_spec.rb, spec/services/cocina_object_store_spec.rb, spec/services/create_object_service_spec.rb, spec/services/ur_admin_policy_factory_spec.rb
So that DIA can be sunset.
Unit, integration test
=> Index locally on object create.

bin/migrate-cocina, bin/migrate-repository-model, bin/validate-cocina
This commit slightly tweaks the progress bar style when running the test-files script.
See sul-dlss/sdr-deploy#260
CI
=> Tweak the progress bar style

app/services/publish/metadata_transfer_service.rb, spec/services/publish/metadata_transfer_service_spec.rb
Purl no longer uses a standalone mods file. It gets the data from the mods within public xml.
See https://github.com/sul-dlss/purl/pull/936
=> Stop transfering mods to purl on publish

app/services/digital_stacks_service.rb, spec/services/digital_stacks_service_spec.rb
So that DigitalStacksService actually deletes files from stacks.
Unit
=> Fix deleting files from stacks.

app/jobs/publish_job.rb, spec/jobs/publish_job_spec.rb
closes #4908
For some reason I can't determine the releaseWF was initiated for some AdminPolicies in stage. Should this happen again this handles the problem more gracefully.
Unit
=> Handle an attempt to publish an AdminPolicy.

app/reports/contributor_identifiers.rb, app/reports/descendant_source_code_no_uri.rb, app/reports/descriptive_shape.rb, app/reports/events_multiple_date_types.rb, app/reports/file_counts.rb
Fixes #4913 
I ran each report on stage without error
=> Update reports to use RepositoryObject (1)

Gemfile.lock, README.md, docker-compose.yml
Update container definitions for a future use case that could make use of them (e.g. integration testing of indexing). This would be an alternative approach to https://github.com/sul-dlss/dor-services-app/pull/4934 which removes all container definitions except for the db. 
However, I'm not sure how to test that the container configurations are correct. They come up, but I'm not sure beyond that. 
All containers come up locally.
=> Updated docker compose

app/models/repository_object_version.rb
When we destroy a RepositoryObjectVersion we also want all of it's UserVersions to be destroyed at the same time.
Fixes #4939 
=> Destroy UserVersions before destroying RepositoryObjectVersion

app/models/repository_object_version.rb, app/models/user_version.rb, spec/models/repository_object_version_spec.rb, spec/models/user_version_spec.rb
Update the validation to check `closed_at` on the RepositoryObjectVersion instead of the status of the parent RepositoryObject.
=> Update UserVersion validation to check closed_at datetime

app/services/publish/public_cocina_service.rb, app/services/publish/public_xml_service.rb, spec/services/publish/metadata_transfer_service_spec.rb, spec/services/publish/public_cocina_service_spec.rb, spec/services/publish/public_xml_service_spec.rb
This will allow us to power the access systems, which rely on the label, from cocina.  Since the public xml is derived from the public cocina, this is no longer needed in the PublicXmlService
=> Move label building from PublicXmlService to PublicCocinaService

app/services/member_service.rb, config/settings/test.yml, spec/services/catalog/folio_writer_spec.rb, spec/services/cleanup_service_spec.rb, spec/services/member_service_spec.rb
Developer happiness and efficiency: while working on #4956, I found flaky tests, noisy tests, and some slow ones. I decided to try improving all of these. This commit includes those changes.
=> Make tests less flaky, less noisy, and faster

Gemfile, Gemfile.lock, app/services/publish/metadata_transfer_service.rb, config/initializers/purl_fetcher_client.rb, spec/services/publish/metadata_transfer_service_spec.rb
closes #4958
Cleaner / easier integration with purl fetcher.
Unit, integration test.
=> Adds purl fetcher client.

app/services/shelving_service.rb, config/settings.yml, spec/services/shelving_service_spec.rb
closes #4930
To allow testing the mechanics of the upload process.
Unit, stage.
=> Transfer files to purl fetcher.

app/models/repository_object.rb, app/services/cocina_object_store.rb, app/services/create_object_service.rb, app/services/update_object_service.rb, app/services/ur_admin_policy_factory.rb, spec/factories/repository_object_versions.rb, spec/factories/repository_objects.rb, spec/requests/create_object_spec.rb, spec/requests/find_object_spec.rb, spec/requests/show_object_spec.rb, spec/requests/update_doi_metadata_spec.rb, spec/requests/update_metadata_spec.rb, spec/requests/update_orcid_work_spec.rb, spec/requests/versions_inventory_spec.rb, spec/services/cocina_object_store_spec.rb, spec/services/create_object_service_spec.rb, spec/services/thumbnail_service_spec.rb, spec/services/update_object_service_spec.rb
refs #4940 
Continue migration to RepositoryObjects.
=> Clean up RepositoryObject conditional code in CocinaObjectStore

app/controllers/release_tags_controller.rb, openapi.yml, spec/requests/release_tags_spec.rb
This will allow the release_publish robot to tell purl-fetcher what the public release tags are.
=> Allow the release_tags API to show the public tags

app/services/cocina/to_xml/content_metadata_generator.rb, spec/fixtures/hj097bm8879_publicObject.xml, spec/services/cocina/to_xml/content_metadata_generator_spec.rb
Nothing uses this data, so we can simplify and have less code
=> Stop producing relationship nodes within contentMetadata

app/services/publish/public_desc_metadata_service.rb, app/services/publish/public_xml_service.rb, app/services/published_relationships_filter.rb, spec/services/publish/dublin_core_service_spec.rb, spec/services/publish/public_desc_metadata_service_spec.rb, spec/services/published_relationships_filter_spec.rb
This reduces the number of times we have to run the query against the database
=> Decouple virtual object lookup from public xml construction

app/services/update_object_service.rb, spec/services/update_object_service_spec.rb
Update will not succeed when not open, so catch early.
Unit
=> Changes UpdateObjectService to raise when not open.

app/services/version_service.rb, spec/services/version_service_spec.rb
Fixes param mismatch and test description of user_version param in VersionService.close
=> Fix default from symbol to string in Version.close for user_version

app/services/version_service.rb
We allow opening_user_name to be nil when opening a new version, but it is possible to get an HB exception if you leave it off when calling the accession method from DSA cient, as shown below.  This should fix the problem by allowing it to be nil via this pathway too.  Error below, triggers this HB alert: https://app.honeybadger.io/projects/50568/faults/107835795   Adding the opening_user_name let's it work:
```
object_client = Dor::Services::Client.object('druid:zb460rp4078')
object_client.accession.start(description: 'do it!', context: {'runOCR' => true})
/Users/petucket/Sites/development/dor-services-client/lib/dor/services/client/versioned_service.rb:45:in `raise_exception_based_on_response!': Internal Server Error: 500 (Response from dor-services-app did not contain a body. …
```
=> opening_user_name can be nil

app/reports/audit_technical_metadata_file_list.rb, config/settings.yml
to run the audit described in https://github.com/sul-dlss/technical-metadata-service/issues/515 (will close that issue once the report has actually been run)
on QA.  once the related puppet changes were applied and the supporting shared_configs updated, i `scp`ed the report code over.  then tested, fixed, refactored for usability, tested, fixed, repeated, until this felt like it'd be likely to run through on prod (or produce helpful logging if it didn't).
i did one full run on QA with this code (448 druids with techMD inconsistencies were found), and also ran both the test report and the single druid method.
example test report stdout (same stdout as full report would be, just limited to 20 druids audited):
```
$ bin/rails r -e p 'AuditTechnicalMetadataFileList.test_report' …
```
=> add report for auditing contents of technical metadata database

app/reports/audit_technical_metadata_file_list.rb
noticed a bug that testing didn't exercise, because techMD QA didn't return any unexpected HTTP response codes when testing.
ran the test report to make sure the happy path didn't blow up (no unexpected responses, so still no exercise of the unexpected response logger code):
```
$ bin/rails r -e p 'AuditTechnicalMetadataFileList.test_report'
druid:bk509qs2277: found technical-metadata-service database; inconsistencies with v11 cocina: {"missing_filenames"=>["asawa.jp2", "maps-africa.jp2", "moore.jp2", "hay.jp2"]}
druid:ww089jm4506: not found in technical-metadata-service database
druid:wy216td0310: found technical-metadata-service database; inconsistencies with v1 cocina: {"missing_filenames"=>["example.jp2"]}
druid:xb970cg0663: found technical-metadata-service database; inconsistencies …
```
=> AuditTechnicalMetadataFileList.process_response needs logger as a param

app/controllers/objects_controller.rb, spec/requests/start_accession_spec.rb
Part of sul-dlss/dor-services-client#427 -- allows us to send workflow context to the workflow service via json in the body of the `accession` request.  The workflow client and workflow server are already setup to receive it and store it.
New specs and QA
=> allow the start accession DSA endpoint to accept workflow context

app/controllers/user_versions_controller.rb, config/routes.rb, openapi.yml, spec/requests/user_versions_inventory_spec.rb, spec/requests/versions_inventory_spec.rb
closes #4993
So that user versions can be displayed in argo.
Unit
=> Adds user version index endpoint.

app/models/repository_object_version.rb, app/services/embargo_release_service.rb, spec/factories/dros.rb, spec/factories/repository_object_versions.rb, spec/services/embargo_release_service_spec.rb
closes #4997
Dro is deprecated.
Unit
=> Change EmbargoReleaseService to use RepositoryObject.

app/models/repository_object.rb, app/services/ur_admin_policy_factory.rb, spec/services/ur_admin_policy_factory_spec.rb
refs #5014
AdminPolicy is deprecated.
=> Refactor UrAdminPolicyFactory to stop creating AdminPolicy.

spec/factories/repository_object_versions.rb, spec/requests/collections_for_object_spec.rb
refs #5014
Dros are deprecated.
=> Changes collections_for_object_spec to use RepositoryObject models.

spec/services/publish/public_desc_metadata_service_spec.rb
refs #5014
Dros are deprecated.
=> Changes PublicDescMetadataServiceSpec to use RepositoryObjects.

spec/requests/graphql_spec.rb
refs #5014
Dros are deprecated.
=> Update graphql_spec to use RepositoryObjects.

app/models/repository_object.rb, spec/services/notifications/object_created_spec.rb
refs #5014
Dros are deprecated.
=> Update object_created_spec to use RepositoryObjects.

app/models/repository_object.rb, app/reports/audit_technical_metadata_file_list.rb
closes #4996
Dro is deprecated.
QA
=> Refactors AuditTechnicalMetadataFileList to use RepositoryObjects.

app/graphql/types/query_type.rb
Dro / Collection / AdminPolicy are deprecated.
=> Do not query legacy models in graphql endpoint.

Gemfile, Gemfile.lock, app/reports/invalid_w3cdtf_dates.rb
We should not have two standards for validating dates.
=> Use cocina-models W3CDTF validator

app/services/version_service.rb, spec/services/version_service_spec.rb
closes #5034
ObjectVersions are going to be removed, but still want to make version check with pres.
Unit
=> Raise when version mismatch with Preservation.

app/controllers/workspaces_controller.rb, app/services/workspace_service.rb, spec/requests/workspaces_spec.rb, spec/services/workspace_service_spec.rb
ocrWF will be making a call to create the relevant `/dor/workspace` druid tree directory. It will not need the source path and symlink, it just wants to the workspace folder.   So this:
- removes the HB alert since we this will be the first consumer to not be sending in the source
- allows DSA to return the directory location created, so it can be used by the caller
- allows client to request metadata and/or content subdirectories also be created (but only if no source is passed in, since if source is passed in, the subdirectories should already exist at the source, and the created directory is actually just a symlink there)
There is a corresponding [dor-services-client PR](https://github.com/sul-dlss/dor-services-client/pull/436) to grab the location and return to the consumer.
Updated …
=> allow the workspace call to return the location created

app/reports/audit_technical_metadata_file_list.rb
* since technical-metadata-service's database only tracks preserved files, filter non-preserved files from the list we send to techMD service for auditing
* remove a straggler usage of `Dro`, since we've gotten rid of that model (follow on from https://github.com/sul-dlss/dor-services-app/pull/5013)
* comment updates for both of the above changes
part of https://github.com/sul-dlss/technical-metadata-service/issues/515
* re-ran the full report on QA.  got 142 results instead of the 369 returned before this change.
* ran the techMD rake task `techmd:generate_for_moab` for a druid in the new result list, and saw it get remediated (job got queued and executed in techMD service, audit detected no error when re-run after that).
* confirmed that non-preserved file names were no longer fed to …
=> AuditTechnicalMetadataFileList: only consider preserved files, touchups for recent data model changes

app/services/member_service.rb, app/services/publish/metadata_transfer_service.rb, app/services/virtual_object_service.rb, app/services/workflow_state_service.rb, spec/services/publish/metadata_transfer_service_spec.rb, spec/services/virtual_object_service_spec.rb
So that when purl-fetcher builds the public xml for the constituents, the constituents get the relationship to the virtual object.
Unit, integration test
=> Republish constituents after virtual object.

app/services/version_service.rb, spec/services/version_service_spec.rb
closes #5047
The versioningWF now only has one step and that step is completed, so no need to close.
Unit, stage integration
=> Stop asking workflow service to close version.

app/services/publish/metadata_transfer_service.rb, spec/services/publish/metadata_transfer_service_spec.rb
Collections don't have files to be shelved.
Unit
=> Do not shelve files for collection.

Dockerfile, docker-compose.yml
Update to a debian based docker image in order to support recent version(s) of openapi_parser and use a base closer to our deployed environments.
=> Update docker base image to debian base

db/migrate/20220422143440_require_object_versions.rb, db/migrate/20220509120943_change_object_version_description.rb, spec/rails_helper.rb
ObjectVersion no longer exists.
=> Get connection from ActiveRecord::Base instead of ObjectVersion.

bin/validate-cocina
Fixes #5065 by switching from the removed `Dro`, `Collection`, and `AdminPolicy` models to `RepositoryObject`
Ran this branch on sdr-infra against stage
=> Update validate-cocina to use RepositoryObject

docker-compose.yml
I didn't see this comment (https://github.com/sul-dlss/dor-services-app/pull/5056#discussion_r1621550558) since it was after the PR was merged. This is just a quick update to pick up that suggestion.
=> Set SECRET_KEY_BASE=1 in docker compose as it's essentially unused

app/services/migrators/remove_release_tags.rb, bin/migrate-cocina, spec/services/migrators/remove_release_tags_spec.rb
Restores the remove release tags migrator so that we can officially remove them from cocina-models.
Ran the migration in stage and then validated the cocina against the https://github.com/sul-dlss/cocina-models/pull/721 branch of cocina-models
=> Restore the remove release tags migratator but for repository objects

app/models/repository_object.rb, bin/migrate-cocina
Add a commit method to migrate-cocina so that we can save changes to `RepositoryObjects`, `RepositoryObjectVersions`, etc in the migration for use cases where we do not want to use the `UpdateVersionService` as that will not always work for prior versions.
This also adds `autosave: true` to the `RepositoryObjectVersion` association in `RepositoryObject` so that we do not require individual saves for versions.
Beyond existing unit tests, I tested this by running on stage.
=> Add a commit mode to migrate-cocina

app/services/workflow_state_service.rb, spec/services/workflow_state_service_spec.rb
Part of https://github.com/sul-dlss/argo/issues/4470
We need the ability to know if an object is in the middle of a text extraction WF (e.g. ocrWF) so we can disable various things (like editing or starting a new ocrWF in Argo).
Updated specs
=> consider ocrWF as part of assembling

app/services/digital_stacks_differ.rb
This updates the `DigitalStacksDiffer` to only use the stuctural metadata from purl when comparing only structural with the current cocina_object.
=> Only instantiate structural metadata when comparing structural

Gemfile, Gemfile.lock
```
warning: /usr/local/rvm/rubies/ruby-3.3.1/lib/ruby/3.3.0/csv.rb was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.4.0. Add csv to your Gemfile or gemspec.
```
=> Add csv to gemfile.

app/reports/apo_catalog_record_id.rb, app/services/registration_csv_converter.rb
This dependency is moving out of stdlib in Ruby 3.4 so it must be managed by bundler.
CI
=> Add csv dependency to bundler

app/jobs/update_doi_metadata_job.rb, spec/jobs/update_doi_metadata_job_spec.rb
This commit gives us more breadcrumbs in Honeybadger in situations like https://app.honeybadger.io/projects/50568/faults/106916123
CI
=> Include helpful diagnostic information in UpdateDoiMetadataJob

app/services/cocina/to_datacite/form.rb, spec/services/cocina/to_datacite/attributes_spec.rb
This avoids including the option `resourceType` in the datacite package if it is nil.
=> Set resourceType to an empty string for Datacite if it's nil

app/jobs/shelve_job.rb, app/services/legacy_shelvable_files_stager.rb, app/services/publish/metadata_transfer_service.rb, app/services/shelvable_files_stager.rb, app/services/shelving_service.rb, spec/jobs/shelve_job_spec.rb, spec/services/legacy_shelvable_files_stager_spec.rb, spec/services/publish/metadata_transfer_service_spec.rb, spec/services/shelvable_files_stager_spec.rb, spec/services/shelving_service_spec.rb
closes #5082
Maintain functionality of legacy shelving.
Unit, stage
=> Shelve files from preservation when using publish/shelve API.

Gemfile, Gemfile.lock, app/services/digital_stacks_differ.rb, spec/services/digital_stacks_differ_spec.rb
closes #5108
To make DSA less tightly bound to purl cocina.
Unit, integration tests.
=> Switch DigitalStacksDiffer to use purl-fetcher file digest endpoint.

app/models/repository_object_version.rb, spec/models/repository_object_version_spec.rb
* This was the behavior with the previous model objects.
* It makes it clearer what was the last cocina version that the data is known to be valid with.
Unit
=> Update stored cocina version to latest when saving.

Gemfile.lock, app/services/publish/metadata_transfer_service.rb, spec/services/publish/metadata_transfer_service_spec.rb
closes #5114
This happens and shouldn't raise an error.
Unit
=> Ignore when item is already unpublished.

app/controllers/user_versions_controller.rb, config/routes.rb, openapi.yml, spec/requests/show_user_version_solr_spec.rb
refs https://github.com/sul-dlss/argo/issues/4515
So that solr can render the details page for a user version, as it is tightly bound to a solr doc. Generating a solr doc on the fly avoids having to repeat logic in Argo.
Unit
=> Adds endpoint for getting solr doc for a user version.

config/initializers/okcomputer.rb, config/settings.yml, spec/requests/status_spec.rb, spec/services/goobi_service_spec.rb
We no longer bother to check this flag, so remove it.
=> Remove obsolete feature flag read_folio

app/validators/cocina/object_validator.rb, config/settings.yml, spec/validators/cocina/object_validator_spec.rb
=> Remove obsolete feature flag file_hierarchy_validation

app/services/publish/metadata_transfer_service.rb, config/settings.yml, spec/services/publish/metadata_transfer_service_spec.rb
closes #5122
HTTP file transfer was encountering timeouts.
Unit
=> Copies files to be shelved to staging area.

app/jobs/shelve_job.rb, app/services/delete_service.rb, app/services/publish/metadata_transfer_service.rb, app/services/shelving_service.rb, config/settings.yml, spec/jobs/shelve_job_spec.rb, spec/services/cleanup_service_spec.rb, spec/services/delete_service_spec.rb, spec/services/publish/metadata_transfer_service_spec.rb, spec/services/shelving_service_spec.rb
We've switching to new publish-shelve API.
Unit
=> Remove legacy publish shelve and all usage of stacks and purl mounts.

app/models/repository_object.rb, app/models/user_version.rb, app/services/user_version_service.rb, openapi.yml, spec/models/user_version_spec.rb, spec/requests/create_user_version_spec.rb, spec/requests/update_user_version_spec.rb, spec/requests/user_versions_inventory_spec.rb, spec/services/user_version_service_spec.rb
closes #5136
To support withdrawing from argo.
Unit
=> Adds additional to user version log. Adds validation so that cannot withdraw head.

app/controllers/versions_controller.rb, app/services/version_service.rb, openapi.yml, spec/services/version_service_spec.rb
closes #5140
So that users can modify objects with user versions (i.e., created in H2) from Argo. Otherwise, the user version doesn't move to the latest object version.
Unit, stage
=> Support new user version mode for update if exists.

app/reports/preservation_versions.rb
I forgot to hit save in vscode.
Prod
=> Fix preservation versions report to use the last closed version instead of head.

app/services/version_service.rb
It was easy for the documentation to get out of sync and wasn't adding value being duped in the same file.
=> Remove redundant documentation in version_service.rb

app/controllers/versions_controller.rb, config/routes.rb, openapi.yml, spec/requests/show_object_version_spec.rb
closes #5147
So that Argo can display object versions.
Unit
=> Adds show endpoint for object versions.

app/controllers/versions_controller.rb, openapi.yml, spec/requests/versions_inventory_spec.rb
closes #5149
Argo needs this info to determine whether a version detail page can be rendered.
Unit
=> Add whether version has cocina to version inventory endpoint.

app/models/repository_object.rb, app/services/cleanup_service.rb, spec/models/repository_object_spec.rb, spec/services/cleanup_service_spec.rb
closes #5152
To help with cleanup.
Unit
=> In clean up service, re-open head version.

app/controllers/versions_controller.rb, config/routes.rb, openapi.yml, spec/requests/show_user_version_spec.rb, spec/requests/show_version_solr_spec.rb
refs https://github.com/sul-dlss/argo/issues/4521
Argo needs it to display object versions.
Unit
=> Add endpoint for object version solr.

app/jobs/withdraw_restore_job.rb, app/models/user_version.rb, app/services/user_version_service.rb, app/services/version_service.rb, db/migrate/20240807210223_change_user_version_state.rb, db/structure.sql, spec/factories/repository_object_versions.rb, spec/factories/user_versions.rb, spec/jobs/withdraw_restore_job_spec.rb, spec/models/user_version_spec.rb, spec/requests/create_user_version_spec.rb, spec/requests/update_user_version_spec.rb, spec/services/migrators/remove_release_tags_spec.rb, spec/services/user_version_service_spec.rb, spec/services/version_service_spec.rb
closes #5158
So that user can correctly withdraw / restore user versions.
Unit
=> Support permanently withdrawing user versions.

app/services/indexer.rb, config/settings.yml, spec/services/indexer_spec.rb
So that DSA can be used for a local docker integration test without needing solr.
Unit
=> Adds enabled flag for solr.

app/models/repository_object.rb, app/services/version_service.rb, lib/tasks/dor_services_app.rake, spec/models/repository_object_spec.rb, spec/services/version_service_spec.rb
Support fixing earlier versions by making new versions.
Andrew
=> Adds rake tasks for creating new object versions and moving user versions.

app/controllers/workspaces_controller.rb, app/jobs/cleanup_job.rb, spec/jobs/cleanup_job_spec.rb, spec/requests/cleanup_workspace_spec.rb
Part of https://github.com/sul-dlss/common-accessioning/issues/1387
DisseminationWF is gone (see #1385), so remove it's reference.  We also don't need to bother even asking for the workflow anymore for this endpoint since it's always going to be accessionWF.  
This changes needs to be coordinated with https://github.com/sul-dlss/common-accessioning/pull/1386 and https://github.com/sul-dlss/dor-services-client/pull/475
HOLD for #1385
Process:
1. Merge https://github.com/sul-dlss/dor-services-client/pull/475 and then cut a new release
2. Update https://github.com/sul-dlss/common-accessioning/pull/1386 to use new dor-services-client release, merge it
3. Merge https://github.com/sul-dlss/dor-services-app/pull/5186
4. Deploy all
Spec
=> remove workflow param from cleanup

Gemfile, Gemfile.lock, app/services/shelvable_files_stager.rb, spec/services/shelvable_files_stager_spec.rb
closes #5193
So that errors are correctly handled when getting files from preservation so that garbage is not shelved.
Unit
=> Changes strategy when staging files from preservation for shelving.

app/controllers/versions_controller.rb, app/jobs/cleanup_version_job.rb, app/models/repository_object.rb, app/services/version_service.rb, config/routes.rb, openapi.yml, spec/jobs/cleanup_job_spec.rb, spec/jobs/cleanup_version_job_spec.rb, spec/requests/versions_spec.rb, spec/services/version_service_spec.rb
closes #5194
This functionality is needed for H3.
Unit
=> Support discarding open object versions.

compose.yaml
The `Settings.workflow.url` change broke the connection between DSA and the workflow server in containerland and this should fix it.
N/A
=> Update env var in containerland to match config change

.circleci/config.yml, Gemfile, Gemfile.lock, README.md, app/controllers/objects_controller.rb, app/jobs/publish_job.rb, app/jobs/robots/dor_repo/accession/publish.rb, app/jobs/robots/robot.rb, app/services/publish/metadata_transfer_service.rb, config/initializers/sidekiq.rb, config/settings.yml, openapi.yml, spec/jobs/publish_job_spec.rb, spec/jobs/robots/dor_repo/accession/publish_spec.rb, spec/rails_helper.rb, spec/requests/publish_object_spec.rb, spec/services/publish/metadata_transfer_service_spec.rb
refs #5197
Simplification. See ticket.
Unit, QA.
=> Adds publish robot.

.circleci/config.yml, Dockerfile
Dockerfile needs contribsys key in order to build. This is because of the recent addition of Sidekiq Pro.
=> Configure docker image to have contribsys key for sidekiq pro.

app/jobs/robots/dor_repo/accession/sdr_ingest_transfer.rb, app/services/preservation_ingest_service.rb, spec/services/preservation_ingest_service_spec.rb
This is an existing race condition that was previously handled by job retries; this makes the robot perform retries for same.
Unit, stage
=> Retry preservation transfer when version mismatch.

config/settings.yml
Doh.  The backup folder for objects where we are stopping accessioning is not correctly configured.  This fixes it.
```
dor_services@dor-services-app-prod-a:/dor$ ls -al
total 7414784
drwxr-xr-x  11 dor_services dor_services       4096 Oct 22 08:37  .
drwxr-xr-x  28 root         root               4096 Jul 23 10:43  ..
drwxrwsr-x 140 dor_services dor_services      32768 Nov 20 15:43  assembly
drwxr-xr-x  20 dor_services dor_services   27148288 Nov 20 15:55  export
drwxrwxr-x   2 dor_services dor_services      16384 Sep 17  2013  import
drwxrwxr-x  57 dor_services dor_services       8192 Oct 23 10:28  preassembly
-rw-------   1 root         root         7562592256 Sep 15  2021  production.log
drwxr-xr-x   4 root         root               4096 Oct 17  2013  sdr1transfer
drwxrwxr-x  65 …
```
=> typo in settings

app/controllers/versions_controller.rb, config/routes.rb, openapi.yml, spec/requests/versions_spec.rb
closes #5243
To allow H3 dashboard to get version statuses more efficiently.
Unit, stage
=> Adds endpoint for getting version statuses in batch.

Gemfile.lock
To get commonmarker out of the dependencies, making the Ruby 3.4 upgrade process smoother.
CI
=> Bump cocina-models to 0.99.3

app/services/embargo_release_service.rb
This avoids creating a cron email when the job is running that just says:
> I, [2025-01-09T02:16:03.789343 #1189047]  INFO -- : Found 87 objects
This email is just noise.
=> Switch logging to debug

app/jobs/reindex_job.rb, app/services/indexer.rb, app/services/indexing/builders/document_builder.rb, app/services/indexing/indexers/basic_indexer.rb, bin/rolling_index, spec/jobs/reindex_job_spec.rb, spec/services/indexer_spec.rb, spec/services/indexing/builders/document_builder_spec.rb, spec/services/indexing/indexers/basic_indexer_spec.rb
refs #5231
To allow better debugging of indexing.
Stage, unit
=> Adds tracing id to troubleshoot indexing.

.rubocop_todo.yml, app/services/catalog/folio_writer.rb, spec/services/catalog/folio_writer_spec.rb
Errors from the QuickMARC API were previously being eaten. This gives us more actionable exceptions and alerts.
If there's a QuickMARC error, don't bother retrying subsequent Folio API interactions. Instead, log a *single* HB alert with a useful title and sufficient context for a developer to figure out what is going on.
CI, tested with a prod object
=> Add more context to HB when editing via QuickMARC

README.md
image link needs to be https to work
markdown preview:
before:
after:
=> [README] fix OpenAPI validator badge image

Dockerfile, compose.yaml
For some reason, the Sidekiq Pro env variable was no longer being automagically injected. No idea why or what changed. This takes a more explicit approach.
Successfully ran `docker compose build`
=> Fix docker compose build

app/services/version_service.rb
Open version endpoint has been returning stale locks.
Stage
=> Make sure current lock is returned when opening version.

config/honeybadger.yml
To normalize HB config for DSA so environment specific `honeybadger.yml` files aren't necessary.
=> Adds common HB config.

app/services/cocina/to_datacite/creator_contributor_funder.rb, spec/services/cocina/to_datacite/attributes_spec.rb
closes #5285
H3 is now sending organizations that have a main organization and a suborganization/department. These need to be mapped to Datacite.
Unit
=> Map organizations that are structured values to Datacite contributors.

Gemfile, Gemfile.lock
We need to pin the mais-orcid-client so that the changes in the new API do not go into effect until we do the new gem release and update the codebase.
=> pin mais-orcid-client

Gemfile, Gemfile.lock
To keep in sync with latest cocina-models patch release and client update. 
=> Bump cocina-models to 0.101.1

app/services/user_version_service.rb, app/services/version_service.rb, spec/services/user_version_service_spec.rb, spec/services/version_service_spec.rb
closes #5313
Accessioning and moving versions was causing concurrent publishing, which was causing PurlFetcher locking errors.
Unit
=> Avoid duplicate publishing.

app/services/catalog/folio_writer.rb, spec/services/catalog/folio_writer_spec.rb
Let the interesting exception bubble up to Honeybadger instead of eating it.
=> Make FOLIO update honeybadger context more interesting

app/services/indexer.rb, config/settings.yml, lib/tasks/missing_druids.rake
Parallelizes reindexing rake task and makes indexing logic configurable.
So that SDR can recover faster from Solr indexing issues.
=> Faster missing druids

app/reports/druids_refresh_false.rb
Since we're no longer using the CSV module to create this report, we need to handle commas and newlines in cocina metadata. 
Ran on sdr-infra.
=> Avoid line breaks and handle commas in columns

app/reports/digital_serials_unreleased.rb
Fixes #5329
This commit makes three changes to the named report:
1. Format all fields as valid CSV, favoring the built-in `#to_csv` method over manually inserting quotes and the like;
2. Preserve the order of the part name and number within the title
3. **ONLY** look at the first title for each object
CI, and I ran it successfully in all envs
=> Revise the unreleased digital serials report

app/controllers/metadata_refresh_controller.rb, app/controllers/objects_controller.rb, app/services/apply_admin_policy_defaults.rb, app/services/constituent_service.rb, app/services/create_object_service.rb, app/services/embargo_release_service.rb, app/services/update_object_service.rb, bin/migrate-cocina, openapi.yml, spec/requests/metadata_refresh_spec.rb, spec/requests/update_metadata_spec.rb, spec/services/apply_admin_policy_defaults_spec.rb, spec/services/create_object_service_spec.rb, spec/services/embargo_release_service_spec.rb, spec/services/update_object_service_spec.rb
Follow on from https://github.com/sul-dlss/dor-services-app/pull/5364
Fixes https://github.com/sul-dlss/hungry-hungry-hippo/issues/1411
Ref https://github.com/sul-dlss/hungry-hungry-hippo/issues/1411 and https://github.com/sul-dlss/hungry-hungry-hippo/issues/1371
Goes with https://github.com/sul-dlss/dor-services-client/pull/527 and https://github.com/sul-dlss/dor-services-client/pull/528
- switches from using event data as a general hash and instead uses specific params
- updates the open api to reflect this
- adds the ability to send the who param when registering objects and pass this into the event
- refactor the `UpdateObjectService.update` method to use cocina object has a param for consistency
CI and deploying to QA
=> Switch how we pass event data from dsa-client to be specific list instea of json

app/services/indexing/builders/orcid_builder.rb
closes #5376
The use of citation status note is deprecated.
Apparently this was untested, as removing it didn't break anything. Sigh.
=> Index all orcids.

app/services/update_object_service.rb, spec/factories/repository_object_versions.rb, spec/requests/update_metadata_spec.rb
Fixes #5373 - record an event during an object update when it is moved from one collection to another
Specs
=> Send collection change event when moved

app/services/workflow_service.rb, spec/services/workflow_service_spec.rb
The existing approach was wrong and did not take into account nils.
=> Correctly invoke workflow client method for getting a workflow.

spec/requests/start_accession_spec.rb
Same as https://github.com/sul-dlss/dor-services-client/pull/557 for DSA
Just verifying that languages come through as an array (for OCR work in the workflow context).  The expectation below the change should verify it comes back out again as a hash.
Part of the investigation of https://github.com/sul-dlss/common-accessioning/issues/1495
=> make spec more complete

app/services/next_step_service.rb, app/services/rabbit_factory.rb, app/services/workflow_creator.rb, app/services/workflow_process_service.rb, config/initializers/bunny_connection_after_fork.rb, lib/tasks/workflow.rake, spec/services/next_step_service_spec.rb, spec/services/workflow_process_service_spec.rb
closes #5432 
Andrew uses this rake task. Same logic for publishing / indexing was in 3 places.
Unit, QA.
=> Adds workflow rake task. Refactors rabbit publishing and indexing when updating next step.

app/jobs/robots/robot.rb, spec/jobs/robots/dor_repo/accession/sdr_ingest_transfer_spec.rb, spec/jobs/robots/robot_spec.rb
The default for a robot is to invoke workflow operations via DSC. For robots running within DSA, workflow operations can be invoked directly.
Unit
=> Uses local workflow services in DSA robots.

config/settings.yml, config/settings/test.yml
So that docker images are built using local workflow. This will allow removing the workflow server images from Argo, etc.
=> Enable local_wf by default.

app/jobs/reindex_job.rb, config/honeybadger.yml
closes #5487
We were getting too many alerts.
=> Change strategy for HB alerting for reindexing deadlocks.

app/services/catalog/folio_reader.rb, spec/services/catalog/folio_reader_spec.rb
According to Folio documentation, literal dollar signs in values causes problems in e.g. quickMARC where they are misinterpreted as subfield delimiters, and should be replaced with `{dollar}`. However, when Folio exports these values back out, they remain escaped. Patch the Folio reader in DSA to handle the one known problematic case of this: abstract text, in this case from the ETD application.
=> Replace escaped dollar sign with literal dollar sign in abstracts

app/services/indexing/indexers/workflow_indexer.rb, app/services/indexing/indexers/workflow_process_indexer.rb, app/services/indexing/indexers/workflows_indexer.rb, app/services/workflow/batch_service.rb, app/services/workflow/process_response.rb, app/services/workflow/service.rb, app/services/workflow/workflow_response.rb, spec/factories/workflow_steps.rb, spec/jobs/batch_reindex_job_spec.rb, spec/services/workflow/batch_service_spec.rb, spec/services/workflow/service_spec.rb, spec/services/workflow/workflow_response_spec.rb
refs #5515
Our successors will not know what XML is.
Unit
=> Drop use of XML for workflows for internal operations.

app/controllers/release_tags_controller.rb, app/services/catalog/folio_writer.rb, app/services/catalog/marc_856_generator.rb, app/services/indexing/indexers/releasable_indexer.rb, app/services/public_metadata_release_tag_service.rb, app/services/publish/metadata_transfer_service.rb, app/services/release_tag_service.rb, spec/services/catalog/folio_writer_spec.rb, spec/services/catalog/marc856_generator_spec.rb, spec/services/indexing/indexers/releasable_indexer_spec.rb, spec/services/public_metadata_release_tag_service_spec.rb, spec/services/publish/metadata_transfer_service_spec.rb, spec/services/release_tag_service_spec.rb
Having these together as a single service required all operations to provide a cocina object. However, it was only really needed for some. This is because it was mixing multiple responsibilities. This splits them out.
=> Separate release tag service from public metadata release tag service.

app/jobs/batch_reindex_job.rb, app/services/indexing/builders/document_builder.rb, app/services/indexing/indexers/releasable_indexer.rb, spec/jobs/batch_reindex_job_spec.rb, spec/services/indexing/builders/document_builder_spec.rb, spec/services/indexing/indexers/releasable_indexer_spec.rb
refs #5518
closes https://github.com/sul-dlss/argo/issues/4653
* Caching parent collections was causing collection titles not to be updated when they were changed.
* Faster re-indexing.
=> Stop caching parent collections. Fetch parent collections and parent collection tags in batch.

app/services/indexing/builders/document_builder.rb, app/services/indexing/indexers/releasable_indexer.rb, app/services/indexing/indexers/workflows_indexer.rb, app/services/indexing/workflow_fields.rb, spec/services/indexing/builders/document_builder_spec.rb, spec/services/indexing/indexers/releasable_indexer_spec.rb, spec/services/indexing/indexers/workflows_indexer_spec.rb, spec/services/indexing/workflow_fields_spec.rb
* Make DocumentBuilder responsible for any lookups, since values can also be passed into DocumentBuilder.
* DocumentBuilder tests were not useful and incomplete.
=> Extract fetching out of the indexers. Improve DocumentBuilder tests.
