- .rubocop.yml
- bin/reports/report-desc-abstract_displayLabels
- bin/reports/report-desc-abstract_types
- lib/unique_report.rb
refs #2741
Requested by Arcadia.
Local
NA
> Adds reports for abstracts.

- .rubocop_todo.yml
- README.md
- app/controllers/metadata_controller.rb
- app/services/publish/public_xml_service.rb
- config/routes.rb
- openapi.yml
- spec/requests/metadata_spec.rb
Connects to sul-dlss/infrastructure-integration-test#241
CI
none
> Add an endpoint for displaying the public XML

- spec/services/cocina/mapping/descriptive/mods/abstract_spec.rb
> Fix typo in abstract spec

- spec/services/cocina/mapping/descriptive/mods/type_of_resource_spec.rb
Closes #2773
CircleCI
n/a
Implementation ticket #2775
> Add mapping for other authority for typeOfResource

- lib/fedora_cache.rb
To support more roundtrip testing.
NA
NA
> Cache additional datastreams.

- app/services/cocina/object_updater.rb
- spec/requests/update_metadata_spec.rb
> Map collection catkey to fedora

- app/services/cocina/object_updater.rb
- bin/generate-cache
- bin/validate-cocina-roundtrip
- lib/fedora_cache.rb
- lib/fedora_loader.rb
refs #2786
Make validation faster.
sdr-deploy
NA
> Performance improvements for validate-cocina-roundtrip.

- app/services/cocina/from_fedora/dro_structural.rb
- app/services/cocina/from_fedora/viewing_direction_helper.rb
- app/services/cocina/normalizers/content_metadata_normalizer.rb
- bin/validate-cocina-roundtrip
- spec/services/cocina/normalizers/content_metadata_normalizer_spec.rb
Better roundtrip validation.
Unit, local
NA
> Normalizes reading order.

- app/services/cocina/to_fedora/content_metadata_generator.rb
- bin/validate-cocina-roundtrip
- spec/services/cocina/to_fedora/content_metadata_generator_spec.rb
closes #2800
It's a mapping error.
Unit, local
NA
> Stop adding empty label nodes.

- .rubocop.yml
- app/models/dor/update_marc_record_service.rb
- app/services/cocina/from_fedora/descriptive/access.rb
- app/services/cocina/from_fedora/descriptive/event.rb
- app/services/cocina/from_fedora/descriptive/form.rb
- app/services/cocina/from_fedora/descriptive/name_builder.rb
- app/services/cocina/from_fedora/descriptive/notes.rb
- app/services/cocina/from_fedora/descriptive/part_builder.rb
- app/services/cocina/from_fedora/descriptive/related_resource.rb
- app/services/cocina/from_fedora/descriptive/subject.rb
- app/services/cocina/from_fedora/descriptive/titles.rb
- app/services/cocina/to_fedora/descriptive/related_resource.rb
- app/services/metadata_service.rb
- app/services/mods_equivalent_service.rb
filter_map has better performance and is recommended by rubocop
> Use filter_map rather than map.compact

- app/services/publish/public_desc_metadata_service.rb
So we understand why this method needs to exist.
> Add method documentation

- app/jobs/shelve_job.rb
- app/services/shelvable_files_stager.rb
- app/services/shelving_service.rb
- spec/jobs/shelve_job_spec.rb
- spec/services/shelvable_files_stager_spec.rb
- spec/services/shelving_service_spec.rb
ref https://github.com/sul-dlss/common-accessioning/issues/754
> Shelve files from preservation

- app/services/cocina/to_fedora/identity.rb
- spec/services/cocina/mapping/identification/apo_identity_spec.rb
- spec/services/cocina/mapping/identification/collection_identity_spec.rb
- spec/services/cocina/mapping/identification/dro_identity_spec.rb
The release tag `when` attribute was not being correctly formatted.
Unit
NA
> Correctly format release tag when attribute.

- app/services/cocina/from_fedora/descriptive/notes.rb
- app/services/cocina/normalizers/mods_normalizer.rb
- app/services/cocina/to_fedora/descriptive/note.rb
- spec/requests/create_collection_spec.rb
- spec/requests/update_metadata_spec.rb
- spec/services/cocina/from_fedora/descriptive/related_resource_spec.rb
- spec/services/cocina/from_fedora/descriptive_spec.rb
- spec/services/cocina/mapper_spec.rb
- spec/services/cocina/mapping/descriptive/h2/note_h2_spec.rb
- spec/services/cocina/mapping/descriptive/mods/abstract_spec.rb
- spec/services/cocina/mapping/descriptive/mods/note_spec.rb
- spec/services/cocina/mapping/descriptive/mods/related_item_spec.rb
- spec/services/cocina/normalizers/mods_normalizer_spec.rb
- spec/services/cocina/object_creator_spec.rb
- spec/services/cocina/to_fedora/descriptive_spec.rb
Fixes #2728  - updated abstract mapping
Note that a number of other tests had to be updated to reflect the updated mappings, see https://github.com/sul-dlss/dor-services-app/issues/2728#issuecomment-833898287
Unskipped tests in #2727 and updated other existing tests as needed with Arcadia's approval.
> updated abstract mapping

- .rubocop.yml
- Gemfile
- Gemfile.lock
there was a CVE
unit tests so far (integration tests after this is merged)
> Upgrade puma

- lib/tasks/seeds/druid:bx911tp9024.xml
- lib/tasks/seeds/druid:hv992ry2431.xml
- lib/tasks/seeds/druid:wr005wn5739.xml
- lib/tasks/seeds/druid:zw306xn5593.xml
- spec/fixtures/apo_druid_fg890hx1234.xml
See https://github.com/sul-dlss/dor-services-app/issues/2852#issuecomment-847215355
This seed/fixture data didn't look like the data actually in production and caused the problem outlined in #2852
> Update seed data to look like production data

- app/services/cocina/from_fedora/descriptive/title_builder.rb
- app/services/cocina/normalizers/mods/title_normalizer.rb
- spec/services/cocina/from_fedora/descriptive/related_resource_spec.rb
- spec/services/cocina/normalizers/mods/title_normalizer_spec.rb
refs https://github.com/sul-dlss/happy-heron/issues/1453
Allow H2 deposit.
Unit
NA
> Stops removing trailing period.

- spec/services/cocina/mapping/descriptive/h2/form_h2_spec.rb
Part of https://github.com/sul-dlss/happy-heron/issues/1392
n/a
n/a
Implementation ticket #2869
> Update H2 form spec to match new mapping

- Gemfile
- Gemfile.lock
- app/services/cocina/from_fedora/access/license.rb
- app/services/publish/rights_metadata.rb
- config/boot.rb
- openapi.yml
- spec/services/cocina/from_fedora/access/license_spec.rb
- spec/services/cocina/from_fedora/collection_access_spec.rb
- spec/services/cocina/from_fedora/dro_access_spec.rb
- spec/services/cocina/mapping/access/collection_access_spec.rb
- spec/services/cocina/mapping/access/dro_access_spec.rb
- spec/services/cocina/normalizers/rights_normalizer_spec.rb
- spec/services/cocina/to_fedora/collection_access_spec.rb
- spec/services/cocina/to_fedora/dro_access_spec.rb
- spec/services/publish/public_xml_service_spec.rb
- spec/services/publish/rights_metadata_spec.rb
> Bump cocina-models to 0.60.0

- config/licenses.yml
> Fix typo in license description

- app/services/cocina/from_fedora/identification.rb
- app/services/cocina/object_updater.rb
- app/services/cocina/to_fedora/identity.rb
- openapi.yml
- spec/requests/update_metadata_spec.rb
- spec/services/cocina/mapping/identification/dro_identity_spec.rb
and updated cocina-models to 0.61.2
> Store DOI in identityMetadata and map it to Cocina

- app/controllers/objects_controller.rb
- app/services/cocina/object_creator.rb
- app/services/doi.rb
- config/settings.yml
- openapi.yml
- spec/requests/create_object_spec.rb
- spec/services/cocina/object_creator_spec.rb
closes #2914
Support assigning DOIs in H2.
Unit
openapi.yml
> Supports assigning DOI.

- spec/services/cocina/mapping/descriptive/h2/admin_metadata_h2_spec.rb
- spec/services/cocina/mapping/descriptive/h2/contributor_h2_spec.rb
- spec/services/cocina/mapping/descriptive/h2/event_h2_spec.rb
Closes #2919 Closes #2916 Closes #2913 
CircleCI
n/a
Implementation ticket #2926
> Make H2-MODS mappings more consistent

- spec/services/cocina/mapping/descriptive/h2_datacite/contributor_h2_datacite_spec.rb
- spec/services/cocina/mapping/descriptive/h2_datacite/identifiers_h2_datacite_spec.rb
- spec/services/cocina/mapping/descriptive/h2_datacite/rights_list_h2_datacite_spec.rb
- spec/services/cocina/mapping/descriptive/h2_datacite/title_h2_datacite_spec.rb
Closes #2921
CircleCI
n/a
Implementation ticket #2928
> Map H2 to additional DataCite fields

- Gemfile
- Gemfile.lock
- app/controllers/objects_controller.rb
- app/jobs/update_doi_metadata_job.rb
- config/settings.yml
- spec/jobs/update_doi_metadata_job_spec.rb
- spec/requests/update_doi_metadata_spec.rb
> Update datacite with the metadata

- app/services/cocina/to_datacite/attributes.rb
- spec/services/cocina/to_datacite/attributes_spec.rb
> Update Datacite metadata so that stub values are valid

- app/jobs/publish_job.rb
correct the comment (prob a copy pasta thing)
> publish_job.rb: fix comment

- spec/services/cocina/mapping/descriptive/h2/contributor_h2_spec.rb
- spec/services/cocina/mapping/descriptive/h2/event_h2_spec.rb
- spec/services/cocina/mapping/descriptive/h2_datacite/contributor_h2_datacite_spec.rb
Partially address #2953 (for contributor)
CircleCI
n/a
> Sync contributor cocina mappings

- spec/services/cocina/mapping/descriptive/h2/event_h2_spec.rb
H2 can't currently provide some of the data the mapping expected
CircleCI
n/a
> Update H2-Cocina-MODS event mapping to match H2 output

- app/services/cocina/from_fedora/descriptive/form.rb
- app/services/cocina/to_fedora/descriptive/form.rb
- spec/services/cocina/mapping/descriptive/h2/form_h2_spec.rb
> Tweaks H2 forms mapping.

- spec/services/cocina/mapping/descriptive/h2/subject_h2_spec.rb
> Enables multiple terms test.

- spec/services/cocina/mapping/descriptive/h2/event_h2_spec.rb
Add missing spec
CircleCI
n/a
Implementation ticket #2970
> Add event spec for when both publication and creation date are present

- spec/services/cocina/mapping/descriptive/h2/event_h2_spec.rb
> Implement specs that need no changes for h2 events

- spec/services/cocina/mapping/descriptive/h2/event_h2_spec.rb
> Fix h2 mapping test for date created

- app/services/cocina/from_fedora/descriptive/event.rb
- spec/services/cocina/mapping/descriptive/h2/event_h2_spec.rb
- spec/services/cocina/mapping/descriptive/mods/origin_info_date_spec.rb
- spec/services/cocina/mapping/descriptive/mods/origin_info_event_type_spec.rb
- spec/services/cocina/mapping/descriptive/mods/origin_info_place_spec.rb
- spec/services/cocina/mapping/descriptive/mods/origin_info_publisher_spec.rb
- spec/services/cocina/mapping/descriptive/mods/origin_info_spec.rb
> When publisher is present add organization type to cocina

- spec/services/cocina/mapping/descriptive/h2/event_h2_spec.rb
Correcting a mapping
CircleCI
n/a
> Add missing MODS to event mapping

- spec/services/cocina/mapping/descriptive/h2/event_h2_spec.rb
The existing test was incorrect.
> Fix event test to use roleTerm rather than roleText

- spec/services/cocina/mapping/descriptive/h2/related_item_h2_spec.rb
- spec/validators/cocina/description_roundtrip_validator_spec.rb
To ensure our code was handling these cases correctly.
it was adding specs.
> add specs for h2 purls in relatedResource

- app/services/cocina/object_updater.rb
> Add a comment explaining tags matching.

- spec/services/cocina/mapping/descriptive/h2/form_h2_spec.rb
Partially addresses https://github.com/sul-dlss/happy-heron/issues/1908
CircleCI
n/a
> Add DataCite to cocina>MODS mapping for form

- app/services/cocina/from_fedora/descriptive/form.rb
- app/services/cocina/to_fedora/descriptive/form.rb
- spec/services/cocina/mapping/descriptive/h2/form_h2_spec.rb
> Store the datacite resourceType in a MODS extension

- app/services/cocina/to_datacite/attributes.rb
- spec/services/cocina/to_datacite/attributes_spec.rb
Better to have no data than bad data.
> Comment out non-required datacite placeholders

- app/services/cocina/to_datacite/attributes.rb
- app/services/cocina/to_datacite/dro_access.rb
- app/services/cocina/to_datacite/form.rb
- app/services/cocina/to_datacite/identifier.rb
- app/services/cocina/to_datacite/note.rb
- app/services/cocina/to_datacite/subject.rb
- app/services/cocina/to_datacite/title.rb
- spec/services/cocina/mapping/access/h2_datacite/dro_access_h2_datacite_spec.rb
- spec/services/cocina/mapping/descriptive/h2_datacite/identifiers_h2_datacite_spec.rb
- spec/services/cocina/mapping/descriptive/h2_datacite/note_h2_datacite_spec.rb
- spec/services/cocina/mapping/descriptive/h2_datacite/subject_h2_datacite_spec.rb
- spec/services/cocina/mapping/descriptive/h2_datacite/title_h2_datacite_spec.rb
Fewer conditionals makes the code easier to reason about.
> [REFACTOR] Remove unnecessary conditionals from code

- app/services/cocina/to_fedora/descriptive/form.rb
- spec/services/cocina/mapping/descriptive/mods/datacite_extension_spec.rb
> Implement datacite extension mapping

- Gemfile
- Gemfile.lock
- app/services/cocina/from_fedora/descriptive/purl.rb
- app/services/cocina/normalizers/mods_normalizer.rb
- config/settings.yml
- openapi.yml
- spec/dor/update_marc_record_service_spec.rb
- spec/requests/collections_for_object_spec.rb
- spec/requests/create_collection_spec.rb
- spec/requests/create_object_spec.rb
- spec/requests/show_object_spec.rb
- spec/requests/update_metadata_spec.rb
- spec/services/cocina/from_fedora/descriptive_spec.rb
- spec/services/cocina/mapping/descriptive/h2/related_item_h2_spec.rb
- spec/services/cocina/mapping/descriptive/mods/geo_extension_spec.rb
- spec/services/cocina/mapping/descriptive/mods/location_spec.rb
- spec/services/cocina/mapping/descriptive/mods/related_item_spec.rb
- spec/services/cocina/mapping/identification/agreement_identity_spec.rb
- spec/services/cocina/mapping/identification/apo_identity_spec.rb
- spec/services/cocina/mapping/identification/collection_identity_spec.rb
- spec/services/cocina/mapping/identification/dro_identity_spec.rb
- spec/services/cocina/normalizers/mods/geo_extension_normalizer_spec.rb
- spec/services/cocina/normalizers/mods_normalizer_spec.rb
- spec/services/cocina/object_creator_spec.rb
- spec/services/cocina/to_datacite/attributes_spec.rb
- spec/validators/cocina/description_roundtrip_validator_spec.rb
> Update to cocina-models 0.62

- spec/services/cocina/mapping/descriptive/h2_datacite/access_h2_datacite_spec.rb
> Implement H2 access to datacite tests.

- spec/services/cocina/mapping/descriptive/h2_datacite/event_h2_datacite_spec.rb
Bring event spec in line with current understanding
CircleCI
n/a
> Simplify event spec

- app/services/cocina/to_datacite/attributes.rb
- spec/services/cocina/to_datacite/attributes_spec.rb
> Make the DOI findable

- spec/services/cocina/mapping/descriptive/h2_datacite/contributor_h2_datacite_spec.rb
Spec changed so instructions need to change too
CircleCI
n/a
> Update instructions for mapping contributors to DataCite

- app/jobs/update_doi_metadata_job.rb
So we can see what we sent to cause the error.
> Provide the request if the response from datacite fails

- app/services/cocina/to_datacite/form.rb
- spec/services/cocina/mapping/descriptive/h2_datacite/form_h2_datacite_spec.rb
closes #3011
More mapping
Unit
NA
> Handle nil-ly cases for form datacite mapping.

- app/services/cocina/to_datacite/form.rb
https://app.honeybadger.io/projects/50568/faults/80994580
> Stop compacting type attributes.

- Gemfile.lock
- app/services/cocina/to_datacite/attributes.rb
- spec/services/cocina/to_datacite/attributes_spec.rb
> Provide a URL to the datacite API

- app/services/cocina/serializer.rb
- spec/services/cocina/serializer_spec.rb
closes #3034
Dates where not serializing, causing an error.
Unit, stage
> Fixes DRO serialization to allow dates.

- app/services/administrative_tags.rb
We're seeing that sometimes an infinite loop occurs.
> Prevent infinite loop in retry

- app/services/cocina/from_fedora/descriptive/subject.rb
- spec/services/cocina/from_fedora/descriptive/subject_spec.rb
> Skip subject nodes that have empty titles

- config/application.rb
- openapi.yml
Related to https://github.com/sul-dlss/argo/issues/2813
> Add a full description of the error response from the tags service

- config/application.rb
- openapi.yml
Having an accurate spec is helpful
> Fix the OpenAPI spec for the response and enable testing it.

- app/services/publish/public_xml_service.rb
> Documenting why we munge resource identifiers for public xml

- README.md
- bin/generate-cache
- bin/validate-cocina-roundtrip
- bin/validate-desc-cocina-roundtrip
- bin/validate-rights-cocina-roundtrip
- bin/validate-to-desc-cocina
- bin/validate-to-mods
Easier validation goodness.
Local
> Adds option to validate scripts to allow a different input file.

- bin/validate-cocina-roundtrip
- bin/validate-rights-cocina-roundtrip
- lib/fedora_loader.rb
- spec/spec_helper.rb
refs #3105
Make sure that performing correct mapping when validating.
Local
> Improves mapping to Fedora items when loading from cache.

- .dockerignore
- .gitignore
- README.md
- bin/copy-cache
- lib/fedora_cache.rb
Makes it easier to test locally.
Local
README
> Adds support for copying cache.

- app/services/cocina/to_fedora/content_metadata_generator.rb
> Less hacky way to create image data node.

- bin/validate-cocina-roundtrip
> Clarifies missing.

- .rubocop.yml
- app/services/publish/metadata_transfer_service.rb
- config/initializers/activefedora_solr_updates.rb
- spec/services/cleanup_service_spec.rb
- spec/services/delete_service_spec.rb
- spec/services/embargo_release_service_spec.rb
- spec/services/publish/metadata_transfer_service_spec.rb
- spec/services/sdr_ingest_service_spec.rb
- spec/support/foxml_helper.rb
> Enabled new rubocops.

- .rubocop.yml
- app/services/cocina/object_creator.rb
- app/services/cocina/object_updater.rb
- app/services/cocina/to_fedora/content_metadata_generator.rb
- spec/services/cocina/mapping/structural/dro_structural_spec.rb
- spec/services/cocina/to_fedora/content_metadata_generator_spec.rb
closes #2765
Better testing. This will be the basis of future roundtrip testing.
> Sets up roundtrip testing for Cocina structural / Fedora contentMD.

- bin/reports/report-content-missing_mimeType
- bin/reports/report-content-missing_size
- lib/report.rb
- lib/unique_report.rb
refs #3155
Help determine if additional mapping/normalization is needed.
sdr-deploy
> Adds report for file nodes missing mimetype attribute.

- bin/reports/report-content-not_in_sequence
refs #2481
Assist with determining how to handle sequence.
sdr-deploy
> Adds report for checking resource sequence in content metadata.

- bin/reports/report-desc-titles-translated
> Translated title report

- spec/requests/update_metadata_spec.rb
> update_metadata_spec fixes.

- app/controllers/application_controller.rb
- app/controllers/objects_controller.rb
- app/services/cocina_object_store.rb
- openapi.yml
- spec/requests/show_object_spec.rb
- spec/requests/update_doi_metadata_spec.rb
- spec/services/cocina_object_store_spec.rb
closes #3143
Provide an abstraction around finding / saving Cocina objects.
Unit
> Adds CocinaObjectPersister.

- app/controllers/objects_controller.rb
- spec/requests/show_object_spec.rb
> Load item.createdDate into  X-Created-At header

- app/controllers/objects_controller.rb
- spec/requests/show_object_spec.rb
The wrong method was being used, causing an error.
Unit
> Fixes create date.

- app/services/cocina/normalizers/embargo_normalizer.rb
super nitpicky touchup to #3207 because it wasn't worth requesting changes over that
unit tests
> EmbargoNormalizer: slightly more idiomatic method name

- app/services/cocina/from_fedora/apo.rb
- spec/services/cocina/mapping/administrative/apo_administrative_spec.rb
closes #3225
Fix mapping bug.
Unit
> Handles roles with person type.

- app/controllers/workspaces_controller.rb
- app/services/workspace_service.rb
- spec/requests/create_workspaces_spec.rb
- spec/requests/reset_workspace_spec.rb
- spec/services/workspace_service_spec.rb
Closes #3175 
Closes #3176 
Unit
> Cocina-ize ResetWorkSpaceController

- app/controllers/objects_controller.rb
- app/models/dor/goobi.rb
- app/services/cocina/object_updater.rb
- app/services/cocina/to_fedora/descriptive.rb
- app/validators/cocina/description_roundtrip_validator.rb
- spec/dor/goobi_spec.rb
- spec/requests/notify_goobi_spec.rb
- spec/support/mods_mapping_spec_helper.rb
closes #3173
Switch Goobi service from using Fedora objects to Cocina objects.
Unit
> Cocina-izes Goobi service.

- spec/services/cocina/to_fedora/administrative_metadata_spec.rb
> Add hasAgreement to broken test breaking the main build

- app/models/admin_policy.rb
- app/models/collection.rb
- app/models/dro.rb
- app/services/cocina_object_store.rb
- db/migrate/20220131194025_create_dro.rb
- db/migrate/20220131194359_create_admin_policy.rb
- db/migrate/20220131194912_create_collection.rb
- db/structure.sql
- spec/factories/admin_policies.rb
- spec/factories/collections.rb
- spec/factories/dros.rb
- spec/models/admin_policy_spec.rb
- spec/models/collection_spec.rb
- spec/models/dro_spec.rb
- spec/services/cocina_object_store_spec.rb
> Add Cocina ActiveRecord models.

- app/services/publish/metadata_transfer_service.rb
- spec/services/publish/metadata_transfer_service_spec.rb
Fixes https://app.honeybadger.io/projects/50568/faults/83838689
Unit test updated
> Properly initialize PublicXmlService in MetadataTransferService

- app/controllers/metadata_controller.rb
- openapi.yml
- spec/requests/mods_update_spec.rb
> Fix the openapi response code and improve testing

- app/controllers/metadata_controller.rb
- app/controllers/mods_controller.rb
- spec/requests/legacy_metadata_update_spec.rb
- spec/requests/mods_update_spec.rb
So that the indexer will be run.
> Publish messages when the legacy metadata or MODS metadata is updated

- app/models/dor/update_marc_record_service.rb
Clearer, more consistent code.
Unit
> Rename variable per naming conventions.

- app/models/dor/update_marc_record_service.rb
- spec/dor/update_marc_record_service_spec.rb
Fixes #3353 
Updated unit test.
> Translate dro and collection uris to terms for the 856 output

- Gemfile
- Gemfile.lock
- openapi.yml
> Update to cocina-models 0.65.0

- Gemfile.lock
- openapi.yml
So that barcodes can be removed
> Update to cocina-models 0.65.1

- app/controllers/queries_controller.rb
- spec/factories/collections.rb
- spec/factories/dros.rb
- spec/factories/druids.rb
- spec/models/collection_spec.rb
- spec/models/dro_spec.rb
- spec/requests/collections_for_object_spec.rb
> QueriesController: rewrite to use Cocina objects

- spec/services/cocina/mapping/descriptive/mods/subject_name_spec.rb
Closes #2684 
Updates the test input to validate mappings.
Updated test data.
> Verify updated/added subject name mappings

- app/services/cocina/to_fedora/dro_access.rb
- app/services/cocina/to_fedora/license.rb
- spec/services/cocina/mapping/access/dro_access_spec.rb
- spec/services/cocina/to_fedora/dro_access_spec.rb
- spec/services/cocina/to_fedora/license_spec.rb
> Allow clearing copyright and license

- bin/migrate
> Enable VersionMigrationService for migration script.

- app/services/cocina/normalizers/identity_normalizer.rb
- spec/services/cocina/normalizers/identity_normalizer_spec.rb
To reduce mental load when looking at this class - I missed something I should have seen.
> Identity normalizer refactor

- app/jobs/create_virtual_objects_job.rb
- app/services/constituent_service.rb
- app/services/item_query_service.rb
- app/services/reset_content_metadata_service.rb
- openapi.yml
- spec/jobs/create_virtual_objects_job_spec.rb
- spec/requests/batch_create_virtual_objects_spec.rb
- spec/services/constituent_service_spec.rb
- spec/services/item_query_service_spec.rb
- spec/services/reset_content_metadata_service_spec.rb
Connects to #3331
This is extracted from #3379, in an attempt to disentangle naming-related changes from the Cocinization-related changes.
CI, just a rename?
None
> Rename virtual objects

- app/services/cocina/object_creator.rb
> Handle nil access

- spec/requests/create_object_spec.rb
> Create a test for creating an object with nil access

- app/services/publish/public_desc_metadata_service.rb
- spec/requests/metadata_spec.rb
- spec/services/publish/dublin_core_service_spec.rb
- spec/services/publish/public_desc_metadata_service_spec.rb
> Lookup parent from solr

- app/services/cocina/normalizers/admin_normalizer.rb
- spec/services/cocina/mapping/administrative/apo_administrative_spec.rb
to make the xml parsing faster and to improve readability of the code.
tests still pass.
> admin_normalizer refactored slightly

- app/services/datastream_extractor.rb
- spec/services/datastream_extractor_spec.rb
closes #3448
Versions need to be included in the moab.
Unit
> Generate versionMetadata.xml from object versions.

- app/services/cocina/object_creator.rb
- app/services/cocina_object_store.rb
- config/settings.yml
- spec/services/cocina/object_creator_spec.rb
- spec/services/cocina_object_store_spec.rb
closes #3144
Begin exercising persistence to postgres.
Unit
> Adds feature for updating, creating, and deleting from postgres.

- spec/services/publish/public_xml_service_spec.rb
This test was only testing the input data and not running the class that is supposed to be tested
> Remove a bad test

- .github/pull_request_template.md
A link makes it clear what is meant by "integration tests"
⚡ ⚠ If this change has cross service impact, ***run integration tests*** and/or test in [stage|qa] environment, in addition to specs. ⚡
no need.
> pull_request_template.md - link out to integration test repo

- app/services/cocina/from_fedora/apo.rb
- app/services/cocina/normalizers/role_normalizer.rb
- spec/services/cocina/mapping/administrative/apo_administrative_spec.rb
closes #3339
Mapping
Before:
```
Status (n=50000; not using Missing for success/different/error stats):
Success:   49891 (99.852%)
Different: 74 (0.148%)
Expected unmapped:     35 (0.07%)
```
After:
```
Status (n=50000; not using Missing for success/different/error stats):
Success:   49891 (99.852%)
Different: 74 (0.148%)
Missing from …
```
> Handle empty roles.

- app/services/preservation_metadata_extractor.rb
- app/services/sdr_ingest_service.rb
- spec/fixtures/workspace/dd/116/zh/0343/dd116zh0343/metadata/cocina.json
- spec/services/preservation_metadata_extractor_spec.rb
- spec/services/sdr_ingest_service_spec.rb
closes #3464
Preserve the cocina representation.
Unit, stage.
> Add cocina.json to preservation bag.

- app/services/cocina/normalizers/content_metadata_normalizer.rb
- spec/services/cocina/normalizers/content_metadata_normalizer_spec.rb
I was confused by some things in the content_metadata_normalizer when I started to work on a ticket, so I got some clarifications, fixed a bug and did some other refactors.
> content_metadata_normalizer refactors

- README.md
> Added note about PARALLEL_PROCESSOR_COUNT.

- app/services/publish/access_conditions.rb
- app/services/publish/public_desc_metadata_service.rb
- spec/services/publish/public_desc_metadata_service_spec.rb
> Decouple PublicDescMetadataService from RightsMetadataDS

- app/services/publish/public_xml_service.rb
- spec/services/publish/public_xml_service_spec.rb
We are trying to get off of Fedora.
> Decouple the release date in public xml from ActiveFedora

- app/services/cocina/object_creator.rb
- app/services/cocina/object_updater.rb
- app/services/cocina_object_store.rb
> Clarify roles of CocinaObjectStore, ObjectCreator, and ObjectUpdater.

- app/services/preservation_metadata_extractor.rb
- spec/services/preservation_metadata_extractor_spec.rb
Fixes bug caught by integration tests.
unit tests and integration tests
> preservation_metadata_extractor: no contentMd for apo or collection

- app/services/publish/metadata_transfer_service.rb
Fixes https://github.com/sul-dlss/common-accessioning/issues/840 (at least part of)
> Fix check for world_discoverable

- app/services/preservation_metadata_extractor.rb
The information was correct and I removed it under the impression it was incorrect.  My bad.
> preservation_metadata_extractor: add back some yard doc info

- config/deploy/migrate.rb
refs #3130
Allow testing of migration in prod-like environment.
> Adds deploy configuration for migrate.

- app/controllers/objects_controller.rb
- spec/requests/destroy_spec.rb
> Decouple destroy from ActiveFedora

- app/controllers/administrative_tags_controller.rb
- app/controllers/application_controller.rb
- spec/requests/administrative_tags_spec.rb
> Decouple AdminTagsController from ActiveFedora

- app/controllers/shelves_controller.rb
- spec/requests/shelving_spec.rb
> Decouple ShelvesController from ActiveFedora

- app/services/cocina_object_store.rb
- config/settings.yml
- spec/services/cocina_object_store_spec.rb
closes #3146
Another step to ~~fedora~~.
Unit. This will require further testing when enabled.
> Implement configurable find for postgres.

- Gemfile
- Gemfile.lock
- app/controllers/mods_controller.rb
- app/services/publish/public_cocina_service.rb
- openapi.yml
- spec/requests/create_object_spec.rb
- spec/requests/mods_update_spec.rb
- spec/requests/show_object_spec.rb
> Updates cocina version.

- app/services/cocina/to_fedora/dro_access.rb
- app/services/cocina/to_fedora/embargo_metadata_generator.rb
- app/services/embargo_release_service.rb
- spec/services/cocina/to_fedora/embargo_metadata_generator_spec.rb
- spec/services/embargo_release_service_spec.rb
> [HOLD] Cocinizes EmbargoReleaseService.

- spec/support/cocina_matchers.rb
Gives more useful information for some types of errors.
> Tweak to cocina matcher.

- .rubocop.yml
- spec/models/object_version_spec.rb
- spec/services/cocina/from_fedora/dro_structural_spec.rb
- spec/services/cocina/mapper_spec.rb
- spec/services/cocina/mapping/descriptive/h2_datacite/form_h2_datacite_spec.rb
- spec/services/cocina/mapping/descriptive/h2_datacite/identifiers_h2_datacite_spec.rb
- spec/services/cocina/to_datacite/event_pub_year_spec.rb
- spec/services/embargo_release_service_spec.rb
- spec/services/mods_equivalent_service_spec.rb
> Enable new cops.

- spec/services/publish/public_xml_service_spec.rb
> Fix a broken test that claimed to be for a collection

- Gemfile
- Gemfile.lock
- app/services/synchronous_indexer.rb
To keep dependencies up to date.
> Upgrade to moab-versioning 5 and Faraday 2

- app/jobs/publish_job.rb
- app/services/publish/dublin_core_service.rb
- app/services/publish/metadata_transfer_service.rb
- spec/jobs/publish_job_spec.rb
This will help us decouple from dor-services
> Remove unused exceptions

- app/controllers/datastreams_controller.rb
- spec/requests/datastreams_spec.rb
This will allow testing cocina-only objects (i.e., not saved to Fedora) without having to disable datastream editing in Argo. (It just won't be supported for cocina-only objects since Argo will receive an empty datastream list for those.)
Unit
> Return empty datastream when cocina exists in postgres.

- app/services/cocina/id_generator.rb
- spec/fixtures/hj097bm8879_publicObject.xml
- spec/requests/create_object_spec.rb
- spec/requests/update_metadata_spec.rb
- spec/services/cocina/from_fedora/dro_structural_spec.rb
- spec/services/cocina/id_generator_spec.rb
- spec/services/cocina/to_fedora/content_metadata_generator_spec.rb
- spec/services/publish/public_xml_service_spec.rb
Fixes #3623
This broke IIIF links on the Access side.
CI + will be tested in stage where there are Access VMs integrated.
> [HOLD] Do not generate slashes in the file/fileset resource ID segment

- app/services/embargo_release_service.rb
- app/validators/cocina/unique_source_id_validator.rb
- spec/requests/create_object_spec.rb
- spec/services/cocina/object_creator_spec.rb
- spec/services/embargo_release_service_spec.rb
Fixes #3639 - replace Dor::SearchService with new SolrService
Updated existing tests 
> replace Dor::SearchService with SolrService

- app/services/cocina_object_store.rb
- app/services/suri_service.rb
- spec/requests/create_collection_spec.rb
- spec/requests/create_object_spec.rb
- spec/services/cocina_object_store_spec.rb
- spec/services/suri_service_spec.rb
Fixes #3636
And, in so doing, tear out a bunch of functionality that is not even supported in the Suri service anymore.
CI, and successfully integration-tested in QA
> Port SuriService from dor-services gem

- app/models/dor/update_marc_record_service.rb
- spec/dor/update_marc_record_service_spec.rb
> Refactor check for equals to avoid guard when descriptive.note is nil

- app/services/cocina/object_creator.rb
- app/services/cocina_object_store.rb
- spec/services/cocina/object_creator_spec.rb
- spec/services/cocina_object_store_spec.rb
- spec/support/cocina_matchers.rb
DOI assignment has to happen regardless of datastore.
Unit, integration tests.
> Extract assigning DOI

- app/controllers/datastreams_controller.rb
- app/models/admin_policy.rb
- app/models/collection.rb
- app/models/dro.rb
- app/services/cocina_object_store.rb
- config/settings.yml
- spec/requests/create_collection_spec.rb
- spec/requests/create_object_spec.rb
- spec/requests/datastreams_spec.rb
- spec/requests/update_metadata_spec.rb
- spec/services/cocina_object_store_spec.rb
> [HOLD] Split datastores

- app/services/cocina/from_fedora/apo.rb
Fewer conditionals is easier to understand.
> Refactor build_apo_administrative to have fewer conditionals

- app/services/publish/public_xml_service.rb
- spec/services/publish/public_xml_service_spec.rb
> Remove fedora from public xml service.

- app/services/preservation_metadata_extractor.rb
- spec/services/preservation_metadata_extractor_spec.rb
> Export only the required datastreams to preservation

- app/controllers/administrative_tags_controller.rb
- app/models/dor/goobi.rb
- app/services/administrative_tags.rb
- app/services/cocina/from_fedora/administrative.rb
- app/services/cocina/from_fedora/dro.rb
- app/services/cocina/from_fedora/viewing_direction_helper.rb
- app/services/cocina_object_store.rb
- app/services/constituent_service.rb
- app/services/delete_service.rb
- app/services/legacy_metadata_service.rb
- app/services/release_tags/identity_metadata.rb
- app/services/shelvable_files_stager.rb
- app/services/synchronous_indexer.rb
- lib/fedora_loader.rb
- openapi.yml
- spec/dor/goobi_spec.rb
- spec/requests/administrative_tags_spec.rb
- spec/requests/create_object_spec.rb
- spec/requests/update_metadata_spec.rb
- spec/services/administrative_tags_spec.rb
- spec/services/cocina/from_fedora/dro_structural_spec.rb
- spec/services/cocina/mapper_spec.rb
- spec/services/cocina_object_store_spec.rb
- spec/services/delete_service_spec.rb
- spec/services/publish/metadata_transfer_service_spec.rb
- spec/services/release_tags/identity_metadata_spec.rb
> Stop using pid as a parameter name

- app/controllers/objects_controller.rb
- app/jobs/create_virtual_objects_job.rb
- app/services/cocina_object_store.rb
> Removed some unnecessary Fedora-specific exceptions.

- app/services/preservation_metadata_extractor.rb
- spec/services/preservation_metadata_extractor_spec.rb
This helps isolate the concerns that need to know about Fedora.
> Decouple PreservationMetadataExtractor from ActiveFedora

- lib/fedora_loader.rb
This was broken in the pid to druid rename.
sdr-deploy
> Fix fedora loader

- Gemfile
- Gemfile.lock
- app/services/cocina/from_fedora/apo_access.rb
- app/services/cocina/from_fedora/dro.rb
- app/services/cocina/from_fedora/dro_structural.rb
- app/services/cocina/mapper.rb
- app/services/cocina_object_store.rb
- app/services/events_migration_service.rb
- app/services/version_migration_service.rb
- bin/migrate
- lib/fedora_migrator.rb
- spec/services/cocina/mapper_spec.rb
- spec/services/cocina_object_store_spec.rb
- spec/spec_helper.rb
part of #3657
look!  a dorky progress bar!
Changes are to error messages provided for Fedora --> Cocina mapping;  no changes to other code except migration script itself being refactored.
coverage drop is due to making a class to be run by the script;  this was useful to easily get Rails logging and instance variables;  the class is temporary (until Fedora goes away) and it doesn't do anything substantially different than the script did
> Migrate script

- lib/fedora_migrator.rb
To allow better understanding of migration speed.
> Add timestamp to migration log.

- app/controllers/objects_controller.rb
- app/services/cocina/object_updater.rb
- app/services/cocina_object_store.rb
> Remove unnecessary exception

- Gemfile
- bin/migrate
- lib/fedora_migrator.rb
refs #3680
Faster migration
Tested on dsa migrate.
> Parallelize migration script.

- config/deploy/qa.rb
To deploy the app to the qa load balancer
Continuing on from successful work yesterday
> Deploy to qa load balancer

- Gemfile.lock
> Bump cocina to 0.69.1

- Gemfile.lock
> Bump cocina to 0.69.2

- spec/services/cocina/mapping/descriptive/mods/identifier_spec.rb
Make descriptive metadata identifiers work like everything else.
> Streamline identifier spec to be more consistent with other specs

- app/models/collection.rb
- app/models/dro.rb
- db/migrate/20220329134023_change_null_for_cocina.rb
- db/structure.sql
- spec/models/collection_spec.rb
- spec/models/dro_spec.rb
Since the DB records have been corrected in QA, it is no longer necessary to handle nulls in the code.
Unit
> New required fields for collections and dros

- app/services/constituent_service.rb
- app/services/item_query_service.rb
- spec/services/constituent_service_spec.rb
- spec/services/item_query_service_spec.rb
> Fixed lingering use of find_with_timestamps.

- app/services/cocina/serializer.rb
- spec/services/cocina/serializer_spec.rb
https://app.honeybadger.io/projects/50568/faults/84731634
Unit
> Fix Cocina Serializer to handle DROWithMetadata.

- spec/services/cocina/mapping/descriptive/mods/title_info_spec.rb
Account for additional edge cases and simplify logic for matching nameTitleGroups.
> Update title_info_spec with different approach

- app/controllers/objects_controller.rb
- spec/requests/update_metadata_spec.rb
> Use standard ETag header

- app/services/cocina/from_fedora/descriptive/primary.rb
Because when I first looked at this class I couldn't tell what it was doing.  Good old "item" -- a nice overloaded term that really didn't apply here.
specs.
> from_fedora/descriptive/primary: improve variable names and give a bit of yard doc

- bin/reports/report-desc-physical_location_types
Fixes #3778
CI and ran in sdr-deploy
> Add a report for unique physical location types

- app/services/publish/public_xml_service.rb
- spec/requests/metadata_spec.rb
- spec/services/publish/public_xml_service_spec.rb
closes #3760
See ticket for explanation.
Unit
> Use TitleBuilder for public XML identity objectLabel.

- bin/reports/report-desc-table_of_contents_types
Fixes #3785
CI and ran report on sdr-deploy
> Add a report for unique table of contents types

- bin/reports/report-desc-origin_info_event_types
> Add a report for unique originInfo event types

- Gemfile
- Gemfile.lock
- bin/generate-cache
- bin/validate-cocina-roundtrip
- bin/validate-rights-cocina-roundtrip
- lib/fedora_cache.rb
- lib/fedora_loader.rb
To make it easier to test cocina models changes without cutting a new release.
local, sdr-deploy
> Remove dor-services-client.

- app/models/dor/update_marc_record_service.rb
- spec/dor/update_marc_record_service_spec.rb
closes #3761
Descriptive title > item label
Unit
> Uses TitleBuilder for UpdateMarcRecordService.

- spec/factories/druids.rb
So it's easier to tell druids generated in this way apart
> Update the druid factory to use random letters

- bin/reports/report-desc-alternative_name_types
Fixes #3779
CI + sdr-deploy run
> Add a report for unique alternative name types

- bin/reports/report-desc-access_cond_types
- bin/reports/report-desc-phys_desc_note_types
> Add reports for unique access condition types and physical description note types

- bin/reports/report-desc-phys_desc_note_types
> Fix the physical description note types report

- spec/services/cocina/mapping/descriptive/mods/name_spec.rb
> Add additional specs for duplicate names

- bin/reports/report-desc-nameid_type
Report unique values of the type attribute for nameIdentifier at any level in MODS.
Closes #3784
> Report on nameIdentifier type in MODS

- bin/reports/report-desc-accesscondition
Resolves #3825. 
Ran report on sdr-deploy, druids.txt file. Report found 153 druids and is attached to the issue. 
> Report on desc accessCondition

- bin/reports/report-desc-part-detail_type
Fixes #3787 - report on unique part detail types
Running on sdr-deploy
> add report for part detail types

- spec/services/cocina/mapping/descriptive/mods/name_spec.rb
> Add spec for multipart duplicate name

- bin/reports/report-desc-identifier_specific_types
- lib/fedora_loader.rb
> Add report for specific identifier type values

- bin/reports/report-desc-iso8601
> Add report for invalid ISO8601 datetimes

- app/services/cocina/from_fedora/descriptive/contributor.rb
- app/services/cocina/to_fedora/descriptive/contributor_writer.rb
- spec/services/cocina/mapping/descriptive/mods/name_spec.rb
Part of #2699, this is a small part of the changes needed for clean nameTitleGroup roundtrip mappings.
```
Status (n=500000; not using Missing for success/different/error stats):
Success:   498958 (99.873%)
Different: 575 (0.115%)
Mapping error:     58 (0.012%)
Expected unmapped:     409 (0.082%)
```
newly FIXED by this change: NONE!
newly BROKEN by this change: NONE!
```
Status …
```
> cocina contributor status and type moved up from name level

- bin/reports/report-desc-invalid_note_types
> Add report for invalid note types

- app/validators/date_time_validator.rb
- bin/reports/report-desc-iso8601
- bin/reports/report-desc-w3cdtf
- spec/validators/date_time_validator_spec.rb
closes #3849
Improve date time validation.
Local
> Adds datetime validator and uses for iso8601 report.

- Gemfile.lock
> Updated cocina models.

- spec/services/cocina/mapping/descriptive/mods/subject_geographic_spec.rb
Implementation ticket #3863 
Update mapping to match type validation
> Add mapping for hierarchical geographic subject with type change

- app/services/cocina/from_fedora/descriptive/subject.rb
- app/services/cocina/to_fedora/descriptive/subject.rb
- spec/services/cocina/mapping/descriptive/mods/subject_geographic_spec.rb
> Fix subject geographic mapping.

- spec/services/cocina/mapping/descriptive/mods/subject_name_spec.rb
> Enabled subject name mapping specs.

- bin/reports/report-content-dark-rights-publish-shelve
- lib/report.rb
The existing report missed some problematic objects.
Local
> Tweaks dark rights report to handle missing rights DS and whitespace.

- bin/reports/report-desc-validation
Allow testing cocina validation changes.
sdr-deploy
> Adds report for invalid desc types.

- Gemfile.lock
> Update cocina models.

- bin/validate-cocina
Allow testing cocina models changes.
QA
> Adds script for validating cocina models changes.

- bin/reports/report-identity-valid-catkey
> Create a report for valid-catkeys

- lib/fedora_migrator.rb
Fixes #3882 - log missing druids during migration
It was not
> log missing druids during migration

- app/services/cocina/to_fedora/descriptive/contributor_writer.rb
- app/services/cocina/to_fedora/descriptive/name_title_group.rb
- app/services/cocina/to_fedora/descriptive/title.rb
closes #3868
Remove redundant code.
> Use NameTitleGroupBuilder methods.

- .rubocop_todo.yml
- app/controllers/marcxml_controller.rb
- app/services/marc_service.rb
- app/services/mods_service.rb
- spec/services/mods_service_spec.rb
Consistency with other similar services.
> Refactor marcxml

- spec/requests/update_metadata_spec.rb
This explains what about the data is wrong
> Update description of a spec context

- spec/models/object_version_spec.rb
- spec/requests/versions_spec.rb
I corrected these typos on two separate PRs that got closed without merging.
> fix some typos I discovered on the way to something else

- spec/requests/create_object_spec.rb
This now tests that the json response is correct.
> Improve test for create conflict

- spec/dor/goobi_spec.rb
This test will fail when the catkey validations in cocina-models are released
> Use valid catkeys in test

- Gemfile
> Remove obsolete description of gem

- spec/services/cocina/mapping/descriptive/mods/title_info_spec.rb
Roundtrip validation review showed data loss for this pattern
> Add spec for uniform title with parallel corporate author

- app/controllers/objects_controller.rb
- spec/requests/start_accession_spec.rb
> Log events when accessioning happens

- .rubocop.yml
- lib/fedora_cache.rb
rubocop elected Macron as president of France for 5 more years.  Beats the alternative.
> appease rubocop masters

- app/models/object_version.rb
- app/services/cocina_object_store.rb
- app/services/version_service.rb
- db/migrate/20220422143440_require_object_versions.rb
- db/structure.sql
- spec/models/object_version_spec.rb
- spec/services/delete_service_spec.rb
- spec/services/version_migration_service_spec.rb
- spec/services/version_service_spec.rb
closes #3905
Enforce cleaner data.
> Add db not null constraints for tag and description fields for object version

- app/services/constituent_service.rb
- app/services/embargo_release_service.rb
- spec/services/constituent_service_spec.rb
- spec/services/embargo_release_service_spec.rb
Significance/description are now required to open a version.
Unit
> Missing version open params

- app/controllers/objects_controller.rb
- app/controllers/versions_controller.rb
- app/services/constituent_service.rb
- app/services/embargo_release_service.rb
- app/services/version_service.rb
- spec/requests/start_accession_spec.rb
- spec/requests/versions_spec.rb
- spec/services/constituent_service_spec.rb
- spec/services/embargo_release_service_spec.rb
- spec/services/version_service_spec.rb
Consistency with the rest of the code base.
Unit
> Refactor version service

- app/controllers/objects_controller.rb
incorrect documentation costs lives.
> objects_controller.accession: adjust yarddoc about params

- app/services/thumbnail_service.rb
- spec/services/thumbnail_service_spec.rb
> Prevent a nil pointer error when hasMimeType is nil

- app/models/dor/update_marc_record_service.rb
- spec/dor/update_marc_record_service_spec.rb
* Clean-up existing spec.
* Handle parallel titles so that release to SearchWorks works correctly.
**Note that this PR contains 2 commits: The first is to clean the existing spec. The second is the change for this ticket. It might be helpful to look at them separately.**
Unit
> Fix 856 generation for parallel title.

- app/services/cocina_object_store.rb
- spec/services/cocina_object_store_spec.rb
Changes could be saved to Fedora even when there is a stale lock.
Unit
> Switch save order (PG before Fedora) in cocina object store.

- Gemfile
- Gemfile.lock
Keep pace with cocina-models changes
CI + will be integration tested in QA
> Bump cocina-models to 0.77.0

- bin/validate-cocina
Faster validation
In stage, cut validation from 18m to 4m.
stage
> Parallelize bin/validate-cocina.

- bin/validate-cocina
Keeping the results file open for hours was resulting in dupe entries (I think).
sdr-deploy
> Validate cocina tweaks

- README.md
> Remove obsolete documentation about seeding the database

- Gemfile
- Gemfile.lock
> Updated cocina model.

- openapi.yml
> Remove Dor::Item reference from the openapi documentation

- spec/requests/metadata_spec.rb
> Remove Dor::Item reference

- config/deploy/migrate.rb
closes #3925
This environment is no longer necessary.
> Removed migrate environment deploy config.

- app/controllers/objects_controller.rb
- spec/jobs/unpublish_job_spec.rb
- spec/requests/preserve_spec.rb
- spec/requests/publish_object_spec.rb
- spec/requests/unpublish_object_spec.rb
Fixes #3981, #3985, #3986
This commit removes references to Fedora-isms from a few specs.
CI
> Defedorize specs

- spec/requests/mods_update_spec.rb
> Remove unnecessary Dor::Item from mods_update_spec

- db/migrate/20220509120943_change_object_version_description.rb
closes #4001
Per Andrew, this makes more sense to users.
QA
> Update object version description to use version instead of tag.

- spec/jobs/publish_job_spec.rb
- spec/jobs/shelve_job_spec.rb
- spec/services/sdr_ingest_service_spec.rb
This doesn't do anything since the code under test doesn't call this metho.
ci
> Remove unnecessary code stub

- spec/requests/create_object_spec.rb
- spec/requests/create_workspaces_spec.rb
> Remove unnecessary stub

- spec/requests/update_metadata_spec.rb
> Remove cruft

- app/services/solr_connection_error.rb
> Remove SolrConnectionError.

- .rubocop_todo.yml
- app/jobs/preserve_job.rb
- app/services/preservation_ingest_service.rb
- spec/jobs/preserve_job_spec.rb
- spec/services/preservation_ingest_service_spec.rb
- spec/services/preserve/bag_verifier_spec.rb
Everything is SDR. But especially the SDR API. And not particularly Preservation.
> Renamed SdrIngestService.

- .circleci/config.yml
Unblocks https://github.com/sul-dlss/dor-services-app/issues/4036
> Begin testing on Ruby 3

- .rubocop.yml
- app/services/cocina/to_xml/access_generator.rb
- app/services/cocina/to_xml/content_metadata_generator.rb
- app/services/cocina/to_xml/content_type.rb
- app/services/cocina/to_xml/rights/file_level.rb
- app/services/cocina/to_xml/rights/object_level.rb
- app/services/goobi_service.rb
- app/services/preservation_metadata_extractor.rb
- app/services/publish/public_xml_service.rb
- app/services/publish/rights_metadata.rb
- app/services/shelving_service.rb
- spec/services/cocina/to_xml/access_generator_spec.rb
- spec/services/cocina/to_xml/content_metadata_generator_spec.rb
- spec/services/shelving_service_spec.rb
> [refactor] Rename the ToFedora module to ToXml

- app/controllers/administrative_tags_controller.rb
- spec/requests/administrative_tags_spec.rb
Otherwise the tags don't show in Argo.
test suite
> Trigger a reindex after tags are changed

- app/validators/date_time_validator.rb
This is simpler to understand.
test suite
> Simplify minute and second pattern

- Gemfile
- Gemfile.lock
- app/reports/bad_iso8601_date.rb
- spec/spec_helper.rb
> Add a report for invalid ISO8601 dates

- app/controllers/workspaces_controller.rb
- app/services/reset_workspace_service.rb
- spec/requests/reset_workspace_spec.rb
- spec/services/reset_workspace_service_spec.rb
Fixes https://github.com/sul-dlss/common-accessioning/issues/907
also
Fixes sul-dlss/common-accessioning/issues/321
no
no
> Remove the export directory when doing the workspace reset

- app/services/publish/public_xml_service.rb
So that we can understand why this data is important.
🤷
> Document the use of barcode and sourceId

- app/services/create_object_service.rb
This makes it possible to register items with a pre-assigned druid.  This is helpful if we have items from production we want to copy into another environment
ci
> Allow minter to be a passed in dependency

- app/services/ur_admin_policy_factory.rb
- db/structure.sql
Fixes #4108 for bootstrapping tests that is flaky.
> Fix factory bootstrapping bug for testing

- Dockerfile
The code that this documentation referred to no longer exists
n/a
> Remove obsolete documentation

- docker-compose.yml
We don't use Fedora any longer.
locally
> Remove fedora from the docker-compose.yml

- Gemfile
- Gemfile.lock
> Bump cocina-models to 0.82.0

- app/services/synchronous_indexer.rb
Connects to https://github.com/sul-dlss/dor_indexing_app/issues/840
We don't use ActiveMQ anymore.
> Update code comment to better reflect current architecture

- app/reports/bad_edtf_dates.rb
- app/reports/bad_w3cdtf_dates.rb
More accurate and more complete reports.
Confirmed on prod this is the right fix by tweaking & re-running the report until I got the expected results.
> Improve W3CDTF and EDTF reports

- app/reports/bad_date_range_encodings.rb
- app/reports/bad_edtf_date_encodings.rb
Fixes #4130 - new report for reporting on edtf dates without encoding set
QA/stage (though it didn't report any problems there...)
> new report for reporting on edtf dates without encoding

- app/reports/contributor_identifiers.rb
- db/structure.sql
- docker-compose.yml
> Add a report for contributor identifiers

- lib/tasks/missing_druids.rake
A small PR to improve the cron email output to be more useful.
> Include the druid list in missing druid email

- app/reports/edtf_lower_x_dates.rb
- app/reports/edtf_upper_x_dates.rb
Part of #4143, this is the code for the requested reports:  edtf dates that have lower case x  and another report for upper case X.
> reports for edtf dates with x or X

- .rubocop.yml
- app/reports/bad_date_range_encodings.rb
- app/reports/bad_edtf_dates.rb
- app/reports/bad_iso8601_dates.rb
- app/reports/bad_w3cdtf_dates.rb
- app/reports/contributor_identifiers.rb
- app/reports/edtf_lower_x_dates.rb
- app/reports/edtf_upper_x_dates.rb
- app/reports/invalid_name_uris.rb
- app/reports/unstructured_display_names.rb
> Report for invalid name uris

- app/reports/invalid_name_uris.rb
I believe this will make the report more general purpose for copying as a new report or a report engine for self-service queries.
> Convert report to run almost entirely in SQL

- app/reports/invalid_language_uris.rb
Fixes #4151 
Report generated: https://gist.github.com/jcoyne/4cb91a08d66693eab2c725138d922b78
> Add a report for invalid language URIs

- app/reports/invalid_location_uris.rb
Fixes #4152
report here https://gist.github.com/jcoyne/c671e5223885cd9fcb702be7ff313cf2
> Add a report for invalid location uris

- app/reports/invalid_location_uris.rb
Per Arcadia's request for more data.
> Add sibling elements to the report for invalid location uris

- .rubocop.yml
- app/reports/invalid_language_uris.rb
- app/reports/invalid_name_uris.rb
- app/services/reset_workspace_service.rb
- spec/requests/administrative_tags_spec.rb
- spec/requests/create_collection_spec.rb
- spec/requests/create_object_spec.rb
- spec/requests/create_workspaces_spec.rb
- spec/requests/destroy_spec.rb
- spec/requests/get_marcxml_spec.rb
- spec/requests/notify_goobi_spec.rb
- spec/requests/preserve_spec.rb
- spec/requests/publish_object_spec.rb
- spec/requests/unpublish_object_spec.rb
- spec/requests/update_marc_record_spec.rb
- spec/requests/update_metadata_spec.rb
- spec/requests/versions_inventory_spec.rb
- spec/requests/versions_spec.rb
- spec/services/goobi_service_spec.rb
Keep up with Rubocop.
Also, remove the extra SQL squishes in the reports.
CI
> Add new Rubocop rules and run auto-correct

- Gemfile
- Gemfile.lock
> Remove unused dependency

- Gemfile
- Gemfile.lock
> Remove unused dor-rights-auth gem

- Gemfile
- Gemfile.lock
- app/controllers/objects_controller.rb
This code is not necessary. 
CI
> Remove dead code and unused gems

- app/services/version_service.rb
Document some information revealed in https://github.com/sul-dlss/preservation_catalog/issues/1921
> Add some documentation about the preservationAuditWF

- app/services/version_service.rb
use an implicit return an provide comments about how this works
ci
> Refactor active_assembly_workflow?

- app/models/symphony_reader.rb
> Remove extraneous conditional

- app/services/version_service.rb
- spec/services/version_service_spec.rb
Remove deprecated parameter.
Unit
> Updated version service for workflow client changes.

- app/reports/invalid_form_uris.rb
- app/reports/invalid_role_uris.rb
Report code for #4178 and #4180
I ran both reports on stage and qa and didn't trap anything.  I changed a record on stage to be trapped for the invalid role uri;  the report worked.
> add 2 reports for invalid uris

- app/reports/unusual_language_source_uris.rb
Fixes #4179 - report on unusual languauge source URIs
Tested on stage and verified an object it found matches the requested query
> add report for unusual language source URIs

- Gemfile
- Gemfile.lock
So we actually are on a released version of HB.
Test suite
> Get back on a released version of honeybadger

- app/controllers/objects_controller.rb
- app/jobs/update_doi_metadata_job.rb
- app/services/cocina/serializer.rb
- config/initializers/custom_serializers.rb
- spec/jobs/update_doi_metadata_job_spec.rb
- spec/services/cocina/serializer_spec.rb
When we built this originally we were on Rails 5.2 which did not have this capability
CI
> Use the serializing capability that is now built into Rails

- app/reports/invalid_role_uris.rb
> Update report for invalid roles

- app/controllers/members_controller.rb
- app/jobs/publish_items_modified_job.rb
- app/services/member_service.rb
- app/services/update_object_service.rb
- spec/jobs/publish_items_modified_job_spec.rb
- spec/requests/update_metadata_spec.rb
- spec/services/update_object_service_spec.rb
> When a collection title is updated, reindex the members

- Gemfile.lock
Temporarily turn off problematic date validation
> Update cocina models to 0.84.1

- Gemfile.lock
Allow dates with single digits
> Update to latest cocina-models

- app/services/cocina/to_datacite/creator_contributor_funder.rb
- spec/services/cocina/mapping/descriptive/h2_datacite/contributor_h2_datacite_spec.rb
Datacite wants only unique contributors to be listed.
Fixes #4203 
CI
> Deduplicate datacite creators

- app/reports/invalid_form_source_codes.rb
Report on invalid form source codes
Fixes #4189
Also:
* Add comment to report about preferring strict JSON querying
> Report on invalid form source codes

- app/reports/invalid_subject_source_codes.rb
Multiple choice (check all that apply):
> report added: invalid_subject_source_codes

- Gemfile.lock
Relax validation on EDTF dates
CI
> Update to the latest cocina-models

- app/reports/invalid_subject_source_codes.rb
Fixes #4214 (which Arcadia already closed)
> report invalid_subject_source_codes adjustments

- app/reports/invalid_edtf_dates.rb
- app/reports/invalid_edtf_structured_dates.rb
Fixes #4218  - hopefully finding all remaining problem children for edtf dates.  But perhaps not.
I ran the report successfully on sdr-infra.
> new report: edtf problem dates; more or less in general, and when structuredValue

- app/reports/subjects_with_double_dash.rb
Fixes #4228
Ran the report and got data
> Report for subjects with a double dash

- app/reports/events_multiple_date_types.rb
Fixes #4229
Stepped through code in rails console and ultimately ran the report.
> add report events_multiple_date_types.rb

- app/reports/invalid_subject_non_source_uris.rb
Fixes #4230
CI, ran report on sdr-infra
> Add report for invalid subject (non-source) URIs

- app/reports/subjects_with_double_dash.rb
Fixes #4237
Ran it and spot checked a few results.
> report subjects_with_double_dash narrows to 2 source codes

- Gemfile
- Gemfile.lock
- openapi.yml
Reverts sul-dlss/dor-services-app#4248
need to revert due to data with EMPTY parallelContributor properties.
> Revert "update to cocina-models 0.85.0; update openapi.yml to remove parallelContributor"

- app/reports/property_contains_property_collections.rb
- app/reports/property_contains_property_dros.rb
- To create a general tool that can be used by devs or @arcadiafalcone for this purpose.
- For #4242
> add reports property_contains_property for dros, collections

- app/reports/property_existence_collections.rb
- app/reports/property_existence_dros.rb
This was a confusing point for me and for Mike, so comment worthy.
> report property_existence... gets another comment

- app/reports/property_contains_property_collections.rb
- app/reports/property_contains_property_dros.rb
- app/reports/property_existence_collections.rb
- app/reports/property_existence_dros.rb
To make it easier for Arcadia to use these reports
> tweak generic property reports to make them easier to adapt

- .rubocop.yml
- app/controllers/application_controller.rb
- app/services/marc_service.rb
- config/initializers/okcomputer.rb
- spec/jobs/update_doi_metadata_job_spec.rb
- spec/models/collection_spec.rb
- spec/models/dro_spec.rb
- spec/models/symphony_reader_spec.rb
- spec/services/create_object_service_spec.rb
- spec/services/digital_stacks_service_spec.rb
- spec/services/publish/metadata_transfer_service_spec.rb
- spec/services/publish/public_desc_metadata_service_spec.rb
- spec/services/update_object_service_spec.rb
mumble mumble common code style mumbe mumble
> add new rubocops and concomittant tweaks to code

- .rubocop.yml
- app/controllers/events_controller.rb
- app/controllers/objects_controller.rb
- spec/jobs/create_event_job_spec.rb
- spec/jobs/create_virtual_objects_job_spec.rb
- spec/jobs/log_failure_job_spec.rb
- spec/jobs/log_success_job_spec.rb
- spec/jobs/preserve_job_spec.rb
- spec/jobs/publish_items_modified_job_spec.rb
- spec/jobs/publish_job_spec.rb
- spec/jobs/shelve_job_spec.rb
- spec/jobs/start_preservation_workflow_job_spec.rb
- spec/jobs/unpublish_job_spec.rb
- spec/jobs/update_doi_metadata_job_spec.rb
- spec/models/object_version_spec.rb
- spec/models/tag_label_spec.rb
- spec/routing/versions_controller_spec.rb
- spec/services/ur_admin_policy_factory_spec.rb
> Adds new rubocops.

- app/controllers/workspaces_controller.rb
- app/jobs/cleanup_job.rb
- app/services/cleanup_service.rb
- spec/jobs/cleanup_job_spec.rb
- spec/requests/cleanup_workspace_spec.rb
- spec/services/cleanup_service_spec.rb
refs https://github.com/sul-dlss/argo/issues/2752
Avoid timeouts
Unit
> Change workspace cleanup to async.

- app/services/shelvable_files_stager.rb
- spec/fixtures/content_diff_reports/ng782rw8378-v3-v4.xml
- spec/services/digital_stacks_service_spec.rb
- spec/services/shelvable_files_stager_spec.rb
refs https://github.com/sul-dlss/dor-services-app/issues/4256
> Support hierarchical file structures for shelving.

- app/validators/cocina/file_hierarchy_validator.rb
- spec/validators/cocina/file_hierarchy_validator_spec.rb
> Handle validating items with no structural.

- app/reports/catalog_links_previous_symphony.rb
Closes #4309, which requested this report.
The report ran and had seemingly correct data.
> add report for 'previous symphony' catalogLinks

- config/schedule.rb
> Fix bugs in whenever schedule

- .rubocop.yml
- config/environments/production.rb
- spec/jobs/publish_job_spec.rb
- spec/jobs/shelve_job_spec.rb
> add new cops

- spec/jobs/publish_job_spec.rb
- spec/jobs/shelve_job_spec.rb
better clarity is good, right?
Connects to #4366
effectively, a comment in 2 specs.
> improve skipped specs reason

- Gemfile
- Gemfile.lock
- openapi.yml
- spec/services/cocina/mapping/descriptive/h2_datacite/identifiers_h2_datacite_spec.rb
- spec/services/cocina/mapping/descriptive/h2_datacite/note_h2_datacite_spec.rb
- spec/services/cocina/mapping/descriptive/h2_datacite/related_resource_h2_datacite_spec.rb
- spec/services/cocina/mapping/descriptive/h2_datacite/subject_h2_datacite_spec.rb
- spec/services/refresh_metadata_action_spec.rb
To keep pace with cocina-models changes in support of the Folio migration.
CI + will be tested in QA
> Update cocina-models to 0.87.0 (for Folio record ID support)

- app/reports/apo_catkey.rb
Fixes #4373 - add a new report to lookup catkeys a given APO
Ran in qa first and then in prod.  Results attached to ticket.
> add new report for looking up catkeys by apo

- app/services/create_object_service.rb
> rename method to remove reference to symphony

- README.md
- app/services/migrators/base.rb
- app/services/migrators/test.rb
- bin/migrate-cocina
- bin/validate-cocina
- spec/services/migrators/test_spec.rb
refs #4349
Provide framework for performing cocina data migrations.
sdr-infra
> Adds support for performing cocina migrations.

- app/services/migrators/add_lane_hrid.rb
- bin/migrate-cocina
- spec/services/migrators/add_lane_hrid_spec.rb
refs #4388
See ticket for context.
Unit, QA
> Adds migrator for adding lane HRID.

- openapi.yml
Lean on the API spec, Committee, and existing schemas to get automatic validation of Folio IDs at the API layer.
CI
> Validate Folio IDs in API more strictly

- Gemfile
- Gemfile.lock
- openapi.yml
- spec/requests/create_object_spec.rb
- spec/requests/update_metadata_spec.rb
Keep pace with cocina-models releases
Will be tested as part of cocina-models rollout
> Bump to cocina-models 0.89.0 release and API spec

- app/services/catalog/marc_856_generator.rb
- app/services/catalog/symphony_writer.rb
- spec/services/catalog/marc856_generator_spec.rb
- spec/services/catalog/symphony_writer_spec.rb
> Refactor 856 marc serialization into hash

- config/settings.yml
> Remove legacy config

- app/services/catalog/add_folio_catalog_links_service.rb
- spec/services/catalog/add_folio_catalog_links_service_spec.rb
closes #4435
Get syncing correct.
Unit
> Adjusts syncing of Lane records.

- app/services/catalog/marc_856_generator.rb
This was the last little bit to make this service class just like our other service classes.
Unit
> Made Marc856Generator more idiomatic.

- app/services/release_tags.rb
I believe this is clearer about what is happening in the transformation
ci
> [refactor] tags_for_what_value

- app/services/release_tags.rb
- spec/services/release_tags_spec.rb
This was never implemented in the UI and has been broken since we switched to Cocina
CI
> Remove unused applicable tag feature

- app/services/release_tags.rb
- spec/services/release_tags_spec.rb
Avoid Hash based programming. Cocina models give us better type checking.
CI
> Use the cocina models for working with release tags

- app/services/release_tags.rb
- spec/services/release_tags_spec.rb
So it's easier to understand what methods are depended on outside of the class.
> Make private methods private

- app/services/cocina_object_store.rb
So we can see which lookup is failing.
CI
> Display a helpful debug message on error

- app/services/release_tags.rb
Unnecessary conditionals are challenging to understand
CI
> refactor combine_two_release_tag_hashes to remove conditionals

- app/services/catalog/folio_writer.rb
- spec/services/catalog/folio_writer_spec.rb
Fixes https://github.com/sul-dlss/dor-services-app/issues/4454
If multiple Folio edits are requested serially, at least two different exceptions may be raised:
* a Faraday timeout
* a StandardError emitted from FolioClient
This is documented in the FolioClient gem: https://github.com/sul-dlss/folio_client/blob/181ee68c8879030734f5ad6a639904145c4ffc06/lib/folio_client/records_editor.rb#L19-L24
Both of these may be safely retried a small number of times, and both conditions go away within seconds. I can be convinced that we ought to transparently handle this in the gem, but I'm not sure we'll be encountered this outside the DSA FolioWriter so maybe this is a fine location for now.
> [HOLD] Retry Folio edit operations a few times 

- spec/services/catalog/folio_writer_spec.rb
For peace of mind this is just making the unrelease a bit more explicit.
Refs #4453
Unit tests.
> Explicit unrelease

- README.md
I stumbled on text that made me scratch my head, so I tried to make it better.
> README:  tweak confusing text in migrations section

- .rubocop.yml
- app/services/migrators/invalid_lane_catkey.rb
- spec/requests/apply_admin_policy_defaults_spec.rb
- spec/requests/background_job_results_spec.rb
- spec/requests/batch_create_virtual_objects_spec.rb
- spec/requests/collections_for_object_spec.rb
- spec/requests/create_object_spec.rb
- spec/requests/events_spec.rb
- spec/requests/get_marcxml_folio_spec.rb
- spec/requests/get_marcxml_symphony_spec.rb
- spec/requests/members_for_collection_spec.rb
- spec/requests/metadata_refresh_spec.rb
- spec/requests/publish_object_spec.rb
- spec/requests/shelving_spec.rb
- spec/requests/show_object_spec.rb
to silence those annoying warnings.
> rubocop: add new cops

- bin/migrate-cocina
I should have caught this earlier when i changed the filename
> correct comment in bin/migrate-cocina

- Gemfile
- Gemfile.lock
- app/controllers/objects_controller.rb
- app/jobs/update_doi_metadata_job.rb
- spec/jobs/update_doi_metadata_job_spec.rb
> Upgrade to Sidekiq7

- app/services/goobi_service.rb
- spec/services/goobi_service_spec.rb
Connects to sul-dlss/common-accessioning#1043
This commit will give us more information about the conditions when this error happens.
CI
> Notify Honeybadger when Goobi service will return the default workflow name

- .circleci/config.yml
- .rubocop.yml
- Dockerfile
- Gemfile.lock
- README.md
- bin/generate-druid-list
To keep pace with Ruby releases.
CI (and will be integration-tested in QA and stage)
> Upgrade to Ruby 3.2.2

- app/reports/version_list.rb
Fixes #4509 - Add a report for exporting all version info metadata to CSV file
By running this branch on sdr-infra
> add report for all versions

- Gemfile
- Gemfile.lock
- app/jobs/update_orcid_work_job.rb
- app/models/orcid_work.rb
- config/settings.yml
- db/migrate/20230716202954_create_orcid_works.rb
- db/structure.sql
- spec/jobs/update_orcid_work_job_spec.rb
> Adds create/update orcid work job.

- app/jobs/update_orcid_work_job.rb
- spec/jobs/update_orcid_work_job_spec.rb
> Delete orcid works when contributor removed.

- app/controllers/metadata_refresh_controller.rb
- app/services/create_object_service.rb
to make code clearer for post-symphony hires
comments only
> adding comments pertaining to folio cutover

- config/settings.yml
- spec/requests/create_collection_spec.rb
- spec/requests/create_object_spec.rb
- spec/requests/get_marcxml_folio_spec.rb
- spec/requests/get_marcxml_symphony_spec.rb
- spec/requests/metadata_refresh_spec.rb
- spec/services/catalog/update_marc_856_record_service_spec.rb
- spec/services/create_object_service_spec.rb
- spec/services/refresh_description_from_catalog_spec.rb
> folio settings now on

- README.md
refs https://github.com/sul-dlss/argo/issues/4059
> Adds reset instructions

- app/services/catalog/folio_writer.rb
- spec/services/catalog/folio_writer_spec.rb
closes #4579
Since previous records were not necessarily migrated, they may be missing.
Unit, Andrew
> Allow a previous folio hrid record to be missing.

- app/services/registration_csv_converter.rb
- lib/tasks/seed.rake
- spec/services/registration_csv_converter_spec.rb
Fixes #4581 
Note that `RegistrationCsvConverter` is largely a direct copy out of Argo for use here (and it's test). 
> Add rake task to register with known druids

- Gemfile
- Gemfile.lock
- spec/requests/create_object_spec.rb
- spec/requests/start_accession_spec.rb
- spec/requests/update_metadata_spec.rb
- spec/requests/versions_spec.rb
> Update cocina models

- app/services/cocina_object_store.rb
- spec/services/cocina_object_store_spec.rb
Avoid a test ordering problem in Argo
> Bootstrap ur admin policy for find.

- app/services/goobi_service.rb
- spec/services/goobi_service_spec.rb
> Update goobi-service post folio cutover

- app/services/publish/public_desc_metadata_service.rb
- spec/services/publish/public_desc_metadata_service_spec.rb
Fixes sul-dlss/happy-heron#3380
CI
> Work around libxml2 bug causing CR characters to be escaped

- bin/validate-cocina
The script wasn't working correctly.
sdr-infra
> Fix flattening in bin/validate-cocina

- app/reports/property_events_with_display_label.rb
> Enhance events with display label report.

- solr_conf/conf/schema.xml
- solr_conf/conf/solrconfig.xml
To avoid problems when running SDR apps against the Solr docker container defined here.
> Solr config files updated to match production Argo

- config/initializers/okcomputer.rb
Detect when a queue is dropped.
QA
> Adds OK Computer check for rabbit queues.

- solr_conf/conf/solrconfig.xml
Fixing a gaff with searchable tags field name.
> use correct field for searchable tags solrconfig.xml

- app/models/dro.rb
- app/services/embargo_release_service.rb
- spec/factories/dros.rb
- spec/services/embargo_release_service_spec.rb
> Determine embargo release from db not solr.

- app/services/delete_service.rb
> Delete crufty comment in delete service.

- solr_conf/conf/solrconfig.xml
To align the solr in this repo with the configurations in our Solr Cloud.
It wasn't, but the sul-solr-config changes were tested in prod.
> update solrconfig.xml to match sul-solr-configs

- config/settings.yml
> Remove unused settings.

- app/models/dro.rb
- app/services/publish/public_desc_metadata_service.rb
- app/services/published_relationships_filter.rb
- app/services/virtual_object.rb
- db/migrate/20240108161425_add_virtual_object_index_to_dros.rb
- db/structure.sql
- spec/services/publish/public_desc_metadata_service_spec.rb
> Get virtual objects from db instead of Solr

- Gemfile
- Gemfile.lock
- bin/rolling_index
- config/deploy.rb
- config/deploy/prod.rb
- config/deploy/qa.rb
- config/deploy/stage.rb
- config/settings.yml
Better indexer performance since removes API calls to DSA.
QA
> Adds rolling indexer

- Gemfile
- Gemfile.lock
> Update cocina models and dor indexing gems.

- Gemfile
- Gemfile.lock
New cocina-models release 0.95.0
> Update cocina-models and dor_indexing

- app/reports/geo_map_coordinates.rb
Fixes #4702 - write a report to look for scanned maps to remediate
Tested on sdr-infra on production database.  Output attached to ticket.
> add new report for scanned map remediation

- solr_conf/conf/schema.xml
- solr_conf/conf/solrconfig.xml
~~Hold for coordination with sul-dlss/argo/pull/4317~~
keeping it all in sync.  whee!
part of sul-dlss/dor_indexing_app/issues/1075
(same changes were made to argo_stage and argo_qa and integration tests were run, now that indexing is complete.
> update solr config files for new argo title fields

- Gemfile.lock
Bump to cocina models latest patch release. 
> Updating cocina-models to 0.95.1

- db/structure.sql
This should have been in #4672
> Provide the schema change for virtual object membership

- db/migrate/20240322161526_change_object_version_tag_null.rb
- db/structure.sql
> Allow the object_versions tag field to be null

- app/controllers/release_tags_controller.rb
- app/services/publish/public_cocina_service.rb
- app/services/release_tags.rb
- config/routes.rb
- openapi.yml
- spec/requests/release_tags_spec.rb
- spec/services/release_tags_spec.rb
> Add an API for release tags

- app/models/release_tag.rb
- db/migrate/20240320203110_create_release_tags.rb
- db/structure.sql
- spec/factories/release_tags.rb
- spec/models/release_tag_spec.rb
> Create a active_record model for release tags

- app/services/release_tags.rb
> Fix typo in release_tags.rb

- app/models/release_tag.rb
- app/services/release_tags.rb
- spec/factories/release_tags.rb
- spec/models/release_tag_spec.rb
- spec/services/release_tags_spec.rb
> Create release tag if release tags already exist

- Gemfile
- Gemfile.lock
it is not used in this project
> Remove stanford-mods dependency

- app/services/migrate_release_tags.rb
> Migrate release tags

- app/services/version_service.rb
Prevent calling to_sym on a potentially nil value
> Allow significance to be optional

- spec/services/publish/public_xml_service_spec.rb
> Add test that shows PURL sitemap release works

- app/services/workflow_state_service.rb
- spec/services/workflow_state_service_spec.rb
> Invoke workflow client with correct args.

- Gemfile.lock
Fixes bug in indexing release tags based on collection(s)
> Update dependencies to pick up dor_indexing update

- app/controllers/objects_controller.rb
- app/controllers/versions_controller.rb
- app/services/constituent_service.rb
- app/services/version_service.rb
- app/services/workflow_state_service.rb
- bin/migrate-cocina
- spec/requests/start_accession_spec.rb
- spec/requests/versions_spec.rb
- spec/services/constituent_service_spec.rb
- spec/services/version_service_spec.rb
- spec/services/workflow_state_service_spec.rb
The definition of open in the Version Service isn't complete.
Unit
> Adds open? to workflow state service.

- app/models/repository_object.rb
- app/models/repository_object_version.rb
- db/migrate/20240328141842_create_repository_objects.rb
- db/migrate/20240328142339_create_repository_object_versions.rb
- db/migrate/20240328142859_add_version_refs_to_repository_objects.rb
- db/migrate/20240328144814_add_unique_version_constraint.rb
- db/structure.sql
- spec/factories/repository_object_versions.rb
- spec/factories/repository_objects.rb
- spec/models/repository_object_spec.rb
- spec/models/repository_object_version_spec.rb
> Add RepositoryObject and RepositoryObjectVersion models

- app/models/repository_object.rb
> Add scopes to RepositoryObject for different object types

- app/models/repository_object.rb
- db/migrate/20240408184127_rename_version_columns.rb
- db/structure.sql
- spec/models/repository_object_spec.rb
- spec/models/repository_object_version_spec.rb
> Give pointers to versions more descriptive names

- app/services/workflow_state_service.rb
> Remove unknown workflow etdAssemblyWF

- app/models/admin_policy.rb
- app/models/collection.rb
- app/models/dro.rb
- spec/models/admin_policy_spec.rb
- spec/models/collection_spec.rb
- spec/models/dro_spec.rb
- spec/requests/create_object_spec.rb
> Remove unused code

- app/services/cocina_object_store.rb
- config/settings.yml
- spec/services/cocina_object_store_spec.rb
> Implement CocinaObjectStore#exists? with RepositoryObject model

- app/services/version_service.rb
- spec/services/version_service_spec.rb
> Call RepositoryObject#close_version! in VersionService.close

- app/models/repository_object_version.rb
- spec/models/repository_object_version_spec.rb
> Update repository object source_id on head version update

- app/controllers/administrative_tags_controller.rb
> Add documentation context

- app/services/workflow_state_service.rb
- spec/services/workflow_state_service_spec.rb
closes #4820
The existing logic didn't correctly determine if a version workflow was active.
Unit, QA, integration test
> Fix WorkflowStateService.open?

- app/services/cocina_object_store.rb
- config/settings.yml
- spec/services/cocina_object_store_spec.rb
> Query RepositoryObject in CocinaObjectStore version method

- app/models/repository_object.rb
> Added comments to RepositoryObject.

- app/services/cocina_object_store.rb
- app/services/delete_service.rb
- spec/services/cocina_object_store_spec.rb
- spec/services/delete_service_spec.rb
> [Refactor] Move RepositoryObject destruction to DeleteService

- app/models/repository_object_version.rb
- spec/factories/repository_object_versions.rb
- spec/models/repository_object_version_spec.rb
> Add to_cocina, to_cocina_with_metadata, and to_h to RepositoryObjectVersion

- app/services/migrators/remove_release_tags.rb
- spec/services/migrators/remove_release_tags_spec.rb
> Add migrator to remove release tags from cocina objects

- app/services/version_service.rb
- spec/services/version_service_spec.rb
> Open RepositoryObject in VersionService.open

- app/services/cocina_object_store.rb
- config/settings.yml
- spec/services/cocina_object_store_spec.rb
To document feature flags and align with the feature flags spec.
Unit
> Align feature flags with feature flags spec.

- app/graphql/types/query_type.rb
- app/models/repository_object_version.rb
- spec/requests/graphql_spec.rb
> Query RepositoryObjects for GraphQL endpoint

- app/services/cocina_object_store.rb
- spec/services/cocina_object_store_spec.rb
> Find objects persisted as RepositoryObjects

- app/reports/latest_release_tags.rb
> Adds release tags report.

- app/services/cocina_object_store.rb
- spec/services/cocina_object_store_spec.rb
> Add repository_object_test feature to CocinaObjectStore#find and #find_by_source_id

- config/environments/test.rb
> Use :none instead of false to address action_dispatch deprecation

- .rubocop.yml
- lib/tasks/missing_druids.rake
Avoid warnings when running rubocop.
> Add new tasks to rubocop

- app/services/update_object_service.rb
- spec/services/update_object_service_spec.rb
> Update repository object in UpdateObjectService

- app/services/version_service.rb
- spec/requests/versions_spec.rb
- spec/services/version_service_spec.rb
It's helpful to see what is actually persisted here
> Remove stubbing from version service spec

- app/models/repository_object_version.rb
Follows the style-guide https://rubystyle.guide/#case-vs-if-else
> Prefer case/when to multiline if/else

- app/services/cocina_object_store.rb
- app/services/repository_object_migrator.rb
- app/services/update_object_service.rb
- spec/services/repository_object_migrator_spec.rb
- spec/services/update_object_service_spec.rb
> Migrate oppotunistically when doing update

- app/services/constituent_service.rb
closes #4874
Proper versioning flow.
Integration
> Update before closing in constituent service.

- app/models/repository_object_version.rb
- app/services/cocina_object_store.rb
- app/services/version_service.rb
- spec/factories/repository_object_versions.rb
- spec/services/version_service_spec.rb
So that integration tests pass. See individual comments.
Unit, integration.
> Fix repository object test

- app/services/update_object_service.rb
- app/services/version_service.rb
To avoid race conditions that were causing RepositoryObject / legacy object comparisons to fail.
integration
> Adds transactions around RepositoryObject creation.

- spec/services/goobi_service_spec.rb
> Fix rubocop workspace

- app/services/cocina_object_store.rb
- app/services/update_object_service.rb
- app/services/version_service.rb
- spec/services/cocina_object_store_spec.rb
- spec/services/update_object_service_spec.rb
Race conditions were creating false reports of cocina comparison failure.
QA
> Compare cocina on update instead of find.

- bin/audit-repository-migration
> Audit migration

- app/models/repository_object.rb
- app/services/version_service.rb
- spec/models/repository_object_spec.rb
- spec/services/version_service_spec.rb
closes #4901
Version descriptions are supposed to be updated.
Unit
> Update version description when opening and closing.

- app/controllers/versions_controller.rb
- spec/requests/versions_inventory_spec.rb
> Return version content from RepositoryObject if it exists

- app/models/repository_object.rb
- spec/services/version_service_spec.rb
To fix the build and make a model more consistent.
CI
> Fix versioning tests and make repository object internally consistent

- app/services/constituent_service.rb
- app/services/item_query_service.rb
- app/services/workflow_state_service.rb
- spec/services/constituent_service_spec.rb
- spec/services/item_query_service_spec.rb
- spec/services/workflow_state_service_spec.rb
So that virtual objects correctly handle / check versioning state.
closes #4879
QA, Andrew
> Fix virtual objects

- app/controllers/objects_controller.rb
- config/routes.rb
- openapi.yml
- spec/requests/reindex_spec.rb
> Reindexing endpoint

- Gemfile.lock
- db/structure.sql
These should be harmless changes to the lock file(s) related to the new laptops being arm chips instead of intel chips.
> Commit lockfile changes based on new laptop architecture

- app/reports/invalid_edtf_dates.rb
- app/reports/invalid_edtf_structured_dates.rb
- app/reports/invalid_form_source_codes.rb
- app/reports/invalid_form_uris.rb
- app/reports/invalid_iso8601_dates.rb
- app/reports/invalid_language_uris.rb
- app/reports/invalid_location_uris.rb
- app/reports/invalid_name_uris.rb
- app/reports/invalid_role_uris.rb
- app/reports/invalid_subject_non_source_uris.rb
- app/reports/property_existence_dros.rb
- app/reports/property_multiple_events.rb
- app/reports/property_nesting_level_collections.rb
- app/reports/property_nesting_level_dros.rb
- app/reports/unusual_language_source_uris.rb
Fixes #4915 
Fixes #4914
Fixes #4917 
Ran each report on stage without error.
> Update more reports to use RepositoryObject and RepositoryObjectVersion

- app/jobs/reindex_by_druid_job.rb
- lib/tasks/rabbitmq.rake
- spec/jobs/reindex_by_druid_job_spec.rb
> Add reindexing job from rabbitmq messages.

- app/controllers/versions_controller.rb
- app/services/constituent_service.rb
- app/services/repository_object_migrator.rb
- spec/requests/versions_spec.rb
- spec/services/constituent_service_spec.rb
- spec/services/update_object_service_spec.rb
> Replace WorkflowStateService.open? with VersionService.open?

- bin/rolling_index
> Fix rolling indexer to use inline indexing.

- app/models/repository_object_version.rb
- app/models/user_version.rb
- db/migrate/20240429201956_create_user_versions.rb
- db/migrate/20240430144139_add_foreign_key_to_user_version.rb
- db/structure.sql
- spec/factories/user_versions.rb
- spec/models/user_version_spec.rb
> Creates initial UserVersion model validating a closed RepositoryObject

- app/services/shelving_service.rb
closes #4952
Less noisy integration tests.
Integration
> Retries creating workspace content dir in ShelvingService.

- app/controllers/objects_controller.rb
- app/jobs/create_virtual_objects_job.rb
- app/services/constituent_service.rb
- app/services/create_object_service.rb
- app/services/delete_service.rb
- app/services/update_object_service.rb
- app/services/version_service.rb
- db/structure.sql
- spec/jobs/create_virtual_objects_job_spec.rb
- spec/requests/start_accession_spec.rb
- spec/services/constituent_service_spec.rb
- spec/services/delete_service_spec.rb
- spec/services/version_service_spec.rb
It is never used and adds noise.
CI
> Remove the event_factory dependency injection

- app/services/publish/metadata_transfer_service.rb
- app/services/unpublish_service.rb
- config/settings.yml
- spec/services/publish/metadata_transfer_service_spec.rb
- spec/services/unpublish_service_spec.rb
refs #4958
Prepare for adding purl fetcher client.
Unit
> Switch purl fetcher configuration.

- app/services/workflow_state_service.rb
- spec/services/workflow_state_service_spec.rb
Ref sul-dlss/common-accessioning/pull/1180 
note: that  PR does not yet have the logic that will be added to end-accession that will actually kick off ocrWF
Proposal to change how we determine if an object is in accessioning, which is used to determine if it can be opened. This makes the requirement that there are no active steps in accessionWF instead of looking at the lifecycle.  This allows us to skip checking the `end-accession` step, which allows us to start ocrWF and open a version, even if that last step is being executed.  Otherwise we are likely to end up in a race condition, where `end-accession` triggers `ocrWF`, which tries to open the version and is blocked, because `end-accession` may not have yet been marked as complete.  
CI
> change how accessioning? is determined

- app/controllers/versions_controller.rb
- app/services/delete_service.rb
- spec/requests/versions_inventory_spec.rb
- spec/services/delete_service_spec.rb
refs #4940 
Migrate to RepositoryObjects.
> Cleanup RepositoryObject conditional code

- app/services/delete_service.rb
> Add missing ! when finding RepositoryObject in DeleteService.

- app/services/update_object_service.rb
- spec/services/update_object_service_spec.rb
> Cleanup RepositoryObject conditional code in UpdateObjectService.

- Gemfile.lock
- app/services/publish/metadata_transfer_service.rb
- spec/services/publish/metadata_transfer_service_spec.rb
> Use the new release API

- Gemfile.lock
> Update to latest version of purl_fetcher-client

- app/services/version_service.rb
- openapi.yml
- spec/services/version_service_spec.rb
> Update user version on close

- spec/services/publish/dublin_core_service_spec.rb
> Remove unnecessary stubbing

- spec/services/publish/metadata_transfer_service_spec.rb
- spec/services/publish/public_xml_service_spec.rb
> Remove unnecessary test stubs

- app/services/publish/public_desc_metadata_service.rb
> Memoized the value based on the input value to this method

- openapi.yml
> Fix openapi typo.

- app/controllers/versions_controller.rb
- app/models/repository_object.rb
- app/services/user_version_service.rb
- app/services/version_service.rb
- spec/services/version_service_spec.rb
To allow user versioning to work correctly.
Unit, QA
> User version fixes and refactoring.

- app/reports/files_with_no_size.rb
> Create a report for files with no size

- db/migrate/20220307201030_add_unique_source_id_to_dros.rb
- db/migrate/20220307201420_add_unique_source_id_to_collections.rb
closes #5000
Dro / Collection are going away.
CI
> Change migrations to use ActiveRecord::Base to get connections.

- app/services/member_service.rb
- spec/services/member_service_spec.rb
closes #4998
Dro is deprecated.
Unit.
> Changes MemberService to use RepositoryObject.

- app/controllers/members_controller.rb
- spec/requests/members_for_collection_spec.rb
closes #4995
Dro is deprecated.
Unit
> Changes MembersController to use RepositoryObject.

- app/models/repository_object.rb
- app/services/preservation_metadata_extractor.rb
- spec/factories/repository_object_versions.rb
- spec/factories/repository_objects.rb
- spec/models/repository_object_spec.rb
- spec/services/preservation_metadata_extractor_spec.rb
> Use version XML from RepositoryObject model in PreservationMetadataExtractor

- app/models/repository_object.rb
- spec/models/repository_object_spec.rb
> Clear closed_at when creating a new RepositoryObjectVersion.

- app/reports/invalid_edtf_dates.rb
- app/reports/invalid_form_source_codes.rb
- app/reports/invalid_iso8601_dates.rb
- app/reports/invalid_subject_non_source_uris.rb
- app/reports/property_contains_property_collections.rb
- app/reports/property_contains_property_dros.rb
- app/reports/property_events_with_display_label.rb
- app/reports/property_existence_collections.rb
- app/reports/property_nesting_level_collections.rb
- app/reports/property_nesting_level_dros.rb
> Switch subset of reports to new repository models

- app/services/digital_stacks_differ.rb
- app/services/shelving_service.rb
- spec/services/digital_stacks_differ_spec.rb
- spec/services/shelving_service_spec.rb
closes #4982
Less janky.
Unit, integration tests.
> Diff cocina from purl to determine what to shelve.

- app/models/repository_object.rb
- app/models/repository_object_version.rb
- app/services/create_object_service.rb
- app/services/version_service.rb
- db/migrate/20240522142556_add_lock_to_repository_object_versions.rb
- db/structure.sql
- spec/factories/repository_object_versions.rb
- spec/factories/repository_objects.rb
- spec/models/repository_object_spec.rb
- spec/models/repository_object_version_spec.rb
- spec/requests/update_metadata_spec.rb
- spec/services/embargo_release_service_spec.rb
- spec/services/update_object_service_spec.rb
Get rid of jankiness.
Unit, integration
> Changes strategy for locking.

- lib/tasks/missing_druids.rake
> Fix missing_druids rake task to use RepositoryObjects.

- app/services/publish/metadata_transfer_service.rb
> Add some documentation about why we send the release.

- spec/services/virtual_object_service_spec.rb
> Fix flappy test.

- .circleci/config.yml
Fixes main build to publish docker image
> Update the circlci orb to get latest docker

- .rubocop.yml
> A bit of rubocop maintenance

- app/controllers/release_tags_controller.rb
- app/models/dor/release_tag.rb
- app/models/release_tag.rb
- app/services/release_tag_service.rb
- spec/models/release_tag_spec.rb
- spec/requests/release_tags_spec.rb
- spec/services/indexing/indexers/releasable_indexer_spec.rb
- spec/services/release_tag_service_spec.rb
> Replace Cocina::Models::ReleaseTag with Dor::ReleaseTag

- app/reports/preservation_versions.rb
refs #5074
Shockingly, preservation and SDR are out of sync ...
> Adds a report for version mismatches.

- Gemfile
- Gemfile.lock
- app/services/publish/public_cocina_service.rb
- openapi.yml
- spec/fixtures/workspace/dd/116/zh/0343/dd116zh0343/metadata/cocina.json
- spec/requests/create_collection_spec.rb
- spec/requests/create_object_spec.rb
- spec/requests/show_object_spec.rb
- spec/requests/update_metadata_spec.rb
- spec/services/cocina/serializer_spec.rb
- spec/services/cocina/to_xml/content_metadata_generator_spec.rb
- spec/services/indexing/indexers/releasable_indexer_spec.rb
- spec/services/publish/public_cocina_service_spec.rb
- spec/services/release_tag_service_spec.rb
Step 3a of a cocina models release
> Bump cocina models

- .rubocop.yml
- Gemfile.lock
Ran sdr-deplosit integration test in stage.
Deployed to prod and verified health checks and argo show pages.
> Bump to ruby 3.3.1

- app/controllers/user_versions_controller.rb
- app/models/repository_object_version.rb
- config/routes.rb
- openapi.yml
- spec/requests/show_user_version_spec.rb
> Show a single user version

- app/controllers/user_versions_controller.rb
- app/models/user_version.rb
- spec/requests/user_versions_inventory_spec.rb
> Display withdrawn attribute on user version index

- app/models/repository_object_version.rb
- app/models/user_version.rb
- spec/requests/show_user_version_spec.rb
- spec/requests/user_versions_inventory_spec.rb
- spec/services/user_version_service_spec.rb
> Validate the RepositoryObjectVersion for a UserVersion has cocina

- app/controllers/user_versions_controller.rb
- app/models/user_version.rb
- config/routes.rb
- openapi.yml
- spec/requests/create_user_version_spec.rb
- spec/requests/update_user_version_spec.rb
closes #5098
Endpoints are going to be necessary to manage user versions from Argo.
Unit
> Adds create and update endpoints for user versions.

- spec/models/user_version_spec.rb
> Improve testing for validation of UserVersion

- app/services/digital_stacks_differ.rb
The previous message was incorrect.
> Fix error message in DigitalStacksDiffer.

- app/services/publish/metadata_transfer_service.rb
- app/services/shelvable_files_stager.rb
- spec/services/shelvable_files_stager_spec.rb
Copying failed in some of our testing.
> Additional logging and checking for shelving files.

- Gemfile
- Gemfile.lock
- app/jobs/publish_job.rb
- app/services/cocina_object_store.rb
- app/services/constituent_service.rb
- app/services/publish/metadata_transfer_service.rb
- app/services/publish/transfer_stager.rb
- app/services/user_version_service.rb
- bin/migrate-cocina
- bin/repub
- spec/jobs/publish_job_spec.rb
- spec/services/constituent_service_spec.rb
- spec/services/publish/metadata_transfer_service_spec.rb
- spec/services/publish/transfer_stager_spec.rb
refs https://github.com/sul-dlss/purl-fetcher/issues/862
Versioning
Unit, Stage
> Provides version info to purl fetcher when publishing.

- app/services/digital_stacks_differ.rb
- app/services/publish/metadata_transfer_service.rb
- spec/services/publish/metadata_transfer_service_spec.rb
closes #5117
So that @andrewjbtw can sleep well at night.
Unit
> Check that shelving was successful.

- app/services/publish/metadata_transfer_service.rb
- app/services/shelvable_files_stager.rb
- spec/services/publish/metadata_transfer_service_spec.rb
- spec/services/shelvable_files_stager_spec.rb
closes #5138
Previous approach was wrong.
Unit
> Change staging from pres to check cocina file size.

- bin/validate-cocina
All versions must be valid, not just head.
sdr-infra against stage DSA.
> Validate all versions.

- Gemfile
- Gemfile.lock
- app/controllers/user_versions_controller.rb
- app/jobs/withdraw_restore_job.rb
- app/services/user_version_service.rb
- spec/jobs/withdraw_restore_job_spec.rb
- spec/requests/create_user_version_spec.rb
- spec/requests/update_user_version_spec.rb
- spec/services/user_version_service_spec.rb
closes #5134
The missing link.
Unit, integration test
> Call purl-fetcher to withdraw / restore user versions.

- app/jobs/publish_job.rb
- app/services/publish/metadata_transfer_service.rb
- app/services/user_version_service.rb
- spec/jobs/publish_job_spec.rb
- spec/services/user_version_service_spec.rb
closes #5161
PURL/stacks needs to know about the move.
Unit
> Republish when moving user version.

- app/models/repository_object.rb
- app/services/member_service.rb
- app/services/publish/metadata_transfer_service.rb
- app/services/virtual_object_service.rb
- spec/models/repository_object_spec.rb
- spec/services/member_service_spec.rb
- spec/services/publish/metadata_transfer_service_spec.rb
- spec/services/virtual_object_service_spec.rb
> Change logic determining whether item is publishable

- Gemfile.lock
Get the longer request timeout.
> New version of purl-fetcher-client

- app/reports/publish_status.rb
> Report about druids lacking a public json record in purl-fetcher's db

- app/controllers/versions_controller.rb
- openapi.yml
- spec/requests/versions_spec.rb
closes #5200
It is isn't used.
> Removes version openable endpoint.

- .rubocop.yml
- app/models/background_job_result.rb
> Rubocop rule update.

- config/settings.yml
> Remove redundant workflow config

- app/services/workflow_state_service.rb
- spec/services/workflow_state_service_spec.rb
Fixes #5228 - ensure the lock icon is deactivated in Argo when an object is still actively processing speech to text
New spec and QA
> check speechToTextWF for assembling

- app/services/embargo_release_service.rb
- spec/services/embargo_release_service_spec.rb
These message are annoying; no action is taken based on them.
> Do not warn when lifting embargo.

- config/deploy.rb
So that dropped bindings are restored.
> Run rabbitmq setup on deploy.

- .circleci/config.yml
- .rubocop.yml
- Dockerfile
- Gemfile.lock
> Upgrade to ruby 3.4.1.

- app/services/migrators/base.rb
> Remove misleading usage of `protected` keyword

- Gemfile.lock
- app/controllers/versions_controller.rb
- openapi.yml
- spec/requests/versions_spec.rb
refs https://github.com/sul-dlss/hungry-hungry-hippo/issues/704
So that it would be available for use in H3.
> Return version description with version status.

- Gemfile
- Gemfile.lock
> Update cocina models and DSC.

- Gemfile.lock
- app/services/indexer.rb
refs #5231
To verify that a Solr commit is being attempted and the ordering of commits.
> Add additional logging to help troubleshoot indexing.

- app/controllers/versions_controller.rb
- app/services/version_service.rb
- app/services/workflow_state_service.rb
- spec/requests/versions_spec.rb
- spec/services/workflow_state_service_spec.rb
So that H3 is faster.
Unit, stage, qa
> Faster version statuses

- app/services/version_service.rb
Reverts sul-dlss/dor-services-app#5280
> Revert "Make sure current lock is returned when opening version."

- app/reports/digital_serials.rb
Improved some comments and readability based on suggestions from @edsu
> Tweaks to digital serials reports

- app/services/embargo_release_service.rb
- spec/services/embargo_release_service_spec.rb
> Fix embargo release service

- lib/tasks/rspec.rake
> Restore rescue in rspec.rake.

- Gemfile
- Gemfile.lock
- openapi.yml
> Bump cocina-models version with openapi.yml changes

- app/services/workflow_service.rb
- spec/services/workflow_service_spec.rb
closes #5309
The method call was wrong.
Unit
> Fix call of workflow client all_workflows method.

- Gemfile
- Gemfile.lock
> Update cocina-models and dor-services-client versions

- Gemfile.lock
Pick up dependency updates w/ cocina-models patch bump
> Update dependencies to pick up cocina patch bump

- app/reports/digital_serials_title_parts.rb
Resolves #5321
To be run on druids: https://drive.google.com/file/d/1UU8ODlZTNJIpDeVkGDoioTmu-Is34EcE/view?usp=drive_link
Run with stage druids.
> Report on digital serials title parts

- app/reports/digital_serials_unreleased.rb
> Add report for unreleased digital serials

- .rubocop.yml
- app/reports/digital_serials_title_parts.rb
Resolves #5331 to include a part label field that shows what the label would look like with migration. There are some questions about this, so keeping this in draft until I can get answers to those.
> Digital serials report with part label field

- Gemfile
- Gemfile.lock
- app/jobs/robots/dor_repo/accession/update_orcid_work.rb
- config/settings.yml
Part of https://github.com/sul-dlss/dor-services-app/issues/5284
Has shared_configs updates too (linked to from ticket above)
~~Waiting on testing switchover~~
> Update mais-orcid-client gem

- Gemfile.lock
keep in sync with cocina-models
> Update cocina-models to 0.103.2

- lib/tasks/missing_druids.rake
> index_unindexed_objects rake refinements

- README.md
- app/services/migrators/base.rb
- bin/migrate-cocina
Document existing migrate process a little more.
> Clarifications on migrating cocina

- app/reports/digital_serials_title_parts.rb
For running pre-migration reports. Also adds back a fix I must have dropped along the way. 
Ran on sdr-infra.
> Adds sort key to reports

- app/jobs/robots/dor_repo/accession/update_orcid_work.rb
- spec/jobs/robots/dor_repo/accession/update_orcid_work_spec.rb
> Delete Orcid works when a graveyard APO.

- app/controllers/workflow_templates_controller.rb
- config/routes.rb
- openapi.yml
- spec/requests/list_workflow_templates_spec.rb
closes #5393
To allow DSA to handle workflow service calls.
Unit
> Adds workflow template endpoint.

- Gemfile
- Gemfile.lock
- app/controllers/workflow_lifecycles_controller.rb
- config/routes.rb
- openapi.yml
- spec/requests/list_workflow_lifecycles_spec.rb
closes #5394
Merge workflow service into DSA.
Unit
> Adds workflow lifecycle endpoint.

- app/controllers/workflow_application_controller.rb
- app/controllers/workflow_lifecycles_controller.rb
- app/controllers/workflow_templates_controller.rb
- app/controllers/workflows_controller.rb
- config/routes.rb
- openapi.yml
- spec/requests/list_workflows_spec.rb
closes #5395
Merge workflow server.
Unit
> Adds workflow list endpoint.

- app/controllers/workflows_controller.rb
- config/routes.rb
- openapi.yml
- spec/requests/show_workflow_spec.rb
closes #5396
Merge workflow service.
Unit
> Adds show workflow endpoint. 

- app/controllers/workflows_controller.rb
- config/routes.rb
- openapi.yml
- spec/requests/create_workflow_spec.rb
closes #5397 
Support workflow endpoints.
Unit
> Adds create workflow endpoint. 

- Gemfile.lock
To pick up cocina-models and DSC updates for support of H3 work. 
> Bumping cocina-models

- app/controllers/workflows_controller.rb
- config/routes.rb
- openapi.yml
- spec/requests/skip_all_workflow_spec.rb
closes #5398 
Merge workflow server.
> Adds workflow skip all endpoint.

- app/controllers/workflow_application_controller.rb
- app/controllers/workflows_controller.rb
- app/services/indexing/indexers/workflows_indexer.rb
- app/services/workflow_service.rb
- app/services/workflow_state_service.rb
- spec/requests/list_workflows_spec.rb
- spec/services/indexing/indexers/workflows_indexer_spec.rb
- spec/services/workflow_service_spec.rb
- spec/services/workflow_state_service_spec.rb
closes #5410
Encapsulate the workflow client.
Unit
> Adds additional workflow methods to workflow service.

- app/controllers/versions_controller.rb
- openapi.yml
- spec/requests/versions_spec.rb
Better errors back to H3. 
Unit and in stage.
> Return 404 for versions lookups

- app/controllers/workflow_templates_controller.rb
- config/routes.rb
- openapi.yml
- spec/requests/show_workflow_template_spec.rb
Supports work to replace DWC in Argo.
CI
> Add endpoint for DSA to show a given workflow template

- app/services/workflow_lifecycle_service.rb
- spec/services/workflow_lifecycle_service_spec.rb
> Fix arguments when calling workflow client query_lifecycle.

- app/controllers/workflow_application_controller.rb
- app/controllers/workflow_processes_controller.rb
- app/services/workflow_process_service.rb
- app/services/workflow_service.rb
- spec/requests/update_workflow_process_spec.rb
- spec/services/workflow_process_service_spec.rb
> Encapsulates updating workflow processes.

- app/services/indexing/workflow_fields.rb
- app/services/workflow_lifecycle_service.rb
- spec/services/indexing/workflow_fields_spec.rb
- spec/services/workflow_lifecycle_service_spec.rb
> Encapsulate workflow status.

- app/jobs/robots/dor_repo/accession/update_orcid_work.rb
- spec/jobs/robots/dor_repo/accession/update_orcid_work_spec.rb
closes #5434
This is an expected occurrence and does not warrant error handling.
Unit
> Ignore when orcid reports that work not found.

- app/models/version_context.rb
- app/models/workflow_step.rb
- app/services/workflow_lifecycle_service.rb
- app/validators/druid_validator.rb
- spec/factories/version_contexts.rb
- spec/factories/workflow_steps.rb
- spec/models/version_context_spec.rb
- spec/models/workflow_step_spec.rb
- spec/services/workflow_lifecycle_service_spec.rb
closes #5437
Merge workflow server.
> Port WorkflowLifecycleService from workflow server

- app/jobs/reindex_by_druid_job.rb
- lib/tasks/rabbitmq.rake
- spec/jobs/reindex_by_druid_job_spec.rb
This is needed when the feature flag is not enabled.
> Restore indexing job.

- app/jobs/reindex_by_druid_job.rb
point to the non-deprecated code that is currently in use
CI
> freshen stale comment on reindex_by_druid_job.rb

- app/services/workflow_service.rb
- spec/services/workflow_service_spec.rb
> Port workflow service delete methods to local wf.

- app/services/workflow_service.rb
- spec/services/workflow_service_spec.rb
> Port workflow service skip all to local wf.

- app/services/workflow_service.rb
- openapi.yml
- spec/services/workflow_service_spec.rb
> Ports workflow service workflows methods to local wf.

- app/services/cocina/to_datacite/creator_contributor_funder.rb
- spec/services/cocina/to_datacite/attributes_spec.rb
> Add contributor affiliation attributes to the datacite mapping

- README.md
So that useful info isn't lost.
> Add workflow info to README

- config/initializers/okcomputer.rb
* Check workflow db tables.
* Stop checking unused rabbit queue
> Update OK computer checks.

- config/initializers/sidekiq.rb
Address sporadic redis timeouts: https://app.honeybadger.io/projects/50568/faults/122449442
stage
> Adjust redis sidekiq configuration.

- Gemfile.lock
- app/services/cocina/to_datacite/creator_contributor_funder.rb
- spec/services/cocina/to_datacite/attributes_spec.rb
Connects to sul-dlss/hydra_etd#1621
CI, stage
> Map ETD contributors to Datacite

- Gemfile
- Gemfile.lock
> Bumping cocina-models and DSC versions

- Gemfile.lock
> Bump sul-orcid-client to latest version

- app/services/cocina/to_datacite/creator_contributor_funder.rb
- spec/services/cocina/to_datacite/attributes_spec.rb
Helps a stuck ETD map to DataCite so it can be accessioned
CI
> Allow mapping ETDs to DataCite

- app/jobs/batch_reindex_job.rb
- app/services/indexing/builders/document_builder.rb
- app/services/indexing/indexers/workflows_indexer.rb
- app/services/workflow/batch_service.rb
- spec/jobs/batch_reindex_job_spec.rb
- spec/services/indexing/builders/document_builder_spec.rb
- spec/services/workflow/batch_service_spec.rb
refs #5518
Faster re-indexing.
Unit
> Retrieve workflows in batch for batch reindexing.

- app/jobs/batch_reindex_job.rb
- app/services/indexing/indexers/releasable_indexer.rb
- spec/jobs/batch_reindex_job_spec.rb
> Fix batch reindexing

- app/controllers/objects_controller.rb
- app/controllers/queries_controller.rb
- app/services/cocina_object_store.rb
- config/routes.rb
- openapi.yml
- spec/requests/find_all_spec.rb
- spec/services/cocina_object_store_spec.rb
Part of https://github.com/sul-dlss/argo/issues/4824
This will be called by argo initially to find all APO collections for registration without making individual SOLR queries.
> Add find_all endpoint to ObjectController
