sul-dlss/dor-services-app

.travis.yml
Gemfile
Gemfile.lock

Note that you have to install oracle for this to install. the dev box already has it installed (see config/deploy.rb). I added a .travis.yml, but it doesn't work because travis does not support Oracle.

bump to dor-services 4.22 and dor-workflow-service to 1.7.7

---

Gemfile
Gemfile.lock
config/environments/local.rb
lib/dor_services_app.rb
spec/dor_services_app_spec.rb
spec/spec_helper.rb

This allows the dor-services-app to mediate requests to the SDR services, instead of requiring all dor-services consumers to get special access to SDR. There will be a corresponding change in dor-services to consume these endpoints instead of accessing SDR directly.

Add SDR service gateway endpoints

---

Gemfile
Gemfile.lock
config/environments/local.rb
lib/dor_services_app.rb
spec/dor_services_app_spec.rb
spec/spec_helper.rb

This backports #18 to the dor-services-4.x branch, allowing us to deploy a new version of `dor-services-app` to production that supports https://github.com/sul-dlss/dor-services/pull/164.

Backport SDR endpoints into dor-services 4.x branch

---

Gemfile
Gemfile.lock
README.md
bin/write_marc_record_test
config/boot.rb
config/deploy.rb
config/environments/local.rb
lib/dor_services_app.rb
lib/update_marc_record_service.rb
spec/dor_services_app_spec.rb
spec/fixtures/sdr_purl/.gitignore
spec/spec_helper.rb
spec/update_marc_spec.rb

Implements a new method called "update_marc_record" which will write out a marc record for syncing up with symphony.  The logic used to be in the item-release robot suite, but it is being extracted here so that it can be called directly without having to invoke a workflow.  The robot will simply call the web service now.  See https://github.com/sul-dlss/item-release/pull/64
fixes sul-dlss/discovery-indexing#1

Add new update marc record web service call

---

app/controllers/application_controller.rb

The Rails routes provide for the item druid to be passed in via `:id` or `:object_id`

allow druids to be passed in via :id or :object_id

---

app/controllers/objects_controller.rb
spec/controllers/objects_controller_spec.rb

Make plain text output the default response format for registering objects

---

config/initializers/okcomputer.rb

ActiveRecord check fails currently, which is expected since there is no database used or configured:
https://dor-services-prod.stanford.edu/status/all

no activerecord check necessary for okcomputer

---

Gemfile.lock
README.md

Motivated by errors thrown when registering web archive seed objects with source_id values of the form sul:SOMETHING-http://www.foo.org
Also add Gemnasium and version badges to README

dor-services v5.21.1 - allow colons in source_id and other_id values

---

app/models/dor/update_marc_record_service.rb
spec/update_marc_spec.rb

set second indicator depending on the objects APO

---

app/models/dor/update_marc_record_service.rb
spec/support/datastreams.rb
spec/update_marc_spec.rb

so that all stanford restricted and location restricted objects get the field.  fixup fixture to put no-download rule on stanford object, add location restricted fixture, add location restricted test.

slightly relax condition for writing z subfield to marc record

---

app/models/dor/service_item.rb
app/models/dor/update_marc_record_service.rb
spec/service_item_spec.rb
spec/support/datastreams.rb
spec/update_marc_spec.rb

when writing out catkeys, cycle through all previous catkeys and write out a simple blank record for each before writing out the actual record
refactored to allow for multiple rows to be written out per object
some other refactoring and new tests
closes #73

Create empty records for previous catkeys

---

config/deploy.rb

This prevents both stage and prod from reporting as "production" and
provides consistency across dlss projects.

Set the honeybadger_env to the capistrano deployment stage

---

Gemfile
Gemfile.lock
config/initializers/dor_config.rb
config/settings.yml

So that we can configure the app to notify purl-fetcher using the API
rather than by putting files in a NFS mount.
Also updated other dependencies.

Update dor-services gem to ~> 5.31

---

Gemfile
Gemfile.lock
spec/controllers/marcxml_controller_spec.rb
spec/controllers/objects_controller_spec.rb
spec/controllers/sdr_controller_spec.rb
spec/goobi_spec.rb
spec/models/symphony_reader_spec.rb
spec/rails_helper.rb

Fakeweb is no longer maintained (last release 2010) and doesn't support
ruby > 2.4+
Fixes #108

Switch from fakeweb to webmock

---

Capfile

This avoids a deprecation warning from Capistrano

Install the capistrano git plugin

---

.travis.yml

I've noted that ruby 2.3.4 is the deployed version

Test with newer ruby versions.

---

app/models/dor/goobi.rb
app/models/dor/service_item.rb
spec/goobi_spec.rb
spec/service_item_spec.rb

add <tags> to goobi notify call with object tags in specified format

---

app/controllers/objects_controller.rb
app/services/workspace_service.rb
spec/services/workspace_service_spec.rb

This will enable us to remove the `Dor::Assemblable` concern from dor-services.
Since dor-services-app is the only one to call that function, it makes sense to remove it
from the library and keep the code close to the caller.
See https://github.com/sul-dlss/dor-services/blob/master/lib/dor/models/concerns/assembleable.rb

add workspace service for creating workspaces

---

app/models/dor/goobi.rb
app/models/dor/service_item.rb
app/models/dor/update_marc_record_service.rb
spec/dor/goobi_spec.rb

Fixes sul-dlss/goobi-robot#30
When the Goobi XML is created, use the text of the first MODS title for the document title if present. If not present, use the object label. Prior to this change, the object label was always used in this context, but the label is not always present, requiring downstream failure and manual remediation.

Return title instead of label in Goobi XML

---

Gemfile
Gemfile.lock
app/controllers/objects_controller.rb
app/controllers/versions_controller.rb
spec/controllers/versions_controller_spec.rb

Refs sul-dlss/argo#1277
Also, remove unnecessary tzinfo-data dependency, as this is only included in the bundle on environments we do not deploy in (Windows and JRuby), and in the meantime, its presence in the bundle causes every bundle command to include a warning message. This message can trip up shell aliases and functions that use bundler, such as grepping the bundle to sleuth out behavior within dependencies.

 Bump dor-services and use services for versioning and workspace creation

---

app/controllers/versions_controller.rb
spec/controllers/versions_controller_spec.rb

* Pass POSTed version params on to `Dor::VersionService`.
* Remove custom param-handling behavior around parsing POSTed JSON bodies to
params hashes, since Rails already does this for us now.
Refs sul-dlss/argo#1277

Pass optional version params to Dor::VersionService

---

app/models/dor/goobi.rb
app/models/dor/service_item.rb
spec/dor/goobi_spec.rb
spec/dor/update_marc_record_service_spec.rb
spec/support/datastreams.rb

deal with special characters in title from any location

---

.rubocop_todo.yml
app/controllers/objects_controller.rb
app/services/dublin_core_service.rb
app/services/mods2dc.xslt
app/services/public_xml_service.rb
app/services/publish_metadata_service.rb
config/settings.yml
spec/controllers/objects_controller_spec.rb
spec/fixtures/ex1_dc.xml
spec/fixtures/ex1_mods.xml
spec/fixtures/ex2_related_dc.xml
spec/fixtures/ex2_related_mods.xml
spec/fixtures/hj097bm8879_contentMetadata.xml
spec/fixtures/hj097bm8879_publicObject.xml
spec/fixtures/item_druid_ab123cd4567.xml
spec/fixtures/item_druid_cg767mn6478.xml
spec/fixtures/item_druid_jw923xn5254.xml
spec/rails_helper.rb
spec/services/dublin_core_service_spec.rb
spec/services/public_xml_service_spec.rb
spec/services/publish_metadata_service_spec.rb

This was previously moved out of dor-services, but it was still being used here.
Once this is here we can refactor the common-accessioning robots to call these
services in dor-services-app.

Move PublishMetadataService in from common-accessioning

---

app/models/dor/goobi.rb

The handler had a condition to only execute if the attempt_number was greater or equal than max_tries
but the handler only executes before running the retry block (e.g. when attempt_number is less than max tries)

Remove a handler that wasn't ever used

---

app/services/sdr_client.rb
app/services/version_service.rb
spec/services/sdr_client_spec.rb
spec/services/version_service_spec.rb

This would happen in the case when the object has been transfered to
sdr, but sdr-services-app is not yet acknowledging queries for this
object.
Fixes #292

The can_open_version? returns false when open_version would fail

---

Gemfile.lock
spec/services/publish_metadata_service_spec.rb

This stops from writing deletes to the filesystem log.
Fixes #285

Upgrade druid-tools to 2.0.0

---

app/controllers/application_controller.rb
config/settings.yml
spec/requests/authorization_spec.rb
spec/requests/metadata_refresh_spec.rb
spec/requests/metadata_spec.rb
spec/support/auth_helper.rb

Drop basic authorization.
This can't be deployed until Hydrus is deployed (with JWT support)

Require JWT token authorization

---

app/services/cleanup_reset_service.rb
app/services/cleanup_service.rb
app/services/delete_service.rb
app/services/prune_service.rb
app/services/publish_metadata_service.rb
spec/services/prune_service_spec.rb

This will allow the methods in druid-tools to be deprecated because dor-services-app is the only place they are used
Fixes #327

Move DruidTools::Druid#prune! and #prune_ancestors from druid-tools

---

app/services/workspace_service.rb
spec/services/prune_service_spec.rb
spec/services/workspace_service_spec.rb

Because dor-services-app is the only consumer of that method

Move mkdir_with_final_link from DruidTools

---

app/controllers/objects_controller.rb
spec/controllers/objects_controller_spec.rb

Fixes #331
@ndushay This is a very specific fix to #331. I'm not sure if you were hoping for a more general (across-the-board) fix. I'm probably inclined to fix the narrowest case and add more error handling as we find other exceptions that don't bubble up useful information, but I am open to pushback on this if you think it's too short-sighted.

Return HTTP 400 with an informative message when metadata to be published

---

app/controllers/versions_controller.rb
app/services/version_service.rb
spec/controllers/versions_controller_spec.rb
spec/services/version_service_spec.rb

Includes:
* Move version open params nested in hash up a level so they are top-level params
* Avoid coercing significance value to a symbol in `VersionsController`; this is already coerced in `VersionService`, and brings symmetry to `#open_params` and `#close_params`
* Prefer `#symbolize_keys` to `#deep_symbolize_keys` when not working with a nested hash structure
* Update YARD documentation in `VersionService` now that the open params have been promoted to top-level
* Prefer `#save!` to `#save` for ActiveFedora objects (do not hide errors)

Dump poorly named and unnecessary hash arg when opening versions

---

app/controllers/versions_controller.rb
app/services/version_service.rb
spec/services/version_service_spec.rb

This means the consumers won't have to do two steps. Fixes #351

Create an event when closing a version

---

.rubocop_todo.yml
app/controllers/objects_controller.rb
config/routes.rb
spec/controllers/objects_controller_spec.rb

Fixes #353
And create a new event on the object associated with the modification.

Create an endpoint for modifying an object's embargo date

---

app/controllers/objects_controller.rb
app/services/constituent_service.rb
app/services/item_query_service.rb
spec/requests/virtual_merge_spec.rb
spec/services/constituent_service_spec.rb
spec/services/item_query_service_spec.rb

Fixes #365 
Includes:
* Add `ItemQueryService.validate_combinable_items`. This new class method takes an array of druids and makes sure each is combinable. If any are not, a hash of errors is created and returned.
* Validate all items to be combined before modifying any of them.
* Raise exception from objects controller when constituent service raises.

Validate constituents before creating virtual object

---

.rubocop.yml
app/controllers/objects_controller.rb
spec/requests/virtual_merge_spec.rb

Refs sul-dlss/argo#1463
Calling `#to_json` on a string before rendering it with the built-in JSON renderer causes a double-escaping to happen.
Also, remove duplicate rubocop exception

Do not double-escape JSON

---

app/controllers/marcxml_controller.rb
app/controllers/metadata_refresh_controller.rb
app/controllers/objects_controller.rb
app/models/symphony_reader.rb
spec/controllers/marcxml_controller_spec.rb
spec/controllers/objects_controller_spec.rb
spec/models/symphony_reader_spec.rb
spec/requests/metadata_refresh_spec.rb

part of #348
~~DO NOT MERGE without PO approval.~~   Per storytime 2019-09-03, this is approved by Andrew.
~~- is the registration form tiny errors adequate notice?~~
This has been tested on stage by changing the new code to ensure the error was raised.
- Created #362 re:  honeybadger errors (currently inconsistent between registration and refresh metadata)
- Created sul-dlss/argo/issues/1545 re: better user experience for errors when refreshing metadata.
after filling in registration form for one item and submitting it.
Note the registration was NOT completed (see the red circle in the column), and we have a tooltip showing the error.  (Pay no attention to the actual numbers in the error message - I faked the failure)  
```
I, [2019-08-30T12:00:05.535674 #9693]  INFO -- : …
```

SymphonyReader validates num bytes in resp body

---

app/controllers/objects_controller.rb
spec/controllers/objects_controller_spec.rb

Fixes #346 
If, say, a collection or APO object is missing when registering an item, we get 
```
ActiveFedora::ObjectNotFoundError (Unable to find 'druid:bh738rc3225' in fedora. See logger for details.):
```
in logs for dor-services-app.
This PR will ensure the useful "Unable to find 'druid:bh738rc3225' in fedora" part is shared with dor-services-client, instead of:
```
Dor::Services::Client::UnexpectedResponse: Not Found: 404 ({"status":404,"error":"Not Found"})
```

surface better error message in ObjectsController

---

app/models/symphony_reader.rb
spec/models/symphony_reader_spec.rb

Fixes #362
FYI:
For Argo registration, we will now see this error in honeybadger.  Yay!
For Argo "refresh metadata", we will now see each of these errors twice in honeybadger:
- from the notification here in dor-services-app
- from the notification in argo due to 500 from dor-service-client

alert honeybadger for incomplete response from Symphony

---

app/controllers/objects_controller.rb
app/controllers/virtual_objects_controller.rb
app/services/constituent_service.rb
app/services/item_query_service.rb
app/services/version_service.rb
config/routes.rb
spec/requests/batch_create_virtual_objects_spec.rb
spec/services/constituent_service_spec.rb
spec/services/item_query_service_spec.rb
spec/services/version_service_spec.rb

Connects to #375 
Connects to sul-dlss/argo#1463
Includes:
* Mark `ObjectsController#update` as soon as be removed
* Make clear in `ItemQueryService` which parents are associated with which combination errors
* Add class method for convenience of checking if a work is open for versioning
* Check whether item is open or openable, NOT whether it allows modification, within `ItemQueryService`
* Handle versioning concerns when adding constituents
* Extract `VirtualObjectsController` from `ObjectsController`: it functions identically to the `ObjectsController` implementation except it can create many virtual objects at a time.
* Enhance parameter validation in `VirtualObjectsController` by using dry-schema

Allow virtual objects to be created in batches

---

.github/pull_request_template.md
README.md
docs/index.html
openapi.json

This has all of the endpoints, but doesn't yet have all the parameters and responses.

Add API documentation

---

app/controllers/application_controller.rb
app/controllers/marcxml_controller.rb
app/controllers/metadata_refresh_controller.rb
app/controllers/objects_controller.rb
app/models/symphony_reader.rb
spec/controllers/marcxml_controller_spec.rb
spec/models/symphony_reader_spec.rb
spec/requests/metadata_refresh_spec.rb
spec/requests/register_object_spec.rb

The bulk of this is "d'oh" -- we need to check the HTTP status code of the response from Symphony and surface the right info.

Symphony responses aren't always status 200

---

openapi.json

These are in the query not the body
`body` is not valid in OAS 3.0 and furthermore these parameters are in the query.
yes

Correct parameter location

---

app/models/symphony_reader.rb
spec/models/symphony_reader_spec.rb

A timeout for a Symphony request should get a specific error message to the end user (e.g. in Argo registration or in Argo refresh_metadata).
Fixes #377
- no change to API (we aren't currently documenting error codes for requests)

surface Faraday::Timeout errors for Symphony response

---

app/controllers/sdr_controller.rb
app/services/sdr_client.rb
config/settings.yml
spec/controllers/sdr_controller_spec.rb
spec/services/sdr_client_spec.rb

Faraday requires you to be explicit when using basic auth, unlike RestClient
Api not changed.

Use faraday to handle basic auth

---

app/controllers/virtual_objects_controller.rb
app/services/version_service.rb
spec/requests/batch_create_virtual_objects_spec.rb
spec/services/version_service_spec.rb

To provide more information to downstream consumers why operations fail and for which objects.
No, and it didn't need to be.

Rescue versioning exceptions and provide more context

---

app/controllers/application_controller.rb
openapi.json
spec/requests/add_release_tags_spec.rb
spec/requests/authorization_spec.rb
spec/requests/batch_create_virtual_objects_spec.rb
spec/requests/collections_for_object_spec.rb
spec/requests/metadata_refresh_spec.rb
spec/requests/metadata_spec.rb
spec/requests/notify_goobi_spec.rb
spec/requests/publish_object_spec.rb
spec/requests/register_object_spec.rb
spec/requests/show_object_spec.rb
spec/requests/update_embargo_spec.rb
spec/requests/update_marc_record_spec.rb
spec/requests/virtual_merge_spec.rb

Log a honeybadger notification when we get the old X-Auth header
Fixes #320
We want to be able to accept the standard Authorization header rather than our custom X-Auth header.
Yes!

Accept the Authorization header

---

app/controllers/objects_controller.rb
app/models/dor/goobi.rb
config/settings.yml

An error was logged:
```
TypeError: class or module required for rescue clause
```
Fixes #404
not necessary, no API change made

Retriable exceptions must be exceptions (not strings)

---

app/services/constituent_service.rb
spec/services/constituent_service_spec.rb

When creating a virtual object, child objects must first be disassociated from other virtual objects before being "merged" into a new virtual object. I discussed this requirement with @andrewjbtw yesterday and he requested and signed off on this change.
Connects to sul-dlss/argo#1463

Do not allow objects to have multiple parents

---

app/controllers/application_controller.rb
spec/requests/authorization_spec.rb

the honeybadger alert is useful for letting us know that a deprecated auth header is being used in production.  but it should be clarified to indicate that the notice is just a warning.
N/A

make honeybadger notification clear that the deprecation warning for X-Auth header usage is just a warning

---

openapi.json

The openapi specification was incorrectly specifying the authentication
Yes

Fix security syntax in openapi.json

---

Gemfile
Gemfile.lock

To make `capistrano-sidekiq` work, restarting sidekiq on a successful deployment.
Nope, not needed.

Add missing `capistrano-sidekiq` dependency

---

config/deploy.rb

Because capistrano was incorrectly using the cap stage as the sidekiq env. Now it is using the same env that the deployed application is running in (which for dor-services-app is always `'production'`.
Nope, unnecessary.

Set sidekiq env explicitly to production

---

app/controllers/sdr_controller.rb
app/services/sdr_client.rb
spec/controllers/sdr_controller_spec.rb

Keep logic out of the controller. This makes the client code reusable for shelving (TBD)
n/a

Move client logic to SdrClient

---

Gemfile
Gemfile.lock
spec/dor/update_marc_record_service_spec.rb
spec/services/constituent_service_spec.rb
spec/services/public_xml_service_spec.rb
spec/services/workspace_service_spec.rb

To keep dor-services-app consistent with other Dor projects.
n/a

upgrade to dor-services 8

---

openapi.json

Add more information about the expected response.
yes

Document response for GET /object/{id}

---

Gemfile.lock
app/services/version_service.rb
spec/services/version_service_spec.rb

Because that method calls the workflow service, which ends up calling back to dor-services-app to get the current version
n/a

Avoid calling active_lifecycle

---

.circleci/config.yml
Gemfile
Gemfile.lock
README.md
app/controllers/background_job_results_controller.rb
app/controllers/virtual_objects_controller.rb
app/jobs/application_job.rb
app/jobs/create_virtual_objects_job.rb
app/models/application_record.rb
app/models/background_job_result.rb
app/views/background_job_results/show.json.jbuilder
config/application.rb
config/database.yml
config/routes.rb
db/migrate/20190917215521_create_background_job_results.rb
db/structure.sql
docker-compose.yml
openapi.json
spec/factories/background_job_results.rb
spec/jobs/create_virtual_objects_job_spec.rb
spec/rails_helper.rb
spec/requests/background_job_results_spec.rb
spec/requests/batch_create_virtual_objects_spec.rb
spec/support/factory_bot.rb

Connects to #336
Deployment blocked by sul-dlss/puppet#4470
* Add ActiveRecord and Postgres as dependencies. This makes it possible to reliably stash information about background jobs in a persistent store, which will be used to run virtual object creation in the background.
* Include `factory_bot_rails` as a dependency which will make it easier to spin
up fixture-like factories when testing with database entities later.
* Create a model and a table for background job results. The model holds any output from the job, an HTTP status code, and a processing status.
* Add factory_bot_rails to the test suite. This allows us to more efficiently test database-backed entities, specifically `BackgroundJobResults`.
* Add new controller and view for background job results.
* Use a background job to …

Handle virtual object creation in a background job

---

.circleci/config.yml
README.md
app/controllers/shelves_controller.rb
openapi.json
spec/requests/shelving_spec.rb

Includes:
* Add validation step to CI build
* Add validator badge to README
* Prefer HTTP 204 over 201 when not creating a new resource
To make our spec validation more transparent and more robust.
Yes.

Validate OpenAPI specification

---

openapi.json

This endpoint was removed in the prior commit, and I missed this.
To correct a prior PR.
This time, yeah! Thanks, @jcoyne

Remove /objects/{id} PATCH from API specification

---

spec/requests/shelving_spec.rb

This is now done in the `AuthHelper`
To remove cruft.
n/a

Remove outdated per-test JWT cruft

---

app/jobs/create_virtual_objects_job.rb
app/models/background_job_result.rb
db/migrate/20190917215521_create_background_job_results.rb
db/structure.sql
openapi.json
spec/factories/background_job_results.rb
spec/jobs/create_virtual_objects_job_spec.rb
spec/requests/background_job_results_spec.rb

I started down this road when discovering in dor-services-client that dor-services-app was not reliably returning JSON as output.
Part of this work includes ensuring the output field of background job results is serialized as JSON (and deserialized as a hash with indifferent access because we are used to dealing with hashes with indifferent access in the Rails context).
To add missing detail to the API specification.
Yes

Document background job result bodies

---

Gemfile
Gemfile.lock
app/services/cocina/mapper.rb
openapi.json
spec/requests/show_object_spec.rb

So we have a way of getting the embargo date for the object
yes

Add embargoReleaseDate to the show route

---

.circleci/config.yml

Avoids a warning:
```
npm WARN saveError ENOENT: no such file or directory, open '/home/circleci/project/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
```
N/A

Install openapi-enforcer-cli globally

---

Gemfile
Gemfile.lock
app/services/cocina/mapper.rb
app/services/release_tags.rb
openapi.json
spec/requests/collections_for_object_spec.rb
spec/requests/show_object_spec.rb

So that Argo doesn't have to be aware of the Fedora 3 data model to display the tags.
Yes

Object#show now returns releaseTags and current_version

---

docker-compose.yml

See https://docs.docker.com/compose/compose-file/#volume-configuration-reference
without this I get:
```
10:37 $ docker-compose up db
Starting dor-services-app_db_1 ... done
Attaching to dor-services-app_db_1
db_1        | FATAL:  "/var/lib/postgresql/data" is not a valid data directory
db_1        | DETAIL:  File "/var/lib/postgresql/data/PG_VERSION" does not contain valid data.
db_1        | HINT:  You might need to initdb.
dor-services-app_db_1 exited with code 1
```

Specify docker volume correctly

---

app/services/cocina/mapper.rb
openapi.json
spec/requests/show_object_spec.rb

Previously an error was raised if an APO object was requested
Yes

Allow APOs to be retrieved by the show handler

---

Gemfile.lock
app/services/version_service.rb
spec/services/version_service_spec.rb

This reverts commit 70a720c26f243688ddde7dcaa05e0b11a1c799af.
Bug https://github.com/sul-dlss/argo/issues/1654
N/a

Revert "Avoid calling active_lifecycle"

---

Gemfile
Gemfile.lock
app/services/version_service.rb
spec/services/version_service_spec.rb

If you don't pass a version the workflow service will make another call back to dor-services-app to get the version. This makes it very slow to open/close versions.
Not an api level change.

Pass the version to the active_version workflow call

---

Gemfile
Gemfile.lock
app/controllers/sdr_controller.rb
app/services/sdr_client.rb
app/services/version_service.rb
config/initializers/preservation_client.rb
config/routes.rb
config/settings.yml
openapi.json
spec/controllers/sdr_controller_spec.rb
spec/services/sdr_client_spec.rb
spec/services/version_service_spec.rb

To use the new preservation-client gem to get current_version from a preservation-catalog ReST endpoint, rather than the Sinatra sdr-services-app.  Also deprecates methods here designed to proxy getting current version from sdr-services-app.
Yes, marked the sdr#current_version endpoint deprecated.
- does this notify Honeybadger appropriately?
- does this have appropriate deprecation warnings?

deprecate sdr#current_version in favor of preservation-client

---

openapi.json

Because the druid parameter was poorly specified before.
yes

Add druid validation

---

Gemfile.lock

preservation-client v0.2.1 fixes bug getting current_version

---

.circleci/config.yml
Dockerfile
Gemfile
Gemfile.lock
README.md
app/controllers/background_job_results_controller.rb
app/controllers/virtual_objects_controller.rb
app/jobs/application_job.rb
app/jobs/create_virtual_objects_job.rb
app/models/application_record.rb
app/models/background_job_result.rb
app/views/background_job_results/show.json.jbuilder
config/application.rb
config/database.yml
config/routes.rb
db/migrate/20190917215521_create_background_job_results.rb
db/structure.sql
docker-compose.yml
docker/invoke.sh
openapi.json
spec/factories/background_job_results.rb
spec/jobs/create_virtual_objects_job_spec.rb
spec/rails_helper.rb
spec/requests/background_job_results_spec.rb
spec/requests/batch_create_virtual_objects_spec.rb
spec/support/factory_bot.rb

Fixes #447 
Includes:
* Align docker configuration with workflow-service
* Document background job result bodies: I started down this road when discovering in dor-services-client that dor-services-app was not reliably returning JSON as output. Part of this work includes ensuring the output field of background job results is serialized as JSON (and deserialized as a hash with indifferent access because we are used to dealing with hashes with indifferent access in the Rails context).
* Add ActiveRecord and Postgres as dependencies. This makes it possible to reliably stash information about background jobs in a persistent store, which will be used to run virtual object creation in the background.
* Include `factory_bot_rails` as a dependency which will make it easier to spin
up fixture-like …

Create virtual objects using database-backed approach

---

config/deploy.rb

This is managed by Puppet, so use the system provided configuration instead of the one from the application
To allow dor-services-app to connect to a database.
No.

Add database config to capistrano linked_files

---

Capfile
Gemfile
Gemfile.lock
config/deploy.rb

This was not needed until now that dor-services-app uses a database and is connected to one in deployed environments.

Run database migrations on deploys

---

Gemfile
Gemfile.lock

Sidekiq 6 doesn't support daemonization, so it doesn't fit into our current deployment patterns
N/A

Pin sidekiq to ~> 5.0

---

db/structure.sql

Previously was generated for postgres 9
N/A

Generate the db structure under postgres 10

---

app/controllers/objects_controller.rb
app/services/dublin_core_service.rb
app/services/public_xml_service.rb
app/services/publish_metadata_service.rb
openapi.json
spec/requests/publish_object_spec.rb
spec/services/public_xml_service_spec.rb

The nil pointer exceptions logged in honeybadger don't make it easy to decide what action needs to be taken.
Yes

Trap for a nil pointer and give a helpful message

---

app/services/dublin_core_service.rb

The Best Code is No Code At All
n/a

Prune unused code

---

Gemfile
Gemfile.lock
app/services/cocina/mapper.rb
openapi.json
spec/requests/collections_for_object_spec.rb
spec/requests/show_object_spec.rb

So that we can differentiate object types in common-accessioning.
Yes

Return Cocina Collections

---

app/services/sdr_client.rb
app/services/shelving_service.rb
spec/services/shelving_service_spec.rb

To fix `NoMethodError: undefined method `group_difference' for #<Faraday::Response:0x...>` for ShelvingService.shelve, used by common-accessioning robots.
Fixes #463 (when deployed).
The error was introduced here:  https://github.com/sul-dlss/dor-services-app/commit/309dbc7b48fd10203dc59f209dd8a77eef7ca09e
n/a

ShelvingService.shelve fixed 'undefined method ' error

---

app/controllers/shelves_controller.rb
config/application.rb

So argo will show something more useful than this when a content dir is missing in the shelve step for common-accessioning.
"shelve : Internal Server Error: 500 (Response from dor-services-app did not contain a body. Check honeybadger for dor-services-app for backtraces, and look into adding a `rescue_from` in dor-services-app to provide more details to the client in the future)"
n/a

ShelvingService provides more details to client when missing content dir

---

app/services/public_xml_service.rb
app/services/publish_metadata_service.rb
spec/services/public_xml_service_spec.rb
spec/services/publish_metadata_service_spec.rb

So it's easier to see where the dependencies are. This is especially important as ReleaseTags makes a remote HTTP call
N/A

Inject ReleaseTags as a dependency

---

app/controllers/shelves_controller.rb
app/services/shelving_service.rb
config/application.rb
spec/requests/shelving_spec.rb
spec/services/shelving_service_spec.rb

Previously it was unclear where this exception was raised from.  This implementation is a little more straightforward and has tests
No, but this changes the code to conform to the documented return values.

Add a wrapping exception with less indirection

---

app/controllers/background_job_results_controller.rb
app/controllers/objects_controller.rb
app/jobs/create_virtual_objects_job.rb
app/jobs/publish_job.rb
app/views/background_job_results/show.json.jbuilder
db/migrate/20191015193638_remove_background_job_results_code.rb
db/structure.sql
openapi.json
spec/factories/background_job_results.rb
spec/jobs/create_virtual_objects_job_spec.rb
spec/jobs/publish_job_spec.rb
spec/requests/background_job_results_spec.rb
spec/requests/publish_object_spec.rb

Objects that have several hundred files may take several minutes to publish, so make this an asynchronous job.  In our testing we found a 600 page book took over 82s to publish
Yes

Publish objects using a background job

---

app/services/item_query_service.rb
app/services/workflow_error_checking_service.rb
spec/services/item_query_service_spec.rb
spec/services/workflow_error_checking_service_spec.rb

To prevent items in an error state from being combined in a virtual merge operation. Requested by @andrewjbtw to restore behavior prior to [this change](https://github.com/sul-dlss/dor-services-app/commit/6d2c990b768556d12a7660a6db984d93dc6dfb6d#diff-d94618b2b5aef0b32a18a4a63b556d4e).
Not necessary.

Check an item's workflow for any errors with the current version

---

app/services/publish_metadata_service.rb

This behavior was originally introduced here: https://github.com/sul-dlss/dor-services/commit/439b8084f5f36567bbefeb954f40ebee82268ff1#diff-8200ce146e3aa5427aa3d4f563164195R81-R82 but none of us (including Ben) can understand why this would be necessary.  Since this slows things down and adds fragility, remove it.
N/A.

Avoid looking for release tags in PURL

---

config/initializers/dor_config.rb
config/settings.yml
config/settings/development.yml

This change was made for consistency as it matches how we do configuration in Argo.
Additionally this allows us to run in development mode without SSL configured.
This depends on https://github.com/sul-dlss/shared_configs/pull/1101
n/a

Don't configure SSL on development

---

app/controllers/workspaces_controller.rb
app/services/cleanup_reset_service.rb
app/services/prune_service.rb
openapi.json
spec/controllers/workspaces_controller_spec.rb
spec/requests/cleanup_workspace_spec.rb

Previously it was just returning 500 with no message
So that common-accessioning has a clue about what went wrong: https://app.honeybadger.io/projects/52894/faults/53522097
yes.

Return a helpful message if a directory doesn't exist

---

.circleci/config.yml
db/structure.sql
docker-compose.yml

You may need to remove the old volume first if you have one.
```
docker-compose down --volumes
```
Because PG 10 is far out of date.
n/a

Upgrade to postgres 11

---

app/controllers/shelves_controller.rb
app/jobs/shelve_job.rb
openapi.json
spec/jobs/shelve_job_spec.rb
spec/requests/shelving_spec.rb

So that web archiving shelving jobs don't time out.
Some web archiving jobs were timing out when processing.
Fixes #485
Yes

Move shelving to a background job

---

config/deploy.rb
config/sidekiq.yml

Currently running one process and we've pegged out the CPU, but only on one core.
This reduces concurrency on each process but increases the number of processes
n/a

Increase the number of sidekiq processes to 3

---

app/jobs/shelve_job.rb

The database connection seems to go bad in very long (> 3 hour long jobs)
n/a

Try releasing and reconnecting to the db

---

app/controllers/workspaces_controller.rb
app/services/reset_workspace_service.rb
openapi.json
spec/controllers/workspaces_controller_spec.rb
spec/requests/reset_workspace_spec.rb
spec/services/reset_workspace_service_spec.rb

Previously it was just giving a 500 error without context or a helpful message.
Yes.

Provide better error messages for reset workspace

---

app/controllers/workspaces_controller.rb
app/services/cleanup_service.rb
app/services/prune_service.rb
spec/requests/cleanup_workspace_spec.rb

Better errors when a directory can't be deleted.
n/a

Provide error handling for when the directory can't be deleted

---

app/jobs/log_failure_job.rb
app/jobs/log_success_job.rb
app/jobs/preserve_job.rb
app/jobs/publish_job.rb
app/jobs/shelve_job.rb
app/jobs/start_preservation_workflow_job.rb
app/services/sdr_ingest_service.rb
spec/jobs/log_failure_job_spec.rb
spec/jobs/log_success_job_spec.rb
spec/jobs/preserve_job_spec.rb
spec/jobs/publish_job_spec.rb
spec/jobs/shelve_job_spec.rb
spec/jobs/start_preservation_workflow_job_spec.rb
spec/services/sdr_ingest_service_spec.rb

This avoids the need for common-accessioning to poll for job completion
Depends on https://github.com/sul-dlss/workflow-server-rails/pull/271

Callback to the workflow service when step is complete

---

app/controllers/objects_controller.rb
app/jobs/log_failure_job.rb
app/jobs/log_success_job.rb
app/jobs/publish_job.rb
app/jobs/shelve_job.rb
spec/jobs/log_failure_job_spec.rb
spec/jobs/log_success_job_spec.rb
spec/jobs/publish_job_spec.rb
spec/jobs/shelve_job_spec.rb
spec/requests/publish_object_spec.rb

Where there is no workflow to call back to
We hadn't considered the case where Argo can do a publish outside of a workflow.
n/a

Handle the case where argo triggers publish

---

app/jobs/log_success_job.rb
app/jobs/shelve_job.rb
spec/jobs/shelve_job_spec.rb

The LogSuccessJob should always receive a workflow argument (which can be nil)
n/a

ShelveJob should provide a workflow for logging

---

app/controllers/metadata_controller.rb
app/services/legacy_metadata_service.rb
config/routes.rb
openapi.json
spec/requests/legacy_metadata_update_spec.rb
spec/services/legacy_metadata_service_spec.rb

This can be used by accessionWF robots so they don't need to make Fedora calls
yes.

Add an API endpoint for handling legacy metadata

---

app/controllers/objects_controller.rb

To surface better error info to the caller (e.g. argo) when objects fail cocina model validation
Current error messages suck:
for argo:  (https://app.honeybadger.io/projects/49894/faults/57442187)
```
Dor::Services::Client::UnexpectedResponse: Internal Server Error: 500 (Response from dor-services-app did not contain a body.                         Check honeybadger for dor-services-app for backtraces,                         and look into adding a `rescue_from` in dor-services-app                         to provide more details to the client in the future)
```
same reflected in dor-services-app: (https://app.honeybadger.io/projects/50568/faults/57389070)
```
Dry::Struct::Error: [Cocina::Models::DRO.new] nil (NilClass) has invalid type for :label violates constraints (type?(String, nil) …
```

add info from Dry::Struct::Error to 500 errors in objects#show

---

app/services/metadata_service.rb
app/services/refresh_metadata_action.rb
spec/services/metadata_service_spec.rb

Based on a discussion in `#dlss-aaas` about metadata refreshes for objects with both a catkey and a barcode, it may be necessary to prefer they catkey when both are present.  This returns the identifiers in a preferred order based on the known prefixes configured so that when the first is selected it will work as desired.

return metadata identifiers in preferred order

---

app/controllers/metadata_refresh_controller.rb
app/services/legacy_metadata_service.rb
app/services/refresh_metadata_action.rb
spec/requests/metadata_refresh_spec.rb
spec/services/legacy_metadata_service_spec.rb

This catches problems earlier than when this was done in common-accessioning
n/a

Validate that object is valid before saving.

---

app/jobs/create_virtual_objects_job.rb
app/services/constituent_service.rb
spec/jobs/create_virtual_objects_job_spec.rb

Because virtual object creation is busted on the Argo side when dor-services-app returns a mix of successful and failed results.
no

Trap constituent service nils argo#1728

---

app/controllers/sdr_controller.rb
app/services/sdr_client.rb
openapi.json

To make deprecation more consistent;  as I will be deprecating the rest of the SDR related code soon, I was paying attention.
Yup.

be more consistent with deprecation messages

---

app/controllers/sdr_controller.rb
openapi.json

To DRY up deprecation warning strings and mark endpoint as deprecated in the API doc
yes

DRY up deprecation warning strings and mark endpoint as deprecated

---

app/controllers/sdr_controller.rb
app/services/digital_stacks_service.rb
app/services/sdr_client.rb
app/services/shelving_service.rb
config/routes.rb
openapi.json
spec/controllers/sdr_controller_spec.rb
spec/services/sdr_client_spec.rb
spec/services/shelving_service_spec.rb

DRAFT:  
- ~~must not be deployed until sul-dlss/preservation_catalog/pull/1250 is deployed.~~
- ~~should not be deployed until sul-dlss/common-accessioning/pull/465 is deployed~~
To get rid of  `cm-inv-diff` API endpoint in sdr-services-app.  We use preservation-client `shelve_content_diff` method instead.
yes - marked DEPRECATED there and also in the code.

Shelve w pres client

---

app/controllers/sdr_controller.rb
app/services/sdr_client.rb
config/routes.rb
openapi.json

- ~~should not be deployed before sul-dlss/argo#1741 is deployed~~
To get rid of `content` and `metadata` API endpoints in sdr-services-app. We use preservation-client gem's `content` or `metadata` method in the caller instead, going directly to preservation-catalog API.
- only caller of `content`:
- was here:  https://github.com/sul-dlss/argo/blob/master/app/controllers/files_controller.rb#L28
- PR sul-dlss/argo#1741
- only caller of `metadata`
- was here: https://github.com/sul-dlss/common-accessioning/blob/master/lib/technical_metadata_service.rb#L105
- PR sul-dlss/common-accessioning/pull/465, deployed with Monday updates on 12/9
yes - marked deprecated there and also in the code.

deprecate API endpoints sdr#content, sdr#metadata and SdrClient.file_content, SdrClient.metadata

---

app/jobs/preserve_job.rb
spec/jobs/preserve_job_spec.rb

Currently there are a lot of jobs that were created when a different branch of code was deployed. Now their failure can't be logged because the wrong arguments are not passed.  Extracted from #506
Fixes #523
n/a

PreserveJob must be called with a workflow

---

app/jobs/start_preservation_workflow_job.rb
app/services/sdr_ingest_service.rb
config/settings.yml
spec/jobs/start_preservation_workflow_job_spec.rb

So that the workflow server can log some record that this job finished successfully.
Ref https://github.com/sul-dlss/workflow-server-rails/pull/293
n/a

Callback when preservation ingest has started

---

.circleci/config.yml

To validation that openapi.json is valid json.
Nope.

Adds JSON validation of openapi.json

---

app/jobs/preserve_job.rb
app/services/sdr_client.rb
app/services/sdr_ingest_service.rb
spec/services/sdr_ingest_service_spec.rb

- ~~PR #529 to use preservation-client v1.0.0 must be merged first, and then this will need a rebase.~~
To get rid of `manifest` API endpoint in sdr-services-app. We use preservation-client `signature_catalog` method instead.
no need as the `manifest` method here was already deprecated.

SdrIngestServices uses pres-client to get signature_catalog (manifest)

---

app/jobs/preserve_job.rb
app/jobs/start_preservation_workflow_job.rb
app/services/version_service.rb
spec/jobs/preserve_job_spec.rb
spec/jobs/start_preservation_workflow_job_spec.rb
spec/services/version_service_spec.rb

Not passing a version is deprecated as the workflow server would have to call back to dor-services-app to get the current version.
n/a

Pass a version when starting a workflow

---

Gemfile.lock

So that all of our projects are consistently on bundler 2.
n/a

Update to bundler 2

---

Gemfile
Gemfile.lock
app/controllers/objects_controller.rb
app/controllers/virtual_objects_controller.rb
config/application.rb
openapi.json
spec/requests/add_release_tags_spec.rb
spec/requests/batch_create_virtual_objects_spec.rb
spec/requests/cleanup_workspace_spec.rb
spec/requests/notify_goobi_spec.rb
spec/requests/preserve_spec.rb
spec/requests/publish_object_spec.rb
spec/requests/reset_workspace_spec.rb
spec/requests/shelving_spec.rb
spec/requests/update_marc_record_spec.rb

This uses the spec for validating requests instead of it just being for documentation. This ensures our documentation is up to date and accurate
Yes

Use committee middleware to verify requests using OpenAPI

---

openapi.json
spec/requests/status_spec.rb

Health checks from Nagios were now getting 404
yes

Add status checks to the OAS

---

openapi.json

Presently the middleware prevents us from monitoring sidekiq.
Ideally this would probably be on a different machine (similar to robot-console)
yes

Add sidekiq support to openapi

---

openapi.json

Currently we are prohibited from looking at particular queues in the dashboard.
yes

Add route for particular sidekiq queues

---

openapi.json

Currently we can't retry jobs from the UI
yes

Add endpoints for retrying jobs

---

app/controllers/versions_controller.rb
app/jobs/create_virtual_objects_job.rb
app/services/constituent_service.rb
app/services/sdr_ingest_service.rb
app/services/shelving_service.rb
app/services/version_service.rb
spec/controllers/versions_controller_spec.rb

closes #545
To make sure that preservation client errors are handled correctly.
No.

Handles and/or documents pres client errors.

---

app/jobs/preserve_job.rb
spec/jobs/preserve_job_spec.rb

Honeybadger is not notifying on these errors, so we only see them by the BackgroundJobId that is in the error message of the workflow process.
n/a

Log errors in PreserveJob in Honeybadger

---

README.md

Viewing on the web is more convenient
n/a

Update link to generated docs

---

Dockerfile

Currently it won't build the image because the Gemfile.lock requires bundler 2.
n/a

Install bundler 2 for docker

---

.circleci/config.yml
Gemfile
Gemfile.lock
README.md
spec/spec_helper.rb

Because we use CodeClimate generally, and this adds maintainability stats. Also, coveralls wasn't integrated with PR checks...

Replace Coveralls with CodeClimate

---

Gemfile.lock

To prevent https://github.com/sul-dlss/dor-workflow-client/issues/144, an error when closing versions.
No.

Updated dor-workflow-client to 3.15.1.

---

Gemfile
Gemfile.lock

So we don't have to depend on git to retrieve the code we need.
n/a

update openapi_parser to a released version

---

app/jobs/preserve_job.rb
app/jobs/publish_job.rb
app/jobs/shelve_job.rb
spec/jobs/preserve_job_spec.rb
spec/jobs/publish_job_spec.rb
spec/jobs/shelve_job_spec.rb

closes #563
So that jobs that update workflows report errors to the correct workflow step.
No.

Set correct workflow steps to report errors for jobs.

---

Gemfile
Gemfile.lock
config/initializers/preservation_client.rb
config/settings.yml

HOLD until: 
pres cat will start requiring that all API clients supply an auth token, or their requests will be rejected as Unauthorized.
Fixes #573
connects to sul-dlss/preservation_catalog#1298
blocks sul-dlss/preservation_catalog#1306
n/a

pass auth token to pres-client

---

app/jobs/log_failure_job.rb

When reporting a workflow error, the error message was split between `error_msg` and `error_txt` fields. The intended use of the `error_txt` field is unclear and is not displayed in Argo.
To address this, the complete error message was added to `error_msg` field.
See https://github.com/sul-dlss/argo/issues/1762
No.

Provides complete workflow error in error_msg field.

---

docker/invoke.sh

The docker container is not correctly starting.
```
$ docker logs -f hydrus_dor-services-app_1
HOST IS: db
Postgres is up - Setting up database
Creating DB. OK to ignore errors about test db.
./docker/invoke.sh: line 18: rails: not found
Migrating db
./docker/invoke.sh: line 23: rails: not found
```
No.

Correctly reference rails when starting docker container.

---

app/controllers/events_controller.rb
app/models/event.rb
app/views/events/index.json.jbuilder
config/routes.rb
db/migrate/20191209192646_create_events.rb
db/structure.sql
openapi.json
spec/requests/events_spec.rb

~DO NOT MERGE:  per F2F team discussions on Jan 7, 2020, we want to wait on this.~
Per team discussion on Jan 14, 2020, okay to proceed.
This is a solution to preservation_catalog#1249 and can also be used as our "provenance service" as well as for adding events showing the objects progress through workflows.
yes.

Add an endpoint for creating events

---

Gemfile
Gemfile.lock
app/jobs/start_preservation_workflow_job.rb
spec/jobs/start_preservation_workflow_job_spec.rb

closes #583
So that new workflows inherit the lane id from the workflow that created it.
No.

Pass lane_id when creating workflow in start_preservation_workflow_job.

---

app/controllers/events_controller.rb
app/controllers/objects_controller.rb
app/controllers/shelves_controller.rb
app/controllers/versions_controller.rb
app/jobs/publish_job.rb
app/jobs/shelve_job.rb
app/services/event_factory.rb
app/services/legacy_metadata_service.rb
app/services/publish_metadata_service.rb
app/services/registration_service.rb
app/services/shelving_service.rb
app/services/version_service.rb
spec/jobs/publish_job_spec.rb
spec/jobs/shelve_job_spec.rb
spec/requests/versions_spec.rb
spec/services/legacy_metadata_service_spec.rb
spec/services/publish_metadata_service_spec.rb
spec/services/registration_service_spec.rb
spec/services/shelving_service_spec.rb
spec/services/version_service_spec.rb

So that we log important events for an object.
n/a

Instrument the code with events

---

app/jobs/preserve_job.rb
app/jobs/publish_job.rb
app/jobs/shelve_job.rb
spec/jobs/preserve_job_spec.rb
spec/jobs/publish_job_spec.rb
spec/jobs/shelve_job_spec.rb

So that workflow step status is set to started.
See https://github.com/sul-dlss/common-accessioning/issues/505
No

Sets workflow step status to started when workflow-related jobs.

---

Gemfile
Gemfile.lock

This was pinned back when we used  dor-workflow-service 2.2.1 which depended on net-http-persistent, but that dependency has bee removed from dor-workflow-service, so we can remove this entirely
n/a

remove unused dependency

---

app/controllers/metadata_controller.rb
openapi.yml
spec/requests/legacy_metadata_update_spec.rb

This will allow us to refactor the provenance robot so that it doesn't need to hit Fedora directly
yes.

Add provenance metadata to the legacy update endpoint

---

Gemfile
Gemfile.lock
app/services/cocina/mapper.rb
openapi.yml
spec/requests/show_object_spec.rb

This will enable us to decouple common-accessioning from direct Fedora calls
Yes

Provide administrative properties of an APO via the Cocina API

---

Gemfile
Gemfile.lock
app/services/cocina/mapper.rb
openapi.yml
spec/requests/show_object_spec.rb
spec/services/cocina/mapper_spec.rb

This will allow the technicalMetadata and shelve robots to see if there are any files. We want to skip those steps when there are no files
n/a

Map contentMetadata to cocina models

---

Gemfile
Gemfile.lock
app/services/cocina/mapper.rb
openapi.yml
spec/requests/collections_for_object_spec.rb
spec/services/cocina/mapper_spec.rb

It's expected here: https://github.com/sul-dlss/common-accessioning/blob/76304371a7fec9c87ea0007325c3e1e34d65e63c/lib/robots/dor_repo/accession/rights_metadata.rb#L27
yes

Add admin policy to cocina models

---

app/controllers/events_controller.rb
app/controllers/objects_controller.rb
app/controllers/shelves_controller.rb
app/jobs/publish_job.rb
app/jobs/shelve_job.rb
app/services/event_factory.rb
app/services/legacy_metadata_service.rb
app/services/publish_metadata_service.rb
app/services/registration_service.rb
app/services/shelving_service.rb
spec/jobs/publish_job_spec.rb
spec/jobs/shelve_job_spec.rb
spec/services/publish_metadata_service_spec.rb
spec/services/shelving_service_spec.rb

Version events were not supplying host.  All jobs now specify which system invoked them.
n/a

Refactor events to supply additional attributes

---

spec/services/cocina/mapper_spec.rb

This is fixed by upgrading cocina-models. Previously trying to convert a collection with release tags would result in an error:
```
undefined method `releaseTags' for #<Cocina::Models::Collection::Administrative>
```
yes

Support for collections with release tags

---

app/services/version_service.rb
spec/services/version_service_spec.rb

This will enable us to record all the information currently in the events datastream.
Fixes #612
n/a

Add who wrote a version to the version event

---

app/services/event_factory.rb

Honeybadger was showing null pointer errors
no.

Don't send invoked_by when there is no context

---

config/initializers/wrap_parameters.rb

This was causing parameters passed to services to be wrapped in an extra hash with "object" as the keys:
```
Parameters: {"object_type"=>"item", "source_id"=>"googlebooks:stanford_20500066514", "admin_policy"=>"druid:sc012gz0974", "tag"=>["Process : Content Type : Book (ltr)", "Registered By : jcoyne85@stanford.edu"], "label"=>":auto", "collection"=>"druid:hv320hk4091", "rights"=>"default", "metadata_source"=>"symphony", "other_id"=>"symphony:10048349", "object"=>{"object_type"=>"item", "source_id"=>"googlebooks:stanford_20500066514", "admin_policy"=>"druid:sc012gz0974", "tag"=>["Process : Content Type : Book (ltr)", "Registered By : jcoyne85@stanford.edu"], "label"=>":auto", "collection"=>"druid:hv320hk4091", "rights"=>"default", "metadata_source"=>"symphony", …
```

Disable ParamsWrapper

---

app/controllers/objects_controller.rb
app/models/dor/registration_response.rb
app/services/registration_service.rb
spec/requests/register_object_spec.rb
spec/services/registration_service_spec.rb

Also refactored tests and removed a Location header from a 4xx response.
* This avoids duplication in computing the location header.
* The old tests grouped multiple scenarios into one test.
* Location headers only make sense on 3xx or 201 responses: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Location
n/a

Refactor: Have the RegistrationService return the RegistrationResponse

---

app/models/dor/update_marc_record_service.rb

Use #dig as it's more readable

---

openapi.yml

And clarify the documentation.
To fix https://app.honeybadger.io/projects/49894/faults/46068943
Yes.

Stop marking source_id as a required property in API spec

---

app/services/registration_service.rb
app/services/reset_workspace_service.rb
spec/services/registration_service_spec.rb

Defaulting from the admin policy object
All objects, when registered should have rightsMetadata.
n/a

Registering an APO should set rightsMetadata

---

Gemfile
Gemfile.lock
app/services/cocina/mapper.rb
spec/requests/show_object_spec.rb

Connects to sul-dlss/common-accessioning#556
To fix a production bug with APOs asserting parent APOs.
no

Allow Cocina::Mapper to build APOs with parent APOs

---

app/services/registration_service.rb
spec/services/registration_service_spec.rb

The label is already trimmed by the RegistrationRequest class
n/a

Stop trimming the label

---

app/services/registration_service.rb
spec/services/registration_service_spec.rb

Using model properties will help us be able to change the implementation without having to change the interface.
n/a

Use model properties rather than add_value

---

app/controllers/marcxml_controller.rb
config/routes.rb
openapi.yml
spec/requests/get_marcxml_spec.rb

closes #594
To re-add a route for getting the MARCXML for an object, so that it can be used to determine the rights of Google books.
Yes.

Re-adds route for getting MARCXML.

---

config/routes.rb

This, and the replaced code, are both incantations listed in the Sidekiq wiki: https://github.com/mperham/sidekiq/wiki/Monitoring#forbidden
I confirmed this was the right incantation by SSHing to a deployed instance and running:
```
2.5.0 :001 > Rails.configuration.secret_token
=> nil
2.5.0 :002 >  Rails.application.credentials[:secret_key_base]
=> nil
2.5.0 :003 > Rails.application.secrets[:secret_key_base]
=> "a non-nil value which is hidden here to protect the instance"
```
I did this because I noticed when troubleshooting sul-dlss/argo#1800 that I could not use the Sidekiq UI to delete or kill individual jobs. I briefly entertained the idea that this was related to committee/OpenAPI but this is not related to OpenAPI.
no

Fix forbidden errors when browsing sidekiq routes

---

app/controllers/objects_controller.rb
spec/requests/register_object_spec.rb

These are parameters added by rails and they just clutter the event data. This filters them out.
n/a

Don't log action and controller in the register event

---

app/services/registration_service.rb
spec/fixtures/apo_druid_fg890hi1234.xml
spec/services/registration_service_spec.rb

We no longer rely on this behavior, and it would be challenging to migrate this from Fedora 3.
Fixes sul-dlss/argo#1802
n/a

Remove the copying relationships from APOs when registering

---

app/services/registration_service.rb
spec/services/registration_service_spec.rb

You must either pass metadata_source='label' or seed_datastreams=['descMetadata'] or this won't be able to make descMetadata
n/a

Raise an error if there is no way to produce the descMetadata

---

app/services/registration_service.rb

So we don't block APOs from registering.
n/a

Update our understanding of how APOs flow through the system

---

app/services/embargo_release_service.rb
config/initializers/activefedora_solr_updates.rb

This mimics what Argo is doing and allows dor_indexing_app to handle all indexing. This is an important step as the indexing code is no longer shared in dor-services gem, so they could potentially be indexing different things.  This also helps reduce load on solr, as every write to fedora already triggers an indexing action via a message from Fedora 3 to activemq, which is read by dor_indexing_app. Furthermore, this increases the reliability of dor-services-app as we no longer have a dependency on writing to solr regularly (see https://app.honeybadger.io/projects/50568/faults/60653735).
Fixes #30
n/a

Disable writing to solr

---

app/controllers/objects_controller.rb
app/services/cocina/mapper.rb
spec/services/cocina/mapper_spec.rb

ETDs don't have descMetadata, so must have special handling.
Fixes  argo/issues#1806
n/a

Etds must have their own mapping to cocina

---

app/controllers/metadata_controller.rb
openapi.yml
spec/requests/legacy_metadata_update_spec.rb

closes #645
To handle a Rubydora error that is thrown when two requests are made concurrently to the same resource.
Yes.

Handles Rubydora error when updating legacy metadata.

---

app/models/etd.rb
spec/models/etd_spec.rb

This is necessary, so that Dor.find will cast etds to this type. Otherwise it'll say: `Etd is not a real class` and return a `Dor::Item`. This is necessary for the `Cocina::Mapper` because Etds do not use descMetadata like ever other object.

Add an etd class so that they can be instantiated via Dor.find

---

app/models/registration_request.rb
app/services/registration_service.rb
openapi.yml
spec/services/registration_service_spec.rb

Fixes #632
To allow for upstream apps to pass abstracts to dor-services-app instead of doing this directly in DOR (in support of decoupling from Fedora).
no

Allow registration requests to specify an optional value for abstract

---

app/controllers/objects_controller.rb
app/controllers/release_tags_controller.rb
app/models/dor/update_marc_record_service.rb
app/services/publish_metadata_service.rb
app/services/release_tags.rb
config/routes.rb
openapi.yml
spec/requests/add_release_tags_spec.rb
spec/services/release_tags_spec.rb

Connects to sul-dlss/google-books#283
Connects to sul-dlss/dor_indexing_app#336
Includes:
* Extract release tags action from objects controller into its own controller
* Add new `#show` action to `ReleaseTagsController`
* Use Committee for validating the `ReleaseTagsController#create` action
* Favor Rails built-in params handling to custom (outdated) handling
* Consolidate release tags-related functionality into `ReleaseTags` service
* Update OpenAPI specification
Yes.

Add endpoint for displaying release tags

---

app/controllers/release_tags_controller.rb
app/services/release_tags.rb
openapi.yml

The documentation did not reflect the totality of what it was doing and one may have wondered why they shouldn't just rely on the tags that are in the object metadata.
yes.

Improve the documentation for release tags service

---

Gemfile
Gemfile.lock
app/services/cocina/object_creator.rb

So that we use the libraries functions, rather than rebuilding.
n/a

Use the build_request method from cocina-models

---

app/services/cocina/mapper.rb
app/services/cocina/object_creator.rb
app/services/embargo_service.rb
openapi.yml
spec/requests/show_object_spec.rb
spec/services/embargo_service_spec.rb

closes #659
So that embargo can be set when doing a cocina deposit.
No.

Adds Embargo Service and uses when doing a cocina deposit.

---

app/controllers/members_controller.rb
app/views/members/index.json.jbuilder
config/routes.rb
openapi.yml
spec/requests/members_for_collection_spec.rb

This allows consumers to determine the members of a collection. Adding this will allow us to close down the dor-fetcher-service and retire the dor-fetcher client.
yes

Add an endpoint that can replace all extant uses of dor-fetcher

---

app/services/cocina/dro_structural_builder.rb
app/services/cocina/mapper.rb
app/services/cocina/object_creator.rb
spec/requests/create_object_spec.rb

I made a mistake earlier and applied the viewingDirection to Images rather than Books.
n/a

Books have viewingDirection, not images

---

app/services/cocina/object_creator.rb
app/services/registration_service.rb
spec/requests/create_object_spec.rb

So we can track when this method was used for registration.
n/a

The new registration method logs an event

---

openapi.yml

Correct agreement type URI in OpenAPI specification

---

app/controllers/metadata_controller.rb
app/services/legacy_metadata_service.rb
openapi.yml
spec/requests/legacy_metadata_update_spec.rb

This will be used by the etd robots so they can be decoupled from Fedora 3
Ref sul-dlss/common-accessioning#582
yes

Allow identityMetadata to be updated using the legacy metadata API

---

app/services/cocina/dro_structural_builder.rb
spec/services/cocina/mapper_spec.rb

Some old objects (circa 2011) use these upcased algorithms.  Modern objects use the downcased version
n/a

Support old digest algorithm codes

---

app/services/cocina/object_creator.rb
app/services/metadata_service.rb
spec/requests/create_object_spec.rb

Fixes #316
So that we don't have `:auto` as the label for new google books.
n/a

Get the label from the catalog when a catkey is provided

---

app/services/cocina/dro_structural_builder.rb
openapi.yml
spec/services/cocina/mapper_spec.rb

Fixes #686
To show the MIME type on the Cocina side of the world.
yes

Pull MIME type from contentMD and map to Cocina model

---

app/controllers/objects_controller.rb
app/models/symphony_reader.rb
openapi.yml
spec/models/symphony_reader_spec.rb
spec/requests/legacy_register_object_spec.rb

closes #694
So that a correct error was returned when Symphony failed. And stop spamming HB.
Yes

Returns 502 from symphony error. Stop logging to HB.

---

Gemfile
Gemfile.lock
app/services/cocina/dro_structural_builder.rb
spec/services/cocina/mapper_spec.rb

Fixes #683 - adds `hasAgreement` to cocina Mapper now that `hasAgreement` is in the structural metadata
N/A

Bump cocina-models to 0.25.0 and add hasAgreement to cocina mapper

---

app/services/cocina/object_creator.rb
spec/requests/create_object_spec.rb

closes #700
So that rights are set when creating an item.
No.
No.

Sets default rights for an item.

---

app/services/cocina/object_creator.rb
spec/requests/create_object_spec.rb

To correct the order in which rights and embargo were applied. (Rights should be set before embargo, as embargo modifies the rights.)
No
No

Change rights before applying embargo.

---

app/controllers/objects_controller.rb
app/controllers/versions_controller.rb
app/services/version_service.rb
config/routes.rb
openapi.yml
spec/requests/start_accession_spec.rb

part of #702 to allow for reaccessioning via Goobi
when done, return to the checklist in #702 
yes

implement endpoint for starting accessioning

---

Gemfile
Gemfile.lock

Tracking a git branch is less stable than using a tagged release like this.
n/a

Upgrade to faraday-middleware 1.0.0.rc1

---

app/services/cocina/object_creator.rb
app/services/content_metadata_generator.rb
openapi.yml
spec/requests/create_object_spec.rb
spec/services/content_metadata_generator_spec.rb

Generate contentMetadata when RequestFileSets are provided

---

openapi.yml

Correct typo in OpenAPI spec description

---

app/controllers/objects_controller.rb
app/services/embargo_release_service.rb
spec/requests/start_accession_spec.rb
spec/services/embargo_release_service_spec.rb

to deal with https://app.honeybadger.io/projects/50568/faults/61304607 when testing new accession call from #703 
also per-empetively fix the same issue in release service

update versioning calls to deal with new event factory

---

Gemfile
Gemfile.lock

Pin iso-639 until we upgrade to ruby 2.6

Pin iso-639 to 0.2.x

---

Gemfile

Clarifying comment as suggested by @ndushay

Add extended commend related to iso-639

---

app/services/cocina/dro_structural_builder.rb
app/services/cocina/mapper.rb
spec/services/cocina/mapper_spec.rb

When a file has image height and width, they need to be mapped to the cocina model.
fixes #692 
n/a
DOES this need to be tested in stage?  There is already a ticket to add an integration test to that suite:  sul-dlss/infrastructure-integration-test#23

image files populate presentation attribute in cocina-model

---

Gemfile
Gemfile.lock
app/services/cocina/access_builder.rb
app/services/cocina/object_creator.rb
openapi.yml
spec/requests/create_object_spec.rb
spec/requests/show_object_spec.rb
spec/services/cocina/access_builder_spec.rb

So that GB can add these properties.
ref sul-dlss/google-books#331
ref sul-dlss/google-books#333
yes

Map copyright and use and reproduction statement to Cocina model

---

openapi.yml

openapi enums are case sensitive, and the significance should come in as lower case (and currently does from argo, and new accession method from dor-services-app)
yes

lower case openapi enum for versioning significance values

---

app/controllers/objects_controller.rb
spec/requests/show_object_spec.rb

Previously when you call `Dor.find` on a ETD druid it would load it as a `Dor::Item`, which causes the mapper to produce an invalid Cocina model
Ref sul-dlss/hydra_etd#327
n/a
yes

Load ETDs as ETDs

---

app/controllers/versions_controller.rb
openapi.yml
spec/services/version_service_spec.rb

to fix a regression introduced in #703 
fixes sul-dlss/argo#1843
basically I inadvertently renamed one of the permitted params in the "close" method to match my new endpoint name, when it should have been left alone ... renaming it caused the existing parameter to be ignored, triggering accessionWF in all cases (even when you didn't want to be triggered with a close version)
n/a

Fix for reaccession issues

---

app/services/cocina/mapper.rb
spec/services/cocina/mapper_spec.rb

closes #695
To provide a more informative error when no sourceId.
No.
No.

Raises informative error when no sourceId.

---

app/models/etd.rb
spec/models/etd_spec.rb

So that the legacy metadata update endpoint can be used
n/a
Yes, it fixes etd robots.

Add contentMetadata to ETDs

---

app/services/cocina/dro_structural_builder.rb
app/services/cocina/object_creator.rb
openapi.yml
spec/requests/create_object_spec.rb
spec/requests/show_object_spec.rb
spec/services/cocina/mapper_spec.rb

And returned by the show endpoint.
Fixes https://github.com/sul-dlss/google-books/issues/391
yes
yes
it will be tested on stage.

Allow collections to be set by the create endpoint

---

app/services/cocina/dro_structural_builder.rb
spec/services/cocina/mapper_spec.rb

to fix a problem where ETDs were not being shelved due to a no longer needed conditional

Allow etds to shelve

---

app/services/cocina/object_creator.rb
app/services/registration_service.rb
app/services/synchronous_indexer.rb
config/settings.yml
spec/requests/create_object_spec.rb
spec/services/registration_service_spec.rb

Since Fedora 3 has no unique constraints, we have to check Solr to see if a sourceId has already been used.  If several requests for one sourceId come in during the latency in the asynch indexing, then we can violate the "source ids should be unique" constraint.  Doing synchronous indexing, narrows the window of time in which such a problem could occur.
Fixes sul-dlss/argo#1845
n/a
n/a

When registering an object, immediately index to Solr

---

app/services/embargo_release_service.rb
lib/tasks/dor_services_app.rake
spec/services/embargo_release_service_spec.rb

Rather than the indirection of Embargoable.  The embargoable methods will be deprecated in dor-services
n.a
no

Call Dor::EmbargoService directly

---

Gemfile
Gemfile.lock
app/services/cocina/access_builder.rb
app/services/cocina/object_creator.rb
app/services/embargo_service.rb
openapi.yml
spec/services/cocina/access_builder_spec.rb
spec/services/embargo_service_spec.rb

So that the useAndReproduction can be changed when the embargo expires
Ref: https://github.com/sul-dlss/google-books/issues/398
yes
Yes

Add useAndReproductionStatement to the embargo

---

app/services/content_metadata_generator.rb
spec/services/content_metadata_generator_spec.rb

refs https://github.com/sul-dlss/google-books/issues/393
So that the resource type is correctly set to "object" when not a "page".
No.
No.

Fix resource type for book files.

---

Gemfile
Gemfile.lock
app/services/cocina/mapper.rb
app/services/cocina/object_creator.rb
openapi.yml
spec/requests/create_object_spec.rb
spec/services/cocina/mapper_spec.rb

refs https://github.com/sul-dlss/google-books/issues/415
So that Google Books can set a project tag.
Yes.
Not yet.

Adds support for project tags.

---

app/services/administrative_tags.rb
spec/services/administrative_tags_spec.rb

Administrative tags are not persisting when created via the administrative tags endpoint.
```
2.6.5 :004 > client.object('druid:nn225zd9469').administrative_tags.create(tags: ["barcode : 20503407474"])
=> true 
2.6.5 :005 > client.object('druid:nn225zd9469').administrative_tags.list
=> ["Process : Content Type : Book (ltr)", "Project : Google Books"] 
```
No
Yes

Fixes creating administrative tags from administrative tags endpoint.

---

app/services/synchronous_indexer.rb
config/settings.yml
spec/requests/create_object_spec.rb
spec/services/registration_service_spec.rb

When the "/" character is first, Faraday assumes an absolute URL, which causes problems when the Faraday connection was initiated with a base path specified. Uncovered this while testing administrative tags work.
No.
It does. And it *works* now!

Use relative path when POSTing to reindex remotely

---

app/services/cocina/dro_structural_builder.rb
spec/services/cocina/mapper_spec.rb

Prevent cocina model validation error when mime-type isn't present

---

app/services/cocina/dro_structural_builder.rb
spec/services/cocina/mapper_spec.rb

closes #749
To fill in the mapping from Fedora to Cocina model.
No
No

Added mapping of file access and administrative.

---

app/controllers/administrative_tags_controller.rb
app/models/administrative_tag.rb
app/models/dor/service_item.rb
app/services/administrative_tags.rb
app/services/cocina/dro_structural_builder.rb
app/services/cocina/mapper.rb
app/services/cocina/object_creator.rb
app/services/registration_service.rb
app/services/release_tags/identity_metadata.rb
config/routes.rb
db/migrate/20200226171829_create_administrative_tags.rb
db/structure.sql
openapi.yml
spec/dor/goobi_spec.rb
spec/dor/service_item_spec.rb
spec/factories/administrative_tags.rb
spec/models/administrative_tag_spec.rb
spec/rails_helper.rb
spec/requests/administrative_tags_spec.rb
spec/services/administrative_tags_spec.rb
spec/services/release_tags/identity_metadata_spec.rb

Connects to #679
This change allows reading administrative tags from the database OR Fedora, and only writes them TO the database, which will give us some time to pull off the migration of tags from Fedora to the database, making a gradual transition.
Yes.
I don't think it does. Tested in stage and in this integration test: https://github.com/sul-dlss/infrastructure-integration-test/pull/34

Store administrative tags in the database

---

app/models/administrative_tag.rb
app/services/administrative_tags.rb
spec/services/administrative_tags_spec.rb

To deal with known bad data on production
No
Yes, it should make for less error-ful interaction

Fix tags with known-weird pattern when migrating

---

app/services/administrative_tags.rb

To prevent lots of HB alerts.
No.
No.

Ignore duplicate validation errors when migrating new records

---

app/services/legacy_tag_service.rb
spec/services/administrative_tags_spec.rb
spec/services/legacy_tag_service_spec.rb

To pull (eventually) dead code in dor-services gem into the app.
No.
No.

Extract dor-services tag services to dor-services-app

---

app/services/administrative_tags.rb

This is the exception thrown, and it does not give us any useful information in an alert since the migrations appear to be working without missing tags.
No
No.

Eat RecordNotUnique exception as well when migrating tags

---

lib/tasks/seeds/druid:bx911tp9024.xml
lib/tasks/seeds/druids

Closes #756
So infrastructure-integration-tests for ETDs have the correct APO object.
na
na

add ETD APO to seed objects

---

app/services/administrative_tags.rb
spec/services/administrative_tags_spec.rb

To cover a case in production where legacy tags look like " Remediated By:Foo". The leading space was not dealt with before.
no
Yes, should fix integration with indexing and Argo facets.

Expand tag normalization when migrating legacy tags

---

app/services/cocina/dro_structural_builder.rb
spec/services/cocina/mapper_spec.rb

refs https://github.com/sul-dlss/google-books/issues/462
Fix mapping of sdrPreserve and shelve.
No.
No.

Fixed sdrPreserve and shelve mapping for files.

---

app/services/datastream_extractor.rb
spec/services/datastream_extractor_spec.rb

closes #720
To stop sending techmd to preservation given new techmd service.
No.
No.

Stop sending techmd to preservation.

---

lib/tasks/seeds/druid:bc778pm9866
lib/tasks/seeds/druid:qc410yz8746
lib/tasks/seeds/druids

So infrastructure-integration-test code can use this APO and Collection object
part of sul-dlss/infrastructure-integration-test/issues/46
na
na  (fyi, I will have a PR updating existing integration tests that are going to random APOs and collections.

add integration-testing APO and collection objects to seeds

---

app/services/cocina/mapper.rb
spec/requests/create_object_spec.rb

Fixes #752
no
yes, it fixes it.

Allow blank descriptive metadata when registering

---

app/jobs/publish_job.rb
app/jobs/shelve_job.rb
app/services/cocina/object_creator.rb
app/services/validate_dark_service.rb
spec/jobs/publish_job_spec.rb
spec/jobs/shelve_job_spec.rb
spec/requests/create_object_spec.rb
spec/services/validate_dark_service_spec.rb

closes #768
closes #769
To make sure that publish and shelve match the access for an object.
No.
Yes.

Adds access validation when creating objects, publishing, and shelving.

---

app/services/cocina/object_creator.rb
spec/requests/create_object_spec.rb

In the registration use case, the only thing that demands the structural subschema is 'isMemberOf', but this is optional, so there's nothing required in it
Fixes #775
no
yes, it fixes it.

Cope with structural subschema not being provided on registration

---

app/services/cocina/object_creator.rb
app/services/validate_dark_service.rb
spec/requests/create_object_spec.rb

This indicates they should use the default provided by the APO
Fixes #776
no
yes, it fixes it.

Handle objects that don't provide access subschema

---

app/jobs/publish_job.rb
app/jobs/shelve_job.rb
spec/jobs/publish_job_spec.rb
spec/jobs/shelve_job_spec.rb

Turn off validation of dark until pre-assembly can make valid objects

---

app/services/cocina/mapper.rb
app/services/cocina/object_creator.rb
spec/requests/create_object_spec.rb

This follows with how the old registration service created stub mods when no catkey was provided. See https://github.com/sul-dlss/dor-services-app/blob/master/app/services/registration_service.rb#L153
no
no

Create stub MODS when catkey and descriptive are not provided

---

app/jobs/publish_job.rb
app/jobs/shelve_job.rb

This was honeybadgering up a storm.
No
No

Completely disable dark validation for shelve and publish.

---

app/services/administrative_tags.rb
spec/services/administrative_tags_spec.rb

Namely, multiple consecutive whitespace characters in the middle of a tag
To fix a production issue.
No.
No.

Fix a new production XML data wrinkle

---

openapi.yml

Caused by them being uppercase. This did the trick in suri-rails work.
To see less noise when validating the API spec.
Yes.
Nope.

Fix warning about missing location headers

---

app/services/administrative_tags.rb

Connects to #805
We do not expect this to happen anymore in the production env.

Alert HB if legacy tags need migrating

---

app/controllers/application_controller.rb
spec/requests/authorization_spec.rb

This should now be a dead code path. We have not had any code using the old token header for months. Remove it and clean up the code.
no
Nope, it shouldn't.

Remove outdated token header warning

---

Capfile
Gemfile
Gemfile.lock
config/deploy.rb
config/deploy/prod.rb
config/deploy/stage.rb
lib/capistrano/tasks/sidekiq.rake

BLOCKED by [related PR](https://github.com/sul-dlss/puppet/pull/5267): sets `profile::systemd_sidekiq::sidekiq_count: 3` in the dor-services-app hiera to keep 3 sidekiq processes running (the default is 5), and allows restarting sidekiq via sudo.
As part of this, remove capistrano-sidekiq dependency (because incompatible with our systemd-ified sidekiq configuration in puppet) and create a new task for restarting sidekiq.
Note that this PR also removes worker responsibility from our web boxes, which
cannot use sidekiq with systemd until they undergo OS upgrades. As we don't
currently need the extra capacity, we'll run workers on dedicated worker boxes
only (using systemd).
To keep pace with Sidekiq.
No.
No.

Restart sidekiq using systemd

---

app/services/administrative_tags.rb

Cleans up the HB alert and removes possibly confusing information.
no
no

Prevent honeybadger from thinking admin tags are honeybadger tags

---

app/controllers/objects_controller.rb
app/controllers/shelves_controller.rb
config/sidekiq.yml
openapi.yml
spec/requests/preserve_spec.rb
spec/requests/publish_object_spec.rb
spec/requests/shelving_spec.rb

closes #816
To support prioritization so that Google Books have lower priority than other items.
No.
Yes.

Adds prioritization for workflow-related jobs.

---

app/controllers/workspaces_controller.rb
openapi.yml
spec/requests/reset_workspace_spec.rb

This prevents a robot error state if another process has called this previously.
Fixes sul-dlss/argo#1896
yes
no

Ignore errors about existing archived directory when resetting workspace

---

Gemfile
Gemfile.lock
app/services/cocina/access_builder.rb
app/services/cocina/object_creator.rb
openapi.yml
spec/requests/collections_for_object_spec.rb
spec/requests/create_object_spec.rb
spec/requests/show_object_spec.rb
spec/services/cocina/access_builder_spec.rb
spec/services/cocina/dro_access_builder_spec.rb

This will allow us to do object registration.
yes
yes, all create requests must pass "download" now or they will default to no-download.

Download and location access

---

app/services/cocina/mapper.rb
app/services/cocina/object_creator.rb
spec/requests/create_object_spec.rb

To allow collections to be registered with project tags.
No.
Will be tested by Hydrus.

Adds support for project tags when registering collections.

---

app/services/cocina/mapper.rb
app/services/cocina/object_creator.rb
spec/requests/create_object_spec.rb

Hydrus requires special handling of descriptive metadata. See https://github.com/sul-dlss/hydrus/issues/421
No
Tested by hydrus.

Special handling for registering hydrus items.

---

app/models/dor/update_marc_record_service.rb

Writing service marc records needs to require shellwords to use it on the rails console.  This method is tested, so unclear why it wasn't caught.
Problem on rails console that is fixed with the require statement:
```
2.5.0 :001 > @item = Dor.find('druid:bb181jh4180')
=> #<Dor::Item pid: "druid:bb181jh4180", admin_policy_object_id: "druid:xs835jp8197">
2.5.0 :002 > Dor::UpdateMarcRecordService.new(@item).update
AdministrativeTag Exists (0.7ms)  SELECT  1 AS one FROM "administrative_tags" WHERE "administrative_tags"."druid" = $1 LIMIT $2  [["druid", "druid:bb181jh4180"], ["LIMIT", 1]]
(0.4ms)  SELECT "administrative_tags"."tag" FROM "administrative_tags" WHERE "administrative_tags"."druid" = $1  [["druid", "druid:bb181jh4180"]]
Traceback (most recent call last):
6: from (irb):2
5: from …
```

need to require shellwords to use

---

app/services/cocina/dro_structural_builder.rb
spec/services/cocina/mapper_spec.rb

**HOLD** until further testing. This is the un-reverted version of https://github.com/sul-dlss/dor-services-app/pull/836.
Fixes sul-dlss/was-registrar-app#221
This should help us map and accession WAS seed and crawl objects. One assumption
in this PR I want to call out for reviewers: We prefer a base index of 1 over a base index of 0. True?
No
I will deploy to stage and 1) run integration specs, and 2) test that some test objects map cleanly to the Cocina model in the Argo UI, do not generate HB alerts, and go through `accessionWF` cleanly.
Can you help me identify 3-5 such objects, @andrewjbtw? They should have `contentMetadata` with ID-less resources, and should be in the error state as described in the ticket. cc: @justinlittman

Generate external identifiers for resources without an ID

---

app/services/cocina/dro_structural_builder.rb
spec/requests/create_object_spec.rb
spec/requests/show_object_spec.rb
spec/requests/update_metadata_spec.rb

closes #845
collection_ids doesn't work properly.
No
No

Switched to item.collection from item.collection_ids.

---

app/models/tag_label.rb
db/migrate/20200507202909_create_tag_labels.rb
db/structure.sql
spec/models/tag_label_spec.rb

This is the first step in a two step process for tag-normalization.  This will allow us to prepopulate the tags table before cutting over all the code to requiring it. The full change is in #854.
Once we deploy this part of it we can begin the migration with:
```ruby
AdministrativeTag.all.find_each do |at|
at.update(tag_label: TagLabel.find_or_create_by!(tag: at.tag))
end
```
no
no

Add TagLabel model

---

app/models/administrative_tag.rb
db/migrate/20200507202950_add_tag_label_id_to_administrative_tags.rb
db/structure.sql

This allows us to further the normalization of AdministrativeTags without a downtime.
Ref #854
Now we can turn off the ability to update tags in Argo, then do:
```
AdministrativeTag.all.find_each do |at|
at.update(tag_label: TagLabel.find_or_create_by!(tag: at.tag))
end
```
Then it's possible to run the final migration in #854

Add tag_label_id to AdministrativeTags

---

app/models/administrative_tag.rb
app/models/tag_label.rb
app/services/administrative_tags.rb
db/migrate/20200507224637_remove_administrative_tag_string_field.rb
db/structure.sql
spec/factories/administrative_tags.rb
spec/factories/tag_labels.rb
spec/models/administrative_tag_spec.rb
spec/services/administrative_tags_spec.rb
spec/services/cocina/mapper_spec.rb
spec/services/release_tags/identity_metadata_spec.rb

There are 29,822 unique tags and 8,139,563 tag instances, so normalizing the tags would offer a significant space savings. This would also make it possible for us to provide autocomplete on tags (currently too slow).  This step was started in #853 which will allow the migration to go smoothly.
Currently holding to deploy #855 and build the new table:
```
AdministrativeTag.all.find_each do |at|
at.update(tag_label: TagLabel.find_or_create_by!(tag: at.tag))
end
```
or
```ruby
ActiveRecord::Base.connection.execute('UPDATE administrative_tags a SET tag_label_id = (SELECT id from tag_labels b WHERE a.tag = b.tag)')
```
no
no

[HOLD] Normalize administrative tags

---

app/controllers/administrative_tags_controller.rb
app/models/dor/service_item.rb
app/services/administrative_tags.rb
app/services/cocina/dro_structural_builder.rb
app/services/cocina/mapper.rb
app/services/cocina/object_creator.rb
app/services/cocina/object_updater.rb
app/services/release_tags/identity_metadata.rb
spec/dor/goobi_spec.rb
spec/dor/service_item_spec.rb
spec/requests/administrative_tags_spec.rb
spec/requests/update_metadata_spec.rb
spec/services/administrative_tags_spec.rb
spec/services/release_tags/identity_metadata_spec.rb

The AdministrativeTags service doesn't depend on the full fedora object, just it's identifier.
no
no

Decouple the AdministrativeTags service from Fedora

---

app/jobs/publish_job.rb

It's trying to update a non-existant workflow step ('publish') right now and it should be updating 'release-publish'

Update the correct step when the releaseWF is publishing

---

config/settings.yml

The `v1` part of the SymWS URL is deprecated and will be removed in the next version of SymWS.
I did not find a test in this repo that references this specific URL path.
`config/setting.yml`

Update URL path by removing v1

---

app/services/cocina/object_creator.rb
spec/requests/create_object_spec.rb

To return the druid when trying to register an item with an existing source id.
Unit tests.
No

Added druid to 409 error message.

---

app/services/cocina/mapper.rb
spec/services/cocina/mapper_spec.rb

We know we have many legacy objects without sourceId.
See conclusions in https://github.com/sul-dlss/dor-services-app/issues/852#issuecomment-626853346
Test suite
none

Don't validate sourceId on legacy objects

---

app/controllers/administrative_tags_controller.rb
app/models/administrative_tag.rb
app/models/tag_label.rb
app/services/administrative_tags.rb
db/migrate/20200521153735_index_administrative_tags_labels.rb
db/structure.sql
spec/models/administrative_tag_spec.rb

Fixes sul-dlss/argo#2064
Would like @jcoyne to review before this is merged.
Prefer uniqueness constraints in the database over application validations, which are prone to race conditions. As part of this work, add a new honeybadger alert if AR validation exceptions are still raised which we would no longer expect.
I'm not sure how to test a race condition fix such as this one.
None.

Ditch uniqueness validation in favor of DB constraint

---

app/services/cocina/mapper.rb
app/services/content_metadata_generator.rb
spec/services/content_metadata_generator_spec.rb

Registering certain types of objects was not correctly setting the contentType.
Test suite
n/a

Expand the number of content types we are mapping to cocina

---

app/services/content_metadata_generator.rb
spec/services/content_metadata_generator_spec.rb

We were setting incorrect resource type for webarchive seeds.
Test suite.
n/a

Use the correct resource type for webarchive_seed objects

---

app/services/cocina/mapper.rb
app/services/cocina/object_creator.rb
app/services/cocina/object_updater.rb
app/services/cocina/to_fedora/content_type.rb
app/services/cocina/to_fedora/process_tag.rb
app/services/content_metadata_generator.rb
spec/requests/update_metadata_spec.rb
spec/services/cocina/mapper_spec.rb

Previously we were deriving this from tags, but tags are not repository items, we should be using the contentType from contentMetadata instead.
This adds support for geo and webarchive_seed.
Test suite
n/a

Derive type from contentType

---

app/models/dor/service_item.rb
app/models/dor/update_marc_record_service.rb
app/services/content_metadata_generator.rb

These ivars were not used in any class except UpdateMarcRecordService
Test suite
n/a

[Refactor] Move ivars into the class where they are used

---

app/services/cocina/object_creator.rb
app/services/cocina/to_fedora/process_tag.rb
spec/requests/create_object_spec.rb

closes #907
So items do not have process tags (e.g., WARCs). This should be allowed, rather than raise.
Unit
No

Handles creating items without process tags.

---

app/controllers/objects_controller.rb
spec/requests/create_object_spec.rb
spec/requests/notify_goobi_spec.rb
spec/requests/update_metadata_spec.rb

This gives us the ability to provide structured information to the consumers about what is wrong and what they might do to fix it. This ensures all errors are reported in a consistent manner.
Test suite
n/a

Switch all errors from objects controller to use JSON-API

---

app/controllers/objects_controller.rb
app/services/cocina/from_fedora/title_mapper.rb
app/services/cocina/mapper.rb
openapi.yml
spec/requests/show_object_spec.rb
spec/services/cocina/from_fedora/title_mapper_spec.rb

and display a more helpful error. 
The current error:
```
Cocina::Models::ValidationError: #/components/schemas/DescriptiveBasicValue/properties/value does not allow null values
```
is rather opaque as to what the problem is.
Test suite
openapi.yml and generated docs.

Trap for the case when an object does not have a title

---

app/controllers/objects_controller.rb
config/settings.yml
openapi.yml
spec/requests/create_object_spec.rb

This will enable us to take registration offline while we migrate the data from suri2 to suri-rails
Test suite
config/settings.yml was updated and this was documented in openapi.yml

Add a feature flipper to disable registration

---

app/services/cocina/object_creator.rb
app/services/cocina/object_updater.rb
app/services/cocina/to_fedora/identity.rb

This reduces duplication between the create & update methods. No functional changes.
Test suite
n/a

Extract identityMetadata mapping

---

app/controllers/objects_controller.rb
app/services/cocina/object_creator.rb
app/services/cocina/object_updater.rb
config/settings/development.yml
spec/services/cocina/object_creator_spec.rb

This relieves these already overburdened classes of the responsibility of how to build the cocina models. No functional changes
Test suite
n/a

[Refactor] Call ObjectCreator and ObjectUpdate with the cocina model

---

app/controllers/objects_controller.rb
app/services/cocina/object_creator.rb
app/validators/cocina/unique_source_id_validator.rb
app/validators/cocina/validation_error.rb

There are no functional changes.
This helps each class have a single responsibility and aligns the validators to use a similar pattern.
This also creates ValidationError, because we were previously using Dor::DuplicateIdError incorrectly because we were giving it a sourceId rather than a PID and reduces dependency on dor-services.
Test suite
n/a

[Refactor] Extract UniqueSourceIdValidator

---

app/controllers/objects_controller.rb
app/services/cocina/object_creator.rb
app/services/cocina/object_updater.rb
app/validators/cocina/apo_existence_validator.rb
config/settings/development.yml
spec/services/cocina/object_creator_spec.rb

This will return a 400 if the apo doesn't exist rather than a 404.
Fixes #922
Test suite
n/a

Create a validator for checking for APO existence

---

app/controllers/metadata_controller.rb
openapi.yml
spec/requests/legacy_metadata_update_spec.rb

This will allow decoupling of gis-robot-suite from Fedora 3
Test suite
openapi.yml

add geoMetadata to the legacy datastream update

---

app/services/shelving_service.rb

No functional changes.
This allows us to remove Dor::ParameterError from dor-services
Test suite
n/a

[Refactor] Create a custom error type for configuration errors

---

.rspec
app/services/version_service.rb
spec/services/version_service_spec.rb

Closes sul-dlss/argo/issues/2093
versions should not be closable if there is an active assemblyWF.
wrote rspec tests; test suite
n/a

version_service: can't close version if active assemblyWF

---

app/services/embargo_release_service.rb
config/deploy.rb
config/deploy/prod.rb
config/deploy/qa.rb
config/deploy/stage.rb
spec/services/embargo_release_service_spec.rb

Fixes sul-dlss/hydra_etd#471
Because the daily embargo release task is not being run, because it isn't scheduled. There were two bugs here:
* Finish setup of whenever gem (needed `whenever_roles` to be set)
* Make EmbargoReleaseService.release_all a class method, as that is how it is in invoked in the dsa:embargo_release task (and that's the only place it's invoked)
Deployed to QA and stage and tested that 1) the expected crontab entry exists, and 2) the rake command in the crontab entry is runnable w/o error.
None.

Re-enable embargo release scheduled task

---

app/services/embargo_release_service.rb
app/services/version_service.rb
spec/services/embargo_release_service_spec.rb
spec/services/version_service_spec.rb

So the release embargo cronjob doesn't send an email full of deprecations ever night.
Test suite
n/a

Remove deprecated workflow-client parameters

---

app/services/embargo_release_service.rb

Connects to sul-dlss/hydra_etd#471
This field changed at some point in the past and this code was not updated, preventing 20% releases.
Manually on server
None

Fix how the embargo release service queries for 20% releaseable items

---

app/services/cocina/from_fedora/identification.rb

Since https://github.com/sul-dlss/hydra_etd/pull/469 was merged
Test suite and tested on stage.
n/a

Expect that ETDs have a sourceId

---

app/services/cocina/object_creator.rb
app/services/cocina/object_updater.rb
app/services/cocina/to_fedora/access.rb
app/services/embargo_service.rb
spec/requests/create_object_spec.rb
spec/requests/show_object_spec.rb
spec/requests/update_metadata_spec.rb
spec/services/embargo_service_spec.rb

because the access is always provided in the create or update.
Fixes #955
Test suite
n/a

There is no reason to wipe out the existing access

---

Gemfile
Gemfile.lock
app/services/cocina/from_fedora/apo.rb
app/services/cocina/object_creator.rb
openapi.yml
spec/requests/collections_for_object_spec.rb
spec/requests/show_object_spec.rb
spec/validators/cocina/validate_dark_service_spec.rb

Because the clients are using 0.34.1
Test suite
openapi.yml.  AdminPolicy is now required in the administrative schema.

Upgrade to cocina-models 0.34.1

---

config/schedule.rb

Cron emails are getting sent with a bunch of warnings and no useful content.
Test suite

Suppress warnings to avoid unnecessary cron emails

---

app/services/cocina/to_fedora/content_metadata_generator.rb
spec/services/cocina/to_fedora/content_metadata_generator_spec.rb

presentation data was not being recorded.
Fixes #975 
Test suite
n/a

Map cocina Presentation schema to imageData nodes in contentMetadata

---

app/services/cocina/to_fedora/content_metadata_generator.rb
spec/services/cocina/to_fedora/content_metadata_generator_spec.rb

Ref #966
See https://consul.stanford.edu/pages/viewpage.action?spaceKey=chimera&title=DOR+content+types%2C+resource+types+and+interpretive+metadata
We were not recording bookData from cocina models. Purl uses this https://github.com/sul-dlss/purl/blob/27d793382d0d7802bd3898d63bf956a9369b0e1d/app/models/content_metadata.rb#L14-L20
Test suite

Book data should be recorded in content metadata

---

app/services/cocina/from_fedora/dro.rb
app/services/cocina/from_fedora/dro_structural.rb
spec/services/cocina/from_fedora/dro_structural_spec.rb
spec/services/cocina/mapper_spec.rb

Fallback to using AdminTags
Fixes #966 
Previously we were not using Fedora for the source of this data, using AdminTags instead.  This is not the correct behavior because AdminTags should be considered ephemeral.  The cannonical source should be Fedora.  We need to fall-back to Admin tags because the google-books (2020) have not been storing this value (#1004)
Test suite.

Use bookData from contentMetadata to get the viewing order

---

app/services/cocina/from_fedora/access.rb
spec/services/cocina/from_fedora/dro_access_spec.rb

To allow controlled digital lending objects to correctly map to cocina models
Tested on stage

Map CDL to a valid cocina model

---

app/services/cocina/from_fedora/descriptive.rb
spec/services/cocina/from_fedora/descriptive_spec.rb

Blocked until @arcadiafalcone releases the expanded MODS -> Cocina mapping (so that we can support displayLabel)
This is done so that was_robot_suite can migrate away from Fedora.
Fixes #849
Test suite
n/a

[Draft] Map original_url to Cocina Description

---

spec/services/cocina/from_fedora/descriptive_spec.rb

Master build is failing on rubocop.
ci
N/A

Fix rubocop error that is causing master build to fail

---

app/services/cocina/from_fedora/contributor_mapper.rb
spec/services/cocina/from_fedora/descriptive_spec.rb

Fixes a production bug where translating descMetada with a namePart that is missing the type attribute throws a 500 up through argo.
Unit
N/A

Do not raise an error if name.type is missing

---

app/services/cocina/from_fedora/dro_structural.rb
spec/services/cocina/from_fedora/dro_structural_spec.rb

fix a production issue where files cannot be downloaded because `hasMemberOrders` was not correctly constructed for the `'Book (flipbook, ltr)'` content type.
unit tests, so far.  will also test on stage before deploying to prod.
n/a, fix for regression to intended behavior

fix file download for flipbook by fixing hasMemberOrders construction

---

app/services/cocina/from_fedora/title_mapper.rb
spec/requests/show_object_spec.rb
spec/services/cocina/mapper_spec.rb

The ETD project has recently undergone updates where the properties are stored in a database and not fedora.  The object is given a proper mods title when it is registered in the SDR.
Test suite.

ETDs now have mods title and no longer rely on properties.

---

app/services/cocina/from_fedora/descriptive.rb
app/services/cocina/from_fedora/descriptive/contributor.rb
app/services/cocina/from_fedora/descriptive/form.rb
app/services/cocina/from_fedora/descriptive/language.rb
app/services/cocina/from_fedora/descriptive/notes.rb

No functional changes
This reduces the number of dependencies in each mapper to just Nokogiri.
Test suite

[Refactor] Decouple mappers from ActiveFedora

---

app/controllers/members_controller.rb
spec/requests/members_for_collection_spec.rb

Fixes sul-dlss/argo#2243
Basically, the collection member solr query wasn't returning anything, preventing collection member release from working correctly.
Tested on -stage, by running a call from argo-stage.

adjust collection member solr query to correctly return collection members

---

app/services/cocina/from_fedora/descriptive/titles.rb
spec/services/cocina/from_fedora/descriptive/titles_spec.rb

The dor-services-client can't support values as integers yet.
See https://github.com/sul-dlss/cocina-models/pull/146
Updated https://argo-stage.stanford.edu/view/druid:bb149mb1196 so that it had a title with nonSort characters
and ran the integration test suite.

Cast note value to String until cocina-models 0.40.0 is used

---

spec/requests/members_for_collection_spec.rb

Object type is actually a multivalued solr field and returns an array, and thus needs to be parsed correctly by consumers (such as common-accessioning in the release robots).  This just makes the mocked data in the test reflect what is actually happening in the real world.
Also see sul-dlss/common-accessioning#695
Test suite

object type is a multivalued solr field; model the response correctly in the test

---

app/services/cocina/from_fedora/descriptive.rb
spec/services/cocina/from_fedora/descriptive_spec.rb

Until we get the mapping sorted out (see #1059), add a guard to prevent bad data

Handle bad cocina-model title mapping

---

app/views/members/index.json.jbuilder
spec/requests/members_for_collection_spec.rb

It appears that some objects (at least in stage) do not have an object type.  This prevents the members call from failing in those cases, instead just returning nil for the object type.
See this as an example of an object in stage that has no object type (missing `objectType_ssim` field): https://argo-stage.stanford.edu/view/druid:vq127xv4292.json
It belongs to this collection: druid:jt898xc8096, which if run the raw solr query, you get this:
```ruby
pid='druid:jt898xc8096'
solr_params={q: "is_member_of_collection_ssim:\"#{ActiveFedora::Base.internal_uri(pid)}\" published_dttsim:[* TO *]",wt::json,fl: 'id,objectType_ssim',rows: 100_000_000}
response = ActiveFedora::SolrService.instance.conn.get 'select', params: solr_params
puts response['response']['docs']
{"id"=>"druid:zr532tp7700", …
```

some objects (in stage at least) have no object type, this guards against it

---

app/services/cocina/object_updater.rb
spec/requests/update_metadata_spec.rb

Because they don't have titles, so they are a special case
Fixes https://github.com/sul-dlss/argo/issues/2248
Test suite.

Ensure that Hydrus objects are able to be updated

---

app/controllers/metadata_controller.rb
openapi.yml
spec/requests/legacy_metadata_update_spec.rb

This will enable argo to do datastream updates without directly talking to Fedora 3.
See https://github.com/sul-dlss/argo/blob/master/config/settings.yml#L107-L114
Test suite

Add administrative, relationships and versions metadata to legacy endpoint

---

app/services/cocina/from_fedora/descriptive/titles.rb
spec/services/cocina/from_fedora/descriptive/titles_spec.rb

A case came through were we were unable to map to cocina models. https://argo.stanford.edu/view/druid:xk774zs1699  This case was not made explicit in https://github.com/sul-dlss-labs/cocina-descriptive-metadata/blob/master/mods_cocina_mappings/mods_to_cocina_titleInfo.txt

Handle titles that are abbreviated but do not specify an authority

---

app/services/cocina/object_updater.rb
spec/requests/update_metadata_spec.rb

Connects to https://app.honeybadger.io/projects/50568/faults/67768441
This allows us to raise the expected exception (`NotImplemented`) when titles mismatch with both simple and structured values.
CI
None

Fix bug related to structured titles

---

app/xslt/MARC21slim2MODS3-7_SDR_v1.xsl

To handle legacy MARC data that was causing errors
Local XSLT transform
n/a

Add first indicator 2 to 100 and 700 in MARC2MODS XSLT and bump version

---

openapi.yml
spec/requests/update_metadata_spec.rb

Committee can't decide which type this is.
See https://github.com/interagent/committee/issues/286
Fixes https://github.com/sul-dlss/argo/issues/2253
Ref https://github.com/sul-dlss/cocina-models/pull/144
Test suite.

Rollback accepting an integer value in the description

---

app/models/dor/update_marc_record_service.rb
spec/dor/update_marc_record_service_spec.rb

For controlled digital lending, Searchworks needs to know (from the MARC record)  whether there's an SDR object with CDL  rights available. We've heard other use cases for additional rights information (e.g. "show me all the world accessible data")

Include a high-level rights characterization in the 856 sent to Symphony

---

app/services/cocina/object_creator.rb
app/services/cocina/object_updater.rb
app/services/cocina/to_fedora/access.rb
app/services/cocina/to_fedora/dro_access.rb
spec/services/cocina/to_fedora/dro_access_spec.rb

This adds no new functionality
This removes a number of conditionals and duplicate code by adding a ToFedora::DROAccess which subclasses ToFedora::Access.  This subclass only handles DROAccess so it can have fewer conditionals.  This makes the code easier to follow.
Test suite.

Extract a ToFedora::DROAccess class

---

app/services/cocina/mapper.rb
app/services/cocina/object_updater.rb
spec/requests/update_metadata_spec.rb

This makes the log more useful when debugging

Log the request regardless of the outcome

---

app/controllers/objects_controller.rb
app/services/cocina/from_fedora/descriptive/titles.rb
app/services/cocina/from_fedora/identification.rb
app/services/cocina/mapper.rb
spec/requests/show_object_spec.rb

This will show a message in argo that one can use rather than having to dig through honeybadger to find out why the request to dor-services-app failed.

Report a sensible error if an object is missing a required sourceId

---

app/xslt/MARC21slim2MODS3-7_SDR_v1.xsl

To make 880-240 and 880-1XX values match
Local XSLT transforms
n/a

Fix nameTitleGroup math

---

app/services/cocina/to_fedora/descriptive.rb
spec/services/cocina/to_fedora/descriptive_spec.rb

This allows us to have a round-trip mapping of descMetadata so that we can begin to evaluate where the mapping is incomplete.
Test suite.
Tested on Stage.

Map Cocina::Models::Description to descMetadata XML

---

.circleci/config.yml
Dockerfile

Ruby 2.7.2 suppresses a lot of unnecessary deprecation warnings.

Use the 2.7.2 ruby docker image

---

app/controllers/objects_controller.rb
app/services/cocina/from_fedora/descriptive.rb
app/services/cocina/from_fedora/descriptive/contributor.rb
app/services/cocina/mapper.rb
spec/requests/show_object_spec.rb
spec/services/cocina/from_fedora/descriptive/contributor_spec.rb

Raise an error that is useful in Argo rather than a NoMethodError
Test suite

Trap for missing expected MODS attribute

---

app/services/cocina/to_fedora/descriptive/subject.rb
spec/services/cocina/to_fedora/descriptive/subject_spec.rb

Running the test mapper in prod was failing when there were no subjects.

Map cocina descriptive when there are no subjects

---

app/services/cocina/from_fedora/descriptive.rb
app/services/cocina/from_fedora/descriptive/event.rb
spec/services/cocina/from_fedora/descriptive/event_spec.rb

This increases the number of descriptive properties that can be round tripped.

Map originInfo to cocina Events

---

app/services/cocina/to_fedora/descriptive/note.rb
spec/services/cocina/to_fedora/descriptive/note_spec.rb

To further the mapping of MODS to cocina descriptive.

Map cocina notes to MODS XML

---

app/services/cocina/from_fedora/descriptive/notes.rb
spec/services/cocina/from_fedora/descriptive_spec.rb

Some notes were not being converted to cocina.

Code all notes to cocina

---

bin/validate-cocina-roundtrip

So we can have metrics about how well we're doing.
```
Status (n=100):
Success:   69 (69.0%)
Different: 14 (14.0%)
Error:     17 (17.0%)
```

Provide some statistics about roundtripping

---

app/services/cocina/from_fedora/descriptive.rb

It is resolving the wrong class in production mode

Load the Descriptive::Event class not the Event class

---

app/services/cocina/from_fedora/descriptive/event.rb
spec/services/cocina/from_fedora/descriptive/event_spec.rb

Map MODS originInfo placeTerm with a code to cocina

---

app/services/cocina/from_fedora/descriptive/contributor.rb
spec/services/cocina/from_fedora/descriptive/contributor_spec.rb

The spreadsheet was updated with the correct term.
Fixes #1183 
See also https://github.com/sul-dlss-labs/cocina-descriptive-metadata/pull/76

Fix mapping for termsOfAddress

---

app/services/cocina/from_fedora/descriptive/subject.rb
spec/services/cocina/from_fedora/descriptive/subject_spec.rb

closes #1184
To handle cases in which coordinates is missing from a geo subject.
Unit
NA

Handle missing coordinates.

---

app/services/cocina/from_fedora/descriptive/titles.rb
app/services/cocina/to_fedora/descriptive/title.rb
spec/services/cocina/from_fedora/descriptive/titles_spec.rb
spec/services/cocina/to_fedora/descriptive/title_spec.rb

See https://github.com/sul-dlss-labs/cocina-descriptive-metadata/commit/9792d5dc04e9a11ad67b328c8f9baf1a09a4ed7f
Fixes #1156

Use person rather than name or personal name for titles

---

app/services/cocina/from_fedora/descriptive/contributor.rb

Should have been removed as part of https://github.com/sul-dlss/dor-services-app/commit/cf3225d275a1f227e7e191d6246be98afb385dea
Fixes #1209

Remove obosolete value from the map

---

app/services/cocina/from_fedora/descriptive/subject.rb
spec/services/cocina/from_fedora/descriptive/subject_spec.rb

Map subject with a corporate name to a cocina organization name

---

app/services/cocina/from_fedora/descriptive/admin_metadata.rb
spec/services/cocina/from_fedora/descriptive/admin_metadata_spec.rb

closes #1229
Allow an identifier to be missing a source.
Unit
NA

Handle identifier without source.

---

app/services/cocina/from_fedora/descriptive/contributor.rb
app/services/cocina/to_fedora/descriptive/contributor.rb
spec/services/cocina/from_fedora/descriptive/contributor_spec.rb
spec/services/cocina/from_fedora/descriptive_spec.rb
spec/services/cocina/to_fedora/descriptive/contributor_spec.rb

Fixes #1105 - implement from_ and to_ fedora mapping for contributor roles
Fixes #1161 - cocina mapping error for role when namePart is empty
Note that #1161 refers to the stage object https://argo-stage.stanford.edu/view/druid:pd967mn2579 which has funky empty name stuff:
```
<name>
<namePart/>
<role>
<roleTerm authority="marcrelator" type="text"/>
</role>
```
Note that roleTerm has attributes but no value, so it is, effectively, no information.
Since contributor roles and all that were already defined fully in cocina-models, I believe I have no openapi changes and no type checking to add - please let me know if that's wrong.
unit tests.  Made a point of using the same starting xml in "from_fedora" specs that I expected in "to_fedora specs.

Contrib roles

---

app/services/cocina/to_fedora/descriptive/related_resource.rb
spec/services/cocina/to_fedora/descriptive/related_resource_spec.rb

closes #1172
This mapping is now supported by cocina models.
Unit
NA

Enabled related resource displaylabel.

---

app/services/cocina/from_fedora/descriptive/form.rb
spec/services/cocina/from_fedora/descriptive/form_spec.rb

closes #1252
displayLabel should be optional for a form note.
Unit
NA

Handles form note without displayLabel.

---

app/services/cocina/to_fedora/descriptive/related_resource.rb

Fixes the rubocop build failure on master

Fix rubocop build failure on master

---

app/services/cocina/to_fedora/descriptive/admin_metadata.rb
spec/services/cocina/from_fedora/descriptive/admin_metadata_spec.rb
spec/services/cocina/to_fedora/descriptive/admin_metadata_spec.rb

Fixes #1255.
`jv711gt9148` has no `<recordOrigin>` element, which "from_fedora" mappings dealt with fine, but the "to_fedora" mappings needed to allow for missing admin_metadata.note field.
functional tests.  (I got the same line to fail with the new functional tests before the fix as was indicated in #1255):
This was the failure while it was a WIP:
```
1) Cocina::ToFedora::Descriptive::AdminMetadata for jv711gt9148 ... builds the xml
Failure/Error: xml.recordOrigin admin_metadata.note&.find { |note| note.type == 'record origin' }.value
NoMethodError:
undefined method `value' for nil:NilClass
```

to_fedora cocina mapping copes with missing admin_metadata.note

---

spec/services/cocina/from_fedora/descriptive/contributor_spec.rb
spec/services/cocina/to_fedora/descriptive/contributor_spec.rb

Arcadia added two more contributor mapping examples in sul-dlss-labs/cocina-descriptive-metadata/pull/100 and also previously added some other mapping examples.
it's just xit specs.

contributor mappings: add xit specs for new cases and fix line numbers

---

app/services/cocina/from_fedora/apo.rb
app/services/cocina/from_fedora/collection.rb
app/services/cocina/from_fedora/descriptive.rb
app/services/cocina/from_fedora/descriptive/hydrus_default_title_builder.rb
app/services/cocina/from_fedora/descriptive/title_builder_strategy.rb
app/services/cocina/from_fedora/dro.rb
app/services/cocina/object_updater.rb
bin/validate-cocina-roundtrip
spec/services/cocina/from_fedora/descriptive_spec.rb

No functional changes.
1. This simplifies the interface for the mapper by passing values rather than heavyweight objects.  This means we need to cache much less to analyze if the repository can use this mapping without error.
2. This does dependency injection that encompasses the conditional about how to build titles and extracts it from the descriptive metadata builder.

Refactor interface of from_fedora mapping

---

app/services/cocina/to_fedora/descriptive/contributor.rb
spec/services/cocina/from_fedora/descriptive/contributor_spec.rb
spec/services/cocina/to_fedora/descriptive/contributor_spec.rb

Fixes #1218
- corrects to_fedora mapping for contributor.name.namePart when it is a structured value
- bonus:   added to_fedora and from_fedora specs for "multiple names, one primary" - started with this thinking it would trip the problem, but it turned out NOT to trip the problem in #1218, AND it turned out to be already implemented.
functional tests were written with the same data as was in the record in ticket #1218 -- the from_fedora as well as the to_fedora.

contributor.name to_fedora mapping fix for structuredValue

---

app/services/cocina/from_fedora/descriptive/related_resource.rb
spec/services/cocina/from_fedora/descriptive/related_resource_spec.rb

refs #1260
This handles incorrect data that has a related resource type of "Other version". The data is mapped to the correct value and HB is notified of the data error.
Unit.
NA

Handles mapping of related resource with incorrect type.

---

app/services/cocina/from_fedora/descriptive/contributor.rb
spec/services/cocina/from_fedora/descriptive/contributor_spec.rb

refs #1273
To handle miscapitalized contributor types. It normalizes to the expected downcase and HB notifies about the bad data.
Unit
NA

Handles miscapitalized contributor types.

---

app/services/cocina/to_fedora/descriptive.rb

Fixes #1219 
Confirmed on stage for the druid in the ticket:
```
<relatedItem type="series">
<titleInfo>
<title>Biblioteca del pensamiento vivo, 18</title>
</titleInfo>
</relatedItem>
```
Unit
N/A

Include RelatedResource in to_fedora descriptive

---

app/services/cocina/from_fedora/descriptive/language.rb
app/services/cocina/to_fedora/descriptive/language.rb
spec/services/cocina/from_fedora/descriptive/language_spec.rb
spec/services/cocina/to_fedora/descriptive/language_spec.rb

**NOTE:  we have a partial mapping for language;  this may actually reduce the number of errors ... not sure if this should be held as a "new mapping" or not.**
Fixes #1216 -- what to do with the language element `objectPart` attribute
Fixes #1090 -- mapping the language element.   (@jcoyne had this ticket. I believe he did PR #1130, which was a beginning, and this PR does the rest)
This PR implements all of Arcadia's examples* in https://github.com/sul-dlss-labs/cocina-descriptive-metadata/blob/master/mods_cocina_mappings/mods_to_cocina_language.txt for both "from_fedora" and "to_fedora" .
Note that the known examples that were failing in prod are covered by the specs:
#1248 - from gf100ky7916 (quick fix with PR #1249), which has
```xml
<language>
<languageTerm …
```

Implement language mappings to_ and from_fedora per Arcadia's examples

---

app/services/cocina/to_fedora/descriptive/contributor.rb
spec/services/cocina/from_fedora/descriptive/contributor_spec.rb
spec/services/cocina/to_fedora/descriptive/contributor_spec.rb

closes #1220
To correctly map multiple contributors and contributors with multiple names and multiple nameParts.
Unit
NA

Fix mapping of multiple contributors.

---

app/services/cocina/from_fedora/descriptive/subject.rb
spec/services/cocina/from_fedora/descriptive/subject_spec.rb

Fixes #1265 
Also updates references to mapping specification for xit statements.
Was able to reproduce the error locally with new unit test, and the fix addressed it.

fix subject name mapping from fedora when name has no type

---

app/services/cocina/from_fedora/descriptive/contributor.rb
app/services/cocina/from_fedora/descriptive/related_resource.rb
app/services/cocina/from_fedora/descriptive/subject.rb
app/services/cocina/from_fedora/descriptive/titles.rb
app/services/cocina/to_fedora/descriptive/contributor.rb
spec/services/cocina/from_fedora/descriptive/contributor_spec.rb
spec/services/cocina/from_fedora/descriptive/related_resource_spec.rb
spec/services/cocina/from_fedora/descriptive/subject_spec.rb
spec/services/cocina/from_fedora/descriptive/titles_spec.rb

To make it clearer which notifications are for data errors.
Unit
NA

Adds data_error tags to appropriate HB notifications.

---

app/services/cocina/from_fedora/descriptive/titles.rb
spec/services/cocina/from_fedora/descriptive/titles_spec.rb

refs #1271
Provide a HB alert, but not raise, when name not found for a title group.
Unit
NA

Handle name not found for title group.

---

bin/validate-to-cocina

Because I hate
```
error. key not found: "isReferencedby"=====================================================    
Did you mean?  "isReferencedBy"
```

validate-to-cocina: turn newlines in error messages into spaces

---

app/controllers/objects_controller.rb
app/services/cocina/mapper.rb
openapi.yml
spec/requests/show_object_spec.rb

Handle unexpected errors from `Cocina::Mapper.build` so that an informative 422 is returned (with a ~~backtrace filtered to dor-services-app code~~full backtrace because my first attempt at filtering was hacky and this seemed useful as-is).  This will hopefully help future `Cocina::Mapper` debugging.
closes #1284
* supported by a bit more hierarchy for `Cocina::Mapper` exceptions
* `ObjectsController#json_api_error`: param for optional meta field in JSON-API error
* `#show`: use meta field for returning backtrace
* test the new functionality
* update openapi spec for new json api error field
unit tests
hopefully code comments and new test suffice

ObjectsController#show: handle all Cocina::Mapper.build exceptions as 422

---

app/services/cocina/from_fedora/descriptive/titles.rb
app/services/cocina/to_fedora/descriptive/title.rb
spec/services/cocina/to_fedora/descriptive/title_spec.rb

Fixes #1234 
Adds a unit test for title with name part subelements.
N/A

Fix mapping of life dates on name part subelements of title

---

app/services/cocina/from_fedora/descriptive/contributor.rb
app/services/cocina/to_fedora/descriptive/contributor.rb
spec/services/cocina/from_fedora/descriptive/contributor_spec.rb
spec/services/cocina/to_fedora/descriptive/contributor_spec.rb

To add mappings indicated for #1276  (a variety of empty name and subelement attributes and values)
bonus content:
- addressed nil `name/namePart` values 
- added fleshed out some TODO specs where code was already implemented.
Before merging:
- wrote unit tests per Arcadia's specs.
-  from-fedora-to-cocina validator

contributor mapping fixes for key not found: ""

---

app/services/cocina/from_fedora/descriptive/related_resource.rb
spec/services/cocina/from_fedora/descriptive/related_resource_spec.rb

tolerate (but alert on) bad data as described in #1268 ("normalize capitalization, but continue to alert for error" when `isReferencedBy` is mis-capitalized).
hopefully updated test and slightly refactored code should suffice

Cocina::FromFedora::Descriptive::RelatedResource -- normalize mis-capitalized type isReferencedBy

---

app/services/cocina/from_fedora/descriptive/contributor.rb
spec/services/cocina/from_fedora/descriptive/contributor_spec.rb

To add mapping grease for #1292 (`<name>` has invalid type attribute of 'primary') and #1293 (`<name>` has invalid type attribute of 'naf')
- wrote unit tests for these cases
- with from-fedora-to-cocina validator
```
$ diff results-master-branch.txt results-name-type-unrec-branch.txt 
1c1
< 723 of 350000 (0.20657142857142857%)
---
> 719 of 350000 (0.20542857142857143%)
722,725d721
< Error: key not found: "primary" (3 errors)
< druid:rw667tg8009
< druid:md049mq5771
< druid:wq793rc8271
731,732d726
< Error: key not found: "naf" (1 errors)
< druid:pw260mt1867
```

name mapping fix for unrecognized type attribute value

---

app/services/cocina/from_fedora/descriptive/subject.rb
spec/services/cocina/from_fedora/descriptive/subject_spec.rb

closes #1311
Handle subjects that have empty name parts, e.g.,
```
<subject authority="lcsh">
<name type="corporate">
<namePart/>
</name>
</subject>
```
Unit
NA

Handle subjects with empty name parts.

---

app/services/cocina/from_fedora/descriptive/contributor.rb
spec/services/cocina/from_fedora/descriptive/contributor_spec.rb

refs #1312
Handles namePart with type but not value, e.g.,
```
<name type="personal">
<namePart>Kielmansegg, Erich Ludwig Friedrich Christian</namePart>
<namePart type="termsOfAddress">Graf von</namePart>
<namePart type="date">1847-1923</namePart>
<namePart type="date"/>
</name>
```
Unit
NA

Handles namePart with type but not value.

---

app/services/cocina/from_fedora/descriptive/contributor.rb
app/services/cocina/from_fedora/descriptive/event.rb
app/services/cocina/from_fedora/descriptive/subject.rb
spec/services/cocina/from_fedora/descriptive/contributor_spec.rb
spec/services/cocina/from_fedora/descriptive/event_spec.rb
spec/services/cocina/from_fedora/descriptive/subject_spec.rb

To add mapping grease for
- #1291 (`<Topic>` element uppercase)  and 
- #1306 (`<subject><name>` has invalid type attribute of "topic")
- wrote unit tests for these cases
- with from-fedora-to-cocina validator
```
$ diff results-master-branch.txt results-topic-branch.txt 
698,721d641
< Error: key not found: "Topic" (11 errors)
< druid:xv661kx4223
< druid:qr684zq1130
< druid:xy743kk5793
< druid:yw448qd5583
< druid:ky082np9069
< druid:gf424bq2099
< druid:rd235fv8920
< druid:fz099qm8777
< druid:bq782pp3515
< druid:jx066kr2212
< druid:qt282gh9166
729,730d648
< Error: key not found: "topic" (1 errors)
< druid:kd333yz5798
```

subject mapping fixes for topic - two separate causes

---

app/services/cocina/from_fedora/descriptive/subject.rb
spec/services/cocina/from_fedora/descriptive/subject_spec.rb

closes #1313
To handle unexpected subject node types, e.g.,
```
<subject authority="lcsh">
<corporate authority="naf" authorityURI="http://id.loc.gov/authorities/names" valueURI="http://id.loc.gov/authorities/names/no89003525">Mooseheart (School)</corporate>
</subject>
```
Unit
NA

Handle unexpected node type.

---

app/services/cocina/from_fedora/descriptive/titles.rb
app/services/cocina/mapper.rb
spec/services/cocina/from_fedora/descriptive/titles_spec.rb
spec/services/cocina/mapper_spec.rb

So that we get HB alerts when there is a mapping/build error.
Unit
NA

Adds HB alerts for build/mapping errors.

---

app/services/cocina/from_fedora/descriptive/related_resource.rb
spec/services/cocina/from_fedora/descriptive/related_resource_spec.rb

Fixes #1325 
- do not alert HB if the resource type is mapped correctly
- DO alert HB if it cannot be mapped (and ignore the type in the mapping)
Modified existing tests and added a new unit test

do not alert hb if we actually do the mapping correctly

---

bin/validate-to-cocina

To separate and log data errors separately from mapping errors.
Locally.
NA

Improved validate-to-cocina handling of data errors.

---

spec/services/cocina/to_fedora/descriptive/contributor_spec.rb

I originally thought some missing descriptive metadata for h2 deposits was caused by a missing to_fedora mapping.  This test proved the mapping was already correct.   But it's still a good test (and mirrors a from_fedora test that already exists).
the change is the addition of a test.

add contributor mapping to_fedora test to match current h2 use case

---

app/services/cocina/to_fedora/descriptive/related_resource.rb
spec/services/cocina/to_fedora/descriptive/related_resource_spec.rb

closes #1344
Fix mapping to Fedora for related resource contributor that does not have a type.
Unit
NA

Fixes related resource contributor without type.

---

app/services/cocina/to_fedora/descriptive/event.rb
spec/services/cocina/to_fedora/descriptive/event_spec.rb

closes #1347
Handle multiple event in which type is missing.
Unit
NA

Handles event missing type.

---

app/services/cocina/to_fedora/descriptive/subject.rb
spec/services/cocina/to_fedora/descriptive/subject_spec.rb

closes #1343
Allow cartographics to be missing forms.
Unit
NA

Handle cartographics missing forms.

---

bin/validate-to-cocina

To allow collection data errors reported to HB.
Locally
NA

Collect data errors in validate-to-cocina.

---

bin/validate-to-cocina

To use the defaults, which is in processes where the number of processes is the number of CPUs.
NA
NA

For validate-to-cocina, use default Parallel options.

---

app/services/cocina/to_fedora/descriptive/admin_metadata.rb
spec/services/cocina/to_fedora/descriptive/admin_metadata_spec.rb

closes #1350
To allow mapping of an identifier when source is missing.
Unit
NA

Handle identifier without a source when mapping to fedora.

---

app/services/cocina/to_fedora/descriptive/event.rb

closes #1355
Add missing event type so that mapping to fedora can succeed.
Local
NA

Adds missing event type.

---

bin/validate-to-cocina

`Data error: 2669938 of 2685579 (99.41759300322202%)` doesn't seem right.
Locally
NA

Clear HB exception.

---

app/services/cocina/to_fedora/descriptive/event.rb

closes #1361
The `capture` event type was missing.
Locally
NA

Add capture as event type for event mapping.

---

app/services/cocina/object_creator.rb
spec/services/cocina/object_creator_spec.rb

part of sul-dlss/happy-heron/issues/240
As part of H2 work -- we want h2 data with cocina descriptive metadata to be mapped into Fedora.
I wrote missing tests for code before I made changes (e.g. item vs collection object, different ways title was getting set, the way we set the abstract for collection records coming from Argo), and I made sure those tests passed along with tests showing that incoming descriptive metadata was being mapped.
Also deployed to qa to test.

Object registration/deposit wired up to use ToFedora mappings

---

app/services/cocina/to_fedora/descriptive/title.rb
spec/services/cocina/to_fedora/descriptive/title_spec.rb

closes #1365
To include all types of name parts when mapping title.
Unit
NA

Handle name part when mapping title.

---

app/services/cocina/to_fedora/descriptive/related_resource.rb
spec/services/cocina/to_fedora/descriptive/related_resource_spec.rb

Connects to https://app.honeybadger.io/projects/50568/faults/69893421 which is causing all deposits to fail in stage.
CI
None

Map related-to null type for H2 related works and links

---

app/services/cocina/to_fedora/descriptive/subject.rb
spec/services/cocina/to_fedora/descriptive/subject_spec.rb

closes #1367
Allow levels of a hierarchical geographic subject to be skipped.
Add continent as a level.
Unit
NA

Handle missing hierarchical geographic and adds continent.

---

app/services/cocina/from_fedora/descriptive/form.rb
spec/services/cocina/from_fedora/descriptive/form_spec.rb

refs #1372
Handle empty cartographic elements to avoid "" values.
Unit
NA

Handle empty cartographic form elements.

---

bin/validate-to-cocina

See:
```
Error: 57 of 500000 (0.0114%)%)                                                                                                                       
Data error: 14818 of 500000 (2.9636%)%)   
```

Remove extra error reporting characters

---

app/services/cocina/to_fedora/descriptive/geographic.rb
spec/services/cocina/to_fedora/descriptive/geographic_spec.rb

closes #1382
So that mapping to fedora doesn't raise when geo has a form, but not a subject.
Unit
NA

Handle mapping geo to fedora when no subject.

---

app/services/cocina/to_fedora/descriptive/subject.rb
spec/services/cocina/to_fedora/descriptive/subject_classification_spec.rb

closes #1383
To not raise when mapping a subject classification without a source.
Unit
NA

Handles subject classification missing source.

---

app/services/cocina/from_fedora/descriptive/form.rb
app/services/cocina/to_fedora/descriptive/form.rb
spec/services/cocina/from_fedora/descriptive/form_spec.rb
spec/services/cocina/from_fedora/descriptive_spec.rb
spec/services/cocina/to_fedora/descriptive/form_spec.rb

Connects to sul-dlss/happy-heron#241
To map H2 types and subtypes from Cocina to Fedora.
Note that I removed a bunch of apparently bogus `xit`s that seemed to be for Fedora to Cocina in a test for Cocina to Fedora.
CI, and also against 500K objects on the sdr-deploy box:
```shell
$ bin/validate-to-cocina -s 500000                                                                                
Error: 57 of 500000 (0.0114%)
Data error: 14818 of 500000 (2.9636%)
```
```shell
$ bin/validate-to-cocina -s 500000                                                                                
Error: 57 of 500000 (0.0114%)
Data error: 14818 of 500000 (2.9636%)
```
```shell
$ bin/validate-to-fedora -s 500000                                                                                
To Fedora …
```

Map structured forms for H2 types and subtypes

---

bin/validate-cocina-roundtrip

There are some differences that need to be ignored when checking round tripping. This takes a new approach: modifying the original XML to make any necessary changes.
Locally
NA

Change approach to normalizing XML for checking equivalence.

---

app/services/cocina/from_fedora/descriptive/subject.rb
spec/services/cocina/from_fedora/descriptive/subject_classification_spec.rb

closes #1396
Because an item can have multiple classifications.
Locally, sdr-deploy
NA

Support multiple classifications.

---

bin/validate-cocina-roundtrip

The MODs version was being normalized even when it was being mapped, resulting in a mistaken difference report.
Locally
NA

Only normalize mods version when not mapped.

---

app/services/cocina/object_creator.rb
app/services/cocina/to_fedora/descriptive.rb
app/services/cocina/to_fedora/descriptive/geographic.rb
bin/validate-cocina-roundtrip
bin/validate-to-fedora
spec/services/cocina/to_fedora/descriptive/geographic_spec.rb
spec/services/cocina/to_fedora/descriptive_spec.rb

Fixes #1371 so that the druid is available in `to_fedora` for the `rdf:about` attribute on the geographic Description block.
Before:
```
<rdf:Description>
<dc:format>image/jpeg</dc:format>
<dc:type>Image</dc:type>
<gmd:centerPoint>
<gml:Point gml:id="ID">
<gml:pos>41.893367 12.483736</gml:pos>
</gml:Point>
</gmd:centerPoint>
</rdf:Description>
</rdf:RDF>
```
After:
```
<rdf:Description rdf:about="http://www.stanford.edu/kk138ps4721">
<dc:format>image/jpeg</dc:format>
<dc:type>Image</dc:type>
<gmd:centerPoint>
<gml:Point gml:id="ID">
<gml:pos>41.893367 12.483736</gml:pos>
</gml:Point>
</gmd:centerPoint>
</rdf:Description>
</rdf:RDF>
```
Unit
N/A

Add rdf:about to the geo Description block

---

app/services/cocina/object_updater.rb
config/settings.yml
spec/requests/update_metadata_spec.rb

This feature is behind a feature flag which is off by default
This will enable a way to update metadata using the cocina api and not needing to send MODS.
Fixes #1398

Allow updates to contain cocina descriptive metadata

---

app/services/cocina/from_fedora/descriptive/form.rb
app/services/cocina/object_updater.rb
app/services/cocina/to_fedora/descriptive/form.rb
spec/services/cocina/from_fedora/descriptive/form_spec.rb
spec/services/cocina/to_fedora/descriptive/form_spec.rb

closes #1416
Genre and form was not being correctly mapped.
Unit / sdr-deploy
NA

Fixes genre / form mapping.

---

app/services/cocina/to_fedora/descriptive/contributor.rb
spec/services/cocina/to_fedora/descriptive/contributor_spec.rb

Part of #1405
to_fedora contributor mapping copes with role when both text and code for role are present.
unit test, also
1.  For the record called out in #1405, cz548fn3478, I did a roundtrip validation for master branch and my branch.
here's the diff:
```
87c87,88
<       <roleTerm type="text" valueURI="http://id.loc.gov/vocabulary/relators/spn" authority="marcrelator" authorityURI="http://id.loc.gov/vocabulary/relators">Sponsor</roleTerm>
---
>       <roleTerm valueURI="http://id.loc.gov/vocabulary/relators/spn" authority="marcrelator" authorityURI="http://id.loc.gov/vocabulary/relators" type="text">Sponsor</roleTerm>
>       <roleTerm valueURI="http://id.loc.gov/vocabulary/relators/spn" authority="marcrelator" authorityURI="http://id.loc.gov/vocabulary/relators" …
```

to_fedora contrib mapping copes with role text AND code

---

app/services/cocina/from_fedora/descriptive/contributor.rb
spec/services/cocina/from_fedora/descriptive/contributor_spec.rb

Closes #1405
to_fedora contributor mapping copes with role when mods has marcrelator role value that is incorrectly capitalized
added unit test;
1.  running single druid  cz548fn3478 roundtrip `bin/validate-cocina-roundtrip -d druid\:cz548fn3478`
This from diffing between master branch results and this branch's results shows the value is downcased in the cocina model:
```
<           "value": "Sponsor",
---
>           "value": "sponsor",
183c181
<           "value": "Photographer",
---
>           "value": "photographer",
453,454c451
```
2. ran 500,000 records through to-cocina validation `bin/validate-to-cocina -s 500000`
master branch
```
To Cocina error: 57 of 500000 (0.0114%)
Data error: 17606 of 500000 (3.5212%)
Missing: 2954 of 500000 (0.5908%)
Error:  isn't one of in …
```

from_fedora mapping contributor: normalize marcrelator value to lowercase

---

app/services/cocina/to_fedora/descriptive/subject.rb
spec/services/cocina/from_fedora/descriptive/subject_spec.rb
spec/services/cocina/to_fedora/descriptive/subject_spec.rb

closes #1418
Authorities for subjects were being mistakingly set.
Unit, sdr-deploy.
NA

Fixes handling of subject authorities.

---

app/services/cocina/from_fedora/descriptive/notes.rb
spec/services/cocina/from_fedora/descriptive/notes_spec.rb
spec/services/cocina/from_fedora/descriptive_spec.rb

closes #1415
Map displayLabel for abstract.
NA

Maps displayLabel for abstract.

---

app/services/cocina/from_fedora/descriptive/contributor.rb
app/services/cocina/to_fedora/descriptive/contributor.rb
spec/services/cocina/from_fedora/descriptive/contributor_spec.rb
spec/services/cocina/to_fedora/descriptive/contributor_spec.rb

Fixes #1406 - maps MODS name authority attributes to cocina and back again
unit test added
1. For the record called out in #1406, cz548fn3478, I did a roundtrip validation for master branch and my branch.  Here is the diff:
```
$ diff cz548fn3478.master.txt cz548fn3478.mybranch.txt 
84c84
<   <name type="corporate" usage="primary">
---
>   <name type="corporate" usage="primary" valueURI="http://id.loc.gov/authorities/names/n82220006" authority="naf" authorityURI="http://id.loc.gov/authorities/names">
157c157,162
<           "value": "Stanford University. School of Engineering"
---
>           "value": "Stanford University. School of Engineering",
>           "uri": "http://id.loc.gov/authorities/names/n82220006",
>           "source": {
>             "code": "naf",
>             "uri": …
```

implement contributor name authority mappings

---

app/services/cocina/from_fedora/descriptive/contributor.rb
spec/services/cocina/from_fedora/descriptive/contributor_spec.rb
spec/services/cocina/from_fedora/descriptive_spec.rb
spec/services/cocina/to_fedora/descriptive/contributor_spec.rb

Fixes #1251 - a couple of wrinkles exposed when working on contributor role mappings a while back
(actually:  "why" is that I saw that these specs weren't written and thought they might "just work" if I implemented the specs ... and it was almost true)
unit tests added
Ran 500,000 records through round trip validation and it didn't get worse: bin/validate-cocina-roundtrip -s 500000
my branch:
```
To Cocina error: 57 of 500000 (0.0114%)
Data error: 17606 of 500000 (3.5212%)
Missing: 2954 of 500000 (0.5908%)
Error:  isn't one of in #/components/schemas/DescriptiveBasicValue/allOf/2/properties/value (57 errors)
Data error: [DATA ERROR] Subject has unknown authority code (14566 errors)
Data error: [DATA ERROR] originInfo/dateOther missing eventType (1019 errors)
Data error: [DATA ERROR] …
```

Contrib role authority tweak

---

app/services/cocina/from_fedora/descriptive/form.rb
spec/services/cocina/from_fedora/descriptive/form_spec.rb

closes #1402
The xpath for selecting the physicalDescription was not specific enough.
NA

Only use the root physicalDescription.

---

app/services/cocina/to_fedora/descriptive/contributor.rb
app/services/cocina/to_fedora/descriptive/language.rb
app/services/cocina/to_fedora/descriptive/note.rb
app/services/cocina/to_fedora/descriptive/subject.rb

I noticed this on the way to doing something else.  I think I'm the guiltiest party, too.

[Refactor] .each is fine when you aren't using the index

---

app/services/cocina/from_fedora/descriptive.rb
app/services/cocina/from_fedora/descriptive/admin_metadata.rb
app/services/cocina/from_fedora/descriptive/contributor.rb
app/services/cocina/from_fedora/descriptive/descriptive_builder.rb
app/services/cocina/from_fedora/descriptive/event.rb
app/services/cocina/from_fedora/descriptive/form.rb
app/services/cocina/from_fedora/descriptive/geographic.rb
app/services/cocina/from_fedora/descriptive/hydrus_default_title_builder.rb
app/services/cocina/from_fedora/descriptive/identifier.rb
app/services/cocina/from_fedora/descriptive/language.rb
app/services/cocina/from_fedora/descriptive/notes.rb
app/services/cocina/from_fedora/descriptive/related_resource.rb
app/services/cocina/from_fedora/descriptive/subject.rb
app/services/cocina/from_fedora/descriptive/titles.rb
spec/services/cocina/from_fedora/descriptive/admin_metadata_spec.rb
spec/services/cocina/from_fedora/descriptive/contributor_spec.rb
spec/services/cocina/from_fedora/descriptive/event_spec.rb
spec/services/cocina/from_fedora/descriptive/form_spec.rb
spec/services/cocina/from_fedora/descriptive/geographic_spec.rb
spec/services/cocina/from_fedora/descriptive/identifier_spec.rb
spec/services/cocina/from_fedora/descriptive/language_spec.rb
spec/services/cocina/from_fedora/descriptive/notes_spec.rb
spec/services/cocina/from_fedora/descriptive/related_resource_spec.rb
spec/services/cocina/from_fedora/descriptive/subject_classification_spec.rb
spec/services/cocina/from_fedora/descriptive/subject_spec.rb
spec/services/cocina/from_fedora/descriptive/titles_spec.rb

refs #1403, #1404
`mods:relatedItems` can contain all of the same elements as `mods:mods`. This changes the mapping so that use the same builders for both.
NA

When mapping from fedora, re-use builders to build related items.

---

app/services/cocina/from_fedora/descriptive/descriptive_builder.rb
app/services/cocina/from_fedora/descriptive/related_resource.rb

Some attributes are not allowed for related resources (adminMetadata and relatedResource). However, some MODS has data that should map to those attributes, which was causing errors.
This omits building those attributes until the appropriate mapping can be determined / changes made to cocina.
Locally
NA

Omit some builders not allowed for related resources.

---

app/services/cocina/to_fedora/descriptive.rb
app/services/cocina/to_fedora/descriptive/descriptive_writer.rb
app/services/cocina/to_fedora/descriptive/related_resource.rb
spec/services/cocina/to_fedora/descriptive/related_resource_spec.rb

`mods:relatedItems` can contain most of the same elements as `mods:mods`. This changes the mapping so that use the same writers for both.
NA

When mapping to fedora, re-use writers to write related items.

---

app/services/cocina/from_fedora/descriptive/contributor.rb
app/services/cocina/to_fedora/descriptive/contributor.rb
app/services/cocina/to_fedora/descriptive/form.rb
spec/requests/show_object_spec.rb
spec/services/cocina/from_fedora/descriptive/contributor_h2_spec.rb
spec/services/cocina/from_fedora/descriptive/contributor_spec.rb
spec/services/cocina/from_fedora/descriptive_spec.rb
spec/services/cocina/to_fedora/descriptive/contributor_h2_spec.rb

Part of #1375 - ensuring that all the mappings needed for contributors by h2 are coded here.
Mapping changes in this PR 
- Cocina contributor type `event` added but it is mapped to `corporate` in MODS, which already has a mapping to Cocina `organization` (in other words, it's not a reciprocal mapping)
- accommodates a cocina contributor having multiple roles.
- DataCite event data should not become a cocina `form`
There are 3 failing specs but I want to put those in a separate PR to avoid potential merging problems, as there is an open PR on `originInfo` mappings, which are implicated in these failing specs.
I used https://github.com/sul-dlss-labs/cocina-descriptive-metadata/blob/master/h2_cocina_mappings/h2_to_cocina_contributor.txt as my source for the two new spec files added;  I was …

more H2 contrib mappings

---

app/services/cocina/from_fedora/descriptive/titles.rb
spec/requests/update_metadata_spec.rb
spec/services/cocina/from_fedora/descriptive/titles_spec.rb
spec/services/cocina/to_fedora/descriptive/title_spec.rb

closes #1451
To adjust the modeling of nonsorting note per @arcadiafalcone.
NA

Moves nonsorting note to sibling of structuredValue.

---

app/services/cocina/from_fedora/descriptive/admin_metadata.rb
spec/services/cocina/from_fedora/descriptive/admin_metadata_spec.rb

closes #1448
Adds from fedora mapping for languageOfCataloging usage attribute.
NA

Adds from fedora mapping for languageOfCataloging usage attribute.

---

app/services/cocina/from_fedora/descriptive/form.rb
spec/services/cocina/from_fedora/descriptive/form_spec.rb

closes #1421
So handle genres that have authorityURI, but no valueURI.
NA

Handles genre without valueURI.

---

bin/validate-cocina-roundtrip
spec/services/cocina/from_fedora/descriptive/subject_spec.rb

closes #1411
There are a variety of equivalent variations for single topics. This normalizes them when checking equivalence.
Locally
NA

Normalize topic for roundtrip.

---

app/services/cocina/from_fedora/descriptive/admin_metadata.rb
spec/services/cocina/from_fedora/descriptive/admin_metadata_spec.rb

Normalize data when languageOfCataloging useage attribute is capitalized

---

bin/validate-cocina-roundtrip

I was doing a little experimentation with trying to leverage super-diff for better result diffs, and I was getting confused.
- "result" vs "roundtrip" since the code used "result" for the roundtripped MODS and also for a match result.
- I prefer the code to be clearer as to where we are talking about Nokogiri::XML objects vs. XML strings
I ran the validator with these changes on sdr-deploy and it worked:
```
Status (n=100):
Success:   35 (35.0%)
Different: 64 (64.0%)
Missing:     1 (1.0%)
```
and was the same as master:
```
Status (n=100):
Success:   35 (35.0%)
Different: 64 (64.0%)
Missing:     1 (1.0%)
```

validate-cocina-roundtrip: variable/method names are important

---

app/services/cocina/from_fedora/descriptive/geographic.rb
spec/services/cocina/from_fedora/descriptive/geographic_spec.rb

Improve mapping when `dc:type` for geo metadata is specified with unexpected capitalization.
see #1464.
* unit tests
* running the to cocina validation over the cache of fedora data...
```
[deploy@sdr-deploy dor-services-app]$ diff results_to-cocina_2020-11-21T05-06-37Z_master_adbb5dc.txt results_to-cocina_2020-11-21T06-41-30Z_geo-ext-format_fba24c6.txt 
1,2c1,2
< To Cocina error: 349 of 2685579 (0.01299533545652539%)
< Data error: 118268 of 2685579 (4.403817575278925%)
---
> To Cocina error: 52 of 2685579 (0.0019362677471040696%)
> Data error: 118565 of 2685579 (4.414876642988347%)
5c5
< Error:  isn't one of in #/components/schemas/DescriptiveBasicValue/allOf/2/properties/value (349 errors)
---
> Error:  isn't one of in #/components/schemas/DescriptiveBasicValue/allOf/2/properties/value …
```

geo extension format and type handling

---

app/services/cocina/from_fedora/descriptive/geographic.rb
spec/services/cocina/from_fedora/descriptive/geographic_spec.rb

compare to #1465.  also intended to handle the data problem described iin #1464, and in particular attempts to address point 3 in https://github.com/sul-dlss/dor-services-app/issues/1464#issuecomment-732058434 (use presence of format info rather than `dc:type` value).
i _think_ this is an improvement on #1465, but wasn't totally sure, hence the separate PR.  probably only one of the two needs to be merged.
* unit tests
* running the to cocina validation over the cache of fedora data...
```
[deploy@sdr-deploy dor-services-app]$ diff results_to-cocina_2020-11-21T05-06-37Z_master_adbb5dc.txt results_to-cocina_2020-11-21T08-00-19Z_geo-ext-format-independent-of-type_873a31c.txt 
1,2c1,2
< To Cocina error: 349 of 2685579 (0.01299533545652539%)
< Data error: 118268 of 2685579 …
```

handle geo extension format and type independently

---

app/services/cocina/from_fedora/descriptive/event.rb
spec/services/cocina/from_fedora/descriptive/event_spec.rb

to address the problem described in #1426 (though based on validation against the fedora cache, this may also introduce a regression in the mapping, i'm not quite sure, so leaving in draft for pairing/discussion)
* unit tests
* validation against the fedora cache
it seems like the change in this PR fixed most but not all of the `missing eventType` error (5417 down to 1341):
```
[deploy@sdr-deploy dor-services-app]$ 
[deploy@sdr-deploy dor-services-app]$ diff results-master-all_2020-11-13.txt results-dateOther-event-type-all_2020-11-13.txt
2c2
< Data error: 95317 of 2685579 (3.549216016359973%)
---
> Data error: 91316 of 2685579 (3.4002351075876005%)
79324,84741d79323
< Data error: [DATA ERROR] originInfo/dateOther missing eventType (5417 errors)
< druid:xv158sd4671
...snip 5414 druids... …
```

to cocina mapping:  originInfo eventType, dateOther

---

app/services/cocina/from_fedora/dro_structural.rb
app/services/cocina/mapper.rb
spec/requests/create_object_spec.rb
spec/requests/update_metadata_spec.rb

Previously it was returning "none" for download access, which was not accurate

Correctly map download access

---

app/services/cocina/to_fedora/descriptive/event.rb
app/services/cocina/to_fedora/descriptive/translated_event.rb
bin/validate-cocina-roundtrip
spec/services/cocina/from_fedora/descriptive/contributor_h2_spec.rb
spec/services/cocina/to_fedora/descriptive/contributor_h2_spec.rb
spec/services/cocina/to_fedora/descriptive/event_spec.rb
spec/services/cocina/to_fedora/descriptive_spec.rb

Closes #1375 - changes to DSA needed for h2 publisher contributors (but of benefit to all our MODS data - cough cough)
- unit tests
- any tweaks to existing tests were confirmed as correct by Arcadia
- got H2 contributor publication mapping tests to pass
- validation results of mapping change on prod data are in a comment below https://github.com/sul-dlss/dor-services-app/pull/1456#issuecomment-731394857 -- IMPROVEMENT!!!

H2 contrib publisher mappings

---

app/services/cocina/from_fedora/descriptive/subject.rb
spec/services/cocina/from_fedora/descriptive/subject_spec.rb

Adds missing implementation and test for parallelValue `geographic` and `geographicTerm`
See https://github.com/sul-dlss-labs/cocina-descriptive-metadata/blob/ad622577057b8bd97b048d7bb13c23c14c62b542/mods_cocina_mappings/mods_to_cocina_subject.txt#L679-L704
New test to replace  `xit` TODO at https://github.com/sul-dlss/dor-services-app/blob/c5233af81c21d19784082d4d4f1c915fc6018bac/spec/services/cocina/from_fedora/descriptive/subject_spec.rb#L699
n/a

ParallelValue for geographic and geographicTerm 

---

app/services/cocina/from_fedora/descriptive/subject_authority_codes.rb

Valid authority codes missing from the validation list were causing many false positive errors.
n/a
n/a

Add missing valid authority codes

---

app/services/cocina/mods_normalizer.rb
spec/services/cocina/mods_normalizer_spec.rb

closes #1486
Normalizes text roleTerms to downcase to improve matching of mapped MODS.
NA

Normalizes text roleTerms to downcase.

---

README.md
app/services/mods_equivalent_service.rb
bin/validate-cocina-roundtrip

Computing Levenstein distance was significantly slowing down `validate-cocina-roundtrip`.
sdr-deploy, unit
README

Fix MODS Equivalent Service performance.

---

app/services/cocina/from_fedora/descriptive/contributor.rb
app/services/cocina/mods_normalizer.rb
spec/services/cocina/from_fedora/descriptive/contributor_spec.rb
spec/services/cocina/from_fedora/descriptive_spec.rb
spec/services/cocina/mods_normalizer_spec.rb

closes #1502
Adds and/or corrects roleTerm authorityURI to improve matching.
NA

Adds or corrects roleTerm authorityURI.

---

app/services/cocina/mods_normalizer.rb
spec/services/cocina/mods_normalizer_spec.rb

closes #1500
Normalizes usage for PURL to improve matching.
NA

Normalizes usage for PURL.

---

app/services/cocina/from_fedora/descriptive/authority_uri.rb
app/services/cocina/from_fedora/descriptive/contributor.rb
app/services/cocina/from_fedora/descriptive/event.rb
app/services/cocina/from_fedora/descriptive/form.rb
app/services/cocina/from_fedora/descriptive/location.rb
app/services/cocina/from_fedora/descriptive/subject.rb
spec/services/cocina/from_fedora/descriptive/contributor_spec.rb
spec/services/cocina/from_fedora/descriptive/event_spec.rb
spec/services/cocina/from_fedora/descriptive/form_spec.rb
spec/services/cocina/from_fedora/descriptive/location_spec.rb

closes #1484
closes #1490
Normalizes authorityURI with trailing slash.
NA

Normalizes authorityURI with trailing slash.

---

app/services/cocina/from_fedora/descriptive/language_script.rb
app/services/cocina/from_fedora/descriptive/location.rb
app/services/cocina/from_fedora/descriptive/titles.rb
app/services/cocina/to_fedora/descriptive/location.rb
spec/services/cocina/from_fedora/descriptive/location_spec.rb
spec/services/cocina/to_fedora/descriptive/location_spec.rb

closes #1510
To map lang and script attributes for `<physicalLocation>`.
NA

Maps lang and script for physicalLocation.

---

app/services/cocina/from_fedora/descriptive/location.rb
app/services/cocina/to_fedora/descriptive/location.rb
spec/services/cocina/from_fedora/descriptive/location_spec.rb
spec/services/cocina/to_fedora/descriptive/location_spec.rb

closes #1509
To map url note.
NA

Maps url note.

---

app/services/cocina/to_fedora/descriptive/contributor.rb
spec/services/cocina/to_fedora/descriptive/contributor_spec.rb

closes #1494
Handle names without types.
NA

Maps name without type to fedora.

---

app/services/cocina/from_fedora/descriptive/admin_metadata.rb
spec/services/cocina/from_fedora/descriptive/admin_metadata_spec.rb

closes #1481
Only a single identifier was being mapped to cocina.
NA

Maps multiple identifiers to cocina.

---

app/services/cocina/from_fedora/descriptive/related_resource.rb
app/services/cocina/to_fedora/descriptive/related_resource.rb
spec/services/cocina/from_fedora/descriptive/related_resource_spec.rb
spec/services/cocina/to_fedora/descriptive/related_resource_spec.rb

closes #1511
To map otherType relatedItems.
NA

Maps otherType relatedItems.

---

app/services/cocina/mods_normalizer.rb
spec/services/cocina/mods_normalizer_spec.rb

To normalize when relatedItem has otherType and type attributes to enhance matching.
NA

Normalizes when relatedItem has otherType and type.

---

app/services/cocina/to_fedora/descriptive/title.rb
spec/services/cocina/to_fedora/descriptive/title_spec.rb

closes #1476
Remove erroneous empty lang attributes for parallel titles.
NA

Removes empty lang for parallel title.

---

app/services/cocina/from_fedora/descriptive/subject.rb
spec/services/cocina/from_fedora/descriptive/subject_name_spec.rb

closes #1497
Fix missing authorityURI for name subject.
NA

Fix missing authorityURI for name subject.

---

app/services/cocina/mods_normalizer.rb
spec/services/cocina/mods_normalizer_spec.rb

closes #1493
To fix normalization of complex subjects.
NA

Fix normalization of complex subjects.

---

app/services/cocina/from_fedora/descriptive/location.rb
spec/services/cocina/from_fedora/descriptive/location_spec.rb

closes #1489
The logic for determining code/value for `<physicalLocation>` was incorrect.
NA

Fixes determining code/value for physicalLocation.

---

.rubocop.yml
app/services/cocina/mods_normalizer.rb
spec/services/cocina/mods_normalizer_spec.rb

closes #1479
So that empty nodes match when checking equivalence.
NA

Remove empty notes.

---

app/services/cocina/mods_normalizer.rb
spec/services/cocina/mods_normalizer_spec.rb

closes #1488
To normalize for unmatched altRepGroups.
NA

Normalize unmatched altRepGroups.

---

app/services/cocina/mods_normalizer.rb
spec/services/cocina/mods_normalizer_spec.rb

closes #1485
Remove empty attributes to help with mapping.
NA

Normalizes empty attributes.

---

app/services/mods_equivalent_service.rb
bin/validate-cocina-roundtrip
spec/services/mods_equivalent_service_spec.rb

closes #1475
To improve matching given that the altRepGroup and nameTitleGroup ids may differ between original and roundtripped MODS.
NA

Normalizes altRepGroup and nameTitleGroup.

---

app/services/cocina/mods_normalizer.rb

closes #1537
To base normalization of authorityURI on mapping code rather than hardcoding.
NA

Normalize all authorityURIs.

---

app/services/cocina/from_fedora/descriptive/form.rb
spec/services/cocina/from_fedora/descriptive/form_spec.rb

closes #1547
Add missing mapping for genre displayLabel.
NA

Map genre displayLabel.

---

app/services/cocina/from_fedora/descriptive/admin_metadata.rb
app/services/cocina/from_fedora/descriptive/language.rb
app/services/cocina/from_fedora/descriptive/language_term.rb
app/services/cocina/mods_normalizer.rb
spec/services/cocina/from_fedora/descriptive/admin_metadata_spec.rb
spec/services/cocina/mods_normalizer_spec.rb

closes #1557
`xml:space` isn't mapped, so removing for matching.
NA

Removes xml:space.

---

app/services/cocina/mods_normalizer.rb
spec/services/cocina/mods_normalizer_spec.rb

To add a missing type attribute for languageTerm.
NA

Nornalize type attribute for languageTerm

---

app/services/cocina/from_fedora/descriptive/event.rb
spec/services/cocina/from_fedora/descriptive/event_spec.rb
spec/services/cocina/to_fedora/descriptive/event_spec.rb

closes #1551
To map events that don't have dates.
NA

Maps events without dates.

---

app/services/cocina/from_fedora/descriptive/identifier.rb
app/services/cocina/to_fedora/descriptive/identifier.rb
spec/services/cocina/from_fedora/descriptive/identifier_spec.rb
spec/services/cocina/to_fedora/descriptive/identifier_spec.rb

closes #1508
To map invalid identifiers.
NA

Maps invalid identifiers.

---

app/services/cocina/add_purl_to_description.rb
app/services/cocina/object_creator.rb
spec/services/cocina/object_creator_spec.rb

This prevents having to do two sequential writes as the purl requires knowing the druid
Ref https://github.com/sul-dlss/happy-heron/pull/230

Add a filter that sets the purl in the description on create

---

app/services/cocina/mods_normalizer.rb
spec/services/cocina/mods_normalizer_spec.rb

closes #1539
Subject authorities are really challenging.
NA

Normalizes subject authority.

---

app/services/cocina/mods_normalizer.rb
spec/services/cocina/mods_normalizer_spec.rb

closes #1542
All `<originInfo>` should be normalized.
NA

Normalizes originInfo that is child of relatedItem.

---

app/services/cocina/to_fedora/descriptive/subject.rb
spec/services/cocina/to_fedora/descriptive/subject_spec.rb

closes #1495
Not all cartographic subjects have subjects (but have forms only).
NA

Handle form-only cartographic subjects.

---

app/services/cocina/to_fedora/descriptive/subject.rb
spec/services/cocina/to_fedora/descriptive/subject_name_spec.rb

closes #1544
Subject authority should only be added when all parts have same authority.
NA

Handles authority for subject that have multiple parts.

---

app/services/cocina/to_fedora/descriptive/subject.rb

And make `Cocina::ToFedora::Descriptive::Subject#all_same_authority?` return a boolean since its value is not used otherwise (i.e., as a string)
Because it was suggested in code review, which I didn't notice before merging.
CI
None

Prefer `Array#uniq` over set operations

---

app/services/cocina/to_fedora/descriptive/subject.rb
spec/services/cocina/to_fedora/descriptive/subject_spec.rb

closes #1549
Topics should have authority attribute even if subject has authority.
NA

Fixes missing authority for topic.

---

bin/validate-cocina-roundtrip

closes #1577
A mismatch was reported, but the reason was not given.
Locally.
NA

Reports if node count mismatch.

---

app/services/cocina/mods_normalizer.rb
spec/services/cocina/mods_normalizer_spec.rb

Fixes #1518 (incorrect PURL normalization with primary usage designation).  Did some refactoring to make this more clear (hopefully)
Added new unit test

search all url nodes for primary designation when normalizing PURLs

---

app/services/cocina/from_fedora/descriptive/event.rb
spec/services/cocina/from_fedora/descriptive/event_spec.rb

closes #1548
Issuance, etc. should be placed on events based on precedence rule (described in ticket).
NA

Select event for issuance, etc. based on precedence rule.

---

app/services/cocina/to_fedora/descriptive/event.rb
spec/services/cocina/to_fedora/descriptive/event_spec.rb

Fixes #1379 -- add a new to_fedora mapping based on (5c) described here: https://github.com/sul-dlss-labs/cocina-descriptive-metadata/pull/110/files
A couple comments:
* The from_fedora mapping described in (5c) already exists, as shown in various tests like this https://github.com/sul-dlss/dor-services-app/blob/master/spec/services/cocina/from_fedora/descriptive/event_spec.rb#L153-L177
* I believe (5b) in PR above is covered in the from_fedora mapping, as shown in this test:  https://github.com/sul-dlss/dor-services-app/blob/master/spec/services/cocina/from_fedora/descriptive/event_spec.rb#L117-L151
This shows an HB alert if any element is missing the 'eventType', so more generalized than described in (5b) (and also not a fatal error, which I'm not sure what would mean).
Unit tests

add a new to fedora mapping

---

README.md
bin/validate-to-cocina
bin/validate-to-fedora

When running tests or reports that produce output files, I find it nice when output is easy to associate with the input that produced it, so I added an option to do that for the cocina validation results, since I was running against a number of branches in a row Friday evening.  Figured others might find it useful, and it was quick to write so I thought it'd save me time in the long run.  Old behavior is still the default.
used the new `-u` flag on friday while running validations.
`validate-to-cocina` and `validate-to-fedora` help messages

validate-to-cocina, validate-to-fedora: provide option to automatically give result files unique descriptive names

---

app/services/cocina/from_fedora/descriptive/contributor.rb
app/services/cocina/to_fedora/descriptive/contributor.rb
spec/services/cocina/from_fedora/descriptive/contributor_spec.rb
spec/services/cocina/to_fedora/descriptive/contributor_spec.rb

closes #1601
Overachievers have multiple roles.
NA

Map multiple roles.

---

app/services/cocina/mods_normalizer.rb
app/services/cocina/to_fedora/descriptive/location.rb
spec/services/cocina/mods_normalizer_spec.rb
spec/services/cocina/to_fedora/descriptive/location_spec.rb

Fixes #1483 - Alters the logic slightly to allow for multiple location blocks and avoids blank blocks.
Additional spec.
N/A

Add individual location blocks for each URL and avoid blank URLs

---

app/services/cocina/mods_normalizer.rb
spec/services/cocina/mods_normalizer_spec.rb

Location normalization wasn't taking into account <relatedItem>.
NA

Fixes location normalization.

---

app/services/cocina/to_fedora/descriptive/subject.rb
spec/services/cocina/to_fedora/descriptive/subject_name_spec.rb

closes #1600
Only add authority attribute to `<name>` when has authorityURI or valueURI.
NA

Fix authority attribute for name subjects.

---

app/services/cocina/from_fedora/descriptive/location.rb
app/services/cocina/to_fedora/descriptive/location.rb
spec/services/cocina/from_fedora/descriptive/location_access_condition_spec.rb
spec/services/cocina/from_fedora/descriptive/location_spec.rb
spec/services/cocina/to_fedora/descriptive/location_access_condition_spec.rb
spec/services/cocina/to_fedora/descriptive/location_spec.rb

Fixes #1594  - map displayLabel for physicalLocation element fedora -> cocina -> fedora
unit tests added.
```
Success:   86175 (86.175%)
Different: 13159 (13.159%)
To Cocina error:     32 (0.032%)
To Fedora error:     24 (0.024%)
```
```
Success:   86763 (86.763%)
Different: 12571 (12.571%)
To Cocina error:     32 (0.032%)
To Fedora error:     24 (0.024%)
```

cocina mappings: map displayLabel attribute for physicalLocation

---

app/services/cocina/to_fedora/descriptive/admin_metadata.rb
spec/services/cocina/to_fedora/descriptive/admin_metadata_spec.rb

closes #1625
Map events without dates.
NA

Handles adminMetadata events without dates.

---

app/services/cocina/mods_normalizer.rb
spec/services/cocina/mods_normalizer_spec.rb

closes #1631
Nornalize bad data.
NA

Normalizes dc:type image.

---

app/services/cocina/from_fedora/descriptive/event.rb
app/services/cocina/to_fedora/descriptive/event.rb
app/services/cocina/to_fedora/descriptive/translated_event.rb
spec/services/cocina/from_fedora/descriptive/event_spec.rb
spec/services/cocina/to_fedora/descriptive/event_spec.rb

Fixes #1478 
Adds multilingual support for origin_info / event mappings.
Coverage drop is due to no tests for when we hit bizarro MODS and log errors and notify honeybadger.
1. **unit tests** from https://github.com/sul-dlss-labs/cocina-descriptive-metadata/blob/master/mods_cocina_mappings/mods_to_cocina_originInfo.txt, including 2 new ones added due to questions as I implemented this.
2. **roundtrip validations**
```
Success:   87516 (87.516%)
Different: 11820 (11.82%)
To Fedora error:     23 (0.023%)
```
```
Success:   87907 (87.907%)
Different: 11429 (11.429%)
To Fedora error:     23 (0.023%)
```
See comments below for specific …

add multilingual support for origin_info / event mappings

---

app/services/cocina/mods_normalizer.rb
spec/services/cocina/mods_normalizer_spec.rb

closes #1660
Because geographic are subjects too.
NA

Normalizes geographic subjects.

---

app/services/cocina/mods_normalizer.rb
spec/services/cocina/mods_normalizer_spec.rb

To make more roundtrip cocina mappings successful by removing a difference that doesn't matter.
Fixes #1671 
1.  unit tests added for mods_normalizer
2. roundtrip stats
```
Success:   89169 (89.169%)
Different: 10190 (10.19%)
```
```
Success:   89522 (89.522%)
Different: 9837 (9.837%)
```

cocina mapping normalization: cover more cases where originInfo need eventType

---

app/services/cocina/mods_normalizer.rb
spec/services/cocina/mods_normalizer_spec.rb

To make more roundtrip cocina mappings successful by removing a difference that doesn't matter.
Fixes #1674
1. **unit tests**
2. **roundtrip stats**
```
Success:   89169 (89.169%)
Different: 10190 (10.19%)
```
```
Success:   89387 (89.387%)
Different: 9972 (9.972%)
```

cocina mapping normalization: sometimes originInfo/place/placeTerm needs type=text

---

Gemfile
Gemfile.lock
openapi.yml

For #1499, we need cocina-models DescriptiveAccessMetadata to have digitalLocation;  this tiny additive change to openapi.yml was merged into cocina-models.  I've just generated the new cocina-models and cut a new cocina-models gem release, 0.44.0;  this brings this app up to date.
unit tests.

openapi.yml: updated with digitalLocation for access per cocina

---

spec/services/cocina/from_fedora/descriptive/titles_spec.rb

Empty titles should be treated as missing titles.
Note that this actually fixed (by accident) in previous work, but this adds the test.
Unit
NA

Raise on empty title

---

app/services/cocina/mods_normalizer.rb
spec/services/cocina/mods_normalizer_spec.rb

closes #1656
Additional normalization of subject authorities.
NA

Normalize subject authorities.

---

app/services/cocina/from_fedora/descriptive/location.rb
app/services/cocina/to_fedora/descriptive/location.rb
spec/services/cocina/from_fedora/descriptive/location_spec.rb
spec/services/cocina/to_fedora/descriptive/location_spec.rb

Fixes #1499.  Or ... at least doesn't make things worse?   See test stats.
unit tests from https://github.com/sul-dlss-labs/cocina-descriptive-metadata/blob/master/mods_cocina_mappings/mods_to_cocina_location.txt
```
Success:   90365 (90.365%)
Different: 8994 (8.994%)
```
```
$ bin/validate-cocina-roundtrip -d druid:hn970dy7259
Status (n=1):
Success:   1 (100.0%)
Missing:     0 (0.0%)
```
```
Success:   90365 (90.365%)
Different: 8994 (8.994%)
```
```
$ bin/validate-cocina-roundtrip -d …
```

cocina mapping MODS location/physicalLocation with type attribute

---

app/services/cocina/to_fedora/descriptive/contributor_writer.rb
spec/services/cocina/to_fedora/descriptive/contributor_spec.rb

Not all name authority attributes were being written.
NA

Name authority attributes

---

app/services/cocina/from_fedora/descriptive/notes.rb
spec/services/cocina/from_fedora/descriptive/notes_spec.rb

closes #1664
Nobody like empty displayLabels.
NA

Removes empty note displayLabels.

---

app/services/cocina/to_fedora/descriptive/subject.rb

closes #1659
To remove hardcoding of hierarchical geo hierarchy when mapping to fedora and instead just use the type as the tag.
NA

Removed hardcoding of hierarchical geo hierarchy when mapping to fedora.

---

app/services/cocina/mods_normalizer.rb
spec/services/cocina/mods_normalizer_spec.rb

closes #1649
Infinite bad data.
NA

Normalizes empty names.

---

app/services/cocina/mods_normalizer.rb
app/services/cocina/to_fedora/descriptive/related_resource.rb
spec/services/cocina/mods_normalizer_spec.rb

closes #1658
Remove empty subtitles.
NA

Normalizes empty subtitles.

---

app/services/cocina/from_fedora/descriptive/event.rb
app/services/cocina/mods_normalizer.rb
app/services/cocina/to_fedora/descriptive/event.rb
spec/services/cocina/from_fedora/descriptive/event_spec.rb
spec/services/cocina/mods_normalizer_spec.rb
spec/services/cocina/to_fedora/descriptive/event_spec.rb

closes #1684
Map originInfo with development dateOther.
NA

Map originInfo with development dateOther.

---

bin/validate-cocina-roundtrip

`validate-cocina-roundtrip` was trying to write files for errors even when running fast.
I ran tests in my head.
NA

Do not write results in running fast.

---

.rubocop.yml
app/services/cocina/to_fedora/descriptive/subject.rb
config/database.yml
spec/services/cocina/from_fedora/descriptive/subject_spec.rb
spec/services/cocina/to_fedora/descriptive/subject_spec.rb

Fixes #1252
To fix #1252.
Also includes:
* Differentiate between env-specific database names …
* This prevents Rails from warning the developer about using the same database for both dev and test, which most of us developers are straddling frequently. This does not affect deployed environments because the checked-in config/database.yml is overwritten with a file that is managed via Puppet. This is intended to remove drag on development.
* Add new Rubocop cops to remove warning
CI and on sdr-deploy (in progress)
```
Success:   91747 (91.747%)
Different: 7612 (7.612%)
```
```
Success:   91750 (91.75%)
Different: 7609 (7.609%)
To …
```

Add occupation subject mapping from Cocina to Fedora

---

app/services/cocina/from_fedora/descriptive/subject.rb
spec/services/cocina/from_fedora/descriptive/subject_spec.rb

closes #1662
Mapping of temporal subjects with ranges.
NA

Maps temporal range.

---

app/services/cocina/from_fedora/descriptive/admin_metadata.rb
app/services/cocina/from_fedora/descriptive/event.rb
app/services/cocina/from_fedora/descriptive/form.rb
app/services/cocina/from_fedora/descriptive/language_term.rb
app/services/cocina/from_fedora/descriptive/location.rb
app/services/cocina/from_fedora/descriptive/name_builder.rb
app/services/cocina/from_fedora/descriptive/subject.rb
app/services/cocina/from_fedora/descriptive/titles.rb
app/services/cocina/from_fedora/descriptive/value_uri.rb
spec/services/cocina/from_fedora/descriptive/value_uri_spec.rb

Fixes #1604
For the purposes of this commit, "unexpected" means that they are strings that do not begin with "http".
To surface more data errors.
CI.
None

Sniff value URIs and alert if they are unexpected

---

app/services/cocina/mods_normalizer.rb
spec/services/cocina/mods_normalizer_spec.rb

Fixes #1661
Combine multiple cartographics nodes into a single one for normalization purposes.
CI and sdr-deploy.
```
Success:   91786 (91.786%)
Different: 7552 (7.552%)
```
```
Success:   91801 (91.801%)
Different: 7537 (7.537%)
```
None

Normalize multiple subject cartographics

---

app/services/cocina/from_fedora/descriptive/hydrus_default_title_builder.rb
spec/requests/create_object_spec.rb

Fixes #1665
To fix #1665.
CI and sdr-deploy
```
Success:   91801 (91.801%)
Different: 7537 (7.537%)
```
```
Success:   91806 (91.806%)
Different: 7532 (7.532%)
```
None

Use default Hydrus title only when no titles exist

---

app/services/cocina/to_fedora/descriptive/form.rb
spec/services/cocina/from_fedora/descriptive_spec.rb
spec/services/cocina/to_fedora/descriptive/form_spec.rb

Fixes #1708
To make progress on round-tripping
CI, and sdr-deploy:
```
Success:   91715 (91.715%)
Different: 7623 (7.623%)
```
```
Success:   91717 (91.717%)
Different: 7621 (7.621%)
```
None

Map form technique and material

---

app/services/cocina/from_fedora/descriptive/titles.rb
spec/services/cocina/from_fedora/descriptive/titles_spec.rb

Fixes #1720
```
Success:   91717 (91.717%)
Different: 7621 (7.621%)
```
```
Success:   91719 (91.719%)
Different: 7619 (7.619%)
```

Map titles with main type as structured values

---

app/services/cocina/to_fedora/descriptive/location.rb
spec/services/cocina/to_fedora/descriptive/location_spec.rb

Fixes #1712
```
Success:   91717 (91.717%)
Different: 7621 (7.621%)
```
```
Success:   92378 (92.378%)
Different: 6960 (6.96%)
```

Mark purl as primary only if no other urls are marked as primary

---

app/services/cocina/from_fedora/descriptive/admin_metadata.rb
app/services/cocina/to_fedora/descriptive/admin_metadata.rb
spec/services/cocina/from_fedora/descriptive/admin_metadata_spec.rb
spec/services/cocina/to_fedora/descriptive/admin_metadata_spec.rb

Fixes #1715
```
Status (n=100000):                                                                                                                                    
Success:   91719 (91.719%)                                                                                                                          
Different: 7619 (7.619%)                                                                                                                            
To Cocina error:     52 (0.052%)                                                                                                                    
To Fedora error:     0 (0.0%)                                                                                                                       
Missing:     610 (0.61%)     
``` …

Map description standard value from Fedora if it exists

---

app/services/cocina/to_fedora/descriptive/title.rb
spec/services/cocina/to_fedora/descriptive/title_spec.rb

Fixes #1710
Before:
```
Success:   93094 (93.094%)
Different: 6244 (6.244%)
```
After
```
Success:   93095 (93.095%)
Different: 6243 (6.243%)
```

Map tranliterated title to fedora

---

Gemfile.lock
README.md
app/services/cocina/to_fedora/descriptive/title.rb
spec/services/cocina/to_fedora/descriptive/title_spec.rb

Fixes #1719
Before:
```
Success:   93094 (93.094%)
Different: 6244 (6.244%)
```
After:
```
Success:   93146 (93.146%)
Different: 6192 (6.192%)
```

Map uniform title with multiple title subelements to Fedora

---

app/services/cocina/from_fedora/descriptive/name_builder.rb
spec/services/cocina/from_fedora/descriptive/contributor_spec.rb

Fixes #1711
Before:
```
Success:   95489 (95.489%)
Different: 3849 (3.849%)
```
After:
```
Success:   95536 (95.536%)
Different: 3802 (3.802%)
```

Map roles within translated names to cocina

---

app/services/cocina/from_fedora/descriptive/subject.rb
app/services/cocina/to_fedora/descriptive/subject.rb
spec/services/cocina/from_fedora/descriptive/subject_spec.rb
spec/services/cocina/to_fedora/descriptive/subject_spec.rb

closes #1718
Handle parallel subjects with different types
NA

Handle parallel subjects with different types.

---

app/services/cocina/from_fedora/descriptive/authority.rb
app/services/cocina/mods_normalizer.rb
spec/services/cocina/from_fedora/descriptive/subject_spec.rb
spec/services/cocina/mods_normalizer_spec.rb

Fixes #1736
```
Status (n=150000):
Success:   143893 (95.92866666666667%)
Different: 5141 (3.4273333333333333%)
To Cocina error:     81 (0.054%)
Missing:     885 (0.59%)
```
```
Status (n=150000):
Success:   144022 (96.01466666666667%)
Different: 5012 (3.3413333333333335%)
To Cocina error:     81 (0.054%)
Missing:     885 (0.59%)
```

Map and normalize subjects with tgm authority

---

app/services/cocina/from_fedora/descriptive/name_builder.rb
app/services/cocina/mods_normalizer.rb
spec/services/cocina/from_fedora/descriptive/contributor_spec.rb
spec/services/cocina/mods_normalizer_spec.rb

Fixes #1760
Before
```
Success:   95997 (95.997%)
Different: 3342 (3.342%)
```
After
```
Success:   96009 (96.009%)
Different: 3330 (3.33%)
```
Note there is no change, because there are other problems with the record druid:yy910cj7795 (namely xlink:href)

Convert roles without URI to cocina

---

app/services/cocina/from_fedora/descriptive/access.rb
app/services/cocina/from_fedora/descriptive/related_resource.rb
spec/services/cocina/from_fedora/descriptive/related_resource_spec.rb

This prevents round tripping
Fixes #1758
```
$ bin/validate-cocina-roundtrip -d druid:xj351bk8174
Status (n=1):
Success:   1 (100.0%)
Missing:     0 (0.0%)
```
```
Success:   96101 (96.101%)
Different: 3238 (3.238%)
```

Ignore empty location nodes when determining whether to add the digitalRepository node

---

app/services/cocina/mods_normalizer.rb
spec/services/cocina/mods_normalizer_spec.rb

Fixes #1745
After:
```
Success:   96501 (96.501%)
Different: 2838 (2.838%)
```

Get rid of empty cartographic nodes in normalization

---

app/services/cocina/to_fedora/descriptive/title.rb
spec/services/cocina/to_fedora/descriptive/title_spec.rb

Fixes #1744
After:
```
Success:   96705 (96.705%)
Different: 2634 (2.634%)
```

Map title language to MODS from cocina

---

app/services/cocina/from_fedora/descriptive/form.rb
app/services/cocina/to_fedora/descriptive/form.rb
spec/services/cocina/from_fedora/descriptive/form_spec.rb
spec/services/cocina/to_fedora/descriptive/form_spec.rb

Fixes #1757
```
Success:   96705 (96.705%)
Different: 2634 (2.634%)
```
```
Success:   96706 (96.706%)
Different: 2633 (2.633%)
```

Map form note types

---

app/services/cocina/mods_normalizer.rb
spec/services/cocina/mods_normalizer_spec.rb

closes #1739
Another case of event that need to be split into own `<originInfo>`.
NA

Normalizes dateCaptured into own event.

---

app/services/cocina/mods_normalizer.rb
spec/services/cocina/mods_normalizer_spec.rb

closes #1749
Remove unmatched nameTitleGroups.
NA

Normalizes unmatched nameTitleGroups.

---

app/services/cocina/from_fedora/descriptive/subject.rb
app/services/cocina/from_fedora/descriptive/title_builder.rb
app/services/cocina/from_fedora/descriptive/titles.rb
app/services/cocina/to_fedora/descriptive/subject.rb
app/services/cocina/to_fedora/descriptive/title.rb
spec/services/cocina/from_fedora/descriptive/subject_name_spec.rb
spec/services/cocina/to_fedora/descriptive/subject_name_spec.rb

closes #1747
To provide more complete mapping of title subjects.
NA

Uses title builders/writers for title subjects.

---

app/services/cocina/from_fedora/descriptive/subject.rb
app/services/cocina/mods_normalizer.rb
spec/services/cocina/from_fedora/descriptive/subject_spec.rb
spec/services/cocina/mods_normalizer_spec.rb

closes #1746
Subject authority normalization is hard.
NA

Handle authority on subject but not topic.

---

app/services/cocina/from_fedora/descriptive/descriptive_builder.rb

Prevent class naming conflict with Cocina.
Unit
NA

Specify module for Access class to prevent conflict with Cocina.

---

app/services/cocina/from_fedora/descriptive/event.rb
app/services/cocina/mods_normalizer.rb
spec/services/cocina/from_fedora/descriptive/event_spec.rb
spec/services/cocina/mods_normalizer_spec.rb

closes #1785
Removes trailing periods from originInfo dates.
NA

Removes trailing periods from originInfo dates.

---

app/services/cocina/mods_normalizer.rb
app/services/cocina/to_fedora/descriptive/geographic.rb
spec/services/cocina/mods_normalizer_spec.rb
spec/services/cocina/to_fedora/descriptive/geographic_spec.rb

closes #1782
Remove gml:id.
NA

Remove gml:id.

---

app/services/cocina/to_fedora/descriptive/name_title_group.rb
spec/services/cocina/to_fedora/descriptive/title_spec.rb

closes #1750
Avoid erroneous nameTitleGroups when contributor and title have same value.
NA

Avoid erroneous nameTitleGroups.

---

app/services/cocina/from_fedora/descriptive/title_builder.rb
app/services/cocina/mods_normalizer.rb
spec/services/cocina/from_fedora/descriptive/titles_spec.rb
spec/services/cocina/mods_normalizer_spec.rb

closes #1781
Ignores and notifies title type.
NA

Ignores and notifies title type.

---

app/services/cocina/from_fedora/descriptive/titles.rb
spec/services/cocina/from_fedora/descriptive/titles_spec.rb
spec/services/cocina/to_fedora/descriptive/title_spec.rb

closes #1738
Because normal multilingual titles aren't complex enough.
NA

Maps complex multilingual title.

---

app/services/cocina/mods_normalizer.rb
spec/services/cocina/mods_normalizer_spec.rb

closes #1748
Removes empty rdf:resource.
NA

Removes empty rdf:resource.

---

app/services/cocina/mods_normalizer.rb
spec/services/cocina/mods_normalizer_spec.rb

closes #1754
Normalize originInfo with publisher and copyrightDate.
NA

Normalize originInfo with publisher and copyrightDate.

---

spec/services/cocina/from_fedora/descriptive/notes_target_audience_spec.rb
spec/services/cocina/to_fedora/descriptive/note_target_audience_spec.rb

To make it easy for dsa rspec code to be kept in synch with cocina-desc-md mapping specifications
unit tests

mapping specs for note targetAudience aligned with cocina-desc-md specs

---

spec/services/cocina/from_fedora/descriptive/subject_classification_spec.rb
spec/services/cocina/to_fedora/descriptive/subject_classification_spec.rb

To make it easy for dsa rspec code to be kept in synch with cocina-desc-md mapping specifications
unit tests

mapping specs for subject classification aligned with cocina-desc-md specs

---

app/services/cocina/mods_normalizer.rb
app/services/cocina/to_fedora/descriptive/event.rb
spec/services/cocina/from_fedora/descriptive/event_spec.rb
spec/services/cocina/mods_normalizer_spec.rb
spec/services/cocina/to_fedora/descriptive/event_spec.rb

closes #1784
Fix mapping and normalization of transliterated publisher.
NA

Fix mapping and normalization of transliterated publisher.

---

.rubocop.yml
spec/services/cocina/from_fedora/descriptive/contributor_spec.rb

To make it easy for dsa rspec code to be kept in synch with cocina-desc-md mapping specifications
unit tests

mapping specs for contrib from_fedora aligned with cocina-desc-md specs

---

spec/services/cocina/from_fedora/descriptive/contributor_spec.rb
spec/services/cocina/to_fedora/descriptive/contributor_spec.rb

To make it easy for dsa rspec code to be kept in synch with cocina-desc-md mapping specifications
unit tests

mapping rspec for contrib to_fedora aligned with cocina-desc-md

---

spec/services/cocina/to_fedora/content_metadata_generator_spec.rb

I've been prompted to do this in the past by rubocop, and it also gives yummy XML syntax highlighting in my IDE as a bonus.
(note:  it's all whitespace changes except the heredoc delimiters)

contentMd to_fedora spec: use heredoc for XML

---

spec/services/cocina/to_fedora/descriptive/contributor_spec.rb
spec/services/cocina/to_fedora/descriptive/event_spec.rb
spec/services/cocina/to_fedora/descriptive/note_target_audience_spec.rb
spec/services/cocina/to_fedora/descriptive/subject_classification_spec.rb
spec/support/mods_mapping_spec_helper.rb

To make it easier to read and maintain to_fedora mapping specs by getting rid of noise in them.  Note that the rest of the specs will be converted to use the shared_example as part of the cocina-descriptive-md alignment work.
unit tests

to_fedora mapping specs get shared_example

---

app/services/cocina/from_fedora/descriptive/event.rb
app/services/cocina/to_fedora/descriptive/event.rb
spec/services/cocina/from_fedora/descriptive/event_spec.rb
spec/services/cocina/to_fedora/descriptive/event_spec.rb

closes #1794
Additional support for originInfo publishers.
NA

Maps originInfo publisher.

---

app/services/cocina/mods_normalizer.rb
spec/services/cocina/from_fedora/descriptive/notes_spec.rb
spec/services/cocina/mods_normalizer_spec.rb
spec/services/cocina/to_fedora/descriptive/note_spec.rb

closes #1796
Map and normalize abstract with type=summary.
NA

Map and normalize abstract with type=summary.

---

README.md
bin/report

Add report for items with xlink:href so that Arcadia can clean data. Add support for multiple reports.
Local
README

xlink:href report

---

spec/services/cocina/from_fedora/descriptive/contributor_spec.rb
spec/services/cocina/to_fedora/descriptive/contributor_spec.rb

closes #1851
Adds labels for that examples can be identified.
Unit
NA

Adds correct labels for name mapping example 5c.

---

spec/services/cocina/to_fedora/descriptive/contributor_spec.rb

closes #1824
Test alignment.
Unit
NA

Remove the name authority URIs from contributor test.

---

bin/report

Fedora is "unreliable".
sdr-deploy
NA

Tweak to bin/reports to handle Fedora flakiness.

---

app/services/cocina/to_fedora/descriptive/contributor_writer.rb
spec/services/cocina/from_fedora/descriptive/contributor_spec.rb
spec/services/cocina/to_fedora/descriptive/contributor_spec.rb

closes #1848
Per Arcadia, add new name mapping example.
NA

Adds name mapping example 5b.

---

app/services/cocina/from_fedora/descriptive/subject.rb
spec/services/cocina/from_fedora/descriptive/subject_classification_spec.rb

closes #1835
Classifications without authority are bad.
Unit
NA

Warns when classification has no authority.

---

spec/services/cocina/from_fedora/descriptive/contributor_spec.rb
spec/services/cocina/to_fedora/descriptive/contributor_spec.rb

closes #1865
Per Arcadia.
Unit
NA

Add example 7i for role code without authority to MODS name mappings.

---

spec/services/cocina/from_fedora/descriptive/contributor_spec.rb
spec/services/cocina/to_fedora/descriptive/contributor_spec.rb

closes #1869
Per Arcadia.
Unit
NA

Add example 9b for multiple names with no roles to MODS name mappings.

---

spec/services/cocina/from_fedora/descriptive/contributor_spec.rb
spec/services/cocina/to_fedora/descriptive/contributor_spec.rb

closes #1867
Per Arcadia.
Unit
NA

Add example 7j for name with multiple roles to MODS name mappings.

---

app/services/cocina/from_fedora/descriptive/event.rb
app/services/cocina/mods_normalizer.rb
app/services/cocina/to_fedora/descriptive/event.rb
spec/services/cocina/from_fedora/descriptive/event_spec.rb
spec/services/cocina/mods_normalizer_spec.rb
spec/services/cocina/to_fedora/descriptive/event_spec.rb

closes #1797
Make sure Arcadia's changed related to originInfo copyright notice are incorporated.
NA

Mappings related to originInfo copyright notice.

---

app/services/cocina/from_fedora/descriptive/name_builder.rb
spec/services/cocina/from_fedora/descriptive/contributor_spec.rb
spec/services/cocina/from_fedora/descriptive_spec.rb
spec/services/cocina/to_fedora/descriptive/contributor_spec.rb

closes #1836
Per Arcadia.
Unit
NA

Remove extrapolated role info from MODS contributor name mappings.

---

app/services/cocina/from_fedora/descriptive/related_resource.rb

closes #1875
Fix the error.
https://github.com/sul-dlss-labs/cocina-descriptive-metadata/issues/332 is to add a spec for the data that triggered.
Locally.
NA

Fix undefined method in part.

---

app/services/cocina/from_fedora/descriptive/geographic.rb
spec/services/cocina/from_fedora/descriptive/geographic_spec.rb

closes #1874
Unnecessary warning
Unit
NA

Stop warning on https PURLs.

---

app/services/cocina/mods_normalizer.rb
spec/services/cocina/mods_normalizer_spec.rb

closes #1836
Since no longer added in mapping, no longer need to normalize.
NA

Removes normalization of role term authority.

---

app/services/cocina/from_fedora/descriptive/authority.rb
app/services/cocina/from_fedora/descriptive/subject.rb
spec/services/cocina/from_fedora/descriptive/subject_name_spec.rb
spec/services/cocina/from_fedora/descriptive/subject_spec.rb

Map unknown authority codes.

---

app/services/cocina/from_fedora/descriptive/subject.rb
app/services/cocina/to_fedora/descriptive/contributor_writer.rb
app/services/cocina/to_fedora/descriptive/role_writer.rb
app/services/cocina/to_fedora/descriptive/subject.rb
bin/validate-cocina-roundtrip
spec/services/cocina/from_fedora/descriptive/subject_name_spec.rb
spec/services/cocina/to_fedora/descriptive/subject_name_spec.rb

closes #1755
Per Arcadia, map name subject with role and displayForm.
NA

Mapping for name subject with role and displayForm

---

app/services/cocina/to_fedora/descriptive.rb

Are you sick of mapping tests that spew out unicode characters as XML encoded unicode character points?  Me too.   This fixes that.
Did this as part of working on refactoring mappings specs as part of spec alignment.  It works.
```
Success:   9789 (97.89%)
Different: 140 (1.4%)
To Cocina error:     3 (0.03%)
Missing:     68 (0.68%)
```
```
Success:   9789 (97.89%)
Different: 140 (1.4%)
To Cocina error:     3 (0.03%)
Missing:     68 (0.68%)
```

cocina/to_fedora/descriptive: ensure utf-8 encoding

---

app/services/cocina/from_fedora/descriptive/admin_metadata.rb
app/services/cocina/to_fedora/descriptive/admin_metadata.rb
spec/services/cocina/from_fedora/descriptive/admin_metadata_spec.rb
spec/services/cocina/to_fedora/descriptive/admin_metadata_spec.rb

fix #1798
unit tests, `validate-cocina-roundtrip` script on sdr-deploy
n/a

allow for adminMetadata to have multiple description standards

---

app/services/cocina/mods_normalizer.rb
app/services/cocina/to_fedora/descriptive.rb
spec/services/cocina/mods_normalizer_spec.rb
spec/services/cocina/to_fedora/descriptive/contributor_h2_spec.rb
spec/services/cocina/to_fedora/descriptive_spec.rb
spec/support/mods_mapping_spec_helper.rb

Arcadia asked for it
```
Success:   98076 (98.076%)
Different: 1286 (1.286%)
To Cocina error:     28 (0.028%)
```
```
Success:   98076 (98.076%)
Different: 1286 (1.286%)
To Cocina error:     28 (0.028%)
```

Use Mods 3.7 instead of Mods 3.6

---

spec/services/cocina/mapping/descriptive/mods/record_info_spec.rb

to fix broken build
the build now passes.

xit formerly passing record_info mods mapping spec until marc -> mods uses MODS 3.7

---

spec/services/cocina/from_fedora/descriptive/form_spec.rb
spec/services/cocina/from_fedora/descriptive/geographic_spec.rb
spec/services/cocina/from_fedora/descriptive/notes_spec.rb
spec/services/cocina/to_fedora/descriptive/geographic_spec.rb

@justinlittman convinced me these comments were just noise and would require extra future work.
changes to specs only, and removing comments at that.

mapping specs - remove unnec comments

---

app/services/cocina/to_fedora/content_metadata_generator.rb
spec/services/cocina/to_fedora/content_metadata_generator_spec.rb

Reverts #1083
Setting the thumb attribute causes the resource to be ignored by the viewer and then the video won't display
Fixes sul-dlss/argo#2373

Media objects should not set the thumb attribute

---

spec/services/cocina/from_fedora/descriptive/notes_spec.rb
spec/services/cocina/mapping/descriptive/mods/note_spec.rb
spec/services/cocina/to_fedora/descriptive/note_spec.rb

To reduce ongoing costs of mods/cocina mappings
it was all test code changes; there should be no coverage decrease (and there's less overall test code!)

mods note <--> cocina mapping specs refactored

---

Gemfile
Gemfile.lock
app/services/cocina/from_fedora/descriptive/title_builder.rb
spec/rails_helper.rb
spec/services/cocina/mapping/descriptive/mods/title_info_spec.rb
spec/support/matchers/deep_ignore_order_matcher.rb

Also, added custom hash matcher that ignores order.
closes #1921
* Less broken tests = better mapping.
* Show diff when comparing cocina hashes for easier debugging.
NA

Fixed Title with xml:space test.

---

spec/services/cocina/mapping/descriptive/h2/admin_metadata_h2_spec.rb

adding Arcadia's mappings for h2 MODS adminMetadata specs.
it adds specs only

add admin_metadata_h2_spec for cocina mappings

---

spec/services/cocina/mapping/descriptive/h2/event_h2_spec.rb

adding Arcadia's mappings for h2 MODS event specs.
it adds specs only

add event_h2_spec for cocina mappings

---

docker-compose.yml

This change only affects the development environment.
This is what we run in production

Upgrade to solr 8 for development

---

app/services/cocina/from_fedora/descriptive/contributor.rb
spec/services/cocina/from_fedora/descriptive/contributor_spec.rb
spec/services/cocina/mapping/descriptive/mods/name_spec.rb
spec/support/mods_mapping_spec_helper.rb

So that contributor correctly return nil when empty rather than an empty structure.
Unit
NA

Mods name specs tweak

---

spec/services/cocina/mapping/descriptive/h2/access_h2_spec.rb

adding Arcadia's mappings for MODS h2 access specs.
it adds two "xit" specs ...

add access_h2_spec for cocina mappings

---

spec/services/cocina/mapping/descriptive/mods/genre_spec.rb
spec/services/cocina/mapping/descriptive/mods/name_spec.rb
spec/services/cocina/mapping/descriptive/mods/part_spec.rb

Standardizing xit practices on mapping specs.
just spec xits

Mods mapping specs - xit unified prefixes

---

spec/services/cocina/mapping/descriptive/mods/title_info_spec.rb

In addition to fixing the broken title mapping spec, I discovered there were 2 specs missing from cocina-descriptive-metadata and I did some formatting.
changes were to single spec file.  Code coverage may increase.

Fix broken title mapping spec

---

spec/services/cocina/mapping/descriptive/h2/access_h2_spec.rb
spec/services/cocina/mapping/descriptive/h2/admin_metadata_h2_spec.rb
spec/services/cocina/mapping/descriptive/h2/event_h2_spec.rb
spec/services/cocina/mapping/descriptive/h2/form_h2_spec.rb
spec/services/cocina/mapping/descriptive/h2/subject_spec.rb

Standardizing xit practices on mapping specs.  Also, I forgot about roundtrip_cocina so was able to add some specs to admin_metadata.
it's all spec code

H2 mappings - xit update

---

spec/services/cocina/mapping/descriptive/mods/name_spec.rb

Two mods name mapping specs, as copied from cocina-descriptive-metadata, were not passing.  Our old specs passed because the cocina was different.   This fix reverts to using "value" instead of "uri" for the cocina identifier, per instructions from Arcadia.
Two specs were added.

mods name spec: identifier as cocina value

---

spec/services/cocina/mapping/descriptive/mods/origin_info_place_spec.rb
spec/services/cocina/mapping/descriptive/mods/origin_info_publisher_spec.rb
spec/services/cocina/mapping/descriptive/mods/origin_info_spec.rb
spec/services/cocina/mapping/descriptive/mods/subject_cartographic_spec.rb
spec/services/cocina/mapping/descriptive/mods/subject_geographic_spec.rb
spec/services/cocina/mapping/descriptive/mods/subject_name_spec.rb
spec/services/cocina/mapping/descriptive/mods/subject_occupation_spec.rb
spec/services/cocina/mapping/descriptive/mods/subject_temporal_spec.rb
spec/services/cocina/mapping/descriptive/mods/subject_topic_spec.rb

syntax highlighting in IDE saves lives.  Or time.  Or avoids errors.  Or something.
specs only changed

mapping specs use ruby hashes

---

app/services/cocina/from_fedora/descriptive/form.rb
app/services/cocina/mods_normalizer.rb
app/services/cocina/to_fedora/descriptive/form.rb
spec/services/cocina/from_fedora/descriptive/form_spec.rb
spec/services/cocina/mapping/descriptive/mods/type_of_resource_spec.rb

Fixes #1969 
I’m assuming that many of the mappings we’re now implementing occur rarely, and thus our roundtrip validation tests may show exactly the same numbers as main.   Roundtrip did show a difference before I adjusted mods_normalizer.
```
Status (n=50000):
Success:   49078 (98.156%)
Different: 595 (1.19%)
To Cocina error:     16 (0.032%)
Missing:     311 (0.622%)
```
```
Status (n=50000):
Success:   49078 (98.156%)
Different: 595 (1.19%)
To Cocina error:     16 (0.032%)
Missing:     311 (0.622%)
```

implement typeOfResource mapping when attribute without value

---

app/services/cocina/to_fedora/descriptive/form.rb

To address https://github.com/sul-dlss/dor-services-app/pull/1980/files#r567118277
specs are sufficient;  there is no actual implementation change, just the removal of a method call.

small refactor to form mapping

---

spec/services/cocina/mapping/descriptive/mods/note_spec.rb

Adds mapping for unnecessary altRepGroup and partially addresses #1936 
n/a
n/a
Implementation ticket #2014

Spec update note

---

app/services/cocina/from_fedora/descriptive/event.rb
app/services/cocina/to_fedora/descriptive/event.rb
spec/services/cocina/from_fedora/descriptive/event_spec.rb
spec/services/cocina/mapping/descriptive/h2/event_h2_spec.rb
spec/services/cocina/mapping/descriptive/mods/origin_info_spec.rb

fixes event mapping for `encoding` and `qualifier` attributes -- Arcadia says 
> "the pattern is for properties to be at the highest [outermost] level to which they apply"
Also required fixing existing originInfo/event mapping specs to be consistent with this newly implemented rule.
Fixes #1971 
Fixes #1972
specs updated plus roundtrip validation:
```
Status (n=50000):
Success:   49078 (98.156%)
Different: 595 (1.19%)
To Cocina error:     16 (0.032%)
Missing:     311 (0.622%)
```
```
Status (n=50000):
Success:   49078 (98.156%)
Different: 595 (1.19%)
To Cocina error:     16 (0.032%)
Missing:     311 (0.622%)
```

Event encoding, qualifier cocina attribs at outermost level to which they apply

---

spec/services/cocina/mapping/descriptive/mods/name_spec.rb

closes #2006
Turns out the test works ...
Unit
NA

Un-xit name with approximate date spec.

---

spec/services/cocina/mapping/descriptive/mods/table_of_contents_spec.rb

Partially addresses #1936 
n/a
n/a

Add external link mapping to table of contents spec

---

spec/services/cocina/mapping/descriptive/mods/name_spec.rb

To fix a mapping error
n/a
n/a

Correct name xlink mapping

---

spec/services/cocina/mapping/descriptive/mods/subject_name_spec.rb

closes #2018
The test passes.
Unit
NA

Un-xited Single subject subelement with authority code same as subject, no URI spec

---

spec/services/cocina/mapping/descriptive/h2/subject_spec.rb

closes #2058
More tests.
Unit
NA

Un-xit H2 mapping for non-FAST term spec.

---

spec/services/cocina/mapping/descriptive/h2/contributor_h2_spec.rb

closes #1992
Why xit when you can green?
Unit
NA

Un-xited contributor H2 specs.

---

spec/services/cocina/mapping/descriptive/mods/name_spec.rb

Un-xit corporate and family names with authority tests.

---

app/services/cocina/from_fedora/descriptive/name_builder.rb
app/services/cocina/mods_normalizers/name_normalizer.rb
spec/services/cocina/from_fedora/descriptive/contributor_spec.rb
spec/services/cocina/mods_normalizers/name_normalizer_spec.rb

Stops normalizing role case.

---

app/services/cocina/to_fedora/descriptive/subject.rb
spec/services/cocina/mapping/descriptive/mods/subject_title_spec.rb

closes #2074
Why can't subjects have titles too?
NA

Implement mappings for title subjects.

---

app/services/cocina/mods_normalizers/origin_info_normalizer.rb
spec/services/cocina/mapping/descriptive/mods/origin_info_date_spec.rb
spec/services/cocina/mapping/descriptive/mods/origin_info_spec.rb
spec/services/cocina/mods_normalizers/origin_info_normalizer_spec.rb

- beef up mapping specs for originInfo in diff flavors of empty
- mods normalization removes empty originInfo elements
- originInfo mapping specs about event type presentation collated and deduped ... and xit'ed the inconsistent one.
it's all specs except mods normalization, which had a spec written for it.

origin_info mapping specs and normalization - a few tweaks

---

app/models/marcxml_resource.rb

We were using version 1, when we should have been using version 2.
Unit
NA

Use correct version of MARC21slim2MODS3-7_SDR XSLT.

---

bin/report

closes #2125
Requested by Arcadia to troubleshoot dateOther elements.
sdr-deploy
NA

Adds report for dateOther.

---

Gemfile
Gemfile.lock

fix #2131 (allow us to unpin super_diff gem)
see https://github.com/mcmire/super_diff/issues/120#issuecomment-776414070
~~will update and take out of draft once there's an official release~~ ready for review, upgraded to [0.6.1](https://github.com/mcmire/super_diff/issues/120#issuecomment-777185023)
* ran test suite on local dev instance
* CI run for this PR
unpinned a gem

upgrade super_diff to version that works w/ CI build

---

spec/services/cocina/mapping/descriptive/mods/origin_info_logic_spec.rb

Arcadia provided some new specs to go with her revised implementation of originInfo <--> event mappings.   This brings those specs into the fold.   It's a small PR!
added specs only

run origin_info_logic_specs that pass

---

app/services/cocina/from_fedora/descriptive/event.rb
app/services/cocina/to_fedora/descriptive/event.rb
spec/services/cocina/mapping/descriptive/h2/event_h2_spec.rb

Fixes #1995.   "release" eventType is presumably a new one from H2 work.
```
Success:   9830 (98.3%)
Different: 102 (1.02%)
Missing:     68 (0.68%)
```
```
Success:   9830 (98.3%)
Different: 102 (1.02%)
Missing:     68 (0.68%)
```

add event type release

---

spec/services/cocina/mapping/descriptive/mods/origin_info_date_spec.rb
spec/services/cocina/mapping/descriptive/mods/origin_info_place_spec.rb

b/c i often "ack" for xit and this helps.

add a little info to some xit messages in mapping specs

---

app/services/cocina/mods_normalizers/origin_info_normalizer.rb
spec/services/cocina/mods_normalizer_spec.rb
spec/services/cocina/mods_normalizers/origin_info_normalizer_spec.rb
spec/support/mods_mapping_spec_helper.rb

for fun and profit.
```
Success:   9830 (98.3%)
Different: 102 (1.02%)
Missing:     68 (0.68%)
```
```
Success:   9830 (98.3%)
Different: 102 (1.02%)
Missing:     68 (0.68%)
```

beef up mapping specs to ensure roundtripping is super stable 

---

bin/refresh-metadata

So that the refresh metadata script can handle Symphony restarts.
sdr-deploy
NA

Also retry on SymphonyReader::ResponseError

---

bin/report

closes #2168
Per Arcadia.
sdr-deploy
NA

Report on legacy Metadata ToolKit records.

---

app/services/cocina/from_fedora/descriptive.rb
app/services/cocina/from_fedora/descriptive/access.rb
app/services/cocina/from_fedora/descriptive/identifier_builder.rb
app/services/cocina/from_fedora/descriptive/related_resource.rb
app/services/cocina/from_fedora/descriptive/subject.rb
app/services/cocina/mods_normalizer.rb
app/services/cocina/mods_normalizers/subject_normalizer.rb
app/services/cocina/to_fedora/descriptive/subject.rb
spec/services/cocina/from_fedora/descriptive/subject_spec.rb
spec/services/cocina/mapping/descriptive/mods/identifier_spec.rb
spec/services/cocina/mapping/descriptive/mods/related_item_spec.rb
spec/services/cocina/mapping/descriptive/mods/subject_spec.rb
spec/services/cocina/mapping/descriptive/mods/subject_topic_spec.rb
spec/services/cocina/mapping/descriptive/mods/type_of_resource_spec.rb
spec/services/cocina/mods_normalizer_spec.rb
spec/services/cocina/mods_normalizers/origin_info_normalizer_spec.rb
spec/services/cocina/mods_normalizers/subject_normalizer_spec.rb

Easiest way to show results of my attempt to normalize removal of empty elements, recursively from #2034.
We appear to have inconsistent rules for mapping empty MODS to cocina --- in some cases, an empty MODS produces no cocina, and in others, it produces cocina but with no useful data in it.
```
Status (n=1000):
Success:   972 (97.2%)
Different: 16 (1.6%)
Missing:     12 (1.2%)
```
```
Status (n=1000):
Success:   976 (97.6%)
Different: 12 (1.2%)
Missing:     12 (1.2%)
```
```
Only in results-norm-1000: druid:br564zr5425.txt
Only in results-norm-1000: druid:kg623mg8697.txt
Only in results-norm-1000: druid:qx562pf7510.txt
diff results-norm-1000/druid:qy796rh6653.txt …
```

Norm empty elements

---

app/services/cocina/from_fedora/descriptive/hydrus_default_title_builder.rb
spec/services/cocina/from_fedora/descriptive/hydrus_default_title_builder_spec.rb

Do not supply Hydrus title for relatedItems.

---

bin/validate-cocina-roundtrip
bin/validate-to-cocina
bin/validate-to-fedora

Because most of us can't remember what "Missing" means in the validation stats.
n/a

validation: better label for 'Missing (no descMetadata)'

---

app/services/cocina/mods_normalizers/subject_normalizer.rb
spec/services/cocina/mods_normalizers/subject_normalizer_spec.rb

More subject authority normalization.
NA

Subject authority normalization

---

bin/report

closes #2199
Route out the bad datas.
Local, sdr-deploy
NA

Adds reports for elements and attributes that start with spaces.

---

bin/validate-to-cocina

closes #2207
Speed up Arcadia's data remediation.
Local
NA

Add option to include APO in validate-to-cocina report.

---

spec/services/cocina/mapping/descriptive/mods/origin_info_spec.rb

To help us do origin info mappings and normalizations that don't break stuff ... before we do the big update of fixing originInfo mappings that roundtrip cleanly.
it uncomments some specs and they pass.

revert part of PR #2130 to get more origin_info specs exercising our code

---

bin/validate-cocina-roundtrip

A MODS normalizer stops roundtrip testing.
sdr-deploy
NA

Catch MODS normalizer errors when roundtripping.

---

spec/services/cocina/mapping/descriptive/mods/genre_spec.rb

To allow roundtripping genre with type
n/a
n/a

Update mapping for genre with form attribute

---

app/services/cocina/from_fedora/descriptive/event.rb
app/services/cocina/mods_normalizers/origin_info_normalizer.rb
app/services/cocina/to_fedora/descriptive/event.rb
spec/services/cocina/mapping/descriptive/mods/origin_info_date_spec.rb
spec/services/cocina/mapping/descriptive/mods/origin_info_logic_spec.rb
spec/services/cocina/mapping/descriptive/mods/origin_info_spec.rb
spec/services/cocina/mods_normalizers/origin_info_normalizer_spec.rb
spec/support/mods_mapping_spec_helper.rb

Improves cocina event mapping and MODS originInfo normalization by filtering out valueless data (empty date values, empty originInfo elements ...)
```
Status (n=25000):
Success:   24601 (98.404%)
Different: 220 (0.88%)
To Cocina error:     1 (0.004%)
Missing (no descMetadata):     178 (0.712%)
```
- kf303dc5137 - **roundtrip eventType changes (from production to publication)** and no empty dateOther
- qx562pf7510 - **roundtrip eventType changes (from manufacture to publication)** and no empty dateOther
- xv158sd4671 - **roundtrip eventType changes (from distribution to publication)** and no empty dateOther
(insignificant:  ordering of elements in mods or cocina)
- by352mp6687, fg349td3577, fv195wh3632, gv022qp2544, jk090bg7477, kq586bq1216, yh127sy5622 -- …

event mapping and normalization filters out valueless data

---

app/services/cocina/mods_normalizers/subject_normalizer.rb
spec/services/cocina/mods_normalizers/subject_normalizer_spec.rb

closes #2234
Normalization was a bit too greedy.
NA

Do not remove geographic subjects with valueURIs.

---

app/services/cocina/to_fedora/descriptive/subject.rb
spec/services/cocina/mapping/descriptive/mods/subject_spec.rb

closes #2219
Appease the mapping gods.
NA

Fix mapping when subject altRepGroups have same types.

---

app/services/cocina/mods_normalizer.rb
spec/services/cocina/mods_normalizer_spec.rb

closes #2273
Remove emptiness.
NA

Normalize empty physicalLocation.

---

app/services/cocina/mods_normalizers/origin_info_normalizer.rb
spec/services/cocina/mods_normalizer_spec.rb
spec/services/cocina/mods_normalizers/geo_extension_normalizer_spec.rb
spec/services/cocina/mods_normalizers/name_normalizer_spec.rb
spec/services/cocina/mods_normalizers/origin_info_normalizer_spec.rb
spec/services/cocina/mods_normalizers/subject_normalizer_spec.rb
spec/services/cocina/mods_normalizers/title_normalizer_spec.rb

- when mods normalization splits originInfo into multiple elements due to date processing, the displayLabel needs to be on each of split originInfo elements  (per Arcadia via slack)
- be_equivalent_to provides syntax highlighting of xml diffs if like things are compared (e.g. strings with strings)
```
Success:   9890 (98.9%)
Different: 41 (0.41%)
Missing (no descMetadata):     69 (0.69%)
```
```
Success:   9890 (98.9%)
Different: 41 (0.41%)
Missing (no descMetadata):     69 (0.69%)
```

mods normalization:  originInfo splits puts displayLabel on each

---

app/services/cocina/mods_normalizer.rb
app/services/cocina/mods_normalizers/geo_extension_normalizer.rb
app/services/cocina/mods_normalizers/name_normalizer.rb
app/services/cocina/mods_normalizers/origin_info_normalizer.rb
app/services/cocina/mods_normalizers/subject_normalizer.rb
app/services/cocina/mods_normalizers/title_normalizer.rb

It helps with spec writing to see actual characters instead of `&Ex58A6;` -- our eyes don't do those sorts of comparisons well.
roundtrip test stats comparison
```
Success:   9890 (98.9%)
Different: 41 (0.41%)
Missing (no descMetadata):     69 (0.69%)
```
```
Success:   9890 (98.9%)
Different: 41 (0.41%)
Missing (no descMetadata):     69 (0.69%)
```

mods normalization has encoding set to UTF-8

---

app/services/cocina/mods_normalizer.rb
app/services/cocina/mods_normalizers/title_normalizer.rb
bin/validate-cocina-roundtrip
spec/services/cocina/mods_normalizer_spec.rb
spec/services/cocina/mods_normalizers/geo_extension_normalizer_spec.rb
spec/services/cocina/mods_normalizers/name_normalizer_spec.rb
spec/services/cocina/mods_normalizers/origin_info_normalizer_spec.rb
spec/services/cocina/mods_normalizers/subject_normalizer_spec.rb
spec/services/cocina/mods_normalizers/title_normalizer_spec.rb
spec/support/mods_mapping_spec_helper.rb

closes #2268
Because Hydrus is "special".
NA

Normalizes Hydrus titles.

---

bin/validate-cocina-roundtrip

Because the stats were misleading - we were never going to get to 100% roundtrip success if we included objects with no descriptiveMetadata in the stats.
```
Status (n=25000):
Success:   24712 (98.848%)
Different: 108 (0.432%)
Missing (no descMetadata):     180 (0.72%)
```
```
Status (n=25000; not using Missing for success/different/error stats):
Success:   24712 (99.56486704270749%)
Different: 108 (0.43513295729250606%)
Missing (no descMetadata):     180 (0.72%)
```

don't count objects without descMetadata in roundtrip stats

---

app/services/cocina/from_fedora/descriptive/related_resource.rb
spec/services/cocina/mapping/descriptive/mods/related_item_spec.rb
spec/services/cocina/mods_normalizer_spec.rb

closes #2274
Who would've thought relatedItem could be empty in so many ways?
NA

Do not map empty relatedItem.

---

app/services/cocina/from_fedora/descriptive/event.rb
app/services/cocina/mods_normalizers/origin_info_normalizer.rb
spec/services/cocina/mapping/descriptive/mods/origin_info_date_spec.rb
spec/services/cocina/mapping/descriptive/mods/origin_info_spec.rb
spec/services/cocina/mods_normalizers/origin_info_normalizer_spec.rb

To improve our roundtripping 
short version:   un-xits some mapping and normalization specs
longer version: 
- when mods mapping splits originInfo into multiple events due to date processing, the displayLabel needs to be on each of split events (per Arcadia via slack)
- mods normalization needs to split mods originInfo elements with both dateCreated and dateIssued, just like the mapping code does
- mods normalization needs to include the displayLabel on both originInfo when split due to eventType developed and dateOther
```
Status (n=25000):
Success:   24712 (98.848%)
Different: 108 (0.432%)
Missing (no descMetadata):     180 (0.72%)
```
```
Status (n=25000):
Success:   24721 (98.884%) …
```

mods normalization: split originInfo when dateIssued and dateCreated

---

bin/cache-o-matic.sh

Quiet ruby warning in cach-o-matic.

---

app/services/cocina/from_fedora/descriptive/event.rb
app/services/cocina/mods_normalizers/origin_info_normalizer.rb
spec/services/cocina/mapping/descriptive/mods/origin_info_spec.rb
spec/services/cocina/mods_normalizers/origin_info_normalizer_spec.rb

mods normalization needs to split mods originInfo elements just like mapping code does
(un-xit 2 mapping / normalization specs)
```
Status (n=25000; not using Missing for success/different/error stats):
Success:   24722 (99.60515713134569%)
Different: 98 (0.39484286865431106%)
Missing (no descMetadata):     180 (0.72%)
```
```
Status (n=25000; not using Missing for success/different/error stats):
Success:   24723 (99.6091861402095%)
Different: 97 (0.39081385979049155%)
Missing (no descMetadata):     180 (0.72%)
```

mods normalization: split originInfo when eventType production and dateCreated and dateOther

---

bin/validate-cocina-roundtrip

to reduce cognitive load when looking at our roundtripping results
No comparison for stats - just showing the number of decimal places reported
```
Status (n=2500; not using Missing for success/different/error stats):
Success:   2465 (99.556%)
Different: 11 (0.444%)
Missing (no descMetadata):     24 (0.96%)
```

validate-cocina-roundtrip - 3 decimal points for percentages only

---

spec/services/cocina/mods_normalizers/origin_info_normalizer_spec.rb

Arcadia raised this issue, which is captured as part of #2240
it's a spec change

originInfo normalizer: ensure all flavors of empty are dealt with

---

spec/services/cocina/mapping/descriptive/mods/origin_info_place_spec.rb

Adds the remaining specs indicated for Issue #2239 (mapping problems encountered while working originInfo)
Closes #2239
it's just specs

add 2 origin_info_place mapping specs per issue #2239

---

app/services/cocina/from_fedora/descriptive/subject.rb
app/services/cocina/mods_normalizers/subject_normalizer.rb
app/services/cocina/to_fedora/descriptive/subject.rb
spec/services/cocina/mapping/descriptive/mods/subject_name_spec.rb
spec/services/cocina/mapping/descriptive/mods/subject_spec.rb
spec/services/cocina/mods_normalizers/subject_normalizer_spec.rb

closes #2301
xlinks. warnings. mappings.
NA

Implement subject xlink mapping and warning.

---

app/services/cocina/from_fedora/descriptive/event.rb

more meaningful param and variable names reduce cognitive load
```
Success:   9901 (99.698%)
Different: 30 (0.302%)
Missing (no descMetadata):     69 (0.69%)
```
```
Success:   9901 (99.698%)
Different: 30 (0.302%)
Missing (no descMetadata):     69 (0.69%)
```

Origin info mapping refactors

---

app/services/cocina/from_fedora/descriptive/related_resource.rb
spec/services/cocina/mapping/descriptive/mods/related_item_spec.rb

Do not map empty number.

---

app/services/cocina/from_fedora/identification.rb
app/services/cocina/object_creator.rb
spec/requests/create_collection_spec.rb

This allows us to asynchronously find out when a druid is assigned for our collection by monitoring rabbitMQ and looking for the sourceId we provided

Support sourceId for collections

---

app/services/mods_equivalent_service.rb
bin/validate-cocina-roundtrip
spec/services/mods_equivalent_service_spec.rb

Some items report that roundtripping is not equivalent, but don't provide the reasons. This fixes those cases by looking for diffs in reverse (roundtripped to original) and by checking attributes on the MODS element.
For example: druid:gt859cc5891, druid:hj975yc6595, druid:hp978sk7611
Local
NA

Improve reporting of diffs.

---

app/services/cocina/mods_normalizers/name_normalizer.rb
spec/services/cocina/mods_normalizers/name_normalizer_spec.rb

closes #2351
All names are equal.
NA

Normalize multilingual name roles.

---

app/services/cocina/from_fedora/descriptive/related_resource.rb
spec/services/cocina/mapping/descriptive/mods/part_spec.rb

closes #2363
Notes aren't supposed to disappear.
NA

Allow relatedItems to have notes.

---

app/services/cocina/from_fedora/descriptive/access.rb
spec/services/cocina/mapping/descriptive/mods/location_spec.rb

closes #2373
No empty shelves.
NA

Do not map empty shelfLocator.

---

bin/report

refs #2355
Make it easier to assess parallel physicalDescriptions.
sdr-deploy
NA

Adds report on parallel physicalDescriptions.

---

app/services/notifications/object_created.rb
spec/services/notifications/object_created_spec.rb

Because they don't have a project so we don't know their routing key

Don't publish object created messages for admin policies

---

spec/services/cocina/mapping/descriptive/mods/origin_info_date_spec.rb
spec/services/cocina/mapping/descriptive/mods/origin_info_event_type_spec.rb

More mappings
n/a
n/a
Implementation ticket #2392

Add legacy MARC2MODS output mappings to originInfo eventType

---

app/controllers/objects_controller.rb
spec/requests/show_object_spec.rb

When an ActiveFedora object is new, the modified_date returns a DateTime, but when it's persisted it returns a string.  Cast this to a datetime so that we can use it as intended

Handle when modified_date is a String

---

Gemfile
Gemfile.lock
app/services/cocina/from_fedora/apo.rb
app/services/cocina/object_creator.rb
app/services/cocina/object_updater.rb
app/services/cocina/to_fedora/apo_rights.rb
openapi.yml
spec/requests/create_object_spec.rb
spec/requests/show_object_spec.rb
spec/requests/update_metadata_spec.rb

We need cocina model changes:
- admin metadata changes to get roles and workflow updates
- event changes for clean roundtripping of MODS originInfo to cocina and back

updates cocina model (and openapi.yml) to 0.52.0

---

Gemfile
Gemfile.lock
openapi.yml

- to keep cocina models in sync
- so Naomi might someday be able to finish with the big rewrite of MODS originInfo -> cocina event mapping
test suite

updates to cocina model 0.53.0 (including openapi.yml)

---

app/services/cocina/from_fedora/descriptive/identifier.rb
app/services/cocina/to_fedora/descriptive/descriptive_writer.rb
app/services/cocina/to_fedora/descriptive/identifier.rb
spec/services/cocina/mapping/descriptive/mods/identifier_spec.rb

closes #2422
Why not parallel identifiers?
NA

Implement mapping for parallel identifier.

---

app/services/cocina/to_fedora/apo_rights.rb
spec/requests/create_object_spec.rb

closes #2434
So that Hydrus tests pass.
Unit
NA

Handle APOs without registration worksflows.

---

app/services/embargo_release_service.rb
spec/services/embargo_release_service_spec.rb

All of the remaining 20% embargos were converted to regular embargos in #2416

Stop doing 20% embargo release

---

app/services/cocina/from_fedora/apo.rb
app/services/cocina/object_creator.rb
app/services/cocina/object_updater.rb
app/services/cocina/to_fedora/roles.rb
spec/requests/create_object_spec.rb
spec/requests/show_object_spec.rb
spec/requests/update_metadata_spec.rb

Supports https://github.com/sul-dlss/argo/issues/2420 and https://github.com/sul-dlss/dor_indexing_app/issues/511

Map roleMetadata to and from cocina for APOs

---

app/services/cocina/from_fedora/descriptive/event.rb
app/services/cocina/mods_normalizers/origin_info_normalizer.rb
spec/services/cocina/mapping/descriptive/mods/origin_info_date_spec.rb
spec/services/cocina/mapping/descriptive/mods/origin_info_spec.rb
spec/services/cocina/mods_normalizers/origin_info_normalizer_spec.rb

Fixes #2450, and some tiny refactorings and comment improvements (which I can split out into a separate PR if desired)
We have data like this:
```xml
<originInfo>
<dateCreated encoding="w3cdtf" keyDate="yes" point="start" qualifier="approximate">1175</dateCreated>
<dateCreated encoding="w3cdtf" keyDate="yes" point="end" qualifier="approximate">1325</dateCreated>
</originInfo>
```
which should be like this:
```xml
<originInfo>
<dateCreated encoding="w3cdtf" keyDate="yes" point="start" qualifier="approximate">1175</dateCreated>
<dateCreated encoding="w3cdtf" point="end" qualifier="approximate">1325</dateCreated>
</originInfo>
```
This PR addresses this by only mapping the start keyDate to cocina in this situation and by having the mods normalization remove the extra keyDate
Note that this …

Event date point keydate

---

app/services/cocina/from_fedora/descriptive/event.rb
spec/services/cocina/mapping/descriptive/mods/origin_info_publisher_spec.rb

Closes #2460
Arcadia decided we are going to keep marcrelator role info when mapping from cocina event to MODS, so xit can be removed.
test suite (no mappings were changed so no need to check roundtrip stats)

event mapping:  keep adding marcrelator role to MODS when mapping from cocina event contrib without one

---

app/services/cocina/from_fedora/descriptive/event.rb
app/services/cocina/mods_normalizers/origin_info_normalizer.rb
spec/services/cocina/mapping/descriptive/mods/origin_info_place_spec.rb
spec/services/cocina/mods_normalizers/origin_info_normalizer_spec.rb

We've been dropping authority information on placeTerm MODS elements if text and code are both specified in a single place element and the authority attributes are on the code element only. I believe this has been true all along, but now that we've quieted down the errors on originInfo roundtripping, this was noticed.
Fixes #2448
```
Success:   99249 (99.867%)
Different: 131 (0.132%)
MODS normalizer error:     1 (0.001%)
Missing (no descMetadata):     619 (0.619%)
```
```
Success:   99279 (99.897%)
Different: 101 (0.102%)
MODS …
```

do not drop authority info on placeTerm in originInfo

---

app/services/cocina/from_fedora/descriptive/event.rb
app/services/cocina/to_fedora/descriptive/event.rb
spec/services/cocina/mapping/descriptive/mods/origin_info_date_spec.rb

- Arcadia said we could treat edtf date ranges in cocina like other date ranges.  This simplified the mapping code.  
- There was a problem with single digit dates disappearing in mapping.  This was fixed.
Closes #2459 - edtf date ranges are like other date ranges
Closes #2461 - single digit date mapping
Closes #2292 - edtf and keyDate
Closes #2392 - edtf and keyDate
```
Success:   99249 (99.867%)
Different: 131 (0.132%)
MODS normalizer error:     1 (0.001%)
Missing (no descMetadata):     619 (0.619%)
```
```
Success:   99281 (99.899%)
Different: 99 (0.1%)
To …
```

event mapping: edtf date ranges are like other date ranges in cocina

---

app/controllers/objects_controller.rb
app/services/delete_service.rb
config/routes.rb
openapi.yml
spec/requests/destroy_spec.rb

For #2385, still need to update DSC and Argo to support this Delete Object Endpoint. 
New spec for delete request, test suite.
n/a

New Delete Object Endpont

---

app/services/cocina/mods_normalizers/origin_info_normalizer.rb
spec/services/cocina/mods_normalizers/origin_info_normalizer_spec.rb

fixes an error being thrown in some mods_normalization cases (when origin_info had a date point)
(fixes 29 out of 29 normalization errors!)
Fixes #2490 
```
$ bin/validate-cocina-roundtrip -d 'druid:kc552wv4693'
...
Status (n=1; not using Missing for success/different/error stats):
Success:   0 (0.0%)
MODS normalizer error:     1 (100.0%)
```
```
$ bin/validate-cocina-roundtrip -d 'druid:kc552wv4693'
...
Status (n=1; not using Missing for success/different/error stats):
Success:   1 (100.0%)
```

origin_info_normalizer: fix keyDate error

---

app/controllers/metadata_controller.rb
config/routes.rb
openapi.yml
spec/requests/metadata_spec.rb

Fixes #1885
Adds an endpoint to retrieve source MODS for a DOR object.
test suite

add metadata/mods endpoint to retrieve source mods

---

app/controllers/metadata_controller.rb
openapi.yml
spec/requests/legacy_metadata_update_spec.rb

Validate rights metadata writes over the legacy API

---

app/controllers/application_controller.rb
app/controllers/metadata_controller.rb
app/controllers/objects_controller.rb
app/services/legacy_metadata_service.rb
app/validators/fedora/rights_validator.rb
app/validators/mods_validator.rb
bin/validate-cocina-roundtrip
openapi.yml
spec/requests/legacy_metadata_update_spec.rb
spec/services/legacy_metadata_service_spec.rb
spec/validators/fedora/rights_validator_spec.rb
spec/validators/mods_validator_spec.rb

refs #2411
Keep out bad data.
Unit
openapi

Adds MODS validation to legacy metadata endpoint.

---

.rubocop.yml
app/services/cocina/object_creator.rb
app/services/cocina/object_updater.rb
app/services/cocina/to_fedora/access.rb
app/services/cocina/to_fedora/identity.rb
spec/requests/update_metadata_spec.rb
spec/services/cocina/object_updater_spec.rb

closes #2410
Reduce the risk of unrelated mapping errors when performing an object update by only update Fedora from the parts of the cocina object that have changed.
In particular, it avoids changes being accidentally made to descriptive metadata.
Not yet.
NA

Support partial object update.

---

Gemfile
Gemfile.lock
README.md
app/services/cocina/from_fedora/apo.rb
app/services/cocina/from_fedora/collection.rb
app/services/cocina/from_fedora/dro.rb
app/services/cocina/mapper.rb
app/services/cocina/object_updater.rb
app/services/deep_equal.rb
bin/generate-cache
bin/report
bin/validate-cocina-roundtrip
bin/validate-desc-cocina-roundtrip
bin/validate-to-desc-cocina
bin/validate-to-mods
lib/fedora_cache.rb
spec/services/cocina/object_updater_spec.rb
spec/services/deep_equal_spec.rb

So we can find mapping errors before our users do.
Local
README

Adds script for roundtripping full cocina objects.

---

app/services/cocina/from_fedora/dro_structural.rb
spec/services/cocina/from_fedora/dro_structural_spec.rb

There is a typo in the modeling for book direction.  This fixes it to match what we do and for the documentation shown here: https://consul.stanford.edu/pages/viewpage.action?spaceKey=chimera&title=DOR+content+types%2C+resource+types+and+interpretive+metadata
Updated the test.

fix reading direction specified in contentMetadata

---

app/services/cocina/from_fedora/dro_structural.rb
app/services/cocina/from_fedora/file_sets.rb
app/services/cocina/id_generator.rb
app/services/cocina/to_fedora/content_metadata_generator.rb
bin/validate-cocina-roundtrip
spec/requests/create_object_spec.rb
spec/requests/update_metadata_spec.rb
spec/services/cocina/from_fedora/dro_structural_spec.rb
spec/services/cocina/to_fedora/content_metadata_generator_spec.rb

closes #2513
Allow for unique and addressable identifiers for files and filesets.
Unit
NA

Eventual unique identifiers for files and file sets.

---

bin/cache-o-matic.sh

The old field disappeared.
sdr-deploy
NA

Changed field used for finding updated records.

---

bin/validate-cocina-roundtrip

Bad caches were causing validate-cocina-roundtrip to crash.
Locally
NA

Report on bad caches for validate-cocina-roundtrip.

---

lib/fedora_cache.rb

Minimize the risk of creating an incomplete cache zip (which may occur when interrupting cache generation). This minimizes the amount of time that a zip is open for writing by performing the slow operations (fetch) before opening the zip.
Local
NA

Fetch datastreams before writing to zip.

---

app/controllers/objects_controller.rb
app/services/cocina/object_creator.rb
app/services/cocina/object_updater.rb
app/validators/cocina/description_roundtrip_validator.rb
app/validators/cocina/roundtrip_validation_error.rb
config/settings.yml
openapi.yml
spec/requests/create_object_spec.rb
spec/requests/update_metadata_spec.rb
spec/services/cocina/object_updater_spec.rb
spec/support/matchers/deep_ignore_order_matcher.rb

To make sure that only changes that can be roundtripped are accepted for create or update. This ensures the integrity of data that is submitted via cocina update or create endpoints.
Unit
NA

Check round trip before doing cocina update or create

---

app/controllers/metadata_controller.rb
app/services/cocina/object_creator.rb
app/services/cocina/object_updater.rb
app/services/legacy_metadata_service.rb
app/validators/cocina/description_roundtrip_validator.rb
config/settings.yml
spec/requests/legacy_metadata_update_spec.rb
spec/services/cocina/object_updater_spec.rb
spec/services/legacy_metadata_service_spec.rb
spec/validators/cocina/description_roundtrip_validator_spec.rb

closes #2515
Prevent non-roundtrippable descriptive metadata from entering via legacy endpoint.
Unit
NA

Validate descriptive roundtripping for legacy metadata updates.

---

app/controllers/admin_policy_defaults_controller.rb
config/routes.rb
openapi.yml
spec/requests/apply_admin_policy_defaults_spec.rb

This will be used so that we can decouple Argo from Fedora.

Create an endpoint for applying admin policy defaults

---

app/controllers/metadata_refresh_controller.rb
app/services/cocina/object_creator.rb
app/services/refresh_metadata_action.rb
bin/refresh-metadata
config/settings.yml
spec/requests/metadata_refresh_spec.rb
spec/services/cocina/object_creator_spec.rb
spec/services/refresh_metadata_action_spec.rb

closes #2532
Help identify desc metadata with roundtripping problems.
Unit
NA

Adds roundtrip validation when refreshing desc metadata.

---

app/controllers/versions_controller.rb
config/routes.rb
openapi.yml
spec/requests/versions_inventory_spec.rb

To decouple Argo from Fedora 3 and to create APIs.

Create an API endpoint that returns the version log

---

app/controllers/administrative_tags_controller.rb
openapi.yml
spec/requests/administrative_tags_spec.rb

The Dor::Item isn't necessary. In the case of roundtrip testing, this is a significant performance hit and breaks the testing when Fedora blips. It also places an unnecessary load on Fedora.
NA
NA

Do not load Dor::Item when retrieving administrative tags.

---

app/controllers/datastreams_controller.rb
config/routes.rb
openapi.yml
spec/requests/datastreams_spec.rb

This will allow us to maintain the existing Argo UI while decoupling it from Fedora.

Provide an API to provide datastream list and content for the Argo UX

---

lib/fedora_cache.rb

closes #2553
Cached objects missing descMetadata were not being correctly handled.
Local
NA

Require label and descMetadata be present when getting from cache.

---

docker/invoke.sh

This ensures an UR-APO exists so that new APOs can be registered and have an APO to register into

Bootstrap the Ur-APO

---

docker/invoke.sh

This reverts commit ea6ce21165c38bbd180357dc830ee9a839c7614b.
This was preventing the argo tests from passing.  While this is a nice to have, it's not critical. We can do this with a `docker-compose web exec` instead.

Revert "Bootstrap the Ur-APO"

---

Gemfile.lock

The old versions have been yanked, which prevents this project from being deployed

Update mime-magic to 0.3.6

---

spec/services/cocina/mapping/descriptive/h2/form_h2_spec.rb

Closes #2585
CircleCI
n/a
No implementation ticket needed - deleting mappings that were never implemented.

Remove unimplemented DataCite types from form mapping
